#####################
# Country main data #
#####################

country =
{ tag                    = ALB
  puppet 		 = ITA
  manpower               = -20.1 # -20 - building queue
  transports             = 16
  # Resource Reserves
  energy                 = 1000
  metal                  = 1000
  rare_materials         = 500
  oil                    = 500
  supplies               = 500
  money                  = 10
  consumer = 0.4000 
  supply = 0.1000 
  production = 0.5000 
  reinforcement = 0.0000 
  upgrading = 0.0000 
  capital                = 390
  policy =
  { date              = { year = 0 month = january day = 0 }
    democratic        = 3
    political_left    = 4
    free_market       = 7
    freedom           = 5
    professional_army = 5
    defense_lobby     = 4
    interventionism   = 1
  }
  nationalprovinces      = { 390 391 413 415 }
  ownedprovinces         = { 390 391 }
  controlledprovinces    = { 390 391 }
  # Eastern Minor Tech '36
  # Group D 1936 techs
  # ######################
  # GW fighter
  techapps               = { 1010 1190 1110 2450 5080 6010 }
	diplomacy = {
		relation = { tag = AFG value = 1 }
		relation = { tag = ARG value = 1 }
		relation = { tag = AST value = 1 }
		relation = { tag = AUS value = -15 }
		relation = { tag = BEL value = 10 }
		relation = { tag = BHU value = 1 }
		relation = { tag = BOL value = 1 }
		relation = { tag = BRA value = 1 }
		relation = { tag = BUL value = 20 }
		relation = { tag = CAN value = 10 }
		relation = { tag = CGX value = 1 }
		relation = { tag = CHC value = 1 }
		relation = { tag = CHI value = 1 }
		relation = { tag = CHL value = 1 }
		relation = { tag = COL value = 1 }
		relation = { tag = COS value = 1 }
		relation = { tag = CSX value = 1 }
		relation = { tag = CUB value = 1 }
		relation = { tag = CXB value = 1 }
		relation = { tag = CYN value = 1 }
		relation = { tag = CZE value = 15 }
		relation = { tag = DEN value = 15 }
		relation = { tag = DOM value = 1 }
		relation = { tag = ECU value = 1 }
		relation = { tag = EGY value = 1 }
		relation = { tag = ENG value = 5 }
		relation = { tag = EST value = 15 }
		relation = { tag = ETH value = 1 }
		relation = { tag = FIN value = 15 }
		relation = { tag = FRA value = 10 }
		relation = { tag = GER value = 5 }
		relation = { tag = GRE value = -20 }
		relation = { tag = GUA value = 1 }
		relation = { tag = HAI value = 1 }
		relation = { tag = HOL value = 15 }
		relation = { tag = HON value = 1 }
		relation = { tag = HUN value = 15 }
		relation = { tag = IND value = 1 }
		relation = { tag = IRE value = 5 }
		relation = { tag = IRQ value = 1 }
		relation = { tag = ITA value = -20 }
		relation = { tag = JAP value = 5 }
		relation = { tag = LAT value = 15 }
		relation = { tag = LIB value = 1 }
		relation = { tag = LIT value = 15 }
		relation = { tag = LUX value = 15 }
		relation = { tag = MAN value = 1 }
		relation = { tag = MEX value = 1 }
		relation = { tag = MLY value = 1 }
		relation = { tag = MON value = 1 }
		relation = { tag = NEP value = 1 }
		relation = { tag = NIC value = 1 }
		relation = { tag = NOR value = 15 }
		relation = { tag = NZL value = 10 }
		relation = { tag = OMN value = 1 }
		relation = { tag = PAN value = 1 }
		relation = { tag = PAR value = 1 }
		relation = { tag = PER value = 1 }
		relation = { tag = PHI value = 1 }
		relation = { tag = POL value = 15 }
		relation = { tag = POR value = 15 }
		relation = { tag = PRU value = 1 }
		relation = { tag = ROM value = 15 }
		relation = { tag = SAF value = 10 }
		relation = { tag = SAL value = 1 }
		relation = { tag = SAU value = 1 }
		relation = { tag = SIA value = 1 }
		relation = { tag = SIK value = 1 }
		relation = { tag = SOV value = 10 }
		relation = { tag = SPA value = 15 }
		relation = { tag = SPR value = 15 }
		relation = { tag = SWE value = 15 }
		relation = { tag = SCH value = 50 }
		relation = { tag = TAN value = 1 }
		relation = { tag = TIB value = 1 }
		relation = { tag = TUR value = 20 }
		relation = { tag = U27 value = 1 }
		relation = { tag = URU value = 1 }
		relation = { tag = USA value = -15 }
		relation = { tag = VEN value = 1 }
		relation = { tag = YEM value = 1 }
		relation = { tag = YUG value = -20 }
	}

	SpyInfo = { country = "ALB" NumberOfSpies = 1 }
	SpyInfo = { country = "BUL" NumberOfSpies = 1 }
	SpyInfo = { country = "GRE" NumberOfSpies = 2 }
	SpyInfo = { country = "ITA" NumberOfSpies = 1 }
	SpyInfo = { country = "YUG" NumberOfSpies = 2 }

  headofstate            = { type = 9 id = 32001 } # King Zog
  headofgovernment       = { type = 9 id = 32054 } # Mehdi Frashëri
  foreignminister        = { type = 9 id = 32003 } # Fuad Asllani
  armamentminister       = { type = 9 id = 32004 } # Rrok Gera
  ministerofsecurity     = { type = 9 id = 32228 } # Ethem Toto
  ministerofintelligence = { type = 9 id = 32226 } # Sami Koka
  chiefofstaff           = { type = 9 id = 32145 } # Xhemal Araniti
  chiefofarmy            = { type = 9 id = 32008 } # Shefki Shatku
  chiefofnavy            = { type = 9 id = 32009 } # Quamar Pakazi
  chiefofair             = { type = 9 id = 32188 } # Nexhip Deva
	province_development = { 
		id = { type = 30658 id = 1 } 
		name = "" 
		progress = 0.0000 
		location = 390 
		cost = 2.0000 
		date = { 
			year = 1953 
			month = june 
			day = 2 
			hour = 0 
			} 
		manpower = 0.1000 
		close_when_finished = yes 
		waitingforclosure = no 
		total_progress = 0.0000 
		size = 28 
		done = 0 
		days = 2518 
		days_for_first = 275 
		gearing_bonus = 0.0000 
		type = infrastructure 
		} 
}
