#####################
# Country main data #
#####################

country =
{ tag                    = ARG
  manpower               = 13.4000 # 50 - building queue
  transports             = 66
  escorts                = 5
  # Resource Reserves
  energy                 = 1995
  metal                  = 1142
  rare_materials         = 499
  oil                    = 312
  supplies               = 808
  money                  = 160
  free                   = { energy = 4 oil = -8 }
#Plentyful in oil, was still an importer as used it #inefficiently for electricity
  consumer = 0.2600 
  supply = 0.0800 
  production = 0.6600 
  reinforcement = 0.0000 
  upgrading = 0.0000 
  capital                = 667
  policy =
  { date              = { year = 0 month = january day = 0 }
    democratic        = 5
    political_left    = 3
    free_market       = 8
    freedom           = 6
    professional_army = 6
    defense_lobby     = 7
    interventionism   = 3
  }
  nationalprovinces      = { 667 853 852 843 844 845 851 854 855 857 858 859 862 863 865 850 866 }
  ownedprovinces         = { 667 853 852 843 844 845 851 854 855 857 858 859 862 863 865 850 }
  controlledprovinces    = { 667 853 852 843 844 845 851 854 855 857 858 859 862 863 865 850 }
  # Semi-Major Tech '36
  # Group C 1936 techs
  # ######################
  techapps               = { 4010 4020 4120 4130 4190  2010 2290 2300 2310 2450 2460 2510 1010 1190 1110 9010 5010 5020 5080 5090 5190 6010 6020
                             3010 3020 3070 3080 3130 3140 3250 3400 3410 8010 8020 8040 8050
                           }
	diplomacy = {
		relation = { tag = AFG value = 1 }
		relation = { tag = ALB value = 1 }
		relation = { tag = AST value = 15 }
		relation = { tag = AUS value = 15 }
		relation = { tag = BEL value = 25 }
		relation = { tag = BHU value = 1 }
		relation = { tag = BOL value = -15 }
		relation = { tag = BRA value = 10 }
		relation = { tag = BUL value = 10 }
		relation = { tag = CAN value = 25 }
		relation = { tag = CGX value = 1 }
		relation = { tag = CHC value = 1 }
		relation = { tag = CHI value = 15 }
		relation = { tag = CHL value = -15 }
		relation = { tag = COL value = 25 }
		relation = { tag = COS value = 10 }
		relation = { tag = CSX value = 1 }
		relation = { tag = CUB value = 10 }
		relation = { tag = CXB value = 1 }
		relation = { tag = CYN value = 1 }
		relation = { tag = CZE value = 10 }
		relation = { tag = DEN value = 10 }
		relation = { tag = DOM value = 1 }
		relation = { tag = ECU value = 20 }
		relation = { tag = EGY value = 1 }
		relation = { tag = ENG value = 25 }
		relation = { tag = EST value = 10 }
		relation = { tag = ETH value = 1 }
		relation = { tag = FIN value = 20 }
		relation = { tag = FRA value = 25 }
		relation = { tag = GER value = -45 }
		relation = { tag = GRE value = 10 }
		relation = { tag = GUA value = 10 }
		relation = { tag = HAI value = 1 }
		relation = { tag = HOL value = 20 }
		relation = { tag = HON value = 10 }
		relation = { tag = HUN value = 10 }
		relation = { tag = IND value = 1 }
		relation = { tag = IRE value = 15 }
		relation = { tag = IRQ value = 1 }
		relation = { tag = ITA value = 20 }
		relation = { tag = JAP value = 15 }
		relation = { tag = LAT value = 1 }
		relation = { tag = LIB value = 1 }
		relation = { tag = LIT value = 1 }
		relation = { tag = LUX value = 1 }
		relation = { tag = MAN value = 1 }
		relation = { tag = MEX value = 20 }
		relation = { tag = MLY value = 1 }
		relation = { tag = MON value = 1 }
		relation = { tag = NEP value = 1 }
		relation = { tag = NIC value = 10 }
		relation = { tag = NOR value = 1 }
		relation = { tag = NZL value = 20 }
		relation = { tag = OMN value = 1 }
		relation = { tag = PAN value = 10 }
		relation = { tag = PAR value = -20 }
		relation = { tag = PER value = 1 }
		relation = { tag = PHI value = 1 }
		relation = { tag = POL value = 10 }
		relation = { tag = POR value = 10 }
		relation = { tag = PRU value = 20 }
		relation = { tag = ROM value = 10 }
		relation = { tag = SAF value = 10 }
		relation = { tag = SAL value = 10 }
		relation = { tag = SAU value = 20 }
		relation = { tag = SIA value = 1 }
		relation = { tag = SIK value = 1 }
		relation = { tag = SOV value = -10 }
		relation = { tag = SPA value = 25 }
		relation = { tag = SPR value = 15 }
		relation = { tag = SWE value = 10 }
		relation = { tag = SCH value = 50 }
		relation = { tag = TAN value = 1 }
		relation = { tag = TIB value = 1 }
		relation = { tag = TUR value = 15 }
		relation = { tag = U27 value = 1 }
		relation = { tag = URU value = 25 }
		relation = { tag = USA value = 40 }
		relation = { tag = VEN value = 20 }
		relation = { tag = YEM value = 1 }
		relation = { tag = YUG value = 1 }
	}

	SpyInfo = { country = "ARG" NumberOfSpies = 4 }
	SpyInfo = { country = "BOL" NumberOfSpies = 2 }
	SpyInfo = { country = "BRA" NumberOfSpies = 4 }
	SpyInfo = { country = "CHL" NumberOfSpies = 4 }
	SpyInfo = { country = "GER" NumberOfSpies = 1 }
	SpyInfo = { country = "PAR" NumberOfSpies = 2 }
	SpyInfo = { country = "PRU" NumberOfSpies = 1 }
	SpyInfo = { country = "SCH" NumberOfSpies = 1 }
	SpyInfo = { country = "URU" NumberOfSpies = 2 }
	SpyInfo = { country = "USA" NumberOfSpies = 4 }
	SpyInfo = { country = "SPR" NumberOfSpies = 2 }

	SpyInfo = { country = "SPA" NumberOfSpies = 2 }

  headofstate            = { type = 9 id = 35001 }
  headofgovernment       = { type = 9 id = 35002 }
  foreignminister        = { type = 9 id = 35003 }
  armamentminister       = { type = 9 id = 35004 }
  ministerofsecurity     = { type = 9 id = 35005 }
  ministerofintelligence = { type = 9 id = 35006 }
  chiefofstaff           = { type = 9 id = 35007 }
  chiefofarmy            = { type = 9 id = 35008 }
  chiefofnavy            = { type = 9 id = 35009 }
  chiefofair             = { type = 9 id = 35010 }

  nationalidentity = "policy_identity_frustrated" 
  socialpolicy = "policy_social_ethnic" 
  nationalculture = "policy_culture_enterprise"

  # Argentine OOB
  landunit =
  { id       = { type = 12000 id = 1 }
    name     = "I Cuerpo de Ejército"
    location = 667 # Buenos Aires
    division =
    { id       = { type = 12000 id = 5 }
      name     = "Supreme HQ"
      type     = hq
      model    = 0
      strength = 100
      extra    = anti_air
    }
    division =
    { id       = { type = 12000 id = 2 }
      name     = "III Brigada 'Pellegrini'"
      strength = 100
      type     = infantry
      extra    = artillery
    }
    division =
    { id       = { type = 12000 id = 3 }
      name     = "II Brigada 'San Martín'"
      strength = 100
      type     = infantry
      extra    = artillery
    }
    division =
    { id       = { type = 12000 id = 4 }
      name     = "I Brigada 'Ing. Krausse'"
      strength = 100
      type     = infantry
    }
  }
  landunit =
  { id       = { type = 12000 id = 6 }
    name     = "II Cuerpo de Ejército"
    location = 667
    division =
    { id       = { type = 12000 id = 7 }
      name     = "VI Brigada de Montaña 'Villegas'"
      strength = 65
      type     = bergsjaeger
    }
    division =
    { id       = { type = 12000 id = 8 }
      name     = "IV Brigada de Infantería"
      strength = 100
      type     = infantry
    }
  }
  # ################################################
  navalunit =
  { name     = "Argentinian Navy"
    id       = { type = 12000 id = 13 }
    location = 853
    base     = 853
    division =
    { id    = { type = 12000 id = 14 }
      name  = "ARA Veinticinco De Mayo"
      type  = heavy_cruiser
      model = 1
      extra1 = naval_sa_l
      extra2 = naval_anti_air_l
      extra3 = none
      brigade_model1 = 0
      brigade_model2 = 1
      brigade_model3 = 0
      }
    division =
    { id    = { type = 12000 id = 15 }
      name  = "ARA Almirante Brown"
      type  = heavy_cruiser
      model = 1
      extra1 = naval_sa_l
      extra2 = naval_anti_air_l
      extra3 = none
      brigade_model1 = 0
      brigade_model2 = 1
      brigade_model3 = 0
    }
    division =
    { id    = { type = 12000 id = 16 }
      name  = "ARA Moreno"
      type  = battleship
      model = 0
      extra1 = naval_sa_l
      extra2 = naval_anti_air_l
      extra3 = none
      extra4 = none
      extra5 = none
      brigade_model1 = 0
      brigade_model2 = 1
      brigade_model3 = 0
      brigade_model4 = 0
      brigade_model5 = 0
    }
    division =
    { id    = { type = 12000 id = 17 }
      name  = "ARA Rivadavia"
      type  = battleship
      model = 0
      extra1 = naval_sa_l
      extra2 = naval_anti_air_l
      extra3 = none
      extra4 = none
      extra5 = none
      brigade_model1 = 0
      brigade_model2 = 1
      brigade_model3 = 0
      brigade_model4 = 0
      brigade_model5 = 0
    }
    division =
    { id    = { type = 12000 id = 18 }
      name  = "ARA Independencia"
      type  = heavy_cruiser
      model = 0
      extra1 = naval_sa_l
      extra2 = naval_anti_air_l
      extra3 = none
      brigade_model1 = 0
      brigade_model2 = 1
      brigade_model3 = 0
    }
    division =
    { id    = { type = 12000 id = 19 }
      name  = "ARA La Libertad"
      type  = heavy_cruiser
      model = 0
      extra1 = naval_sa_l
      extra2 = naval_anti_air_l
      extra3 = none
      brigade_model1 = 0
      brigade_model2 = 1
      brigade_model3 = 0
    }
    division =
    { id    = { type = 12000 id = 20 }
      name  = "ARA Generale Belgrano"
      type  = light_cruiser
      model = 0
      extra1 = naval_anti_air_s
      extra2 = none
      brigade_model1 = 1
      brigade_model2 = 0
    }
    division =
    { id    = { type = 12000 id = 21 }
      name  = "ARA Generale Pueyrredon"
      type  = light_cruiser
      model = 0
      extra1 = naval_anti_air_s
      extra2 = none
      brigade_model1 = 1
      brigade_model2 = 0
    }
    division =
    { id    = { type = 12000 id = 22 }
      name  = "1st Destroyer Flotilla"
      type  = destroyer
      model = 1
      extra1 = naval_anti_air_s
      brigade_model1 = 1
    }
    division =
    { id    = { type = 12000 id = 23 }
      name  = "2nd Destroyer Flotilla"
      type  = destroyer
      model = 0
      extra1 = naval_anti_air_s
      brigade_model1 = 1
    }
    division =
    { id    = { type = 12000 id = 24 }
      name  = "1st Submarine Flotilla"
      type  = submarine
      model = 1
    }
  }
  # ################################################
  airunit =
  { id       = { type = 12000 id = 9 }
    name     = "Aviación del Ejército"
    location = 667
    base     = 667
    division =
    { id       = { type = 12000 id = 10 }
      name     = "Grupo Aérea Nro. 1"
      strength = 50
      type     = interceptor
      model    = 0
    }
  }
  airunit =
  { id       = { type = 12000 id = 11 }
    name     = "Aviación Naval"
    location = 667
    base     = 667
    division =
    { id       = { type = 12000 id = 12 }
      name     = "Fuerza Aeronaval Nro. 1"
      strength = 50
      type     = naval_bomber
      model    = 0
    }
  } 
	province_development = { 
		id = { type = 12000 id = 25 } 
		name = "" 
		progress = 0.0000 
		location = 843 
		cost = 2.0000 
		date = { 
			year = 1940 
			month = january 
			day = 12 
			hour = 0 
			} 
		manpower = 0.1000 
		close_when_finished = yes 
		waitingforclosure = no 
		total_progress = 0.0000 
		size = 32 
		done = 0 
		days = 2208 
		days_for_first = 96 
		gearing_bonus = 0.0000 
		speed_step = 2 
		type = infrastructure 
		} 
	province_development = { 
		id = { type = 12000 id = 26 } 
		name = "" 
		progress = 0.0000 
		location = 855 
		cost = 2.0000 
		date = { 
			year = 1943 
			month = november 
			day = 5 
			hour = 0 
			} 
		manpower = 0.1000 
		close_when_finished = yes 
		waitingforclosure = no 
		total_progress = 0.0000 
		size = 36 
		done = 0 
		days = 2208 
		days_for_first = 96 
		gearing_bonus = 0.0000 
		type = infrastructure 
		} 
	province_development = { 
		id = { type = 12000 id = 27 } 
		name = "" 
		progress = 0.0000 
		location = 863 
		cost = 2.0000 
		date = { 
			year = 1942 
			month = december 
			day = 26 
			hour = 0 
			} 
		manpower = 0.1000 
		close_when_finished = yes 
		waitingforclosure = no 
		total_progress = 0.0000 
		size = 32 
		done = 0 
		days = 2208 
		days_for_first = 96 
		gearing_bonus = 0.0000 
		type = infrastructure 
		} 
	province_development = { 
		id = { type = 12000 id = 28 } 
		name = "" 
		progress = 0.0000 
		location = 844 
		cost = 2.0000 
		date = { 
			year = 1944 
			month = september 
			day = 25 
			hour = 0 
			} 
		manpower = 0.1000 
		close_when_finished = yes 
		waitingforclosure = no 
		total_progress = 0.0000 
		size = 32 
		done = 0 
		days = 2516 
		days_for_first = 120 
		gearing_bonus = 0.0000 
		type = infrastructure 
		} 
	province_development = { 
		id = { type = 12000 id = 29 } 
		name = "" 
		progress = 0.0000 
		location = 852 
		cost = 2.0000 
		date = { 
			year = 1942 
			month = february 
			day = 17 
			hour = 0 
			} 
		manpower = 0.1000 
		close_when_finished = yes 
		waitingforclosure = no 
		total_progress = 0.0000 
		size = 28 
		done = 0 
		days = 2208 
		days_for_first = 96 
		gearing_bonus = 0.0000 
		type = infrastructure 
		} 
	province_development = { 
		id = { type = 12000 id = 30 } 
		name = "" 
		progress = 0.0000 
		location = 851 
		cost = 2.0000 
		date = { 
			year = 1942 
			month = february 
			day = 17 
			hour = 0 
			} 
		manpower = 0.1000 
		close_when_finished = yes 
		waitingforclosure = no 
		total_progress = 0.0000 
		size = 28 
		done = 0 
		days = 2208 
		days_for_first = 96 
		gearing_bonus = 0.0000 
		type = infrastructure 
		} 
	province_development = { 
		id = { type = 12000 id = 31 } 
		name = "" 
		progress = 0.0000 
		location = 845 
		cost = 2.0000 
		date = { 
			year = 1946 
			month = june 
			day = 24 
			hour = 0 
			} 
		manpower = 0.1000 
		close_when_finished = yes 
		waitingforclosure = no 
		total_progress = 0.0000 
		size = 32 
		done = 0 
		days = 2516 
		days_for_first = 144 
		gearing_bonus = 0.0000 
		type = infrastructure 
		} 
	province_development = { 
		id = { type = 12000 id = 32 } 
		name = "" 
		progress = 0.0000 
		location = 667 
		cost = 2.0000 
		date = { 
			year = 1941 
			month = june 
			day = 26 
			hour = 0 
			} 
		manpower = 0.1000 
		close_when_finished = yes 
		waitingforclosure = no 
		total_progress = 0.0000 
		size = 25 
		done = 0 
		days = 2208 
		days_for_first = 96 
		gearing_bonus = 0.0000 
		type = infrastructure 
		} 
	brigade_development = { 
		id = { type = 12000 id = 33 } 
		name = "Basic Sea Mines" 
		progress = 0.0000 
		location = 667 
		cost = 0.1600 
		date = { 
			year = 1936 
			month = september 
			day = 16 
			hour = 0 
			} 
		manpower = 0.0500 
		close_when_finished = yes 
		waitingforclosure = no 
		retooling_time = 40.0000 
		total_progress = 0.0000 
		size = 5 
		done = 0 
		days = 40 
		days_for_first = 48 
		gearing_bonus = 0.0000 
		type = naval_mines 
		model = 0 
		} 
	brigade_development = { 
		id = { type = 12000 id = 34 } 
		name = "Capital Torpedoes" 
		progress = 0.0000 
		location = 667 
		cost = 0.4800 
		date = { 
			year = 1936 
			month = october 
			day = 14 
			hour = 0 
			} 
		manpower = 0.0500 
		close_when_finished = yes 
		waitingforclosure = no 
		retooling_time = 30.0000 
		total_progress = 0.0000 
		size = 6 
		done = 0 
		days = 255 
		days_for_first = 48 
		gearing_bonus = 0.0000 
		type = naval_torpedoes_l 
		model = 0 
		} 
}
