###################################################################################
# Naval Bases mostly from CORE mod, modified by Jarski
###################################################################################

#############################
# Albania
#############################

province = { id = 390 naval_base = { type = naval_base size = 1 current_size = 1 } } # Tirana

#############################
# Argentina
#############################

province = { id = 667 naval_base = { type = naval_base size = 2 current_size = 2 } } # Buenos Aires
province = { id = 853 naval_base = { type = naval_base size = 3 current_size = 3 } } # Bahia Blanca

#############################
# Australia
#############################

province = { id = 1670 naval_base = { type = naval_base size = 1 current_size = 1 } } # Rabaul
province = { id = 1679 naval_base = { type = naval_base size = 1 current_size = 1 } } # Port Moresby
province = { id = 1696 naval_base = { type = naval_base size = 1 current_size = 1 } } # Townsville
province = { id = 1703 naval_base = { type = naval_base size = 1 current_size = 1 } } # Darwin
province = { id = 1712 naval_base = { type = naval_base size = 2 current_size = 2 } } # Perth
province = { id = 1722 naval_base = { type = naval_base size = 1 current_size = 1 } } # Brisbane
province = { id = 1727 naval_base = { type = naval_base size = 5 current_size = 5 } } # Sydney
province = { id = 1729 naval_base = { type = naval_base size = 1 current_size = 1 } } # Tasmania
province = { id = 1730 naval_base = { type = naval_base size = 1 current_size = 1 } } # Melbourne
province = { id = 1733 naval_base = { type = naval_base size = 1 current_size = 1 } } # Adelaide

#############################
# Belgium
#############################

province = { id = 45   naval_base = { type = naval_base size = 2 current_size = 2 } } # Ghent
province = { id = 1095 naval_base = { type = naval_base size = 1 current_size = 1 } } # Banana
province = { id = 1127 air_base = { type = air_base size = 1 current_size = 1 } } # Elisabethville
province = { id = 1142 air_base = { type = air_base size = 1 current_size = 1 } } # Leopoldville


#############################
# Brazil
#############################

province = { id = 879 naval_base = { type = naval_base size = 1 current_size = 1 } } # Belem
province = { id = 881 naval_base = { type = naval_base size = 2 current_size = 2 } } # Recife
province = { id = 885 naval_base = { type = naval_base size = 3 current_size = 3 } } # Rio de Janeiro
province = { id = 886 naval_base = { type = naval_base size = 2 current_size = 2 } } # São Paulo

#############################
# Bulgaria
#############################

province = { id = 422 naval_base = { type = naval_base size = 1 current_size = 1 } } # Varna

#############################
# Canada
#############################
province = { id = 541 naval_base = { type = naval_base size = 2 current_size = 2 } } # Vancouver 
province = { id = 556 naval_base = { type = naval_base size = 2 current_size = 2 } } # Vancouver Island
province = { id = 579 naval_base = { type = naval_base size = 4 current_size = 4 } } # Halifax
province = { id = 586 naval_base = { type = naval_base size = 2 current_size = 2 } } # Quebec City

#############################
# Chile
#############################

province = { id = 840 naval_base = { type = naval_base size = 3 current_size = 3 } } # Santiago
province = { id = 856 naval_base = { type = naval_base size = 1 current_size = 1 } } # Puerto Montt

#############################
# Columbia
#############################

province = { id = 803 naval_base = { type = naval_base size = 1 current_size = 1 } } # Barranquilla

#############################
# Costa Rica
#############################

# No Naval Bases

#############################
# Cuba
#############################

province = { id = 654 naval_base = { type = naval_base size = 1 current_size = 1 } } # Havana
province = { id = 657 naval_base = { type = naval_base size = 1 current_size = 1 } } # Guantamano

#############################
# Denmark
#############################

province = { id = 1   naval_base = { type = naval_base size = 1 current_size = 1 } } # Reykjavik
province = { id = 292 naval_base = { type = naval_base size = 1 current_size = 1 } } # Aalborg
province = { id = 294 naval_base = { type = naval_base size = 4 current_size = 4 } } # Copenhagen

#############################
# Dominican Republic
#############################

# No Naval Bases

#############################
# Ecuador
#############################

province = { id = 815 naval_base = { type = naval_base size = 1 current_size = 1 } } # Quito

#############################
# Egypt
#############################

province = { id = 901 naval_base = { type = naval_base size = 2 current_size = 2 } } # Port Said
province = { id = 906 naval_base = { type = naval_base size = 5 current_size = 5 } } # Alexandria

#############################
# El Salvador
#############################

#No Naval Bases

#############################
# Estonia
#############################

province = { id = 194  naval_base = { type = naval_base size = 4 current_size = 4 } } # Tallinn

#############################
# Finland
#############################

province = { id = 141  naval_base = { type = naval_base size = 2 current_size = 2 } } # Turku
province = { id = 142  naval_base = { type = naval_base size = 4 current_size = 4 } } # Helsinki
province = { id = 132  naval_base = { type = naval_base size = 1 current_size = 1 } } # Petsamo

#############################
# France
#############################

province = { id = 32   naval_base = { type = naval_base size = 7 current_size = 7 } } # Brest
province = { id = 34   naval_base = { type = naval_base size = 4 current_size = 4 } } # Lorient
province = { id = 35   naval_base = { type = naval_base size = 7 current_size = 7 } } # Nantes/St. Nazaire
province = { id = 38   naval_base = { type = naval_base size = 3 current_size = 3 } } # Cherbourg
province = { id = 41   naval_base = { type = naval_base size = 2 current_size = 2 } } # Le Havre
province = { id = 325  naval_base = { type = naval_base size = 3 current_size = 3 } } # Bourdeaux
province = { id = 364  naval_base = { type = naval_base size = 4 current_size = 4 } } # Marseille
province = { id = 365  naval_base = { type = naval_base size = 5 current_size = 5 } } # Toulon
province = { id = 939  naval_base = { type = naval_base size = 1 current_size = 1 } } # Tunis
province = { id = 940  naval_base = { type = naval_base size = 3 current_size = 3 } } # Bizerte
province = { id = 953  naval_base = { type = naval_base size = 2 current_size = 2 } } # Oran
province = { id = 958  naval_base = { type = naval_base size = 2 current_size = 2 } } # Casablanca
province = { id = 981  naval_base = { type = naval_base size = 2 current_size = 2 } } # Dakar

province = { id = 1037 naval_base = { type = naval_base size = 1 current_size = 1 } } # Djibouti
province = { id = 1137 naval_base = { type = naval_base size = 1 current_size = 1 } } # Tananarive
province = { id = 1328 naval_base = { type = naval_base size = 1 current_size = 1 } } # Hanoi
province = { id = 1337 naval_base = { type = naval_base size = 2 current_size = 2 } } # Saigon
province = { id = 1751 naval_base = { type = naval_base size = 1 current_size = 1 } } # Tahiti
province = { id = 1794 naval_base = { type = naval_base size = 1 current_size = 1 } } # Beirut

#############################
# Germany
#############################

province = { id = 80  naval_base = { type = naval_base size = 10 current_size = 10 } } # Wilhelmshaven
province = { id = 87  naval_base = { type = naval_base size = 6  current_size = 6  } } # Bremen (also represents the port of Hamburg)
province = { id = 89  naval_base = { type = naval_base size = 4  current_size = 4  } } # Lübeck
province = { id = 90  naval_base = { type = naval_base size = 8  current_size = 8  } } # Kiel
province = { id = 296 naval_base = { type = naval_base size = 1  current_size = 1  } } # Rostock
province = { id = 510 naval_base = { type = naval_base size = 2  current_size = 2  } } # Königsberg

#############################
# Greece
#############################

province = { id = 400  naval_base = { type = naval_base size = 1  current_size = 1 } } # The Cyclades
province = { id = 396  naval_base = { type = naval_base size = 1  current_size = 1 } } # Crete
province = { id = 401  naval_base = { type = naval_base size = 3  current_size = 3 } } # Athens

#############################
# Guatemala
#############################

# No Naval Bases

#############################
# Haiti
#############################

# No Naval Bases

#############################
# Hondurus
#############################

# No Naval Bases

#############################
# India / Burma
#############################

province = { id = 1299 naval_base = { type = naval_base size = 2 current_size = 2 } } # Rangoon
province = { id = 1457 naval_base = { type = naval_base size = 1 current_size = 1 } } # Calcutta
province = { id = 1494 naval_base = { type = naval_base size = 1 current_size = 1 } } # Karachi
province = { id = 1505 naval_base = { type = naval_base size = 3 current_size = 3 } } # Bombay
province = { id = 1509 naval_base = { type = naval_base size = 1 current_size = 1 } } # Madras

#############################
# Iraq
#############################

province = { id = 1823 naval_base = { type = naval_base size = 1 current_size = 1 } } # Basrah

#############################
# Ireland
#############################

province = { id = 30   naval_base = { type = naval_base size = 2 current_size = 2 } } # Dublin

#############################
# Italy
#############################

province = { id = 368  naval_base = { type = naval_base size = 7 current_size = 7 } } # Genoa
province = { id = 369  naval_base = { type = naval_base size = 5 current_size = 5 } } # La Spezia
province = { id = 378  naval_base = { type = naval_base size = 7 current_size = 7 } } # Venice - Trieste 
province = { id = 513  naval_base = { type = naval_base size = 4 current_size = 4 } } # Florence - Livorno
province = { id = 517  naval_base = { type = naval_base size = 2 current_size = 2 } } # Pescara - Ancona
province = { id = 521  naval_base = { type = naval_base size = 5 current_size = 5 } } # Naples
province = { id = 523  naval_base = { type = naval_base size = 5 current_size = 5 } } # Taranto
province = { id = 525  naval_base = { type = naval_base size = 2 current_size = 2 } } # Palermo
province = { id = 534  naval_base = { type = naval_base size = 2 current_size = 2 } } # Sardinia

province = { id = 398  naval_base = { type = naval_base size = 1 current_size = 1 } } # Dodecanese
province = { id = 399  naval_base = { type = naval_base size = 1 current_size = 1 } } # Rhodes
province = { id = 919  naval_base = { type = naval_base size = 1 current_size = 1 } } # Tobruk
province = { id = 932  naval_base = { type = naval_base size = 1 current_size = 1 } } # Tripoli
province = { id = 1033 naval_base = { type = naval_base size = 1 current_size = 1 } } # Massaua

#############################
# Japan
#############################

province = { id = 1179 naval_base = { type = naval_base size = 1  current_size = 1  } } # Sapporo
province = { id = 1181 naval_base = { type = naval_base size = 2  current_size = 2  } } # Akita
province = { id = 1184 naval_base = { type = naval_base size = 10 current_size = 10 } } # Tokyo
province = { id = 1185 naval_base = { type = naval_base size = 2  current_size = 2  } } # Nagoya
province = { id = 1186 naval_base = { type = naval_base size = 4  current_size = 4  } } # Kanazawa
province = { id = 1187 naval_base = { type = naval_base size = 4  current_size = 4  } } # Osaka
province = { id = 1188 naval_base = { type = naval_base size = 6  current_size = 6  } } # Hiroshima
province = { id = 1190 naval_base = { type = naval_base size = 8  current_size = 8  } } # Fukuoka
province = { id = 1196 naval_base = { type = naval_base size = 3  current_size = 3  } } # Busan
province = { id = 1202 naval_base = { type = naval_base size = 3  current_size = 3  } } # Dalian
province = { id = 1322 naval_base = { type = naval_base size = 3  current_size = 3  } } # Kaohsiung
province = { id = 1608 naval_base = { type = naval_base size = 1  current_size = 1  } } # Kwajalein
province = { id = 1613 naval_base = { type = naval_base size = 3  current_size = 3  } } # Truk
province = { id = 1621 naval_base = { type = naval_base size = 1  current_size = 1  } } # Palau
province = { id = 1627 naval_base = { type = naval_base size = 1  current_size = 1  } } # Saipan
province = { id = 1785 naval_base = { type = naval_base size = 1  current_size = 1  } } # Marcus Island
province = { id = 1601 naval_base = { type = naval_base size = 1  current_size = 1  } } # Eniwetok

#############################
# Latvia
#############################

province = { id = 197 naval_base = { type = naval_base size = 4 current_size = 4 } } # Riga

#############################
# Liberia
#############################

# No Naval Bases

#############################
# Lithuania
#############################

province = { id = 206 naval_base = { type = naval_base size = 2 current_size = 2 } } # Memel

#############################
# Mexico
#############################

province = { id = 754 naval_base = { type = naval_base size = 1 current_size = 1 } } # Acapulco
province = { id = 755 naval_base = { type = naval_base size = 1 current_size = 1 } } # Villahermosa

#############################
# Nationalist China
#############################

province = { id = 1214 naval_base = { type = naval_base size = 1 current_size = 1 } } # Yantai
province = { id = 1215 naval_base = { type = naval_base size = 1 current_size = 1 } } # Quindao
province = { id = 1237 naval_base = { type = naval_base size = 4 current_size = 4 } } # Shanghai
province = { id = 1244 naval_base = { type = naval_base size = 1 current_size = 1 } } # Fuzhou
province = { id = 1248 naval_base = { type = naval_base size = 2 current_size = 2 } } # Shantou
province = { id = 1313 naval_base = { type = naval_base size = 3 current_size = 3 } } # Guangzhou
province = { id = 1321 naval_base = { type = naval_base size = 1 current_size = 1 } } # Hainan
province = { id = 1247 naval_base = { type = naval_base size = 1 current_size = 1 } } # Xiamen
province = { id = 1239 naval_base = { type = naval_base size = 1 current_size = 1 } } # Ningbo

#############################
# Netherlands
#############################

province = { id = 46   naval_base = { type = naval_base size = 4 current_size = 4 } } # Rotterdam
province = { id = 47   naval_base = { type = naval_base size = 6 current_size = 6 } } # Amsterdam

province = { id = 801  naval_base = { type = naval_base size = 1 current_size = 1 } } # Curacao

#############################
# Netherlands East Indies
#############################

province = { id = 1358 naval_base = { type = naval_base size = 1 current_size = 1 } } # Palembang
province = { id = 1628 naval_base = { type = naval_base size = 2 current_size = 2 } } # Batavia
province = { id = 1629 naval_base = { type = naval_base size = 1 current_size = 1 } } # Tjilatjap
province = { id = 1632 naval_base = { type = naval_base size = 4 current_size = 4 } } # Soerabaja
province = { id = 1642 naval_base = { type = naval_base size = 1 current_size = 1 } } # Pontianak
province = { id = 1650 naval_base = { type = naval_base size = 1 current_size = 1 } } # Balikipapan
province = { id = 1656 naval_base = { type = naval_base size = 1 current_size = 1 } } # Ceram

#############################
# New Zealand
#############################

province = { id = 1871 naval_base = { type = naval_base size = 4 current_size = 4 } } # Wellington

#############################
# Nicaragua
#############################

#No Naval Bases

#############################
# Norway
#############################

province = { id = 107 naval_base = { type = naval_base size = 3 current_size = 3 } } # Oslo
province = { id = 108 naval_base = { type = naval_base size = 2 current_size = 2 } } # Kristenland
province = { id = 110 naval_base = { type = naval_base size = 1 current_size = 1 } } # Bergen
Province = { id = 118 naval_base = { type = naval_base size = 2 current_size = 2 } } # Trondheim
province = { id = 125 naval_base = { type = naval_base size = 2 current_size = 2 } } # Narvik
province = { id = 117 naval_base = { type = naval_base size = 1 current_size = 1 } } # Ålesund

#############################
# Oman
#############################

province = { id = 1819 naval_base = { type = naval_base size = 1 current_size = 1 } } # Mascate

#############################
# Panama
#############################

#No Naval Bases

#############################
# Persia
#############################

province = { id = 1497 naval_base = { type = naval_base size = 1 current_size = 1 } } # Bandar Abbas

#############################
# Peru
#############################

province = { id = 830  naval_base = { type = naval_base size = 2 current_size = 2 } } # Lima

#############################
# Philippines
#############################

province = { id = 1737 naval_base = { type = naval_base size = 6 current_size = 6 } } # Manila
province = { id = 1750 naval_base = { type = naval_base size = 1 current_size = 1 } } # Davao

#############################
# Poland
#############################

province = { id = 303  naval_base = { type = naval_base size = 4 current_size = 4 } } # Danzig

#############################
# Portugal
#############################

province = { id = 336  naval_base = { type = naval_base size = 4 current_size = 4 } } # Lissabon
province = { id = 1096 naval_base = { type = naval_base size = 1 current_size = 1 } } # Loanda
province = { id = 1122 naval_base = { type = naval_base size = 1 current_size = 1 } } # Lourenço Marques
province = { id = 1146 naval_base = { type = naval_base size = 1 current_size = 1 } } # Cap Verde Islands
province = { id = 1316 naval_base = { type = naval_base size = 1 current_size = 1 } } # Macao
province = { id = 1658 naval_base = { type = naval_base size = 1 current_size = 1 } } # East Timor
province = { id = 1867 naval_base = { type = naval_base size = 1 current_size = 1 } } # The Azores

#############################
# Romania
#############################

province = { id = 423 naval_base = { type = naval_base size = 3 current_size = 3 } } # Constanta

#############################
# Saudi Arabia
#############################

# No Naval Bases

#############################
# Shanxi 
#############################

province = { id = 1204 naval_base = { type = naval_base size = 1 current_size = 1 } } # Tianjin

#############################
# Siam
#############################

province = { id = 1343 naval_base = { type = naval_base size = 1 current_size = 1 } } # Bangkok
province = { id = 1345 naval_base = { type = naval_base size = 3 current_size = 3 } } # Thom Buri

#############################
# Spain
#############################

province = { id = 334 air_base = { type = air_base size = 2  current_size = 2} }
province = { id = 349 air_base = { type = air_base size = 1  current_size = 1} }
province = { id = 351 air_base = { type = air_base size = 2  current_size = 2} }
province = { id = 339 air_base = { type = air_base size = 2  current_size = 1} }
province = { id = 353 air_base = { type = air_base size = 2  current_size = 2} }
province = { id = 334 naval_base = { type = naval_base size = 5 current_size = 5 } } # La Coruña - El Ferrol
province = { id = 347 naval_base = { type = naval_base size = 3 current_size = 3 } } # Seville
province = { id = 352 naval_base = { type = naval_base size = 4 current_size = 4 } } # Murcia
province = { id = 357 naval_base = { type = naval_base size = 2 current_size = 2 } } # Barcelona
province = { id = 536 naval_base = { type = naval_base size = 2 current_size = 2 } } # Menorca
province = { id = 957 naval_base = { type = naval_base size = 1 current_size = 1 } } # Ceuta
province = { id = 964 naval_base = { type = naval_base size = 1 current_size = 1 } } # Tenerife
province = { id = 1091 naval_base = { type = naval_base size = 1 current_size = 1 } } # Bata

#############################
# South Africa (incl SW Africa)
#############################

province = { id = 1108 naval_base = { type = naval_base size = 1 current_size = 1 } } # Walvis Bay
province = { id = 1116 naval_base = { type = naval_base size = 4 current_size = 4 } } # Cape Town
province = { id = 1119 naval_base = { type = naval_base size = 2 current_size = 2 } } # Durban

#############################
# Sweden
#############################

province = { id = 93  naval_base = { type = naval_base size = 2 current_size = 2 } } # Malmö
province = { id = 95  naval_base = { type = naval_base size = 2 current_size = 2 } } # Karlskrona
province = { id = 98  naval_base = { type = naval_base size = 2 current_size = 2 } } # Göteborg
province = { id = 101 naval_base = { type = naval_base size = 5 current_size = 5 } } # Stockholm

#############################
# Turkey
#############################

province = { id = 409 naval_base = { type = naval_base size = 4 current_size = 4 } } # Istanbul
province = { id = 437 naval_base = { type = naval_base size = 1 current_size = 1 } } # Izmir

#############################
# United Kingdom
#############################

province = { id = 5  naval_base = { type = naval_base size = 6  current_size = 6  } } # Scapa Flow
province = { id = 8  naval_base = { type = naval_base size = 6  current_size = 6  } } # Dunfermline - Rosyth
province = { id = 9  naval_base = { type = naval_base size = 6  current_size = 6  } } # Glasgow
province = { id = 10 naval_base = { type = naval_base size = 6  current_size = 6  } } # Edinburgh
province = { id = 11 naval_base = { type = naval_base size = 4  current_size = 4  } } # Sunderland
province = { id = 12 naval_base = { type = naval_base size = 2  current_size = 2  } } # Blackpool
province = { id = 13 naval_base = { type = naval_base size = 4  current_size = 4  } } # Sheffield
province = { id = 14 naval_base = { type = naval_base size = 7  current_size = 7  } } # Liverpool
province = { id = 15 naval_base = { type = naval_base size = 4  current_size = 4  } } # Cardiff
province = { id = 17 naval_base = { type = naval_base size = 4  current_size = 4  } } # Norwich
province = { id = 20 naval_base = { type = naval_base size = 8  current_size = 8  } } # Dover
province = { id = 21 naval_base = { type = naval_base size = 10 current_size = 10 } } # Portsmouth
province = { id = 22 naval_base = { type = naval_base size = 3  current_size = 3  } } # Bristol
province = { id = 23 naval_base = { type = naval_base size = 8  current_size = 8  } } # Plymouth
province = { id = 28 naval_base = { type = naval_base size = 6  current_size = 6  } } # Belfast

province = { id = 31   naval_base = { type = naval_base size = 4 current_size = 4 } } # Malta
province = { id = 348  naval_base = { type = naval_base size = 6 current_size = 6 } } # Gibraltar
province = { id = 538  naval_base = { type = naval_base size = 1 current_size = 1 } } # Bermuda
province = { id = 576  naval_base = { type = naval_base size = 1 current_size = 1 } } # Newfoundland
province = { id = 807  naval_base = { type = naval_base size = 1 current_size = 1 } } # Barbados
province = { id = 809  naval_base = { type = naval_base size = 1 current_size = 1 } } # Trinidad
province = { id = 866  naval_base = { type = naval_base size = 1 current_size = 1 } } # Falkland Islands
province = { id = 891  naval_base = { type = naval_base size = 1 current_size = 1 } } # Jamaica
province = { id = 988  naval_base = { type = naval_base size = 1 current_size = 1 } } # Freetown
province = { id = 1008 naval_base = { type = naval_base size = 3 current_size = 3 } } # Lagos
province = { id = 1148 naval_base = { type = naval_base size = 1 current_size = 1	} } # St. Helena
province = { id = 1315 naval_base = { type = naval_base size = 6 current_size = 3 } } # Hong Kong
province = { id = 1353 naval_base = { type = naval_base size = 8 current_size = 6 } } # Singapore
province = { id = 1516 naval_base = { type = naval_base size = 4 current_size = 4 } } # Trincomalee
province = { id = 1517 naval_base = { type = naval_base size = 1 current_size = 1 } } # Colombo
province = { id = 1813 naval_base = { type = naval_base size = 2 current_size = 2 } } # Aden
province = { id = 1822 naval_base = { type = naval_base size = 1 current_size = 1 } } # Kuwait City
province = { id = 1064 air_base = { type = air_base size = 2 current_size = 2 } } # Entebbe


#############################
# Uruguay
#############################

province = { id = 849  naval_base = { type = naval_base size = 1 current_size = 1 } } # Montevideo

#############################
# United States
#############################

province = { id = 549  naval_base = { type = naval_base size = 1  current_size = 1  } } # Anchorage
province = { id = 583  naval_base = { type = naval_base size = 2  current_size = 2  } } # Portland, ME
province = { id = 596  naval_base = { type = naval_base size = 5  current_size = 5  } } # Manchester - Portsmouth
province = { id = 600  naval_base = { type = naval_base size = 8  current_size = 8  } } # Boston
province = { id = 601  naval_base = { type = naval_base size = 5  current_size = 5  } } # Hartford
province = { id = 602  naval_base = { type = naval_base size = 10 current_size = 10 } } # New York
province = { id = 603  naval_base = { type = naval_base size = 6  current_size = 6  } } # Newark
province = { id = 605  naval_base = { type = naval_base size = 8  current_size = 8  } } # Dover - Philadelphia
province = { id = 606  naval_base = { type = naval_base size = 3  current_size = 3  } } # Washington DC
province = { id = 607  naval_base = { type = naval_base size = 2  current_size = 2  } } # Baltimore
province = { id = 633  naval_base = { type = naval_base size = 10 current_size = 10 } } # Norfolk
province = { id = 644  naval_base = { type = naval_base size = 4  current_size = 4  } } # Charleston, SC
province = { id = 651  naval_base = { type = naval_base size = 1  current_size = 1  } } # Miami
province = { id = 663  naval_base = { type = naval_base size = 8  current_size = 8  } } # Pearl Harbor
province = { id = 676  naval_base = { type = naval_base size = 1  current_size = 1  } } # Mobile
province = { id = 748  naval_base = { type = naval_base size = 1  current_size = 1  } } # Corpus Christi
province = { id = 761  naval_base = { type = naval_base size = 6  current_size = 6  } } # San Diego
province = { id = 762  naval_base = { type = naval_base size = 6  current_size = 6  } } # Los Angeles
province = { id = 765  naval_base = { type = naval_base size = 7  current_size = 7  } } # San Francisco
province = { id = 782  naval_base = { type = naval_base size = 6  current_size = 6  } } # Tacoma

province = { id = 889  naval_base = { type = naval_base size = 4  current_size = 4  } } # Canal Zone
province = { id = 895  naval_base = { type = naval_base size = 2  current_size = 2  } } # Puerto Rico
province = { id = 1624 naval_base = { type = naval_base size = 1  current_size = 1  } } # Guam


#############################
# Soviet Union
#############################

province = { id = 154  naval_base = { type = naval_base size = 4 current_size = 4 } } # Archangelsk
province = { id = 133  naval_base = { type = naval_base size = 2 current_size = 2 } } # Murmansk
province = { id = 187  naval_base = { type = naval_base size = 8 current_size = 8 } } # Leningrad
province = { id = 234  naval_base = { type = naval_base size = 6 current_size = 6 } } # Kershon - Nikolayev
#province = { id = 253  
#anti_air = { type = flak size = 1.0000 current_size = 1.0000 } 
#naval_base = { type = naval_base size = 4 current_size = 4 } 
#air_base = { type = air_base size = 2  current_size = 2 }
#landfort = { type = land_fort size = 3.0000 current_size = 3.0000 }
#coastalfort = { type = coastal_fort size = 5.0000 current_size = 5.0000 }
#} # Sevastopol
province = { id = 255  naval_base = { type = naval_base size = 2 current_size = 2 } } # Novorossisk
province = { id = 1172 naval_base = { type = naval_base size = 1 current_size = 1 } } # Petropavlovsk-Kamchatskij
province = { id = 1372 naval_base = { type = naval_base size = 4 current_size = 4 } } # Vladivostok

#############################
# Venezuela
#############################

province = { id = 804  naval_base = { type = naval_base size = 1 current_size = 1 } } # Maracaibo

#############################
# Yemen
#############################

province = { id = 1812 naval_base = { type = naval_base size = 1 current_size = 1 } } # Sanaa

#############################
# Yugoslavia
#############################

province = { id = 384  naval_base = { type = naval_base size = 1 current_size = 1 } } # Split
province = { id = 388  naval_base = { type = naval_base size = 1 current_size = 1 } } # Dubrovnik
province = { id = 389  naval_base = { type = naval_base size = 1 current_size = 1 } } # Podgorica


###############################################################################################
# Air bases
###############################################################################################

#############################
# Afghanistan
#############################

province = { id = 1486 air_base = { type = air_base size = 1 current_size = 1 } } # Kabul

#############################
# Albania
#############################

province = { id = 390 air_base = { type = air_base size = 1 current_size = 1 } } # Tirana

#############################
# Argentina
#############################

province = { id = 667 air_base = { type = air_base size = 1 current_size = 1 } } # Buenos Aires
province = { id = 853 air_base = { type = air_base size = 1 current_size = 1 } } # Bahia Blanca

#############################
# Australia
#############################

province = { id = 1669 air_base = { type = air_base size = 1 current_size = 1 } } # New Ireland
province = { id = 1670 air_base = { type = air_base size = 1 current_size = 1 } } # Rabaul
province = { id = 1672 air_base = { type = air_base size = 1 current_size = 1 } } # Lae
province = { id = 1679 air_base = { type = air_base size = 1 current_size = 1 } } # Port Moresby
province = { id = 1682 air_base = { type = air_base size = 1 current_size = 1 } } # Bougainville
province = { id = 1693 air_base = { type = air_base size = 1 current_size = 1 } } # Cairns
province = { id = 1696 air_base = { type = air_base size = 1 current_size = 1 } } # Townsville
province = { id = 1698 air_base = { type = air_base size = 1 current_size = 1 } } # Rockhampton
province = { id = 1703 air_base = { type = air_base size = 1 current_size = 1 } } # Darwin
province = { id = 1712 air_base = { type = air_base size = 1 current_size = 1 } } # Perth
province = { id = 1722 air_base = { type = air_base size = 1 current_size = 1 } } # Brisbane
province = { id = 1727 air_base = { type = air_base size = 2 current_size = 2 } } # Sydney
province = { id = 1728 air_base = { type = air_base size = 1 current_size = 1 } } # Canberra
province = { id = 1729 air_base = { type = air_base size = 1 current_size = 1 } } # Tasmania
province = { id = 1730 air_base = { type = air_base size = 1 current_size = 1 } } # Melbourne
province = { id = 1732 air_base = { type = air_base size = 1 current_size = 1 } } # Mount Gambier

#############################
# Austria
#############################

province = { id = 377  air_base = { type = air_base size = 2 current_size = 2 } } # Innsbruck
province = { id = 463  air_base = { type = air_base size = 3 current_size = 3 } } # Vienna

#############################
# Belgium
#############################

province = { id = 45   air_base = { type = air_base size = 2 current_size = 2 } } # Ghent
province = { id = 50   air_base = { type = air_base size = 2 current_size = 2 } } # Antwerp
province = { id = 51   air_base = { type = air_base size = 3 current_size = 3 } } # Brussels

province = { id = 1095 air_base = { type = air_base size = 1 current_size = 1 } } # Banana

#############################
# Bolivia
#############################

province = { id = 832 air_base = { type = air_base size = 1 current_size = 1 } } # La Paz

#############################
# Brazil
#############################

province = { id = 848 air_base = { type = air_base size = 1 current_size = 1 } } # Pôrto Alegre
province = { id = 885 air_base = { type = air_base size = 1 current_size = 1 } } # Rio de Janeiro
province = { id = 886 air_base = { type = air_base size = 1 current_size = 1 } } # São Paulo

#############################
# Bulgaria
#############################

province = { id = 417 air_base = { type = air_base size = 2 current_size = 2 } } # Sofia
province = { id = 422 air_base = { type = air_base size = 1 current_size = 1 } } # Varna
 
#############################
# Canada
#############################

province = { id = 541 air_base = { type = air_base size = 1 current_size = 1 } } # Vancouver
province = { id = 569 air_base = { type = air_base size = 1 current_size = 1 } } # Winnipeg
province = { id = 579 air_base = { type = air_base size = 1 current_size = 1 } } # Halifax
province = { id = 581 air_base = { type = air_base size = 1 current_size = 1 } } # Saint Johns
province = { id = 585 air_base = { type = air_base size = 1 current_size = 1 } } # Montréal
province = { id = 586 air_base = { type = air_base size = 1 current_size = 1 } } # Québec City
province = { id = 588 air_base = { type = air_base size = 1 current_size = 1 } } # Ottawa
province = { id = 797 air_base = { type = air_base size = 2 current_size = 2 } } # Calgary

#############################
# Chile
#############################

province = { id = 840 air_base = { type = air_base size = 1 current_size = 1 } } # Santiago

#############################
# Colombia
#############################

province = { id = 803 air_base = { type = air_base size = 1 current_size = 1 } } # Barranquilla

#############################
# Costa Rica
#############################

province = { id = 540 air_base = { type = air_base size = 1 current_size = 1 } } # San José

#############################
# Cuba
#############################

province = { id = 654 air_base = { type = air_base size = 1 current_size = 1 } } # Havana

#############################
# Czechoslovakia
#############################

province = { id = 466 air_base = { type = air_base size = 2 current_size = 2 } } # Strakonice
province = { id = 469 air_base = { type = air_base size = 2 current_size = 2 } } # Prague
province = { id = 475 air_base = { type = air_base size = 1 current_size = 1 } } # Brno
province = { id = 476 air_base = { type = air_base size = 1 current_size = 1 } } # Bratislava

#############################
# Denmark
#############################

province = { id = 92  air_base = { type = air_base size = 1 current_size = 1 } } # Århus
province = { id = 292 air_base = { type = air_base size = 1 current_size = 1 } } # Aalborg
province = { id = 294 air_base = { type = air_base size = 2 current_size = 2 } } # Copenhagen

province = { id = 1   air_base = { type = air_base size = 1 current_size = 1 } } # Reykjavik

#############################
# Dominican Republic
#############################

province = { id = 894 air_base = { type = air_base size = 1 current_size = 1 } } # Santo Domingo

#############################
# Ecuador
#############################

province = { id = 815 air_base = { type = air_base size = 1 current_size = 1 } } # Quito

#############################
# El Salvador
#############################

province = { id = 759 air_base = { type = air_base size = 1 current_size = 1 } } # San Salvador

#############################
# Egypt
#############################

province = { id = 901 air_base = { type = air_base size = 2 current_size = 2 } } # Port Said
province = { id = 903 air_base = { type = air_base size = 2 current_size = 2 } } # Cairo
province = { id = 906 air_base = { type = air_base size = 2 current_size = 2 } } # Alexandria
province = { id = 911 air_base = { type = air_base size = 2 current_size = 2 } } # Mersah Matruh

#############################
# Estonia
#############################

province = { id = 194 air_base = { type = air_base size = 1 current_size = 1 } } # Tallinn

#############################
# Ethiopia
#############################

province = { id = 1046 air_base = { type = air_base size = 1 current_size = 1 } } # Addis Ababa

#############################
# Finland
#############################

province = { id = 132 air_base = { type = air_base size = 1 current_size = 1 } } # Petsamo
province = { id = 137 air_base = { type = air_base size = 1 current_size = 1 } } # Oulu
province = { id = 141 air_base = { type = air_base size = 1 current_size = 1 } } # Turku
province = { id = 142 air_base = { type = air_base size = 3 current_size = 3 } } # Helsinki
province = { id = 143 air_base = { type = air_base size = 1 current_size = 1 } } # Tampere

#############################
# France
#############################

province = { id = 18  air_base = { type = air_base size = 3 current_size = 3 } } # Calais
province = { id = 32  air_base = { type = air_base size = 3 current_size = 3 } } # Brest
province = { id = 38  air_base = { type = air_base size = 3 current_size = 3 } } # Cherbourg
province = { id = 41  air_base = { type = air_base size = 3 current_size = 3 } } # Le Havre
province = { id = 44  air_base = { type = air_base size = 2 current_size = 2 } } # Lille
province = { id = 56  air_base = { type = air_base size = 6 current_size = 6 } } # Paris
province = { id = 59  air_base = { type = air_base size = 2 current_size = 2 } } # Cholet
province = { id = 72  air_base = { type = air_base size = 4 current_size = 4 } } # Metz
province = { id = 318 air_base = { type = air_base size = 3 current_size = 3 } } # Dijon
province = { id = 325 air_base = { type = air_base size = 3 current_size = 3 } } # Bordeaux
province = { id = 359 air_base = { type = air_base size = 2 current_size = 2 } } # Toulouse
province = { id = 364 air_base = { type = air_base size = 3 current_size = 3 } } # Marseille
province = { id = 367 air_base = { type = air_base size = 1 current_size = 1 } } # Corsica

province = { id = 939  air_base = { type = air_base size = 2 current_size = 2 } } # Tunis
province = { id = 946  air_base = { type = air_base size = 1 current_size = 1 } } # Bougie
province = { id = 949  air_base = { type = air_base size = 2 current_size = 2 } } # Algiers
province = { id = 953  air_base = { type = air_base size = 2 current_size = 2 } } # Oran
province = { id = 958  air_base = { type = air_base size = 2 current_size = 1 } } # Casablanca
province = { id = 993  air_base = { type = air_base size = 1 current_size = 1 } } # Abidjan
province = { id = 1037 air_base = { type = air_base size = 1 current_size = 1 } } # Djibouti
province = { id = 1135 air_base = { type = air_base size = 1 current_size = 1 } } # Reunion
province = { id = 1136 air_base = { type = air_base size = 1 current_size = 1 } } # Mauritius
province = { id = 1137 air_base = { type = air_base size = 1 current_size = 1 } } # Tananarive
province = { id = 1328 air_base = { type = air_base size = 1 current_size = 1 } } # Hanoi
province = { id = 1337 air_base = { type = air_base size = 2 current_size = 2 } } # Saigon
province = { id = 1794 air_base = { type = air_base size = 1 current_size = 1 } } # Beirut
province = { id = 1862 air_base = { type = air_base size = 1 current_size = 1 } } # Aleppo

#############################
# Germany
#############################

province = { id = 67  air_base = { type = air_base size = 4 current_size = 3 } } # Essen
province = { id = 80  air_base = { type = air_base size = 4 current_size = 3 } } # Wilhelmshafen
province = { id = 81  air_base = { type = air_base size = 2 current_size = 2 } } # Münster
province = { id = 82  air_base = { type = air_base size = 4 current_size = 4 } } # Kassel
province = { id = 89  air_base = { type = air_base size = 2 current_size = 2 } } # Lübeck
province = { id = 90  air_base = { type = air_base size = 4 current_size = 3 } } # Kiel
province = { id = 296 air_base = { type = air_base size = 2 current_size = 2 } } # Rostock
province = { id = 300 air_base = { type = air_base size = 7 current_size = 6 } } # Berlin
province = { id = 311 air_base = { type = air_base size = 4 current_size = 3 } } # Dresden
province = { id = 313 air_base = { type = air_base size = 4 current_size = 3 } } # Frankfurt-am-Main
province = { id = 314 air_base = { type = air_base size = 4 current_size = 3 } } # Stuttgart
province = { id = 376 air_base = { type = air_base size = 4 current_size = 4 } } # Munich
province = { id = 473 air_base = { type = air_base size = 4 current_size = 4 } } # Breslau
province = { id = 510 air_base = { type = air_base size = 2 current_size = 2 } } # Königsberg

#############################
# Greece
#############################

province = { id = 403 air_base = { type = air_base size = 1 current_size = 1 } } # Larisa
province = { id = 395 air_base = { type = air_base size = 1 current_size = 1 } } # Corinthe
province = { id = 396 air_base = { type = air_base size = 1 current_size = 1 } } # Crete
province = { id = 401 air_base = { type = air_base size = 2 current_size = 2 } } # Athens

#############################
# Guatemala
#############################

province = { id = 757 air_base = { type = air_base size = 1 current_size = 1 } } # Guatemala

#############################
# Haiti
#############################

province = { id = 892 air_base = { type = air_base size = 1 current_size = 1 } } # Port-au-Prince

#############################
# Honduras
#############################

province = { id = 760 air_base = { type = air_base size = 1 current_size = 1 } } # Tegucigalpa

#############################
# Hungary
#############################

province = { id = 457 air_base = { type = air_base size = 2 current_size = 2 } } # Budapest
province = { id = 458 air_base = { type = air_base size = 1 current_size = 1 } } # Györ
province = { id = 497 air_base = { type = air_base size = 1 current_size = 1 } } # Debrecen

#############################
# India/Burma
#############################

province = { id = 1457 air_base = { type = air_base size = 2 current_size = 2 } } # Calcutta
province = { id = 1469 air_base = { type = air_base size = 2 current_size = 2 } } # Delhi
province = { id = 1475 air_base = { type = air_base size = 1 current_size = 1 } } # Lahore
province = { id = 1477 air_base = { type = air_base size = 1 current_size = 1 } } # Meerut
province = { id = 1483 air_base = { type = air_base size = 1 current_size = 1 } } # Peshawar
province = { id = 1505 air_base = { type = air_base size = 2 current_size = 2 } } # Bombay
province = { id = 1506 air_base = { type = air_base size = 1 current_size = 1 } } # Pune

province = { id = 1296 air_base = { type = air_base size = 1 current_size = 1 } } # Mandalay
province = { id = 1299 air_base = { type = air_base size = 1 current_size = 1 } } # Rangoon

#############################
# Iraq
#############################

province = { id = 1823 air_base = { type = air_base size = 1 current_size = 1 } } # Basrah
province = { id = 1860 air_base = { type = air_base size = 1 current_size = 1 } } # Kirkuk
province = { id = 1866 air_base = { type = air_base size = 1 current_size = 1 } } # Baghdad

#############################
# Ireland
#############################

province = { id = 30  air_base = { type = air_base size = 1 current_size = 1 } } # Dublin

#############################
# Italy
#############################

province = { id = 368  air_base = { type = air_base size = 2 current_size = 2 } } # Genoa
province = { id = 370  air_base = { type = air_base size = 4 current_size = 4 } } # Milan
province = { id = 378  air_base = { type = air_base size = 4 current_size = 4 } } # Venice
province = { id = 399  air_base = { type = air_base size = 1 current_size = 1 } } # Rhodes
province = { id = 513  air_base = { type = air_base size = 2 current_size = 2 } } # Florence
province = { id = 515  air_base = { type = air_base size = 6 current_size = 6 } } # Rome
province = { id = 521  air_base = { type = air_base size = 2 current_size = 2 } } # Naples
province = { id = 523  air_base = { type = air_base size = 4 current_size = 4 } } # Taranto
province = { id = 525  air_base = { type = air_base size = 2 current_size = 2 } } # Palermo
province = { id = 526  air_base = { type = air_base size = 2 current_size = 2 } } # Catania
province = { id = 534  air_base = { type = air_base size = 4 current_size = 4 } } # Sardinia

province = { id = 919  air_base = { type = air_base size = 1 current_size = 1 } } # Tobruk
province = { id = 923  air_base = { type = air_base size = 1 current_size = 1 } } # Barca
province = { id = 924  air_base = { type = air_base size = 2 current_size = 2 } } # Bengazi
province = { id = 932  air_base = { type = air_base size = 2 current_size = 2 } } # Tripoli
province = { id = 1039 air_base = { type = air_base size = 2 current_size = 2 } } # Asmara
province = { id = 1056 air_base = { type = air_base size = 1 current_size = 1 } } # Mogadishu

#############################
# Japan
#############################

province = { id = 1602	air_base = { type = air_base size = 1  current_size = 1	} } # Wotje
province = { id = 1176	air_base = { type = air_base size = 1  current_size = 1	} } # Toyohara
province = { id = 1179	air_base = { type = air_base size = 1  current_size = 1 } } # Sapporo
province = { id = 1180	air_base = { type = air_base size = 1  current_size = 1	} } # Sendai
province = { id = 1182	air_base = { type = air_base size = 1  current_size = 1	} } # Fukushima
province = { id = 1184	air_base = { type = air_base size = 6  current_size = 6 } } # Tokyo 
province = { id = 1185	air_base = { type = air_base size = 4  current_size = 4 } } # Nagoya 
province = { id = 1186  air_base = { type = air_base size = 1  current_size = 1 } } # Kanazawa
province = { id = 1187	air_base = { type = air_base size = 4  current_size = 4 } } # Osaka 
province = { id = 1188	air_base = { type = air_base size = 6  current_size = 6	} } # Hiroshima 
province = { id = 1189	air_base = { type = air_base size = 1  current_size = 1	} } # Shikoku
province = { id = 1190	air_base = { type = air_base size = 6  current_size = 6	} } # Fukuoka 
province = { id = 1193	air_base = { type = air_base size = 2  current_size = 2	} } # Okinawa
province = { id = 1195	air_base = { type = air_base size = 2  current_size = 2	} } # Gwangju
province = { id = 1196  air_base = { type = air_base size = 4  current_size = 4 } } # Busan
province = { id = 1199	air_base = { type = air_base size = 2  current_size = 2	} } # Seoul
province = { id = 1202	air_base = { type = air_base size = 5  current_size = 5	} } # Dalian
province = { id = 1322	air_base = { type = air_base size = 4  current_size = 4	} } # Kaohsiung
province = { id = 1391  air_base = { type = air_base size = 2  current_size = 2 } } # Hyesan
province = { id = 1397  air_base = { type = air_base size = 2  current_size = 2 } } # Changde
province = { id = 1599	air_base = { type = air_base size = 1  current_size = 1	} } # Iwo Jima
province = { id = 1608	air_base = { type = air_base size = 1  current_size = 1	} } # Kwajalein
province = { id = 1613  air_base = { type = air_base size = 2  current_size = 2 } } # Truk
province = { id = 1621	air_base = { type = air_base size = 1  current_size = 1 } } # Palau
province = { id = 1627	air_base = { type = air_base size = 1  current_size = 1	} } # Saipan

#############################
# Latvia
#############################

province = { id = 197	air_base = { type = air_base size = 1  current_size = 1	} } # Riga

#############################
# Liberia
#############################

province = { id = 992   air_base = { type = air_base size = 1  current_size = 1 } } # Monrovia

#############################
# Lithuania
#############################

province = { id = 206   air_base = { type = air_base size = 1  current_size = 1 } } # Memel
province = { id = 207	air_base = { type = air_base size = 1  current_size = 1	} } # Kaunas

#############################
# Malay States
#############################

province = { id = 1352  air_base = { type = air_base size = 1  current_size = 1 } } # Kuala Lumpur

#############################
# Manchukuo
#############################

province = { id = 1374  air_base = { type = air_base size = 2  current_size = 2 } } # Jiamusi
province = { id = 1379  air_base = { type = air_base size = 2  current_size = 2 } } # Harbin
province = { id = 1380  air_base = { type = air_base size = 2  current_size = 2 } } # Qiqihar
province = { id = 1390  air_base = { type = air_base size = 2  current_size = 2 } } # Xinjing

#############################
# Mexico
#############################

province = { id = 752	air_base = { type = air_base size = 2  current_size = 2	} } # Mexico City
province = { id = 754   air_base = { type = air_base size = 1  current_size = 1 } } # Acapulco

#############################
# Mongolia
#############################

province = { id = 1404  air_base = { type = air_base size = 1  current_size = 1 } } # Ulan Bator

#############################
# Nationalist China
#############################

province = { id = 1235  air_base = { type = air_base size = 1  current_size = 1 } } # Nanjing
province = { id = 1276  air_base = { type = air_base size = 1  current_size = 1 } } # Lanzhou
province = { id = 1360  air_base = { type = air_base size = 2  current_size = 2 } } # Chengdu
province = { id = 1238  air_base = { type = air_base size = 3  current_size = 3 } } # Hangzhou
province = { id = 1205	air_base = { type = air_base size = 1  current_size = 1	} } # Beijing
province = { id = 1269  air_base = { type = air_base size = 1  current_size = 1 } } # Xi'an

#Guangxi

province = { id = 1313 air_base = { type = air_base size = 1 current_size = 1 } } # Guangzhou
province = { id = 1319 air_base = { type = air_base size = 1 current_size = 1 } } # Nanning

#############################
# Netherlands
#############################

province = { id = 46	air_base = { type = air_base size = 3  current_size = 3 } } # Rotterdam
province = { id = 47	air_base = { type = air_base size = 2  current_size = 2 } } # Amsterdam

#############################
# Netherlands East Indies
#############################

province = { id = 1358	air_base = { type = air_base size = 1  current_size = 1	} } # Palembang
province = { id = 1628	air_base = { type = air_base size = 2  current_size = 2	} } # Batavia
province = { id = 1631	air_base = { type = air_base size = 1  current_size = 1	} } # Djokjakarta
province = { id = 1632	air_base = { type = air_base size = 1  current_size = 1	} } # Soerabaja
province = { id = 1641	air_base = { type = air_base size = 1  current_size = 1	} } # Bandjermasin
province = { id = 1642	air_base = { type = air_base size = 1  current_size = 1	} } # Pontianak
province = { id = 1653  air_base = { type = air_base size = 1  current_size = 1 } } # Menado
province = { id = 1656  air_base = { type = air_base size = 1  current_size = 1 } } # Ceram

#############################
# New Zealand
#############################

province = { id = 1868	air_base = { type = air_base size = 1  current_size = 1 } } # Auckland
province = { id = 1871	air_base = { type = air_base size = 1  current_size = 1 } } # Wellington
province = { id = 1872	air_base = { type = air_base size = 1  current_size = 1 } } # Christchurch

#############################
# Nicaragua
#############################

province = { id = 539   air_base = { type = air_base size = 1  current_size = 1 } } # Managua

#############################
# Norway
#############################

province = { id = 107	air_base = { type = air_base size = 3  current_size = 2 } } # Oslo
province = { id = 109	air_base = { type = air_base size = 1  current_size = 0	} } # Stavanger
province = { id = 110	air_base = { type = air_base size = 1  current_size = 1	} } # Bergen
province = { id = 118	air_base = { type = air_base size = 1  current_size = 1	} } # Trondheim
province = { id = 125	air_base = { type = air_base size = 1  current_size = 0 } } # Narvik
province = { id = 117   air_base = { type = air_base size = 1 current_size = 1 } } # Ålesund

#############################
# Oman
#############################

province = { id = 1819  air_base = { type = air_base size = 1  current_size = 1 } } # Mascate

#############################
# Panama
#############################

province = { id = 888   air_base = { type = air_base size = 1  current_size = 1 } } # Panamá

#############################
# Paraguay
#############################

province = { id = 846   air_base = { type = air_base size = 1  current_size = 1 } } # Ciudad del Este

#############################
# Peru
#############################

province = { id = 830 	air_base = { type = air_base size = 1  current_size = 1 } } # Lima

#############################
# Persia
#############################

province = { id = 1497  air_base = { type = air_base size = 1  current_size = 1 } } # Bandar Abbas
province = { id = 1825	air_base = { type = air_base size = 1  current_size = 1	} } # Abadan

#############################
# Phillipines
#############################

province = { id = 1737	air_base = { type = air_base size = 1  current_size = 1	} } # Manila
province = { id = 1739  air_base = { type = air_base size = 2  current_size = 2 } } # Clark Field
province = { id = 1740	air_base = { type = air_base size = 1  current_size = 1	} } # Lingayen Gulf

#############################
# Poland
#############################

province = { id = 211   air_base = { type = air_base size = 2  current_size = 1 } } # Lida
province = { id = 303   air_base = { type = air_base size = 2  current_size = 1 } } # Danzig
province = { id = 305   air_base = { type = air_base size = 2  current_size = 1 } } # Torun
province = { id = 307   air_base = { type = air_base size = 2  current_size = 1 } } # Poznan
province = { id = 479   air_base = { type = air_base size = 2  current_size = 1 } } # Crakow
province = { id = 483   air_base = { type = air_base size = 2  current_size = 2 } } # Lodz
province = { id = 485   air_base = { type = air_base size = 4  current_size = 4 } } # Warsaw
province = { id = 487   air_base = { type = air_base size = 2  current_size = 2 } } # Lublin
province = { id = 501   air_base = { type = air_base size = 2  current_size = 2 } } # Lvov

#############################
# Portugal
#############################

province = { id = 336   air_base = { type = air_base size = 3  current_size = 3 } } # Lissabon
province = { id = 1096  air_base = { type = air_base size = 1  current_size = 1 } } # Loanda
province = { id = 1122  air_base = { type = air_base size = 1  current_size = 1 } } # Lourenço Marques
province = { id = 1146  air_base = { type = air_base size = 1  current_size = 1 } } # Cap Verde Islands
province = { id = 1316  air_base = { type = air_base size = 1  current_size = 1 } } # Macao
province = { id = 1867  air_base = { type = air_base size = 1  current_size = 1 } } # The Azores

#############################
# Romania
#############################

province = { id = 423   air_base = { type = air_base size = 1  current_size = 1 } } # Constanta
province = { id = 424	air_base = { type = air_base size = 3  current_size = 3 } } # Bucharest

#############################
# Saudi Arabia
#############################

province = { id = 1804  air_base = { type = air_base size = 1  current_size = 1 } } # Medina

#############################
# Siam
#############################

province = { id = 1343	air_base = { type = air_base size = 2  current_size = 2 } } # Bangkok
province = { id = 1345  air_base = { type = air_base size = 1  current_size = 1 } } # Thom Buri

#############################
# Spain
#############################

province = { id = 330	air_base = { type = air_base size = 2  current_size = 2	} } # Saragossa
province = { id = 333	air_base = { type = air_base size = 2  current_size = 2 } } # Burgos
province = { id = 333	air_base = { type = air_base size = 1  current_size = 1 } } # La Coruña
province = { id = 341   air_base = { type = air_base size = 4  current_size = 4 } } # Madrid
province = { id = 347   air_base = { type = air_base size = 3  current_size = 3 } } # Seville
province = { id = 352 	air_base = { type = air_base size = 2  current_size = 2 } } # Murcia
province = { id = 357	air_base = { type = air_base size = 3  current_size = 3	} } # Barcelona
province = { id = 535	air_base = { type = air_base size = 1  current_size = 1	} } # Mallorca
province = { id = 536	air_base = { type = air_base size = 1  current_size = 1	} } # Menorca
province = { id = 957	air_base = { type = air_base size = 2  current_size = 2	} } # Ceuta
province = { id = 963   air_base = { type = air_base size = 1  current_size = 1 } } # Gran Canaria
province = { id = 972   air_base = { type = air_base size = 1  current_size = 1 } } # Villa Cisneros
province = { id = 1091  air_base = { type = air_base size = 1  current_size = 1 } } # Bata

#############################
# South Africa
#############################

province = { id = 1108  air_base = { type = air_base size = 1  current_size = 1 } } # Walvis Bay
province = { id = 1116	air_base = { type = air_base size = 1  current_size = 1	} } # Cape Town
province = { id = 1119  air_base = { type = air_base size = 1  current_size = 1 } } # Durban

#############################
# Sweden
#############################

province = { id = 93	air_base = { type = air_base size = 1  current_size = 1	} } # Malmö
province = { id = 95    air_base = { type = air_base size = 2  current_size = 2 } } # Karlskrona
province = { id = 98    air_base = { type = air_base size = 2  current_size = 2 } } # Göteborg
province = { id = 101	air_base = { type = air_base size = 4  current_size = 4	} } # Stockholm
province = { id = 127  	air_base = { type = air_base size = 1  current_size = 1 } } # Luleå
province = { id = 100  	air_base = { type = air_base size = 2  current_size = 2 } } # Norrköping


#############################
# Switzerland
#############################

province = { id = 530	air_base = { type = air_base size = 1  current_size = 1	} } # Geneva
province = { id = 532	air_base = { type = air_base size = 1  current_size = 1	} } # Bern
province = { id = 533	air_base = { type = air_base size = 1  current_size = 1	} } # Zurich

#############################
# Turkey
#############################

province = { id = 408	air_base = { type = air_base size = 1  current_size = 1	} } # Bursa
province = { id = 409	air_base = { type = air_base size = 2  current_size = 2 } } # Istanbul
province = { id = 439   air_base = { type = air_base size = 1  current_size = 1 } } # Izmit
province = { id = 440	air_base = { type = air_base size = 1  current_size = 1	} } # Karabük
province = { id = 445	air_base = { type = air_base size = 1  current_size = 1 } } # Gaziantep
province = { id = 448   air_base = { type = air_base size = 2  current_size = 2 } } # Ankara

#############################
# United Kingdom
#############################

province = { id = 5    air_base = { type = air_base size = 1 current_size = 1 } } # Scapa Flow
province = { id = 8    air_base = { type = air_base size = 2 current_size = 2 } } # Dunfermline
province = { id = 9    air_base = { type = air_base size = 2 current_size = 2 } } # Glasgow
province = { id = 10   air_base = { type = air_base size = 2 current_size = 2 } } # Edinburgh
province = { id = 11   air_base = { type = air_base size = 3 current_size = 3 } } # Sunderland
province = { id = 12   air_base = { type = air_base size = 2 current_size = 2 } } # Blackpool
province = { id = 13   air_base = { type = air_base size = 4 current_size = 4 } } # Sheffield 
province = { id = 14   air_base = { type = air_base size = 4 current_size = 4 } } # Liverpool
province = { id = 15   air_base = { type = air_base size = 2 current_size = 2 } } # Cardiff
province = { id = 16   air_base = { type = air_base size = 6 current_size = 6 } } # Birmingham 
province = { id = 17   air_base = { type = air_base size = 4 current_size = 4 } } # Norwich 
province = { id = 19   air_base = { type = air_base size = 6 current_size = 6 } } # London 
province = { id = 20   air_base = { type = air_base size = 6 current_size = 6 } } # Dover 
province = { id = 21   air_base = { type = air_base size = 4 current_size = 4 } } # Portsmouth
province = { id = 22   air_base = { type = air_base size = 4 current_size = 4 } } # Bristol 
province = { id = 23   air_base = { type = air_base size = 4 current_size = 4 } } # Plymouth 
province = { id = 28   air_base = { type = air_base size = 2 current_size = 2 } } # Belfast

province = { id = 31   air_base = { type = air_base size = 2 current_size = 2 } } # Malta
province = { id = 348  air_base = { type = air_base size = 2 current_size = 2 } } # Gibraltar
province = { id = 444  air_base = { type = air_base size = 1 current_size = 1 } } # Cyprus
province = { id = 538  air_base = { type = air_base size = 1 current_size = 1 } } # Bermuda
province = { id = 576  air_base = { type = air_base size = 1 current_size = 1 } } # Newfoundland
province = { id = 652  air_base = { type = air_base size = 1 current_size = 1 } } # Andros
province = { id = 668  air_base = { type = air_base size = 1 current_size = 1 } } # Long Island
province = { id = 809  air_base = { type = air_base size = 1 current_size = 1 } } # Trinidad
province = { id = 866  air_base = { type = air_base size = 1 current_size = 1 } } # Falkland Islands
province = { id = 873  air_base = { type = air_base size = 1 current_size = 1 } } # Georgetown
province = { id = 891  air_base = { type = air_base size = 1 current_size = 1 } } # Jamaica
province = { id = 988  air_base = { type = air_base size = 1 current_size = 1 } } # Freetown
province = { id = 1002 air_base = { type = air_base size = 1 current_size = 1 } } # Accra
province = { id = 1008 air_base = { type = air_base size = 1 current_size = 1 } } # Lagos
province = { id = 1060 air_base = { type = air_base size = 1 current_size = 1 } } # Nairobi
province = { id = 1061 air_base = { type = air_base size = 1 current_size = 1 } } # Mombasa
province = { id = 1066 air_base = { type = air_base size = 1 current_size = 1 } } # Khartoum
province = { id = 1315 air_base = { type = air_base size = 2 current_size = 2 } } # Hong Kong
province = { id = 1353 air_base = { type = air_base size = 4 current_size = 4 } } # Singapore
province = { id = 1516 air_base = { type = air_base size = 2 current_size = 2 } } # Trincomalee
province = { id = 1517 air_base = { type = air_base size = 2 current_size = 2 } } # Colombo
province = { id = 1644 air_base = { type = air_base size = 1 current_size = 1 } } # Kuching
province = { id = 1797 air_base = { type = air_base size = 2 current_size = 2 } } # Jerusalem
province = { id = 1813 air_base = { type = air_base size = 1 current_size = 1 } } # Aden
province = { id = 1822 air_base = { type = air_base size = 1 current_size = 1 } } # Kuwait City

#############################
# Uruguay
#############################

province = { id = 849   air_base = { type = air_base size = 1  current_size = 1 } } # Montevideo

#############################
# USA
#############################

province = { id = 549	air_base = { type = air_base size = 1  current_size = 1 } } # Anchorage
province = { id = 592   air_base = { type = air_base size = 2  current_size = 2 } } # Plattsburgh
province = { id = 595   air_base = { type = air_base size = 2  current_size = 2 } } # Concord
province = { id = 600  	air_base = { type = air_base size = 4  current_size = 4 } } # Boston
province = { id = 602   air_base = { type = air_base size = 6  current_size = 6 } } # New York
province = { id = 603	air_base = { type = air_base size = 4  current_size = 4 } } # Newark
province = { id = 606	air_base = { type = air_base size = 4  current_size = 4 } } # Washington D.C.
province = { id = 608	air_base = { type = air_base size = 5  current_size = 5 } } # Philadelphia
province = { id = 614   air_base = { type = air_base size = 2  current_size = 2 } } # Pittsburgh
province = { id = 616   air_base = { type = air_base size = 2  current_size = 2 } } # Detroit
province = { id = 620   air_base = { type = air_base size = 4  current_size = 4 } } # Chicago
province = { id = 621   air_base = { type = air_base size = 2  current_size = 2 } } # Milwaukee
province = { id = 626	air_base = { type = air_base size = 2  current_size = 2 } } # Decatur
province = { id = 628	air_base = { type = air_base size = 2  current_size = 2 } } # Columbus
province = { id = 631	air_base = { type = air_base size = 3  current_size = 3 } } # Charlotteville
province = { id = 633	air_base = { type = air_base size = 5  current_size = 5 } } # Norfolk
province = { id = 634	air_base = { type = air_base size = 3  current_size = 3	} } # Wilmington
province = { id = 637   air_base = { type = air_base size = 2  current_size = 2 } } # Charlotte
province = { id = 640   air_base = { type = air_base size = 2  current_size = 2 } } # Louisville
province = { id = 644	air_base = { type = air_base size = 2  current_size = 2	} } # Charleston
province = { id = 648	air_base = { type = air_base size = 2  current_size = 2	} } # Jacksonville
province = { id = 651   air_base = { type = air_base size = 4  current_size = 4 } } # Miami
province = { id = 663   air_base = { type = air_base size = 4  current_size = 4 } } # Pearl Harbour
province = { id = 669	air_base = { type = air_base size = 2  current_size = 2	} } # Augusta
province = { id = 670   air_base = { type = air_base size = 2  current_size = 2 } } # Atlanta
province = { id = 673   air_base = { type = air_base size = 2  current_size = 2 } } # Memphis
province = { id = 676	air_base = { type = air_base size = 3  current_size = 3	} } # Mobile
province = { id = 678	air_base = { type = air_base size = 4  current_size = 4 } } # Biloxi
province = { id = 681	air_base = { type = air_base size = 3  current_size = 3 } } # Alexandria
province = { id = 684   air_base = { type = air_base size = 2  current_size = 2 } } # Little Rock
province = { id = 689   air_base = { type = air_base size = 2  current_size = 2 } } # St. Louis
province = { id = 692   air_base = { type = air_base size = 2  current_size = 2 } } # Des Moines
province = { id = 693   air_base = { type = air_base size = 2  current_size = 2 } } # Minneapolis
province = { id = 698   air_base = { type = air_base size = 2  current_size = 2 } } # Bismarck
province = { id = 707   air_base = { type = air_base size = 2  current_size = 2 } } # Denver
province = { id = 713   air_base = { type = air_base size = 2  current_size = 2 } } # Oklahoma City
province = { id = 716   air_base = { type = air_base size = 2  current_size = 2 } } # Houston
province = { id = 717	air_base = { type = air_base size = 4  current_size = 4 } } # San Antonio
province = { id = 725   air_base = { type = air_base size = 2  current_size = 2 } } # Santa Fe
province = { id = 733   air_base = { type = air_base size = 4  current_size = 4 } } # Salt Lake City
province = { id = 748   air_base = { type = air_base size = 3  current_size = 3 } } # Corpus Christi
province = { id = 761   air_base = { type = air_base size = 4  current_size = 4 } } # San Diego
province = { id = 762	air_base = { type = air_base size = 4  current_size = 4 } } # Los Angeles
province = { id = 763	air_base = { type = air_base size = 2  current_size = 2	} } # Fresno
province = { id = 764   air_base = { type = air_base size = 2  current_size = 2 } } # Sacramento
province = { id = 765	air_base = { type = air_base size = 4  current_size = 4 } } # San Francisco
province = { id = 780   air_base = { type = air_base size = 4  current_size = 4 } } # Seattle
province = { id = 783   air_base = { type = air_base size = 2  current_size = 2 } } # Portland
province = { id = 789	air_base = { type = air_base size = 2  current_size = 2 } } # Omaha
province = { id = 793   air_base = { type = air_base size = 2  current_size = 2 } } # Tulsa

province = { id = 889   air_base = { type = air_base size = 2  current_size = 2 } } # Colon
province = { id = 1624  air_base = { type = air_base size = 1  current_size = 1 } } # Guam
province = { id = 1786  air_base = { type = air_base size = 1  current_size = 1 } } # Wake Island

#############################
# USSR
#############################

province = { id = 133   air_base = { type = air_base size = 1  current_size = 1 } } # Murmansk
province = { id = 154	air_base = { type = air_base size = 1  current_size = 1 } } # Archangelsk
province = { id = 163   air_base = { type = air_base size = 2  current_size = 2 } } # Stalingrad
province = { id = 168	air_base = { type = air_base size = 1  current_size = 1 } } # Gorkij
province = { id = 174   air_base = { type = air_base size = 2  current_size = 2 } } # Kalinin
province = { id = 175   air_base = { type = air_base size = 6  current_size = 5 } } # Moscow
province = { id = 178   air_base = { type = air_base size = 1  current_size = 1 } } # Yaroslavl
province = { id = 186	air_base = { type = air_base size = 2  current_size = 2 } } # Luga
province = { id = 187	air_base = { type = air_base size = 8  current_size = 6 } } # Leningrad
province = { id = 200  	air_base = { type = air_base size = 4  current_size = 3 } } # Pskov
province = { id = 217  	air_base = { type = air_base size = 3  current_size = 2 } } # Vitebsk
province = { id = 220   air_base = { type = air_base size = 6  current_size = 5 } } # Mogilev
province = { id = 221   air_base = { type = air_base size = 2  current_size = 2 } } # Bobraisk
province = { id = 227   air_base = { type = air_base size = 2  current_size = 2 } } # Zhitomir
province = { id = 233   air_base = { type = air_base size = 3  current_size = 2 } } # Odessa
province = { id = 236   air_base = { type = air_base size = 2  current_size = 2 } } # Krivoy Rog
province = { id = 238   air_base = { type = air_base size = 6  current_size = 5 } } # Kiev
province = { id = 243   air_base = { type = air_base size = 2  current_size = 2 } } # Kursk
province = { id = 246   air_base = { type = air_base size = 2  current_size = 2 } } # Zaporozhye
province = { id = 248   air_base = { type = air_base size = 2  current_size = 2 } } # Kharkov
province = { id = 256	air_base = { type = air_base size = 1  current_size = 1 } } # Krasnodar
province = { id = 258	air_base = { type = air_base size = 2  current_size = 2 } } # Rostov
province = { id = 273   air_base = { type = air_base size = 1  current_size = 1 } } # Gomel
province = { id = 282   air_base = { type = air_base size = 4  current_size = 3 } } # Orel
province = { id = 285   air_base = { type = air_base size = 2  current_size = 2 } } # Vyazma
province = { id = 1163  air_base = { type = air_base size = 1  current_size = 1 } } # Yakutsk
province = { id = 1175	air_base = { type = air_base size = 1  current_size = 1 } } # Ocha
province = { id = 1368  air_base = { type = air_base size = 2  current_size = 1 } } # Komsomolsk-na-Amure
province = { id = 1368  air_base = { type = air_base size = 2  current_size = 2 } } # Khabarovsk
province = { id = 1372	air_base = { type = air_base size = 3  current_size = 2 } } # Vladivostok
province = { id = 1384  air_base = { type = air_base size = 2  current_size = 2 } } # Chita
province = { id = 1416  air_base = { type = air_base size = 1  current_size = 1 } } # Irkutsk
province = { id = 1427 	air_base = { type = air_base size = 1  current_size = 1 } } # Tashkent
province = { id = 1523  air_base = { type = air_base size = 1  current_size = 1 } } # Tynda
province = { id = 1548  air_base = { type = air_base size = 1  current_size = 1 } } # Novosibirsk
province = { id = 1552  air_base = { type = air_base size = 1  current_size = 1 } } # Omsk
province = { id = 1574  air_base = { type = air_base size = 1  current_size = 1 } } # Chelyabinsk
province = { id = 1827  air_base = { type = air_base size = 1  current_size = 1 } } # Naberezhnye Chelny
province = { id = 1828  air_base = { type = air_base size = 1  current_size = 1 } } # Kuybyshev
province = { id = 1832  air_base = { type = air_base size = 1  current_size = 1 } } # Saratov
province = { id = 1838  air_base = { type = air_base size = 1  current_size = 1 } } # Astrakhan
province = { id = 1848	air_base = { type = air_base size = 2  current_size = 2 } } # Batum
province = { id = 1856	air_base = { type = air_base size = 2  current_size = 2 } } # Yerevan
province = { id = 1907  air_base = { type = air_base size = 2  current_size = 2 } } # Baku
  
#############################
# Venezuela
#############################

province = { id = 804	air_base = { type = air_base size = 1  current_size = 1 } } # Maracaibo

#############################
# Yemen
#############################

province = { id = 1812	air_base = { type = air_base size = 1  current_size = 1	} } # Sanaa

#############################
# Yugoslavia
#############################

province = { id = 382	air_base = { type = air_base size = 2  current_size = 1 } } # Zagreb
province = { id = 384	air_base = { type = air_base size = 1  current_size = 1 } } # Split
province = { id = 387	air_base = { type = air_base size = 1  current_size = 1 } } # Mostar
province = { id = 415	air_base = { type = air_base size = 3  current_size = 1 } } # Pristina
province = { id = 453	air_base = { type = air_base size = 3  current_size = 2 } } # Belgrade

#############################
# Yunnan
#############################

province = { id = 1307	air_base = { type = air_base size = 2  current_size = 2 } } # Kunming



# EOF
