#####################
# Country main data #
#####################

country =
{ tag                    = BRA
  # Resource Reserves
  energy                 = 1532
  metal                  = 970
  rare_materials         = 383
  oil                    = 72
  supplies               = 812
  money                  = 100
  manpower               = 35.3000 # 125 - building queue
  consumer = 0.2549 
  supply = 0.0500 
  production = 0.6951 
  reinforcement = 0.0000 
  upgrading = 0.0000 
  capital                = 885
  transports             = 96
  escorts                = 0
  policy =
  { date              = { year = 0 month = january day = 0 }
    democratic        = 6
    political_left    = 9
    free_market       = 8
    freedom           = 7
    professional_army = 5
    defense_lobby     = 6
    interventionism   = 3
  }
  nationalprovinces      = { 848 847 835 834 825 823 822 820 872 824 826 878 876 877 879 883 887 886 885 884 882 880 881 }
  ownedprovinces         = { 848 847 835 834 825 823 822 820 872 824 826 878 876 877 879 883 887 886 885 884 882 880 881 }
  controlledprovinces    = { 848 847 835 834 825 823 822 820 872 824 826 878 876 877 879 883 887 886 885 884 882 880 881 }
  # Semi-Major Tech '36
  # Group C 1936 techs
  # ######################
  techapps               = { 4010 4020 4120  2010 2290 2300 2310 2450 2460 2510 1010 1190 1110 9010 5010 5080 5090 5190 6010 6020 3010 3070 3130
                             3250 3400 8010 8020 8040 8050
                           }
	diplomacy = {
		relation = { tag = AFG value = 1 }
		relation = { tag = ALB value = 1 }
		relation = { tag = ARG value = 10 }
		relation = { tag = AST value = 25 }
		relation = { tag = AUS value = 15 }
		relation = { tag = BEL value = 20 }
		relation = { tag = BHU value = 1 }
		relation = { tag = BOL value = -15 }
		relation = { tag = BUL value = 20 }
		relation = { tag = CAN value = 40 }
		relation = { tag = CGX value = 1 }
		relation = { tag = CHC value = 1 }
		relation = { tag = CHI value = 1 }
		relation = { tag = CHL value = 10 }
		relation = { tag = COL value = 25 }
		relation = { tag = COS value = 30 }
		relation = { tag = CSX value = 1 }
		relation = { tag = CUB value = 30 }
		relation = { tag = CXB value = 1 }
		relation = { tag = CYN value = 1 }
		relation = { tag = CZE value = 20 }
		relation = { tag = DEN value = 30 }
		relation = { tag = DOM value = 25 }
		relation = { tag = ECU value = 35 }
		relation = { tag = EGY value = 1 }
		relation = { tag = ENG value = 40 }
		relation = { tag = EST value = 1 }
		relation = { tag = ETH value = 1 }
		relation = { tag = FIN value = 1 }
		relation = { tag = FRA value = 40 }
		relation = { tag = GER value = 35 }
		relation = { tag = GRE value = 15 }
		relation = { tag = GUA value = 25 }
		relation = { tag = HAI value = 20 }
		relation = { tag = HOL value = 35 }
		relation = { tag = HON value = 25 }
		relation = { tag = HUN value = 10 }
		relation = { tag = IND value = 5 }
		relation = { tag = IRE value = 20 }
		relation = { tag = IRQ value = 1 }
		relation = { tag = ITA value = 40 }
		relation = { tag = JAP value = 30 }
		relation = { tag = LAT value = 1 }
		relation = { tag = LIB value = 1 }
		relation = { tag = LIT value = 1 }
		relation = { tag = LUX value = 1 }
		relation = { tag = MAN value = 1 }
		relation = { tag = MEX value = 30 }
		relation = { tag = MLY value = 1 }
		relation = { tag = MON value = 1 }
		relation = { tag = NEP value = 1 }
		relation = { tag = NIC value = 25 }
		relation = { tag = NOR value = 15 }
		relation = { tag = NZL value = 15 }
		relation = { tag = OMN value = 1 }
		relation = { tag = PAN value = 25 }
		relation = { tag = PAR value = -15 }
		relation = { tag = PER value = 15 }
		relation = { tag = PHI value = 1 }
		relation = { tag = POL value = 15 }
		relation = { tag = POR value = 50 }
		relation = { tag = PRU value = -5 }
		relation = { tag = ROM value = 15 }
		relation = { tag = SAF value = 20 }
		relation = { tag = SAL value = 20 }
		relation = { tag = SAU value = 15 }
		relation = { tag = SIA value = 10 }
		relation = { tag = SIK value = 1 }
		relation = { tag = SOV value = 35 }
		relation = { tag = SPA value = 30 }
		relation = { tag = SPR value = 30 }
		relation = { tag = SWE value = 30 }
		relation = { tag = SCH value = 50 }
		relation = { tag = TAN value = 1 }
		relation = { tag = TIB value = 1 }
		relation = { tag = TUR value = 25 }
		relation = { tag = U27 value = 1 }
		relation = { tag = URU value = -15 }
		relation = { tag = USA value = 45 }
		relation = { tag = VEN value = 25 }
		relation = { tag = YEM value = 1 }
		relation = { tag = YUG value = 1 }
	}

	SpyInfo = { country = "BRA" NumberOfSpies = 4 }
	SpyInfo = { country = "ARG" NumberOfSpies = 4 }
	SpyInfo = { country = "BOL" NumberOfSpies = 2 }
	SpyInfo = { country = "CHL" NumberOfSpies = 2 }
	SpyInfo = { country = "COL" NumberOfSpies = 1 }
	SpyInfo = { country = "ENG" NumberOfSpies = 1 }
	SpyInfo = { country = "FRA" NumberOfSpies = 1 }
	SpyInfo = { country = "GER" NumberOfSpies = 1 }
	SpyInfo = { country = "HOL" NumberOfSpies = 1 }
	SpyInfo = { country = "PAR" NumberOfSpies = 4 }
	SpyInfo = { country = "POR" NumberOfSpies = 1 }
	SpyInfo = { country = "PRU" NumberOfSpies = 2 }
	SpyInfo = { country = "SCH" NumberOfSpies = 1 }
	SpyInfo = { country = "URU" NumberOfSpies = 4 }
	SpyInfo = { country = "USA" NumberOfSpies = 1 }
	SpyInfo = { country = "VEN" NumberOfSpies = 2 }

  headofstate            = { type = 9 id = 34001 }
  headofgovernment       = { type = 9 id = 34002 }
  foreignminister        = { type = 9 id = 34003 }
  armamentminister       = { type = 9 id = 34004 }
  ministerofsecurity     = { type = 9 id = 34005 }
  ministerofintelligence = { type = 9 id = 34006 }
  chiefofstaff           = { type = 9 id = 34007 }
  chiefofarmy            = { type = 9 id = 34008 }
  chiefofnavy            = { type = 9 id = 34009 }
  chiefofair             = { type = 9 id = 34010 }
  landunit =
  { id       = { type = 10008 id = 1 }
    name     = "1o Exército do Brasil"
    location = 883
    division =
    { id       = { type = 10008 id = 2 }
      name     = "I Divisão de Infantaria"
      strength = 100
      type     = infantry
      extra    = artillery
    }
    division =
    { id       = { type = 10008 id = 3 }
      name     = "II Divisão de Infantaria"
      strength = 100
      type     = infantry
    }
    division =
    { id       = { type = 10008 id = 4 }
      name     = "CCLXVIII Divisão do Guarda Civíl"
      strength = 100
      type     = militia
      extra    = anti_air
    }
    division =
    { id       = { type = 10008 id = 5 }
      name     = "CCLXIX Divisão do Guarda Civíl"
      strength = 100
      type     = militia
    }
  }
  landunit =
  { id       = { type = 10008 id = 6 }
    name     = "2o Exército do Brasil"
    location = 885
    division =
    { id       = { type = 10008 id = 7 }
      name     = "III Divisão de Infantaria"
      strength = 100
      type     = infantry
    }
    division =
    { id       = { type = 10008 id = 8 }
      name     = "XCII Divisão de Cavalaria"
      strength = 100
      type     = cavalry
    }
  }
  # #####################################################
  navalunit =
  { id       = { type = 10008 id = 11 }
    location = 885
    base     = 885
    name     = "Navais do Transporte"
    division =
    { id   = { type = 10008 id = 12 }
      name = "1. Flotilla de Navios de Transporte"
      type = transport
    }
    division =
    { id   = { type = 10008 id = 13 }
      name = "2. Flotilla de Navios de Transporte"
      type = transport
    }
    division =
    { id   = { type = 10008 id = 14 }
      name = "3. Flotilla de Navios de Transporte"
      type = transport
    }
    division =
    { id   = { type = 10008 id = 15 }
      name = "4. Flotilla de Navios de Transporte"
      type = transport
    }
    division =
    { id   = { type = 10008 id = 16 }
      name = "5. Flotilla de Navios de Transporte"
      type = transport
    }
    division =
    { id   = { type = 10008 id = 17 }
      name = "6. Flotilla de Navios de Transporte"
      type = transport
    }
  }
  navalunit =
  { name     = "Brazilian Navy"
    id       = { type = 10008 id = 18 }
    location = 885
    base     = 885
    division =
    { id    = { type = 10008 id = 19 }
      name  = "São Paulo"
      type  = battleship
      model = 0
      extra1 = naval_sa_l
      extra2 = naval_anti_air_l
      extra3 = none
      extra4 = none
      extra5 = none
      brigade_model1 = 0
      brigade_model2 = 1
      brigade_model3 = 0
      brigade_model4 = 0
      brigade_model5 = 0
    }
    division =
    { id    = { type = 10008 id = 20 }
      name  = "Minas Gerais"
      type  = battleship
      model = 0
      extra1 = naval_sa_l
      extra2 = naval_anti_air_l
      extra3 = none
      extra4 = none
      extra5 = none
      brigade_model1 = 0
      brigade_model2 = 1
      brigade_model3 = 0
      brigade_model4 = 0
      brigade_model5 = 0
    }
    division =
    { id    = { type = 10008 id = 21 }
      name  = "Bahia"
      type  = light_cruiser
      model = 0
      extra1 = naval_anti_air_s
      extra2 = none
      brigade_model1 = 1
      brigade_model2 = 0
    }
    division =
    { id    = { type = 10008 id = 22 }
      name  = "Rio Grande do Sul"
      type  = light_cruiser
      model = 0
      extra1 = naval_anti_air_s
      extra2 = none
      brigade_model1 = 1
      brigade_model2 = 0
    }
  }
  # #########################################################
  airunit =
  { id       = { type = 10008 id = 9 }
    name     = "Aereo do Brésil"
    location = 885
    base     = 885
    division =
    { id       = { type = 10008 id = 10 }
      name     = "1. Grupo de Caças"
      strength = 50
      type     = interceptor
      model    = 0
    }
  } 
	province_development = { 
		id = { type = 10008 id = 23 } 
		name = "" 
		progress = 0.0000 
		location = 885 
		cost = 2.0000 
		date = { 
			year = 1942 
			month = may 
			day = 23 
			hour = 0 
			} 
		manpower = 0.1000 
		close_when_finished = yes 
		waitingforclosure = no 
		total_progress = 0.0000 
		size = 28 
		done = 0 
		days = 2299 
		days_for_first = 101 
		gearing_bonus = 0.0000 
		type = infrastructure 
		} 
	province_development = { 
		id = { type = 10008 id = 30 } 
		name = "" 
		progress = 0.0000 
		location = 884 
		cost = 2.0000 
		date = { 
			year = 1942 
			month = may 
			day = 23 
			hour = 0 
			} 
		manpower = 0.1000 
		close_when_finished = yes 
		waitingforclosure = no 
		total_progress = 0.0000 
		size = 28 
		done = 0 
		days = 2299 
		days_for_first = 101 
		gearing_bonus = 0.0000 
		type = infrastructure 
		} 
	province_development = { 
		id = { type = 10008 id = 31 } 
		name = "" 
		progress = 0.0000 
		location = 886 
		cost = 2.0000 
		date = { 
			year = 1942 
			month = may 
			day = 23 
			hour = 0 
			} 
		manpower = 0.1000 
		close_when_finished = yes 
		waitingforclosure = no 
		total_progress = 0.0000 
		size = 28 
		done = 0 
		days = 2299 
		days_for_first = 101 
		gearing_bonus = 0.0000 
		type = infrastructure 
		} 
	province_development = { 
		id = { type = 10008 id = 32 } 
		name = "" 
		progress = 0.0000 
		location = 848 
		cost = 2.0000 
		date = { 
			year = 1947 
			month = september 
			day = 28 
			hour = 0 
			} 
		manpower = 0.1000 
		close_when_finished = yes 
		waitingforclosure = no 
		total_progress = 0.0000 
		size = 28 
		done = 0 
		days = 2299 
		days_for_first = 151 
		gearing_bonus = 0.0000 
		type = infrastructure 
		} 
	province_development = { 
		id = { type = 10008 id = 33 } 
		name = "" 
		progress = 0.0000 
		location = 848 
		cost = 5.0000 
		date = { 
			year = 1942 
			month = may 
			day = 16 
			hour = 0 
			} 
		manpower = 1.0000 
		close_when_finished = yes 
		waitingforclosure = no 
		total_progress = 0.0000 
		size = 8 
		done = 0 
		days = 2298 
		days_for_first = 287 
		gearing_bonus = 0.0000 
		type = ic 
		} 
	province_development = { 
		id = { type = 10008 id = 34 } 
		name = "" 
		progress = 0.0000 
		location = 824 
		cost = 2.0000 
		date = { 
			year = 1953 
			month = january 
			day = 28 
			hour = 0 
			} 
		manpower = 0.1000 
		close_when_finished = yes 
		waitingforclosure = no 
		total_progress = 0.0000 
		size = 30 
		done = 0 
		days = 2620 
		days_for_first = 252 
		gearing_bonus = 0.0000 
		type = infrastructure 
		} 
	province_development = { 
		id = { type = 10008 id = 35 } 
		name = "" 
		progress = 0.0000 
		location = 825 
		cost = 2.0000 
		date = { 
			year = 1956 
			month = june 
			day = 2 
			hour = 0 
			} 
		manpower = 0.1000 
		close_when_finished = yes 
		waitingforclosure = no 
		total_progress = 0.0000 
		size = 36 
		done = 0 
		days = 2941 
		days_for_first = 252 
		gearing_bonus = 0.0000 
		type = infrastructure 
		} 
	province_development = { 
		id = { type = 10008 id = 36 } 
		name = "" 
		progress = 0.0000 
		location = 826 
		cost = 2.0000 
		date = { 
			year = 1954 
			month = march 
			day = 9 
			hour = 0 
			} 
		manpower = 0.1000 
		close_when_finished = yes 
		waitingforclosure = no 
		total_progress = 0.0000 
		size = 32 
		done = 0 
		days = 2620 
		days_for_first = 252 
		gearing_bonus = 0.0000 
		type = infrastructure 
		} 
	brigade_development = { 
		id = { type = 10008 id = 37 } 
		name = "Capital Torpedoes" 
		progress = 0.0000 
		location = 885 
		cost = 0.5040 
		date = { 
			year = 1936 
			month = may 
			day = 0 
			hour = 0 
			} 
		manpower = 0.0500 
		close_when_finished = yes 
		waitingforclosure = no 
		retooling_time = 22.5000 
		total_progress = 0.0000 
		size = 2 
		done = 0 
		days = 98 
		days_for_first = 50 
		gearing_bonus = 0.0000 
		type = naval_torpedoes_l 
		model = 0 
		} 
	brigade_development = { 
		id = { type = 10008 id = 38 } 
		name = "Torpedoes" 
		progress = 0.0000 
		location = 885 
		cost = 0.5040 
		date = { 
			year = 1936 
			month = may 
			day = 0 
			hour = 0 
			} 
		manpower = 0.0500 
		close_when_finished = yes 
		waitingforclosure = no 
		retooling_time = 22.5000 
		total_progress = 0.0000 
		size = 2 
		done = 0 
		days = 98 
		days_for_first = 50 
		gearing_bonus = 0.0000 
		type = naval_torpedoes_s 
		model = 0 
		} 
	brigade_development = { 
		id = { type = 10008 id = 39 } 
		name = "Basic Sea Mines" 
		progress = 0.0000 
		location = 885 
		cost = 0.2520 
		date = { 
			year = 1936 
			month = may 
			day = 0 
			hour = 0 
			} 
		manpower = 0.0500 
		close_when_finished = yes 
		waitingforclosure = no 
		retooling_time = 22.5000 
		total_progress = 0.0000 
		size = 2 
		done = 0 
		days = 98 
		days_for_first = 50 
		gearing_bonus = 0.0000 
		type = naval_mines 
		model = 0 
		} 
	brigade_development = { 
		id = { type = 10008 id = 40 } 
		name = "36' AA" 
		progress = 0.0000 
		location = 885 
		cost = 0.4200 
		date = { 
			year = 1937 
			month = may 
			day = 8 
			hour = 0 
			} 
		manpower = 0.1000 
		close_when_finished = yes 
		waitingforclosure = no 
		retooling_time = 22.5000 
		total_progress = 0.0000 
		size = 6 
		done = 0 
		days = 467 
		days_for_first = 88 
		gearing_bonus = 0.0000 
		type = naval_anti_air_s 
		model = 1 
		} 
}
