#####################
# Country main data #
#####################

country =
{ tag                    = CAN
  # Resource Reserves
  energy                 = 2228
  metal                  = 1446
  rare_materials         = 1530
  oil                    = 894
  supplies               = 136
  money                  = 100
  manpower               = 35.0000 # 35 - building queue no more
  consumer = 0.2834 
  supply = 0.0500 
  production = 0.6666 
  reinforcement = 0.0000 
  upgrading = 0.0000 
  capital                = 588
  transports             = 272
  escorts                = 3

	diplomacy = {
		relation = { tag = AFG value = 1 }
		relation = { tag = ALB value = 10 }
		relation = { tag = ARG value = 25 }
		relation = { tag = AST value = 50 }
		relation = { tag = AUS value = 10 }
		relation = { tag = BEL value = 35 }
		relation = { tag = BHU value = 50 }
		relation = { tag = BOL value = 1 }
		relation = { tag = BRA value = 40 }
		relation = { tag = BUL value = 10 }
		relation = { tag = CGX value = 1 }
		relation = { tag = CHC value = -10 }
		relation = { tag = CHI value = 30 }
		relation = { tag = CHL value = 15 }
		relation = { tag = COL value = 15 }
		relation = { tag = COS value = 10 }
		relation = { tag = CSX value = 1 }
		relation = { tag = CUB value = 15 }
		relation = { tag = CXB value = 1 }
		relation = { tag = CYN value = 1 }
		relation = { tag = CZE value = 35 }
		relation = { tag = DEN value = 20 }
		relation = { tag = DOM value = 10 }
		relation = { tag = ECU value = 25 }
		relation = { tag = EGY value = 50 }
		relation = { tag = ENG value = 150 }
		relation = { tag = EST value = 10 }
		relation = { tag = ETH value = 30 }
		relation = { tag = FIN value = 20 }
		relation = { tag = FRA value = 50 }
		relation = { tag = GER value = 30 }
		relation = { tag = GRE value = 30 }
		relation = { tag = GUA value = 10 }
		relation = { tag = HAI value = 10 }
		relation = { tag = HOL value = 30 }
		relation = { tag = HON value = 10 }
		relation = { tag = HUN value = 10 }
		relation = { tag = IND value = 50 }
		relation = { tag = IRE value = 40 }
		relation = { tag = IRQ value = 50 }
		relation = { tag = ITA value = 25 }
		relation = { tag = JAP value = 25 }
		relation = { tag = LAT value = 10 }
		relation = { tag = LIB value = 15 }
		relation = { tag = LIT value = 10 }
		relation = { tag = LUX value = 10 }
		relation = { tag = MAN value = -10 }
		relation = { tag = MEX value = 30 }
		relation = { tag = MLY value = 50 }
		relation = { tag = MON value = 1 }
		relation = { tag = NEP value = 50 }
		relation = { tag = NIC value = 10 }
		relation = { tag = NOR value = 20 }
		relation = { tag = NZL value = 50 }
		relation = { tag = OMN value = 50 }
		relation = { tag = PAN value = 30 }
		relation = { tag = PAR value = 10 }
		relation = { tag = PER value = 25 }
		relation = { tag = PHI value = 20 }
		relation = { tag = POL value = 35 }
		relation = { tag = POR value = 30 }
		relation = { tag = PRU value = 30 }
		relation = { tag = ROM value = 25 }
		relation = { tag = SAF value = 50 }
		relation = { tag = SAL value = 10 }
		relation = { tag = SAU value = 20 }
		relation = { tag = SIA value = 10 }
		relation = { tag = SIK value = 1 }
		relation = { tag = SOV value = 20 }
		relation = { tag = SPA value = 30 }
		relation = { tag = SPR value = 30 }
		relation = { tag = SWE value = 30 }
		relation = { tag = SCH value = 50 }
		relation = { tag = TAN value = 1 }
		relation = { tag = TIB value = 1 }
		relation = { tag = TUR value = 25 }
		relation = { tag = U27 value = 175 guaranteed = { day = 30 month = december year = 1935 } access = yes }
		relation = { tag = URU value = 10 }
		relation = { tag = USA value = 100 }
		relation = { tag = VEN value = 40 }
		relation = { tag = YEM value = 50 }
		relation = { tag = YUG value = 20 }
	}

	SpyInfo = { country = "CAN" NumberOfSpies = 3 }
	SpyInfo = { country = "ARG" NumberOfSpies = 1 }
	SpyInfo = { country = "AUS" NumberOfSpies = 2 }
	SpyInfo = { country = "BRA" NumberOfSpies = 1 }
	SpyInfo = { country = "CHI" NumberOfSpies = 1 }
	SpyInfo = { country = "CUB" NumberOfSpies = 1 }
	SpyInfo = { country = "CZE" NumberOfSpies = 1 }
	SpyInfo = { country = "EGY" NumberOfSpies = 1 }
	SpyInfo = { country = "ENG" NumberOfSpies = 4 }
	SpyInfo = { country = "FIN" NumberOfSpies = 2 }
	SpyInfo = { country = "FRA" NumberOfSpies = 2 }
	SpyInfo = { country = "GER" NumberOfSpies = 1 }
	SpyInfo = { country = "GRE" NumberOfSpies = 1 }
	SpyInfo = { country = "HOL" NumberOfSpies = 1 }
	SpyInfo = { country = "IND" NumberOfSpies = 1 }
	SpyInfo = { country = "IRE" NumberOfSpies = 1 }
	SpyInfo = { country = "JAP" NumberOfSpies = 1 }
	SpyInfo = { country = "MEX" NumberOfSpies = 1 }
	SpyInfo = { country = "MLY" NumberOfSpies = 1 }
	SpyInfo = { country = "PAN" NumberOfSpies = 1 }
	SpyInfo = { country = "PER" NumberOfSpies = 1 }
	SpyInfo = { country = "PHI" NumberOfSpies = 1 }
	SpyInfo = { country = "POR" NumberOfSpies = 1 }
	SpyInfo = { country = "SAF" NumberOfSpies = 1 }
	SpyInfo = { country = "SAU" NumberOfSpies = 1 }
	SpyInfo = { country = "SPR" NumberOfSpies = 1 }
	SpyInfo = { country = "SCH" NumberOfSpies = 1 }
	SpyInfo = { country = "TUR" NumberOfSpies = 1 }
	SpyInfo = { country = "U27" NumberOfSpies = 6 }
	SpyInfo = { country = "USA" NumberOfSpies = 4 }

  nationalprovinces      = { 556  541  555  554  552  558  557  796  797  799  798  795  794  559  560  561  563  566  567  570  568  569  571  565 
                             572  588  589  590  591  587  585  584  573  586  574  564  581  580  579  578  1909
                           }
  ownedprovinces         = { 556  541  555  554  552  558  557  796  797  799  798  795  794  559  560  561  563  566  567  570  568  569  571  565 
                             572  588  589  590  591  587  585  584  573  586  574  564  581  580  579  578  1909
                           }
  controlledprovinces    = { 556  541  555  554  552  558  557  796  797  799  798  795  794  559  560  561  563  566  567  570  568  569  571  565 
                             572  588  589  590  591  587  585  584  573  586  574  564  581  580  579  578  1909
                           }
  # Commonwealth Tech '36
  # UK 1936 techs
  # ######################
  techapps               = { 1310 1010  1020  1190  1200  1210  1220  14000 2010     2290  2300  2310  2450  2460  2510  3010  3020  3070  4010  4020 
                             4120  4130  5010  5020  5080  5090  5190  5310  6010  6030  6120  8010  8020  8030  8040  8050  8070  8100  8120 
                             9010  9020  9030  9140 
			4250
                           }
  blueprints             = { 2150 }
  policy =
  { date              = { year = 0 month = january day = 0 }
    democratic        = 10
    political_left    = 2
    free_market       = 10
    freedom           = 10
    professional_army = 6
    defense_lobby     = 2
    interventionism   = 4
  }
  headofstate            = { type = 9 id = 45001 }
  headofgovernment       = { type = 9 id = 45002 }
  foreignminister        = { type = 9 id = 45003 }
  armamentminister       = { type = 9 id = 45004 }
  ministerofsecurity     = { type = 9 id = 45005 }
  ministerofintelligence = { type = 9 id = 45006 }
  chiefofstaff           = { type = 9 id = 45007 }
  chiefofarmy            = { type = 9 id = 45008 }
  chiefofnavy            = { type = 9 id = 45009 }
  chiefofair             = { type = 9 id = 45010 }

landunit = {
	id = { type = 20000 id = 100 }
	name = "Royal Canadian Army"
	location = 588

	division = {
		id = { type = 12010 id = 1 }
		name = "1st Canadian Army"
		strength = 100
		type = hq
		model = 0
		extra = engineer
	}
	division = {
		id = { type = 12010 id = 2 }
		name = "1st Canadian Infantry Div."
		strength = 25
		type = infantry
		model = 0
		extra = artillery
		brigade_model = 0
	}
}

landunit = {
	id = { type = 20000 id = 101 }
	name = "1st Coast Brigade"
	location = 579

	division = {
		id = { type = 12010 id = 102 }
		name = "1st Coast Brigade"
		type = garrison
		model = 0
		strength = 40
		locked = yes
		extra = artillery
		brigade_model = 1
	}
}

landunit = {
	id = { type = 20000 id = 103 }
	name = "3rd Coast Brigade"
	location = 581

	division = {
		id = { type = 12010 id = 104 }
		name = "3rd Coast Brigade"
		type = garrison
		model = 0
		strength = 40
		locked = yes
	}
}

landunit = {
	id = { type = 20000 id = 105 }
	name = "5th Coast Brigade"
	location = 541

	division = {
		id = { type = 12010 id = 106 }
		name = "5th Coast Brigade"
		type = garrison
		model = 0
		strength = 40
		locked = yes
		extra = artillery
		brigade_model = 1
	}
}

  navalunit =
  { id       = { type = 20000 id = 3 }
    location = 579
    base     = 579
    name     = "Canadian Transport Fleet"
    division =
    { id   = { type = 20000 id = 4 }
      name = "'Empress of Japan' Flotilla"
      type = transport
    }
    division =
    { id   = { type = 20000 id = 5 }
      name = "'Empress of Australia' Flotilla"
      type = transport
    }
    division =
    { id   = { type = 20000 id = 6 }
      name = "'Empress of Britain' Flotilla"
      type = transport
    }
    division =
    { id   = { type = 20000 id = 9 }
      name = "'Empress of Canada' Flotilla"
      type = transport
    }
    division =
    { id   = { type = 20000 id = 10 }
      name = "'Empress of Russia' Flotilla"
      type = transport
    }
    division =
    { id   = { type = 20000 id = 11 }
      name = "'Empress of Asia' Flotilla"
      type = transport
    }
  }
  navalunit =
  { id       = { type = 20000 id = 7 }
    name     = "Royal Canadian Navy"
    location = 579
    base     = 579
    division =
    { id       = { type = 20000 id = 8 }
      name     = "Destroyer Flotilla 1"
      strength = 100
      type     = destroyer
      model    = 0
      extra1 = naval_fire_controll_s
      brigade_model1 = 0
    }
  } 
	province_development = { 
		id = { type = 20000 id = 18 } 
		name = "" 
		progress = 0.0000 
		location = 572 
		cost = 5.0000 
		date = { 
			year = 1948 
			month = october 
			day = 18 
			hour = 0 
			} 
		manpower = 1.0000 
		close_when_finished = yes 
		waitingforclosure = no 
		total_progress = 0.0000 
		size = 16 
		done = 0 
		days = 28800 
		days_for_first = 288 
		gearing_bonus = 0.0000 
		type = ic 
		} 
	province_development = { 
		id = { type = 20000 id = 19 } 
		name = "" 
		progress = 0.0000 
		location = 555 
		cost = 5.0000 
		date = { 
			year = 1937 
			month = august 
			day = 6 
			hour = 0 
			} 
		manpower = 1.0000 
		close_when_finished = yes 
		waitingforclosure = no 
		total_progress = 0.0000 
		size = 2 
		done = 0 
		days = 576 
		days_for_first = 288 
		gearing_bonus = 0.0000 
		type = ic 
		} 
	province_development = { 
		id = { type = 20000 id = 20 } 
		name = "" 
		progress = 0.0000 
		location = 797 
		cost = 5.0000 
		date = { 
			year = 1937 
			month = august 
			day = 6 
			hour = 0 
			} 
		manpower = 1.0000 
		close_when_finished = yes 
		waitingforclosure = no 
		total_progress = 0.0000 
		size = 2 
		done = 0 
		days = 576 
		days_for_first = 288 
		gearing_bonus = 0.0000 
		type = ic 
		} 
	province_development = { 
		id = { type = 20000 id = 13 } 
		name = "" 
		progress = 0.0000 
		location = 588 
		cost = 2.0000 
		date = { 
			year = 1941 
			month = april 
			day = 8 
			hour = 0 
			} 
		manpower = 0.1000 
		close_when_finished = yes 
		waitingforclosure = no 
		total_progress = 0.0000 
		size = 24 
		done = 0 
		days = 1899 
		days_for_first = 96 
		gearing_bonus = 0.0000 
		type = infrastructure 
		} 
	province_development = { 
		id = { type = 20000 id = 14 } 
		name = "" 
		progress = 0.0000 
		location = 541 
		cost = 2.0000 
		date = { 
			year = 1942 
			month = august 
			day = 3 
			hour = 0 
			} 
		manpower = 0.1000 
		close_when_finished = yes 
		waitingforclosure = no 
		total_progress = 0.0000 
		size = 24 
		done = 0 
		days = 1899 
		days_for_first = 120 
		gearing_bonus = 0.0000 
		type = infrastructure 
		} 
	province_development = { 
		id = { type = 20000 id = 15 } 
		name = "" 
		progress = 0.0000 
		location = 555 
		cost = 2.0000 
		date = { 
			year = 1949 
			month = march 
			day = 7 
			hour = 0 
			} 
		manpower = 0.1000 
		close_when_finished = yes 
		waitingforclosure = no 
		total_progress = 0.0000 
		size = 24 
		done = 0 
		days = 1899 
		days_for_first = 240 
		gearing_bonus = 0.0000 
		type = infrastructure 
		} 
	province_development = { 
		id = { type = 20000 id = 16 } 
		name = "" 
		progress = 0.0000 
		location = 796 
		cost = 2.0000 
		date = { 
			year = 1942 
			month = february 
			day = 17 
			hour = 0 
			} 
		manpower = 0.1000 
		close_when_finished = yes 
		waitingforclosure = no 
		total_progress = 0.0000 
		size = 28 
		done = 0 
		days = 2208 
		days_for_first = 96 
		gearing_bonus = 0.0000 
		type = infrastructure 
		} 
	province_development = { 
		id = { type = 20000 id = 17 } 
		name = "" 
		progress = 0.0000 
		location = 572 
		cost = 2.0000 
		date = { 
			year = 1942 
			month = august 
			day = 3 
			hour = 0 
			} 
		manpower = 0.1000 
		close_when_finished = yes 
		waitingforclosure = no 
		total_progress = 0.0000 
		size = 24 
		done = 0 
		days = 1899 
		days_for_first = 120 
		gearing_bonus = 0.0000 
		type = infrastructure 
		} 
	province_development = { 
		id = { type = 20000 id = 21 } 
		name = "" 
		progress = 0.0000 
		location = 797 
		cost = 2.0000 
		date = { 
			year = 1942 
			month = may 
			day = 24 
			hour = 0 
			} 
		manpower = 0.1000 
		close_when_finished = yes 
		waitingforclosure = no 
		total_progress = 0.0000 
		size = 24 
		done = 0 
		days = 1899 
		days_for_first = 96 
		gearing_bonus = 0.0000 
		type = infrastructure 
		} 
}
