#####################
# Country main data #
#####################

country =
{ tag                    = CHC
  intrinsic_gov_type     = leninist
  capital                = 1271 # Yan'an
  # Resource Reserves
  energy                 = 200
  metal                  = 200
  rare_materials         = 100
  oil                    = 100
  supplies               = 800
  money                  = 50
  consumer = 0.0000 
  supply = 0.0000 
  production = 1.0000 
  reinforcement = 0.0000 
  upgrading = 0.0000 
  manpower               = 344.9 # 350 - building queue

	diplomacy = {
		relation = { tag = AFG value = -10 }
		relation = { tag = ALB value = 1 }
		relation = { tag = ARG value = 1 }
		relation = { tag = AST value = -10 }
		relation = { tag = AUS value = 1 }
		relation = { tag = BEL value = 1 }
		relation = { tag = BHU value = 1 }
		relation = { tag = BOL value = 1 }
		relation = { tag = BRA value = 1 }
		relation = { tag = BUL value = 1 }
		relation = { tag = CAN value = -10 }
		relation = { tag = CGX value = -20 }
		relation = { tag = CHI value = -75 }
		relation = { tag = CHL value = 1 }
		relation = { tag = COL value = 1 }
		relation = { tag = COS value = 1 }
		relation = { tag = CSX value = -25 }
		relation = { tag = CUB value = 1 }
		relation = { tag = CXB value = -40 }
		relation = { tag = CYN value = -10 }
		relation = { tag = CZE value = 1 }
		relation = { tag = DEN value = 1 }
		relation = { tag = DOM value = 1 }
		relation = { tag = ECU value = 1 }
		relation = { tag = EGY value = 1 }
		relation = { tag = ENG value = -15 }
		relation = { tag = EST value = 1 }
		relation = { tag = ETH value = 1 }
		relation = { tag = FIN value = 1 }
		relation = { tag = FRA value = -20 }
		relation = { tag = GER value = -25 }
		relation = { tag = GRE value = 1 }
		relation = { tag = GUA value = 1 }
		relation = { tag = HAI value = 1 }
		relation = { tag = HOL value = 1 }
		relation = { tag = HON value = 1 }
		relation = { tag = HUN value = 1 }
		relation = { tag = IND value = -10 }
		relation = { tag = IRE value = 1 }
		relation = { tag = IRQ value = 1 }
		relation = { tag = ITA value = -15 }
		relation = { tag = JAP value = -50 }
		relation = { tag = LAT value = 1 }
		relation = { tag = LIB value = 1 }
		relation = { tag = LIT value = 1 }
		relation = { tag = LUX value = 1 }
		relation = { tag = MAN value = -75 }
		relation = { tag = MEX value = 1 }
		relation = { tag = MLY value = -15 }
		relation = { tag = MON value = -25 }
		relation = { tag = NEP value = -10 }
		relation = { tag = NIC value = 1 }
		relation = { tag = NOR value = 1 }
		relation = { tag = NZL value = -10 }
		relation = { tag = OMN value = 1 }
		relation = { tag = PAN value = 1 }
		relation = { tag = PAR value = 1 }
		relation = { tag = PER value = 1 }
		relation = { tag = PHI value = -10 }
		relation = { tag = POL value = 1 }
		relation = { tag = POR value = -10 }
		relation = { tag = PRU value = 1 }
		relation = { tag = ROM value = 1 }
		relation = { tag = SAF value = 1 }
		relation = { tag = SAL value = 1 }
		relation = { tag = SAU value = 1 }
		relation = { tag = SIA value = -10 }
		relation = { tag = SIK value = 1 }
		relation = { tag = SOV value = 40 }
		relation = { tag = SPA value = 1 }
		relation = { tag = SPR value = 1 }
		relation = { tag = SWE value = 1 }
		relation = { tag = SCH value = 1 }
		relation = { tag = TAN value = -30 }
		relation = { tag = TIB value = -10 }
		relation = { tag = TUR value = 1 }
		relation = { tag = U27 value = 1 }
		relation = { tag = URU value = 1 }
		relation = { tag = USA value = -15 }
		relation = { tag = VEN value = 1 }
		relation = { tag = YEM value = 1 }
		relation = { tag = YUG value = 1 }
	}

	SpyInfo = { country = "CHC" NumberOfSpies = 8 }
	SpyInfo = { country = "CAN" NumberOfSpies = 1 }
	SpyInfo = { country = "CGX" NumberOfSpies = 4 }
	SpyInfo = { country = "CHI" NumberOfSpies = 6 }
	SpyInfo = { country = "CSX" NumberOfSpies = 6 }
	SpyInfo = { country = "CXB" NumberOfSpies = 4 }
	SpyInfo = { country = "CYN" NumberOfSpies = 2 }
	SpyInfo = { country = "ENG" NumberOfSpies = 1 }
	SpyInfo = { country = "FRA" NumberOfSpies = 2 }
	SpyInfo = { country = "IND" NumberOfSpies = 1 }
	SpyInfo = { country = "MAN" NumberOfSpies = 4 }
	SpyInfo = { country = "MLY" NumberOfSpies = 1 }
	SpyInfo = { country = "MON" NumberOfSpies = 2 }
	SpyInfo = { country = "NEP" NumberOfSpies = 1 }
	SpyInfo = { country = "POR" NumberOfSpies = 1 }
	SpyInfo = { country = "SIA" NumberOfSpies = 2 }
	SpyInfo = { country = "SIK" NumberOfSpies = 4 }
	SpyInfo = { country = "SOV" NumberOfSpies = 2 }
	SpyInfo = { country = "TAN" NumberOfSpies = 4 }
	SpyInfo = { country = "TIB" NumberOfSpies = 4 }
	SpyInfo = { country = "USA" NumberOfSpies = 1 }

  nationalprovinces      = { 1305 1293 1282 1281 1327 1307 1308 1309 1325 1320 1321 1319 1310 1318 1312 1311 1313 1317 1314 1360 1361 1362 1363 1364
                             1365 1277 1275 1269 1268 1267 1266 1279 1280 1265 1264 1263 1262 1261 1260 1259 1258 1257 1256 1255 1254 1253 1252 1251
                             1250 1249 1248 1247 1246 1245 1244 1243 1242 1241 1240 1239 1238 1237 1236 1235 1234 1233 1232 1231 1230 1229 1228 1227
                             1226 1225 1224 1223 1222 1221 1220 1219 1218 1217 1216 1215 1214 1213 1212 1211 1210 1209 1208 1207 1206 1205 1270 1271
                             1273 1203 1204 1394 1395 1396 1397 1389 1390 1377 1378 1375 1374 1379 1530 1380 1387 1382 1381 1398 1386 1388 1202 1323
                             1322 1324 1439 1440 1441 1442 1443 1444 1448 1450 1451 1452 1453 1283 1421 1433 1432 1435 1445 1447 1446 1431 1430 1274
                             1276 1294 1315 1272 1278 1316
                           }
  ownedprovinces         = { 1270 1271 1275 }
  controlledprovinces    = { 1270 1271 1275 }
  # Group E 1936 techs
  # ######################
  # GW fighter
  techapps               = { 14080 1010 1110 1190 5080 6210 6300 1310 }
  blueprints             = { 1020 }
  policy =
  { date              = { year = 0 month = january day = 0 }
    democratic        = 1
    political_left    = 10
    free_market       = 1
    freedom           = 2
    professional_army = 3
    defense_lobby     = 10
    interventionism   = 5
  }
  headofstate            = { type = 9 id = 51001 }
  headofgovernment       = { type = 9 id = 51002 }
  foreignminister        = { type = 9 id = 51003 }
  armamentminister       = { type = 9 id = 51004 }
  ministerofsecurity     = { type = 9 id = 51005 }
  ministerofintelligence = { type = 9 id = 51006 }
  chiefofstaff           = { type = 9 id = 51007 }
  chiefofarmy            = { type = 9 id = 51008 }
  chiefofnavy            = { type = 9 id = 51009 }
  chiefofair             = { type = 9 id = 51010 }

#LAND OOB

landunit = {
	location = 1271
	name = "1. Fangmianjun"
	id = { type = 24000 id = 1001 }

	division = {
		experience = 40
		id = { type = 24000 id = 1002 }
		name = "1. Juntuan"
		type = bergsjaeger
		model = 0
		}

	division = {
		experience = 20
		id = { type = 24000 id = 1003 }
		name = "15. Juntuan"
		type = bergsjaeger
		model = 0
		}

	division = {
		experience = 20
		id = { type = 24000 id = 1004 }
		name = "5. Juntuan"
		type = bergsjaeger
		model = 0
		}
	division = {
		id = { type = 24000 id = 10041 }
		name = "Di 1 Fangmianjun"
		type = hq
		model = 0
		}
	dig_in = 20.000 
	}

landunit = {
	location = 1275
	name = "4. Fangmianjun"
	id = { type = 24000 id = 1005 }

	division = {
		experience = 20
		id = { type = 24000 id = 1006 }
		name = "3. Juntuan"
		type = bergsjaeger
		model = 0
		}	
	
	division = {
		experience = 20
		id = { type = 24000 id = 1007 }
		name = "2. Juntuan"
		type = bergsjaeger
		model = 0
		}

	division = {
		experience = 20
		id = { type = 24000 id = 1008 }
		name = "6. Juntuan"
		type = bergsjaeger
		model = 0
		}
		
	division = {
		experience = 20
		id = { type = 24000 id = 1009 }
		name = "8. Juntuan"
		type = bergsjaeger
		model = 0
		}

	dig_in = 20.000 
	}

landunit = {
	location = 1270 # Xianyang
	name = "26. Jun Tuan"
	id = { type = 24000 id = 1010 }

	division = {
		experience = 20
		id = { type = 24000 id = 1011 }
		name = "26. Jun"
		type = bergsjaeger
		model = 0
		}

	division = {
		experience = 20
		id = { type = 24000 id = 1012 }
		name = "27. Jun"
		type = bergsjaeger
		model = 0
		}

	division = {
		experience = 20
		id = { type = 24000 id = 1013 }
		name = "30. Jun"
		type = militia
		model = 0
		}

	division = {
		experience = 20
		id = { type = 24000 id = 1014 }
		name = "31. Jun"
		type = militia
		model = 0
		}

	dig_in = 20.000 
	}

#2nd ARMY OOB

landdivision = {
	dormant = yes
	id = { type = 24000 id = 1015 }
	name = "25. Jun"
	type = militia
	model = 0
	strength = 100
	max_strength = 100
	experience = 20
	}
	
landdivision = {
	dormant = yes
	id = { type = 24000 id = 1016 }
	name = "4. Jun"
	type = militia
	model = 0
	strength = 100
	max_strength = 100
	experience = 20
	}	
	
landdivision = {
	dormant = yes
	id = { type = 24000 id = 1017 }
	name = "10. Jun"
	type = bergsjaeger
	model = 0
	strength = 100
	max_strength = 100
	experience = 20
	}

landdivision = {
	dormant = yes
	id = { type = 24000 id = 1018 }
	name = "11. Jun"
	type = bergsjaeger
	model = 0
	strength = 100
	max_strength = 100
	experience = 20
	}

landdivision = {
	dormant = yes
	id = { type = 24000 id = 1019 }
	name = "12. Jun"
	type = bergsjaeger
	model = 0
	strength = 100
	max_strength = 100
	experience = 20
	}

landdivision = {
	dormant = yes
	id = { type = 24000 id = 1020 }
	name = "13. Jun"
	type = bergsjaeger
	model = 0
	strength = 100
	max_strength = 100
	experience = 20
	}	
	
	province_development = { 
		id = { type = 24000 id = 20 } 
		name = "" 
		progress = 0.0000 
		location = 1271 
		cost = 2.0000 
		date = { 
			year = 1953 
			month = march 
			day = 6 
			hour = 0 
			} 
		manpower = 0.1000 
		close_when_finished = yes 
		waitingforclosure = no 
		total_progress = 0.0000 
		size = 32 
		done = 0 
		days = 2474 
		days_for_first = 240 
		gearing_bonus = 0.0000 
		type = infrastructure 
		} 
}
