#####################
# Country main data #
#####################

country =
{ tag                    = CZE
  # Resource Reserves
  energy                 = 4386
  metal                  = 1248
  rare_materials         = 666
  oil                    = 42
  supplies               = 1406
  money                  = 90
  manpower               = 143.1000  # 150 - building queue -5 for HQ
  consumer = 0.3300 
  supply = 0.1700 
  production = 0.5000 
  reinforcement = 0.0000 
  upgrading = 0.0000 
  capital                = 469

	diplomacy = {
		relation = { tag = AFG value = 1 }
		relation = { tag = ALB value = 15 }
		relation = { tag = ARG value = 10 }
		relation = { tag = AST value = 35 }
		relation = { tag = AUS value = 30 }
		relation = { tag = BEL value = 35 }
		relation = { tag = BHU value = 1 }
		relation = { tag = BOL value = 1 }
		relation = { tag = BRA value = 20 }
		relation = { tag = BUL value = 25 }
		relation = { tag = CAN value = 35 }
		relation = { tag = CGX value = 1 }
		relation = { tag = CHC value = 1 }
		relation = { tag = CHI value = 15 }
		relation = { tag = CHL value = 1 }
		relation = { tag = COL value = 15 }
		relation = { tag = COS value = 1 }
		relation = { tag = CSX value = 1 }
		relation = { tag = CUB value = 1 }
		relation = { tag = CXB value = 1 }
		relation = { tag = CYN value = 1 }
		relation = { tag = DEN value = 35 }
		relation = { tag = DOM value = 1 }
		relation = { tag = ECU value = 15 }
		relation = { tag = EGY value = 1 }
		relation = { tag = ENG value = 75 }
		relation = { tag = EST value = 15 }
		relation = { tag = ETH value = 30 }
		relation = { tag = FIN value = 30 }
		relation = { tag = FRA value = 65 }
		relation = { tag = GER value = 30 }
		relation = { tag = GRE value = 30 }
		relation = { tag = GUA value = 1 }
		relation = { tag = HAI value = 1 }
		relation = { tag = HOL value = 30 }
		relation = { tag = HON value = 1 }
		relation = { tag = HUN value = 35 }
		relation = { tag = IND value = 1 }
		relation = { tag = IRE value = 35 }
		relation = { tag = IRQ value = 1 }
		relation = { tag = ITA value = 40 }
		relation = { tag = JAP value = 20 }
		relation = { tag = LAT value = 20 }
		relation = { tag = LIB value = 1 }
		relation = { tag = LIT value = 20 }
		relation = { tag = LUX value = 35 }
		relation = { tag = MAN value = 1 }
		relation = { tag = MEX value = 20 }
		relation = { tag = MLY value = 1 }
		relation = { tag = MON value = 1 }
		relation = { tag = NEP value = 1 }
		relation = { tag = NIC value = 1 }
		relation = { tag = NOR value = 25 }
		relation = { tag = NZL value = 30 }
		relation = { tag = OMN value = 1 }
		relation = { tag = PAN value = 1 }
		relation = { tag = PAR value = 1 }
		relation = { tag = PER value = 20 }
		relation = { tag = PHI value = 1 }
		relation = { tag = POL value = 50 }
		relation = { tag = POR value = 20 }
		relation = { tag = PRU value = 15 }
		relation = { tag = ROM value = 40 guaranteed = { day = 30 month = december year = 1935 } }
		relation = { tag = SAF value = 35 }
		relation = { tag = SAL value = 1 }
		relation = { tag = SAU value = 10 }
		relation = { tag = SIA value = 10 }
		relation = { tag = SIK value = 1 }
		relation = { tag = SOV value = 75 }
		relation = { tag = SPA value = 25 }
		relation = { tag = SPR value = 45 }
		relation = { tag = SWE value = 40 }
		relation = { tag = SCH value = 50 }
		relation = { tag = TAN value = 1 }
		relation = { tag = TIB value = 1 }
		relation = { tag = TUR value = 30 }
		relation = { tag = U27 value = 1 }
		relation = { tag = URU value = 1 }
		relation = { tag = USA value = 40 }
		relation = { tag = VEN value = 30 }
		relation = { tag = YEM value = 1 }
		relation = { tag = YUG value = 40 guaranteed = { day = 30 month = december year = 1935 } }
	}

	SpyInfo = { country = "CZE" NumberOfSpies = 6 }
	SpyInfo = { country = "AUS" NumberOfSpies = 4 }
	SpyInfo = { country = "BUL" NumberOfSpies = 1 }
	SpyInfo = { country = "ENG" NumberOfSpies = 2 }
	SpyInfo = { country = "FRA" NumberOfSpies = 2 }
	SpyInfo = { country = "GER" NumberOfSpies = 3 }
	SpyInfo = { country = "HUN" NumberOfSpies = 4 }
	SpyInfo = { country = "ITA" NumberOfSpies = 1 }
	SpyInfo = { country = "POL" NumberOfSpies = 4 }
	SpyInfo = { country = "POR" NumberOfSpies = 1 }
	SpyInfo = { country = "ROM" NumberOfSpies = 2 }
	SpyInfo = { country = "SOV" NumberOfSpies = 4 }
	SpyInfo = { country = "SPR" NumberOfSpies = 1 }
	SpyInfo = { country = "SCH" NumberOfSpies = 1 }
	SpyInfo = { country = "TUR" NumberOfSpies = 1 }
	SpyInfo = { country = "USA" NumberOfSpies = 1 }
	SpyInfo = { country = "YUG" NumberOfSpies = 2 }

  nationalprovinces      = { 471 472 466 467 470 469 468 474 475 478 477 490 499 476 }
  ownedprovinces         = { 471 472 466 467 470 469 468 474 475 478 477 490 499 476 }
  controlledprovinces    = { 471 472 466 467 470 469 468 474 475 478 477 490 499 476 }
  # Eastern Minor Tech '36
  # Group C 1936 techs
  # ######################
  techapps               = { 1010  1020  1110  1190  1310  14000 2010  2020  2030  2040    2150 2290  2300  2310  2400 2450  2460  2510  4010  4020  4120 
                             5010  5020  5080  5090  5190  6010  6020  9010
                           }
  policy =
  { date              = { year = 0 month = january day = 0 }
    democratic        = 9
    political_left    = 3
    free_market       = 9
    freedom           = 8
    professional_army = 5
    defense_lobby     = 9
    interventionism   = 5
  }
  headofstate            = { type = 9 id = 24001 }
  headofgovernment       = { type = 9 id = 24002 }
  foreignminister        = { type = 9 id = 24003 }
  armamentminister       = { type = 9 id = 24004 }
  ministerofsecurity     = { type = 9 id = 24005 }
  ministerofintelligence = { type = 9 id = 24006 }
  chiefofstaff           = { type = 9 id = 24007 }
  chiefofarmy            = { type = 9 id = 24008 }
  chiefofnavy            = { type = 9 id = 24009 }
  chiefofair             = { type = 9 id = 24010 }
  # ################################
  # Czech army
  # ################################
  # The 8th Corps, based as reserves in Slovakia
  landunit =
  { id       = { type = 26000 id = 1 }
    location = 490
    name     = "VIII Druh Vojenského Utvaru"
    division =
    { id       = { type = 26000 id = 2 }
      name     = "9. divize"
      type     = infantry
      strength = 100
      model    = 0
    }
    division =
    { id       = { type = 26000 id = 3 }
      name     = "15. divize"
      type     = infantry
      strength = 100
      model    = 0
    }
    division =
    { id       = { type = 26000 id = 4 }
      name     = "21. divize"
      type     = infantry
      strength = 100
      model    = 0
    }
  }
  # General Reserves, based in Moravia
  landunit =
  { id       = { type = 26000 id = 5 }
    location = 467
    name     = "Generálni Rezeny"
    division =
    { id       = { type = 26000 id = 6 }
      name     = "1. rychlá divize"
      type     = light_armor
      model    = 1
      strength = 100
    }
    division =
    { id       = { type = 26000 id = 7 }
      name     = "4. divize"
      type     = infantry
      strength = 100
      model    = 0
      extra    = artillery
    }
    division =
    { id       = { type = 26000 id = 8 }
      name     = "12. divize"
      type     = infantry
      strength = 100
      model    = 0
    }
    division =
    { id    = { type = 26000 id = 9 }
      name  = "13. motostrelecká divize"
      type  = infantry
      model = 1
      extra = armored_car
    }
    division =
    { id       = { type = 26000 id = 10 }
      name     = "16. divize"
      type     = infantry
      strength = 100
      model    = 0
    }
    division =
    { id       = { type = 26000 id = 11 }
      name     = "22. divize"
      type     = infantry
      strength = 100
      model    = 0
    }
  }
  # 1st Army - in Bohemia
  landunit =
  { id       = { type = 26000 id = 12 }
    location = 471
    name     = "I Armáda"
    division =
    { id       = { type = 26000 id = 100 }
      name     = "Cechoslovák hlavní štáb"
      type     = hq
      strength = 100
      model    = 0
      extra    = anti_air
    }
    division =
    { id       = { type = 26000 id = 13 }
      name     = "18. divize"
      type     = infantry
      strength = 100
      model    = 0
    }
    division =
    { id       = { type = 26000 id = 14 }
      name     = "2. divize"
      type     = infantry
      strength = 100
      model    = 0
    }
    division =
    { id       = { type = 26000 id = 15 }
      name     = "5. divize"
      type     = infantry
      strength = 100
      model    = 0
      extra    = artillery
    }
    division =
    { id       = { type = 26000 id = 16 }
      name     = "3. divize"
      type     = infantry
      strength = 100
      model    = 0
    }
    division =
    { id       = { type = 26000 id = 17 }
      name     = "17. divize"
      type     = infantry
      strength = 100
      model    = 0
    }
  }
  # 2nd Army - N-Moravia
  landunit =
  { id       = { type = 26000 id = 18 }
    location = 472
    name     = "II Armáda"
    division =
    { id       = { type = 26000 id = 19 }
      name     = "1. horská brigáda"
      type     = bergsjaeger
      strength = 100
      model    = 0
    }
    division =
    { id       = { type = 26000 id = 20 }
      name     = "7. divize"
      type     = infantry
      strength = 100
      model    = 0
    }
  }
  # 4th Army - Slovakia
  landunit =
  { id       = { type = 26000 id = 21 }
    location = 477
    name     = "IV Armáda"
    division =
    { id       = { type = 26000 id = 22 }
      name     = "3. rychlá divize"
      type     = light_armor
      model    = 1
      strength = 100
    }
    division =
    { id       = { type = 26000 id = 23 }
      name     = "10. divize"
      type     = infantry
      strength = 100
      model    = 0
    }
    division =
    { id       = { type = 26000 id = 24 }
      name     = "11. divize"
      type     = infantry
      strength = 100
      model    = 0
      extra    = anti_air
    }
  }
  # 3rd Army - S-Morawia
  landunit =
  { id       = { type = 26000 id = 25 }
    location = 467
    name     = "III Armáda"
    division =
    { id       = { type = 26000 id = 26 }
      name     = "2. rychlá divize"
      type     = light_armor
      model    = 1
      strength = 100
    }
    division =
    { id       = { type = 26000 id = 27 }
      name     = "4. rychlá divize"
      type     = light_armor
      model    = 0
      strength = 100
    }
    division =
    { id    = { type = 26000 id = 28 }
      name  = "14. motostrelecká divize"
      type  = infantry
      model = 1
      extra = armored_car
    }
    division =
    { id       = { type = 26000 id = 29 }
      name     = "19. divize"
      type     = infantry
      strength = 100
      model    = 0
    }
    division =
    { id       = { type = 26000 id = 30 }
      name     = "6. divize"
      type     = infantry
      strength = 100
      model    = 0
      extra    = engineer
    }
    division =
    { id       = { type = 26000 id = 31 }
      name     = "20. divize"
      type     = infantry
      strength = 100
      model    = 0
    }
  } 

#########################################################################
# Airforce
#########################################################################

  airunit =
  { id       = { type = 26000 id = 43 }
    name = "I. Vzdusné Síly Armády"
    location = 469
    base     = 469
    division =
    { id       = { type = 26000 id = 44 }
      name = "1. stihaci letecky pluk" 
      strength = 70
      model    = 0
      type     = interceptor
    }
    division =
    { id       = { type = 26000 id = 45 }
      name = "1. bombardovaci letecky pluk" 
      strength = 70
      model    = 0
      type     = cas
    }
  }

  airunit =
  { id       = { type = 26000 id = 46 }
    name = "II. Vzdusné Síly Armády"
    location = 476
    base     = 476
    division =
    { id       = { type = 26000 id = 47 }
      name     = "2. stihaci letecky pluk"
      strength = 70
      model    = 0
      type     = interceptor
    }
  }

#########################################################################
# Constructions
#########################################################################

	province_development = { 
		id = { type = 26000 id = 36 } 
		name = "" 
		progress = 0.0000 
		location = 470 
		cost = 5.0000 
		date = { 
			year = 1937 
			month = december 
			day = 2 
			hour = 0 
			} 
		manpower = 1.0000 
		close_when_finished = yes 
		waitingforclosure = no 
		total_progress = 0.0000 
		size = 4 
		done = 0 
		days = 979 
		days_for_first = 245 
		gearing_bonus = 0.0000 
		speed_step = 1 
		type = ic 
		} 
	province_development = { 
		id = { type = 26000 id = 38 } 
		name = "" 
		progress = 0.0000 
		location = 474 
		cost = 2.0000 
		date = { 
			year = 1938 
			month = august 
			day = 23 
			hour = 0 
			} 
		manpower = 0.1000 
		close_when_finished = yes 
		waitingforclosure = no 
		total_progress = 0.0000 
		size = 20 
		done = 0 
		days = 1342 
		days_for_first = 82 
		gearing_bonus = 0.0000 
		speed_step = 1 
		type = infrastructure 
		} 
	province_development = { 
		id = { type = 26000 id = 49 } 
		name = "" 
		progress = 0.0000 
		location = 471 
		cost = 2.0000 
		date = { 
			year = 1938 
			month = august 
			day = 23 
			hour = 0 
			} 
		manpower = 0.1000 
		close_when_finished = yes 
		waitingforclosure = no 
		total_progress = 0.0000 
		size = 20 
		done = 0 
		days = 1342 
		days_for_first = 82 
		gearing_bonus = 0.0000 
		speed_step = 1 
		type = infrastructure 
		} 
	province_development = { 
		id = { type = 26000 id = 41 } 
		name = "" 
		progress = 0.0000 
		location = 470 
		cost = 2.0000 
		date = { 
			year = 1938 
			month = august 
			day = 23 
			hour = 0 
			} 
		manpower = 0.1000 
		close_when_finished = yes 
		waitingforclosure = no 
		total_progress = 0.0000 
		size = 20 
		done = 0 
		days = 1342 
		days_for_first = 82 
		gearing_bonus = 0.0000 
		speed_step = 1 
		type = infrastructure 
		} 
	province_development = { 
		id = { type = 26000 id = 34 } 
		name = "" 
		progress = 0.0000 
		location = 469 
		cost = 2.0000 
		date = { 
			year = 1939 
			month = september 
			day = 28 
			hour = 0 
			} 
		manpower = 0.1000 
		close_when_finished = yes 
		waitingforclosure = no 
		total_progress = 0.0000 
		size = 20 
		done = 0 
		days = 1342 
		days_for_first = 82 
		gearing_bonus = 0.0000 
		type = infrastructure 
		} 
	province_development = { 
		id = { type = 26000 id = 50 } 
		name = "" 
		progress = 0.0000 
		location = 477 
		cost = 2.0000 
		date = { 
			year = 1939 
			month = september 
			day = 28 
			hour = 0 
			} 
		manpower = 0.1000 
		close_when_finished = yes 
		waitingforclosure = no 
		total_progress = 0.0000 
		size = 20 
		done = 0 
		days = 1342 
		days_for_first = 82 
		gearing_bonus = 0.0000 
		type = infrastructure 
		} 
	province_development = { 
		id = { type = 26000 id = 51 } 
		name = "" 
		progress = 0.0000 
		location = 466 
		cost = 2.0000 
		date = { 
			year = 1939 
			month = september 
			day = 28 
			hour = 0 
			} 
		manpower = 0.1000 
		close_when_finished = yes 
		waitingforclosure = no 
		total_progress = 0.0000 
		size = 20 
		done = 0 
		days = 1342 
		days_for_first = 82 
		gearing_bonus = 0.0000 
		type = infrastructure 
		} 
	province_development = { 
		id = { type = 26000 id = 52 } 
		name = "" 
		progress = 0.0000 
		location = 490 
		cost = 2.0000 
		date = { 
			year = 1940 
			month = june 
			day = 19 
			hour = 0 
			} 
		manpower = 0.1000 
		close_when_finished = yes 
		waitingforclosure = no 
		total_progress = 0.0000 
		size = 24 
		done = 0 
		days = 1601 
		days_for_first = 82 
		gearing_bonus = 0.0000 
		type = infrastructure 
		} 
	province_development = { 
		id = { type = 26000 id = 32 } 
		name = "" 
		progress = 0.0000 
		location = 476 
		cost = 2.0000 
		date = { 
			year = 1939 
			month = september 
			day = 28 
			hour = 0 
			} 
		manpower = 0.1000 
		close_when_finished = yes 
		waitingforclosure = no 
		total_progress = 0.0000 
		size = 20 
		done = 0 
		days = 1342 
		days_for_first = 82 
		gearing_bonus = 0.0000 
		type = infrastructure 
		} 
	province_development = { 
		id = { type = 26000 id = 53 } 
		name = "" 
		progress = 0.0000 
		location = 478 
		cost = 2.0000 
		date = { 
			year = 1939 
			month = september 
			day = 28 
			hour = 0 
			} 
		manpower = 0.1000 
		close_when_finished = yes 
		waitingforclosure = no 
		total_progress = 0.0000 
		size = 20 
		done = 0 
		days = 1342 
		days_for_first = 82 
		gearing_bonus = 0.0000 
		type = infrastructure 
		} 
}