##############################
# Country definition for FRA #
##############################

province = { id = 875 supplypool = 1 } # Cayenne
province =
{ id         = 949
  supplypool = 500
  oilpool    = 1
}              # Algiers
province = { id = 1037 supplypool = 1 } # Djibouti
province = { id = 1692 supplypool = 1 } # Noumea
province = { id = 1137 supplypool = 1 } # Tananarive
province = { id = 1135 supplypool = 1 } # Reunion
province = { id = 1751 supplypool = 1 } # Tahiti

#####################
# Country main data #
#####################

country =
{ tag                    = FRA
  capital                = 56
  # Resource Reserves
  energy                 = 14760
  metal                  = 9965
  rare_materials         = 2958
  oil                    = 1906
  supplies               = 6276
  money                  = 400
  consumer = 0.3000 
  supply = 0.1900 
  production = 0.5100 
  reinforcement = 0.0000 
  upgrading = 0.0000 
  manpower               = 26.6000 
  transports             = 600
  escorts                = 31
  peacetime_ic_mod       = 0.25
	diplomacy = {
		relation = { tag = AFG value = -10 }
		relation = { tag = ALB value = 10 }
		relation = { tag = ARG value = 25 }
		relation = { tag = AST value = 50 }
		relation = { tag = AUS value = 35 }
		relation = { tag = BEL value = 50 guaranteed = { day = 7 month = january year = 1935 } }
		relation = { tag = BHU value = 1 }
		relation = { tag = BOL value = 15 }
		relation = { tag = BRA value = 40 }
		relation = { tag = BUL value = 30 }
		relation = { tag = CAN value = 50 }
		relation = { tag = CGX value = 45 }
		relation = { tag = CHC value = -20 }
		relation = { tag = CHI value = 40 }
		relation = { tag = CHL value = 30 }
		relation = { tag = COL value = 40 }
		relation = { tag = COS value = 15 }
		relation = { tag = CSX value = 35 }
		relation = { tag = CUB value = 40 }
		relation = { tag = CXB value = 30 }
		relation = { tag = CYN value = 30 }
		relation = { tag = CZE value = 65 guaranteed = { day = 7 month = january year = 1935 } }
		relation = { tag = DEN value = 40 }
		relation = { tag = DOM value = 15 }
		relation = { tag = ECU value = 35 }
		relation = { tag = EGY value = 50 }
		relation = { tag = ENG value = 50 }
		relation = { tag = EST value = 20 }
		relation = { tag = ETH value = 50 }
		relation = { tag = FIN value = 40 }
		relation = { tag = GER value = 15 }
		relation = { tag = GRE value = 40 }
		relation = { tag = GUA value = 20 }
		relation = { tag = HAI value = 60 }
		relation = { tag = HOL value = 45 guaranteed = { day = 7 month = january year = 1935 } }
		relation = { tag = HON value = 20 }
		relation = { tag = HUN value = 20 }
		relation = { tag = IND value = 50 }
		relation = { tag = IRE value = 40 }
		relation = { tag = IRQ value = 50 }
		relation = { tag = ITA value = 35 }
		relation = { tag = JAP value = 35 }
		relation = { tag = LAT value = 20 }
		relation = { tag = LIB value = 30 }
		relation = { tag = LIT value = 20 }
		relation = { tag = LUX value = 75 guaranteed = { day = 7 month = january year = 1935 } }
		relation = { tag = MAN value = -15 }
		relation = { tag = MEX value = 35 }
		relation = { tag = MLY value = 40 }
		relation = { tag = MON value = -15 }
		relation = { tag = NEP value = 1 }
		relation = { tag = NIC value = 20 }
		relation = { tag = NOR value = 35 }
		relation = { tag = NZL value = 50 }
		relation = { tag = OMN value = 50 }
		relation = { tag = PAN value = 40 }
		relation = { tag = PAR value = 15 }
		relation = { tag = PER value = 40 }
		relation = { tag = PHI value = 35 }
		relation = { tag = POL value = 50 guaranteed = { day = 7 month = january year = 1935 } }
		relation = { tag = POR value = 35 }
		relation = { tag = PRU value = 20 }
		relation = { tag = ROM value = 45 }
		relation = { tag = SAF value = 50 }
		relation = { tag = SAL value = 20 }
		relation = { tag = SAU value = 25 }
		relation = { tag = SIA value = 30 }
		relation = { tag = SIK value = 20 }
		relation = { tag = SOV value = 45 }
		relation = { tag = SPA value = 25 }
		relation = { tag = SPR value = 45 }
		relation = { tag = SWE value = 40 }
		relation = { tag = SCH value = 50 guaranteed = { day = 30 month = december year = 1935 } }
		relation = { tag = TAN value = -15 }
		relation = { tag = TIB value = 20 }
		relation = { tag = TUR value = 40 guaranteed = { day = 7 month = january year = 1935 } }
		relation = { tag = U27 value = 1 }
		relation = { tag = URU value = 20 }
		relation = { tag = USA value = 50 }
		relation = { tag = VEN value = 45 }
		relation = { tag = YEM value = 50 }
		relation = { tag = YUG value = 45 guaranteed = { day = 30 month = august year = 1934 } }

		relation = { tag = VIE value = 200 access = yes }
		relation = { tag = CMB value = 200 access = yes }
		relation = { tag = LAO value = 200 access = yes }
		relation = { tag = SYR value = 200 access = yes }
		relation = { tag = LEB value = 200 access = yes }
	}

	SpyInfo = { country = "FRA" NumberOfSpies = 5 }
	SpyInfo = { country = "ARG" NumberOfSpies = 1 }
	SpyInfo = { country = "AUS" NumberOfSpies = 2 }
	SpyInfo = { country = "BEL" NumberOfSpies = 4 }
	SpyInfo = { country = "BRA" NumberOfSpies = 2 }
	SpyInfo = { country = "BUL" NumberOfSpies = 1 }
	SpyInfo = { country = "CAN" NumberOfSpies = 2 }
	SpyInfo = { country = "CGX" NumberOfSpies = 3 }
	SpyInfo = { country = "CHC" NumberOfSpies = 1 }
	SpyInfo = { country = "CHI" NumberOfSpies = 4 }
	SpyInfo = { country = "CHI" NumberOfSpies = 1 }
	SpyInfo = { country = "COL" NumberOfSpies = 1 }
	SpyInfo = { country = "CSX" NumberOfSpies = 1 }
	SpyInfo = { country = "CUB" NumberOfSpies = 1 }
	SpyInfo = { country = "CXB" NumberOfSpies = 1 }
	SpyInfo = { country = "CYN" NumberOfSpies = 2 }
	SpyInfo = { country = "CZE" NumberOfSpies = 6 }
	SpyInfo = { country = "DOM" NumberOfSpies = 1 }
	SpyInfo = { country = "ECU" NumberOfSpies = 1 }
	SpyInfo = { country = "EGY" NumberOfSpies = 2 }
	SpyInfo = { country = "ENG" NumberOfSpies = 4 }
	SpyInfo = { country = "ETH" NumberOfSpies = 1 }
	SpyInfo = { country = "FIN" NumberOfSpies = 1 }
	SpyInfo = { country = "GER" NumberOfSpies = 4 }
	SpyInfo = { country = "GRE" NumberOfSpies = 1 }
	SpyInfo = { country = "HAI" NumberOfSpies = 2 }
	SpyInfo = { country = "HOL" NumberOfSpies = 3 }
	SpyInfo = { country = "HUN" NumberOfSpies = 1 }
	SpyInfo = { country = "IND" NumberOfSpies = 1 }
	SpyInfo = { country = "IRQ" NumberOfSpies = 1 }
	SpyInfo = { country = "ITA" NumberOfSpies = 4 }
	SpyInfo = { country = "JAP" NumberOfSpies = 1 }
	SpyInfo = { country = "LIB" NumberOfSpies = 1 }
	SpyInfo = { country = "LUX" NumberOfSpies = 3 }
	SpyInfo = { country = "MAN" NumberOfSpies = 1 }
	SpyInfo = { country = "MEX" NumberOfSpies = 2 }
	SpyInfo = { country = "MLY" NumberOfSpies = 2 }
	SpyInfo = { country = "NOR" NumberOfSpies = 1 }
	SpyInfo = { country = "NZL" NumberOfSpies = 1 }
	SpyInfo = { country = "PAN" NumberOfSpies = 2 }
	SpyInfo = { country = "PER" NumberOfSpies = 1 }
	SpyInfo = { country = "POL" NumberOfSpies = 2 }
	SpyInfo = { country = "POR" NumberOfSpies = 3 }
	SpyInfo = { country = "ROM" NumberOfSpies = 3 }
	SpyInfo = { country = "SAF" NumberOfSpies = 1 }
	SpyInfo = { country = "SIA" NumberOfSpies = 2 }
	SpyInfo = { country = "SOV" NumberOfSpies = 2 }
	SpyInfo = { country = "SPR" NumberOfSpies = 6 }
	SpyInfo = { country = "SCH" NumberOfSpies = 4 }
	SpyInfo = { country = "TUR" NumberOfSpies = 2 }
	SpyInfo = { country = "U02" NumberOfSpies = 1 }
	SpyInfo = { country = "USA" NumberOfSpies = 2 }
	SpyInfo = { country = "VEN" NumberOfSpies = 1 }
	SpyInfo = { country = "YUG" NumberOfSpies = 1 }

	SpyInfo = { country = "SPA" NumberOfSpies = 3 }

  # Togoland
  # Metropolitan France
  nationalprovinces      = { 
# Metropolitan France
529 527 366 365 367 364 363 362 358 328 327 326 325 324 359 361 319 360 322 323 59  60  61  62  63  318 317 316 73  72 64  53  44  43  18  54  42  55  41  56  57  58  32  33  34  35  36  37  38  39  40  320 321 528  

#CARIBBEAN
#Fr.Guyana
875 
#Guadeloupe
898 
#Martinique
899 

#NORTH AFRICA
#Morocco
#956 969 968 959 958 960 966 
#Algeria
943 942 945 944 946 947 949 948 951 950 952 953 
#Algeria interior
#1013 1014 970 
#Tunisia
#935 934 936 938 937 939 940 941 

#EQUATORIAL AFRICA
#1075 1076 1092 1093 

#INDIAN OCEAN AREA
#Madagascar
#1134 1137 
#Reunion
1135 

#ASIA
#Indochine	
#1338 1339 1340 1337 1335 1336 1334 1333 1332 1341 1329 1328 1306 1326 

#PACIFIC
#Vanuatu
#1690 1689 1688 
#New Caledonia
1692 1691 1687
#Tahiti
1751 
} 
 
  ownedprovinces         = { 529  527  366  365  367  364  363  362  358  328  327  326  325  324  359  361  319  360  322  323  59   60   61   62  
                             63   318  317  316  73   72   64   53   44   43   18   54   42   55   41   56   57   58   32   33   34   35   36   37  
                             38   39   40   320  321  528  875  898  899  956  969  968  959  958  960  966  1014 970  1013 943  942  945  944  946 
                             947  949  948  951  950  952  953  935  934  936  938  937  939  940  941  1037 973 
                             974  975  1083 1084 998  976  977  978  981  984  987  989  990  985  980  986  979  994  996  997  1005 1006 991  995 
                             993  1088 1082 1081 1080 1079 1086 1070 1078 1077 1087 1089 1092 1093 1075 1076 1134 1137 1135
                             1692 1691 1687 1690 1689 1688 1751 1003 1004
                           }
  # Togoland
  # Metropolitan France
  controlledprovinces    = { 529  527  366  365  367  364  363  362  358  328  327  326  325  324  359  361  319  360  322  323  59   60   61   62  
                             63   318  317  316  73   72   64   53   44   43   18   54   42   55   41   56   57   58   32   33   34   35   36   37  
                             38   39   40   320  321  528  875  898  899  956  969  968  959  958  960  966  1014 970  1013 943  942  945  944  946 
                             947  949  948  951  950  952  953  935  934  936  938  937  939  940  941  1037 973 
                             974  975  1083 1084 998  976  977  978  981  984  987  989  990  985  980  986  979  994  996  997  1005 1006 991  995 
                             993  1088 1082 1081 1080 1079 1086 1070 1078 1077 1087 1089 1092 1093 1075 1076 1134 1137 1135
                             1692 1691 1687 1690 1689 1688 1751 1003 1004
                           }
  # FRA 1936 techs
  # ######################
  techapps               = { 4010  4020  4120  4130    2150 2010  2020  2030  2290  2300  2310  2040  2450  2460  2510  1010  1020  1190  1200  1110 
                             2400  1310  5010  5020  5080  5090  5190  5200  5310  5320  5470  5480  9010  9020  9030  9040  6010  6030 
                             6120  8010  8020  8030  8040  8050  8070  8100  3010  3020  3030  3070  3080  3090  3100  3130  3140  3150  3190  3200 
                             3210  3220  3230  3250  3260  3270  3280  3290  3320  3330  3400  3410  3420  14000 8120
			3470
                           }
  blueprints             = { 1070 }
  policy =
  { date              = { year = 0 month = january day = 0 }
    democratic        = 10
    political_left    = 6
    free_market       = 8
    freedom           = 10
    professional_army = 3
    defense_lobby     = 7
    interventionism   = 5
  }
  headofstate            = { type = 9 id = 2001 }
  headofgovernment       = { type = 9 id = 2002 }
  foreignminister        = { type = 9 id = 2003 }
  armamentminister       = { type = 9 id = 2004 }
  ministerofsecurity     = { type = 9 id = 2005 }
  ministerofintelligence = { type = 9 id = 2006 }
  chiefofstaff           = { type = 9 id = 2007 }
  chiefofarmy            = { type = 9 id = 2008 }
  chiefofnavy            = { type = 9 id = 2009 }
  chiefofair             = { type = 9 id = 2010 }

  nationalidentity = "policy_identity_conciliatory" 
	socialpolicy = "policy_social_liberal"
	nationalculture = "policy_culture_civic"

  # #################
  # ###FRENCH OOB####
  # #################
  landunit =
  { id       = { type = 13500 id = 1 }
    name     = "7e Armée"
    location = 55
    division =
    { id    = { type = 13500 id = 2 }
      name  = "4e Division d'Infanterie"
      type  = infantry
      extra = artillery
    }
    division =
    { id   = { type = 13500 id = 3 }
      name = "60e Division d'Infanterie"
      type = infantry
    }
    division =
    { id    = { type = 13500 id = 4 }
      name  = "41e Division Cuirassée de Réserve"
      type  = light_armor
      model = 1
    }
    division =
    { id       = { type = 13500 id = 5 }
      name     = "25e Div. d'Infanterie Motorisée"
      strength = 70
      type     = infantry
      model    = 1
      extra    = armored_car
    }
  }
  landunit =
  { id       = { type = 13500 id = 6 }
    name     = "1ère Armée"
    location = 63
    division =
    { id    = { type = 13500 id = 7 }
      name  = "1ère Div. Légère Motorisée"
      type  = infantry
      model = 1
      extra = armored_car
    }
    division =
    { id    = { type = 13500 id = 8 }
      name  = "1ère Division d'Infanterie"
      type  = infantry
      extra = anti_tank
    }
    division =
    { id    = { type = 13500 id = 9 }
      name  = "2e Division Cuirassée de Réserve"
      type  = light_armor
      model = 1
    }
    division =
    { id    = { type = 13500 id = 10 }
      name  = "12e Div. d'Infanterie Motorisée"
      type  = infantry
      model = 1
      extra = armored_car
    }
    division =
    { id    = { type = 13500 id = 11 }
      name  = "2e Div. d'Infanterie Nord-Africaine"
      type  = infantry
      extra = anti_tank
    }
  }
  landunit =
  { id       = { type = 13500 id = 12 }
    name     = "Armée des Alpes"
    location = 527
    division =
    { id   = { type = 13500 id = 13 }
      name = "65e Div. d'Infanterie de Montagne"
      type = bergsjaeger
    }
    division =
    { id   = { type = 13500 id = 14 }
      name = "64e Div. d'Infanterie de Montagne"
      type = bergsjaeger
    }
  }
  landunit =
  { id       = { type = 13500 id = 15 }
    name     = "XIX Région Militaire"
    location = 949
    division =
    { id   = { type = 13500 id = 16 }
      name = "85e Div. d'Infanterie d'Afrique"
      type = infantry
    }
    division =
    { id       = { type = 13500 id = 17 }
      name     = "182e Div. d'Infanterie d'Afrique"
      strength = 60
      type     = infantry
    }
  }
  landunit =
  { id       = { type = 13500 id = 18 }
    name     = "Troupes du Maroc"
    location = 959
    division =
    { id       = { type = 13500 id = 19 }
      name     = "3e Division Marocaine"
      strength = 60
      type     = infantry
      extra    = anti_tank
    }
  }
  landunit =
  { id       = { type = 13500 id = 20 }
    name     = "9e Armée"
    location = 64
    division =
    { id   = { type = 13500 id = 21 }
      name = "4e Division d'Infanterie"
      type = infantry
    }
    division =
    { id    = { type = 13500 id = 22 }
      name  = "1ère Div. Légère de Cavalerie"
      type  = cavalry
      model = 1
    }
    division =
    { id       = { type = 13500 id = 23 }
      name     = "1ère Div. d'Infanterie Motorisée"
      strength = 70
      type     = infantry
      model    = 1
      extra    = armored_car
    }
    division =
    { id    = { type = 13500 id = 24 }
      name  = "18e Division d'Infanterie"
      type  = infantry
      extra = anti_air
    }
  }
  landunit =
  { id       = { type = 13500 id = 25 }
    name     = "2e Armée"
    location = 72
    division =
    { id   = { type = 13500 id = 26 }
      name = "2e Div. Légère de Cavalerie"
      type = cavalry
    }
    division =
    { id    = { type = 13500 id = 27 }
      name  = "71e Division d'Infanterie"
      type  = infantry
      extra = anti_tank
    }
    division =
    { id       = { type = 13500 id = 28 }
      name     = "41e Division d'Infanterie"
      strength = 70
      type     = infantry
    }
    division =
    { id   = { type = 13500 id = 29 }
      name = "1ère Div. d'Infanterie Coloniale"
      type = infantry
    }
  }
  landunit =
  { id       = { type = 13500 id = 30 }
    name     = "Armée de Tunisie"
    location = 939
    division =
    { id       = { type = 14000 id = 31 }
      name     = "QG Armée d'Afrique"
      type     = hq
      model    = 0
      strength = 100
    }
    division =
    { id       = { type = 13500 id = 32 }
      name     = "83e Div. d'Infanterie d'Afrique"
      strength = 100
      type     = infantry
      extra    = anti_tank
    }
    division =
    { id   = { type = 13500 id = 33 }
      name = "81e Div. d'Infanterie d'Afrique"
      type = infantry
    }
    division =
    { id       = { type = 13500 id = 34 }
      name     = "6e Division Légère de Cavalerie"
      strength = 65
      type     = cavalry
    }
  }
  landunit =
  { id       = { type = 13500 id = 35 }
    name     = "3e Armée"
    location = 53
    division =
    { id       = { type = 13500 id = 36 }
      name     = "3e Div. Légère de Cavalerie"
      strength = 75
      type     = cavalry
    }
    division =
    { id   = { type = 13500 id = 37 }
      name = "6e Division d'Infanterie"
      type = infantry
    }
    division =
    { id   = { type = 13500 id = 38 }
      name = "8e Division d'Infanterie"
      type = infantry
    }
    division =
    { id    = { type = 13500 id = 39 }
      name  = "3e Div. d'Infanterie Nord-Africaine"
      type  = infantry
      extra = anti_tank
    }
    division =
    { id   = { type = 13500 id = 40 }
      name = "26e Division d'Infanterie"
      type = infantry
    }
    division =
    { id   = { type = 13500 id = 41 }
      name = "42e Division d'Infanterie"
      type = infantry
    }
    division =
    { id    = { type = 13500 id = 42 }
      name  = "20e Division d'Infanterie"
      type  = infantry
      extra = artillery
    }
  }
  landunit =
  { id       = { type = 13500 id = 43 }
    name     = "Troupes d'Indochine"
    location = 1337
    division =
    { id       = { type = 13500 id = 44 }
      name     = "Division du Tonkin"
      strength = 65
      type     = infantry
    }
    division =
    { id       = { type = 13500 id = 45 }
      name     = "Division de Cochinchine-Cambodge"
      strength = 60
      type     = infantry
      extra    = engineer
    }
  }
  landunit =
  { id       = { type = 13500 id = 46 }
    name     = "Corps Expéditionnaire"
    location = 1037
    division =
    { id       = { type = 13500 id = 47 }
      name     = "1ère Légère d`Infanterie"
      strength = 100
      type     = infantry
      model    = 1
    }
    division =
    { id       = { type = 13500 id = 48 }
      name     = "1ère/2e de Chasseurs Montagne"
      strength = 100
      type     = bergsjaeger
    }
  }
  landunit =
  { id       = { type = 13500 id = 49 }
    name     = "4e Armée"
    location = 316
    division =
    { id       = { type = 13500 id = 50 }
      name     = "11e Division d'Infanterie"
      strength = 70
      type     = infantry
    }
    division =
    { id   = { type = 13500 id = 51 }
      name = "45e Division d'Infanterie"
      type = infantry
    }
    division =
    { id    = { type = 13500 id = 52 }
      name  = "52e Div. d'Infanterie d'Afrique"
      type  = infantry
      extra = artillery
    }
  }
  landunit =
  { id       = { type = 13500 id = 53 }
    name     = "5e Armée"
    location = 366
    division =
    { id       = { type = 13500 id = 54 }
      name     = "24e Division d'Infanterie"
      strength = 70
      type     = infantry
    }
    division =
    { id   = { type = 13500 id = 55 }
      name = "31e Div. d'Infanterie de Montagne"
      type = bergsjaeger
    }
    division =
    { id    = { type = 13500 id = 56 }
      name  = "70e Division d'Infanterie"
      type  = infantry
      extra = anti_tank
    }
    division =
    { id    = { type = 13500 id = 57 }
      name  = "30e Division d'Infanterie"
      type  = infantry
      extra = anti_tank
    }
  }
  landunit =
  { id       = { type = 13500 id = 58 }
    name     = "8e Armée"
    location = 73
    division =
    { id       = { type = 13500 id = 60 }
      name     = "QG Ligne Maginot"
      type     = hq
      model    = 0
      strength = 100
    }
    division =
    { id       = { type = 13500 id = 61 }
      name     = "13e Division d'Infanterie"
      strength = 70
      type     = infantry
      extra    = anti_tank
    }
    division =
    { id       = { type = 13500 id = 62 }
      name     = "19e Division d'Infanterie"
      strength = 70
      type     = infantry
    }
    division =
    { id   = { type = 13500 id = 59 }
      name = "54e Division d'Infanterie"
      type = infantry
    }
  }
  # ######################################
  # ####### France Navy OOB ##############
  # ######################################
  navalunit =
  { id       = { type = 13500 id = 63 }
    name     = "1ère Flotte de la France"
    location = 32
    base     = 32
    division =
    { id            = { type = 13500 id = 64 }
      name          = "Béarn"
      type          = carrier
      model         = 1
      extra         = cag
      brigade_model = 1
    }
    division =
    { id    = { type = 13500 id = 65 }
      name  = "Algérie"
      type  = heavy_cruiser
      model = 2
      extra1 = naval_anti_air_l
      extra2 = naval_fire_controll_l
      extra3 = naval_spotter_l
      brigade_model1 = 1
      brigade_model2 = 1
      brigade_model3 = 1
    }
    division =
    { id    = { type = 13500 id = 66 }
      name  = "Primauguet"
      type  = light_cruiser
      model = 1
      extra1 = naval_anti_air_s
      extra2 = naval_spotter_s
      brigade_model1 = 0
      brigade_model2 = 1
    }
    division =
    { id    = { type = 13500 id = 67 }
      name  = "Duguay-Trouin"
      type  = light_cruiser
      model = 1
      extra1 = naval_anti_air_s
      extra2 = naval_spotter_s
      brigade_model1 = 0
      brigade_model2 = 1
    }
    division =
    { id    = { type = 13500 id = 68 }
      name  = "Lamotte-Picquet"
      type  = light_cruiser
      model = 1
      extra1 = naval_anti_air_s
      extra2 = naval_spotter_s
      brigade_model1 = 0
      brigade_model2 = 1
    }
    division =
    { id    = { type = 13500 id = 69 }
      name  = "La Galissonnière"
      type  = light_cruiser
      model = 3
      extra1 = naval_anti_air_s
      extra2 = naval_spotter_s
      brigade_model1 = 1
      brigade_model2 = 1
    }
    division =
    { id    = { type = 13500 id = 70 }
      name  = "1ère Flotille de Contre-torpilleurs"
      type  = destroyer
      model = 1
      extra1 = naval_fire_controll_s
      brigade_model1 = 1
    }
    division =
    { id    = { type = 13500 id = 71 }
      name  = "2e Flotille de Contre-torpilleurs"
      type  = destroyer
      model = 0
      extra1 = naval_fire_controll_s
      brigade_model1 = 0
    }
    division =
    { id    = { type = 13500 id = 72 }
      name  = "3e Flotille de Contre-torpilleurs"
      type  = destroyer
      model = 0
      extra1 = naval_fire_controll_s
      brigade_model1 = 0
    }
  }
  navalunit =
  { id       = { type = 13500 id = 73 }
    name     = "2e Flotte de la France"
    location = 364
    base     = 364
    division =
    { id    = { type = 13500 id = 74 }
      name  = "Courbet"
      type  = battleship
      model = 0
      extra1 = naval_sa_l
      extra2 = naval_fire_controll_l
      extra3 = none
      extra4 = none
      extra5 = none
      brigade_model1 = 0
      brigade_model2 = 0
      brigade_model3 = 0
      brigade_model4 = 0
      brigade_model5 = 0
    }
    division =
    { id    = { type = 13500 id = 75 }
      name  = "Paris"
      type  = battleship
      model = 0
      extra1 = naval_sa_l
      extra2 = naval_fire_controll_l
      extra3 = none
      extra4 = none
      extra5 = none
      brigade_model1 = 0
      brigade_model2 = 0
      brigade_model3 = 0
      brigade_model4 = 0
      brigade_model5 = 0
    }
    division =
    { id    = { type = 13500 id = 76 }
      name  = "Suffren"
      type  = heavy_cruiser
      model = 1
      extra1 = naval_anti_air_l
      extra2 = naval_fire_controll_l
      extra3 = naval_spotter_l
      brigade_model1 = 1
      brigade_model2 = 1
      brigade_model3 = 1
    }
    division =
    { id    = { type = 13500 id = 77 }
      name  = "Duquesne"
      type  = heavy_cruiser
      model = 1
      extra1 = naval_anti_air_l
      extra2 = naval_fire_controll_l
      extra3 = naval_spotter_l
      brigade_model1 = 0
      brigade_model2 = 0
      brigade_model3 = 0
    }
    division =
    { id    = { type = 13500 id = 78 }
      name  = "Pluton"
      type  = light_cruiser
      model = 0
      extra1 = naval_anti_air_s
      extra2 = naval_fire_controll_s
      brigade_model1 = 0
      brigade_model2 = 1
    }
    division =
    { id    = { type = 13500 id = 79 }
      name  = "Jeanne d'Arc"
      type  = light_cruiser
      model = 1
      extra1 = naval_anti_air_s
      extra2 = naval_spotter_s
      brigade_model1 = 1
      brigade_model2 = 1
    }
    division =
    { id    = { type = 13500 id = 80 }
      name  = "4e Flotille de Contre-torpilleurs"
      type  = destroyer
      model = 1
      extra1 = naval_fire_controll_s
      brigade_model1 = 0
    }
    division =
    { id    = { type = 13500 id = 81 }
      name  = "5e Flotille de Contre-torpilleurs"
      type  = destroyer
      model = 1
      extra1 = naval_fire_controll_s
      brigade_model1 = 0
    }
    division =
    { id    = { type = 13500 id = 82 }
      name  = "6e Flotille de Contre-torpilleurs"
      type  = destroyer
      model = 0
      extra1 = naval_fire_controll_s
      brigade_model1 = 0
    }
  }
  navalunit =
  { id       = { type = 13500 id = 83 }
    name     = "3e Flotte de la France"
    location = 939
    base     = 939
    division =
    { id    = { type = 13500 id = 84 }
      name  = "Ocean"
      type  = battleship
      model = 0
      extra1 = naval_sa_l
      extra2 = naval_fire_controll_l
      extra3 = none
      extra4 = none
      extra5 = none
      brigade_model1 = 0
      brigade_model2 = 0
      brigade_model3 = 0
      brigade_model4 = 0
      brigade_model5 = 0
    }         # Renamed from Jean Bart 1936
    division =
    { id    = { type = 13500 id = 85 }
      name  = "Bretagne"
      type  = battleship
      model = 1
      extra1 = naval_sa_l
      extra2 = naval_fire_controll_l
      extra3 = naval_anti_air_l
      extra4 = none
      extra5 = none
      brigade_model1 = 1
      brigade_model2 = 1
      brigade_model3 = 1
      brigade_model4 = 0
      brigade_model5 = 0
    }
    division =
    { id    = { type = 13500 id = 200 }
      name  = "Commandant-Teste"
      type  = escort_carrier
      model = 0
      extra1 = b_u1
      brigade_model1 = 0
    }
    division =
    { id    = { type = 13500 id = 86 }
      name  = "Foch"
      type  = heavy_cruiser
      model = 1
      extra1 = naval_anti_air_l
      extra2 = naval_fire_controll_l
      extra3 = naval_spotter_l
      brigade_model1 = 1
      brigade_model2 = 1
      brigade_model3 = 1
    }
    division =
    { id    = { type = 13500 id = 87 }
      name  = "Tourville"
      type  = heavy_cruiser
      model = 1
      extra1 = naval_anti_air_l
      extra2 = naval_fire_controll_l
      extra3 = naval_spotter_l
      brigade_model1 = 0
      brigade_model2 = 0
      brigade_model3 = 0
    }
    division =
    { id    = { type = 13500 id = 88 }
      name  = "7e Flotille de Contre-torpilleurs"
      type  = destroyer
      model = 2
      extra1 = naval_fire_controll_s
      brigade_model1 = 1
    }
    division =
    { id    = { type = 13500 id = 89 }
      name  = "8e Flotille de Contre-torpilleurs"
      type  = destroyer
      model = 2
      extra1 = naval_fire_controll_s
      brigade_model1 = 1
    }
    division =
    { id    = { type = 13500 id = 90 }
      name  = "9e Flotille de Contre-torpilleurs"
      type  = destroyer
      model = 2
      extra1 = naval_fire_controll_s
      brigade_model1 = 1
    }
    division =
    { id    = { type = 13500 id = 91 }
      name  = "10e Flotille de Contre-torpilleurs"
      type  = destroyer
      model = 2
      extra1 = naval_fire_controll_s
      brigade_model1 = 1
    }
  }
  navalunit =
  { id       = { type = 13500 id = 92 }
    name     = "4e Flotte de la France"
    location = 32
    base     = 32
    division =
    { id    = { type = 13500 id = 93 }
      name  = "Lorraine"
      type  = battleship
      model = 1
      extra1 = naval_sa_l
      extra2 = naval_fire_controll_l
      extra3 = naval_spotter_l
      extra4 = naval_anti_air_l
      extra5 = none
      brigade_model1 = 1
      brigade_model2 = 1
      brigade_model3 = 1
      brigade_model4 = 1
      brigade_model5 = 0
    }
    division =
    { id    = { type = 13500 id = 94 }
      name  = "Provence"
      type  = battleship
      model = 1
      extra1 = naval_sa_l
      extra2 = naval_fire_controll_l
      extra3 = naval_anti_air_l
      extra4 = none
      extra5 = none
      brigade_model1 = 1
      brigade_model2 = 1
      brigade_model3 = 1
      brigade_model4 = 0
      brigade_model5 = 0
    }
    division =
    { id    = { type = 13500 id = 95 }
      name  = "Colbert"
      type  = heavy_cruiser
      model = 1
      extra1 = naval_anti_air_l
      extra2 = naval_fire_controll_l
      extra3 = naval_spotter_l
      brigade_model1 = 1
      brigade_model2 = 1
      brigade_model3 = 1
    }
    division =
    { id    = { type = 13500 id = 96 }
      name  = "Dupleix"
      type  = heavy_cruiser
      model = 1
      extra1 = naval_anti_air_l
      extra2 = naval_fire_controll_l
      extra3 = naval_spotter_l
      brigade_model1 = 1
      brigade_model2 = 1
      brigade_model3 = 1
    }
    division =
    { id    = { type = 13500 id = 97 }
      name  = "Emile Bertin"
      type  = light_cruiser
      model = 2
      extra1 = naval_fire_controll_s
      extra2 = naval_spotter_s
      brigade_model1 = 1
      brigade_model2 = 1
    }
    division =
    { id    = { type = 13500 id = 98 }
      name  = "11e Flotille de Contre-torpilleurs"
      type  = destroyer
      model = 1
      extra1 = naval_fire_controll_s
      brigade_model1 = 1
    }
  }
  navalunit =
  { id       = { type = 13500 id = 99 }
    name     = "1ère Flotte de Sous-marins"
    location = 364
    base     = 364
    division = { 
    id = { type = 13500 id = 201 } 
    name = "Surcouf" 
    type = submarine
    model = 7
    extra1 = naval_spotter_s
    extra2 = naval_torpedoes_s
    brigade_model1 = 0
    brigade_model2 = 0
    } 
    division =
    { id    = { type = 13500 id = 100 }
      name  = "1ère Flotille de Sous-Marins"
      type  = submarine
      model = 1
    }
    division =
    { id    = { type = 13500 id = 101 }
      name  = "2e Flotille de Sous-Marins"
      type  = submarine
      model = 1
    }
    division =
    { id    = { type = 13500 id = 102 }
      name  = "3e Flotille de Sous-Marins"
      type  = submarine
      model = 1
    }
    division =
    { id    = { type = 13500 id = 103 }
      name  = "4e Flotille de Sous-Marins"
      type  = submarine
      model = 1
    }
    division =
    { id    = { type = 13500 id = 104 }
      name  = "5e Flotille de Sous-Marins"
      type  = submarine
      model = 0
    }
  }
  navalunit =
  { id       = { type = 13500 id = 105 }
    name     = "2e Flotte de Sous-marins"
    location = 364
    base     = 364
    division =
    { id    = { type = 13500 id = 106 }
      name  = "6e Flotille de Sous-Marins"
      type  = submarine
      model = 1
    }
    division =
    { id    = { type = 13500 id = 107 }
      name  = "7e Flotille de Sous-Marins"
      type  = submarine
      model = 1
    }
    division =
    { id    = { type = 13500 id = 108 }
      name  = "8e Flotille de Sous-Marins"
      type  = submarine
      model = 1
    }
    division =
    { id    = { type = 13500 id = 109 }
      name  = "9e Flotille de Sous-Marins"
      type  = submarine
      model = 1
    }
    division =
    { id    = { type = 13500 id = 110 }
      name  = "10e Flotille de Sous-Marins"
      type  = submarine
      model = 2
    }
  }
  navalunit =
  { id       = { type = 13500 id = 120 }
    name     = "3e Flotte de Sous-marins"
    location = 939
    base     = 939
    division =
    { id    = { type = 13500 id = 121 }
      name  = "11e Flotille de Sous-Marins"
      type  = submarine
      model = 2
    }
    division =
    { id    = { type = 13500 id = 122 }
      name  = "12e Flotille de Sous-Marins"
      type  = submarine
      model = 2
    }
    division =
    { id    = { type = 13500 id = 123 }
      name  = "13e Flotille de Sous-Marins"
      type  = submarine
      model = 2
    }
    division =
    { id    = { type = 13500 id = 124 }
      name  = "14e Flotille de Sous-Marins"
      type  = submarine
      model = 2
    }
    division =
    { id    = { type = 13500 id = 125 }
      name  = "15e Flotille de Sous-Marins"
      type  = submarine
      model = 2
    }
  }
  navalunit =
  { id       = { type = 13500 id = 126 }
    location = 1337
    base     = 1337
    name     = "Transport Expéditionnaire"
    division =
    { id   = { type = 13500 id = 127 }
      name = "1ère Flotille de Convois"
      type = transport
    }
    division =
    { id   = { type = 13500 id = 128 }
      name = "2e Flotille de Convois"
      type = transport
    }
    division =
    { id   = { type = 13500 id = 129 }
      name = "3e Flotille de Convois"
      type = transport
    }
  }
  navalunit =
  { id       = { type = 13500 id = 130 }
    location = 364
    base     = 364
    name     = "Transport Général"
    division =
    { id   = { type = 13500 id = 131 }
      name = "4e Flotille de Convois"
      type = transport
    }
    division =
    { id   = { type = 13500 id = 132 }
      name = "5e Flotille de Convois"
      type = transport
    }
    division =
    { id   = { type = 13500 id = 133 }
      name = "6e Flotille de Convois"
      type = transport
    }
    division =
    { id   = { type = 13500 id = 134 }
      name = "7e Flotille de Convois"
      type = transport
    }
  }

#AIR OOB

airunit = {
	id = { type = 13500 id = 2001 }
	name = "1re Division Aérienne"
	location = 56 # Paris
	base = 56

	division = {
		id = { type = 13500 id = 2002 }
		name = "Groupement de Bombardement 6"
		strength = 60
		type = tactical_bomber
		model = 0
		}
	}

airunit = {
	location = 318 # Dijon
	base = 318
	id = { type = 13500 id = 2003 }
	name = "3e Division Aérienne"

	division = { 
		id = { type = 13500 id = 2004 }
		name = "Groupement de Bombardement 10"
		strength = 60
		type = tactical_bomber
		model = 0
	}
}

airunit = {
	location = 56 # Paris
	base = 56
	id = { type = 13500 id = 2005 }
	name = "Groupement de Chasse 21"

	division = {
		id = { type = 13500 id = 2006 }
		name = "Groupement de Chasse 21"
		strength = 80
		type = interceptor
		model = 1
	}
}

airunit = {
	location = 44 # Lille
	base = 44
	id = { type = 13500 id = 2007 }
	name = "Groupement de Chasse 23"

	division = {
		id = { type = 13500 id = 2008 }
		name = "Groupement de Chasse 23"
		strength = 80
		type = interceptor
		model = 0
	}
}

airunit = {
	location = 72 # Metz
	base = 72 # Metz
	id = { type = 13500 id = 2009 }
	name = "Groupement de Chasse 22"

		division = {
		id = { type = 13500 id = 2010 }
		name = "Groupement de Chasse 22"
		strength = 80
		type = interceptor
		model = 1
		}
	}

airunit = {
	location = 318 # Dijon
	base = 318 # Dijon
	id = { type = 13500 id = 2011 }
	name = "Groupement de Chasse 24"

		division = {
		id = { type = 13500 id = 2012 }
		name = "Groupement de Chasse 24"
		strength = 80
		type = interceptor
		model = 0
		}
	}

airunit = {
	location = 949 # Algiers
	base = 949
	id = { type = 13500 id = 2013 }
	name = "Groupe Aérien Nord Africaine"

	division = {
		id = { type = 13500 id = 2014 }
		name = "Groupe Aérien Nord Africaine"
		strength = 60
		type = interceptor
		model = 0
		}
	}

airunit = {
	location = 1337 # Saigon
	base = 1337
	id = { type = 13500 id = 2015 }
	name = "Groupe Aérien Indochine"

	division = {
		id = { type = 13500 id = 2016 }
		name = "Groupe Aérien Indochine"
		strength = 40
		type = interceptor
		model = 0
	}
}

airunit = {
	location = 32 # Brest
	base = 32
	id = { type = 13500 id = 2017 }
	name = "Zone de l'Atlantique"

	division = {
		id = { type = 13500 id = 2018 }
		name = "Zone de l'Atlantique"
		type = naval_bomber
		model = 0
	}
}

airunit = {
	location = 939 # Tunis
	base = 939
	id = { type = 13500 id = 2019 }
	name = "Zone Méditerranéen"

	division = { 
		id = { type = 13500 id = 2020 }
		name = "Zone Méditerranéen"
		type = naval_bomber
		model = 0
	}
}

  # #################################
  # Naval units under construction
  # #################################

	province_development = { 
		id = { type = 13500 id = 158 } 
		name = "" 
		progress = 0.0000 
		location = 56 
		cost = 2.0000 
		date = { 
			year = 1939 
			month = january 
			day = 6 
			hour = 0 
			} 
		manpower = 0.1000 
		close_when_finished = yes 
		waitingforclosure = no 
		total_progress = 0.0000 
		size = 20 
		done = 0 
		days = 1536 
		days_for_first = 96 
		gearing_bonus = 0.0000 
		speed_step = 1 
		type = infrastructure 
		} 
	province_development = { 
		id = { type = 13500 id = 169 } 
		name = "" 
		progress = 0.0000 
		location = 72 
		cost = 2.0000 
		date = { 
			year = 1939 
			month = january 
			day = 6 
			hour = 0 
			} 
		manpower = 0.1000 
		close_when_finished = yes 
		waitingforclosure = no 
		total_progress = 0.0000 
		size = 20 
		done = 0 
		days = 1536 
		days_for_first = 96 
		gearing_bonus = 0.0000 
		speed_step = 1 
		type = infrastructure 
		} 
	province_development = { 
		id = { type = 13500 id = 170 } 
		name = "" 
		progress = 0.0000 
		location = 73 
		cost = 5.0000 
		date = { 
			year = 1938 
			month = may 
			day = 24 
			hour = 0 
			} 
		manpower = 1.0000 
		close_when_finished = yes 
		waitingforclosure = no 
		total_progress = 0.0000 
		size = 3 
		done = 0 
		days = 1152 
		days_for_first = 288 
		gearing_bonus = 0.0000 
		type = ic 
		} 
	province_development = { 
		id = { type = 13500 id = 171 } 
		name = "" 
		progress = 0.0000 
		location = 72 
		cost = 5.0000 
		date = { 
			year = 1938 
			month = may 
			day = 24 
			hour = 0 
			} 
		manpower = 1.0000 
		close_when_finished = yes 
		waitingforclosure = no 
		total_progress = 0.0000 
		size = 3 
		done = 0 
		days = 1152 
		days_for_first = 288 
		gearing_bonus = 0.0000 
		type = ic 
		} 
	province_development = { 
		id = { type = 13500 id = 155 } 
		name = "" 
		progress = 0.0000 
		location = 44 
		cost = 5.0000 
		date = { 
			year = 1938 
			month = may 
			day = 24 
			hour = 0 
			} 
		manpower = 1.0000 
		close_when_finished = yes 
		waitingforclosure = no 
		total_progress = 0.0000 
		size = 3 
		done = 0 
		days = 1152 
		days_for_first = 288 
		gearing_bonus = 0.0000 
		type = ic 
		} 
	province_development = { 
		id = { type = 13500 id = 183 } 
		name = "" 
		progress = 0.0000 
		location = 44 
		cost = 2.0000 
		date = { 
			year = 1939 
			month = january 
			day = 6 
			hour = 0 
			} 
		manpower = 0.1000 
		close_when_finished = yes 
		waitingforclosure = no 
		total_progress = 0.0000 
		size = 20 
		done = 0 
		days = 1536 
		days_for_first = 96 
		gearing_bonus = 0.0000 
		speed_step = 1 
		type = infrastructure 
		} 
	province_development = { 
		id = { type = 13500 id = 185 } 
		name = "" 
		progress = 0.0000 
		location = 73 
		cost = 2.0000 
		date = { 
			year = 1939 
			month = january 
			day = 6 
			hour = 0 
			} 
		manpower = 0.1000 
		close_when_finished = yes 
		waitingforclosure = no 
		total_progress = 0.0000 
		size = 20 
		done = 0 
		days = 1536 
		days_for_first = 96 
		gearing_bonus = 0.0000 
		speed_step = 1 
		type = infrastructure 
		} 
	province_development = { 
		id = { type = 13500 id = 161 } 
		name = "" 
		progress = 0.0000 
		location = 364 
		cost = 2.0000 
		date = { 
			year = 1940 
			month = april 
			day = 6 
			hour = 0 
			} 
		manpower = 0.1000 
		close_when_finished = yes 
		waitingforclosure = no 
		total_progress = 0.0000 
		size = 20 
		done = 0 
		days = 1536 
		days_for_first = 96 
		gearing_bonus = 0.0000 
		type = infrastructure 
		} 
	province_development = { 
		id = { type = 13500 id = 186 } 
		name = "" 
		progress = 0.0000 
		location = 316 
		cost = 2.0000 
		date = { 
			year = 1940 
			month = april 
			day = 6 
			hour = 0 
			} 
		manpower = 0.1000 
		close_when_finished = yes 
		waitingforclosure = no 
		total_progress = 0.0000 
		size = 20 
		done = 0 
		days = 1536 
		days_for_first = 96 
		gearing_bonus = 0.0000 
		type = infrastructure 
		} 
	province_development = { 
		id = { type = 13500 id = 172 } 
		name = "" 
		progress = 0.0000 
		location = 36 
		cost = 2.0000 
		date = { 
			year = 1940 
			month = april 
			day = 6 
			hour = 0 
			} 
		manpower = 0.1000 
		close_when_finished = yes 
		waitingforclosure = no 
		total_progress = 0.0000 
		size = 20 
		done = 0 
		days = 1536 
		days_for_first = 96 
		gearing_bonus = 0.0000 
		type = infrastructure 
		} 
	province_development = { 
		id = { type = 13500 id = 188 } 
		name = "" 
		progress = 0.0000 
		location = 365 
		cost = 2.0000 
		date = { 
			year = 1940 
			month = april 
			day = 6 
			hour = 0 
			} 
		manpower = 0.1000 
		close_when_finished = yes 
		waitingforclosure = no 
		total_progress = 0.0000 
		size = 20 
		done = 0 
		days = 1536 
		days_for_first = 96 
		gearing_bonus = 0.0000 
		type = infrastructure 
		} 
	province_development = { 
		id = { type = 13500 id = 174 } 
		name = "" 
		progress = 0.0000 
		location = 363 
		cost = 2.0000 
		date = { 
			year = 1940 
			month = april 
			day = 6 
			hour = 0 
			} 
		manpower = 0.1000 
		close_when_finished = yes 
		waitingforclosure = no 
		total_progress = 0.0000 
		size = 20 
		done = 0 
		days = 1536 
		days_for_first = 96 
		gearing_bonus = 0.0000 
		type = infrastructure 
		} 
	province_development = { 
		id = { type = 13500 id = 175 } 
		name = "" 
		progress = 0.0000 
		location = 40 
		cost = 2.0000 
		date = { 
			year = 1940 
			month = april 
			day = 6 
			hour = 0 
			} 
		manpower = 0.1000 
		close_when_finished = yes 
		waitingforclosure = no 
		total_progress = 0.0000 
		size = 20 
		done = 0 
		days = 1536 
		days_for_first = 96 
		gearing_bonus = 0.0000 
		type = infrastructure 
		} 
	province_development = { 
		id = { type = 13500 id = 151 } 
		name = "" 
		progress = 0.0000 
		location = 358 
		cost = 2.0000 
		date = { 
			year = 1940 
			month = april 
			day = 6 
			hour = 0 
			} 
		manpower = 0.1000 
		close_when_finished = yes 
		waitingforclosure = no 
		total_progress = 0.0000 
		size = 20 
		done = 0 
		days = 1536 
		days_for_first = 96 
		gearing_bonus = 0.0000 
		type = infrastructure 
		} 
	province_development = { 
		id = { type = 13500 id = 191 } 
		name = "" 
		progress = 0.0000 
		location = 319 
		cost = 2.0000 
		date = { 
			year = 1939 
			month = november 
			day = 8 
			hour = 0 
			} 
		manpower = 0.1000 
		close_when_finished = yes 
		waitingforclosure = no 
		total_progress = 0.0000 
		size = 18 
		done = 0 
		days = 1536 
		days_for_first = 96 
		gearing_bonus = 0.0000 
		type = infrastructure 
		} 
	province_development = { 
		id = { type = 13500 id = 153 } 
		name = "" 
		progress = 0.0000 
		location = 53 
		cost = 2.0000 
		date = { 
			year = 1940 
			month = april 
			day = 6 
			hour = 0 
			} 
		manpower = 0.1000 
		close_when_finished = yes 
		waitingforclosure = no 
		total_progress = 0.0000 
		size = 20 
		done = 0 
		days = 1536 
		days_for_first = 96 
		gearing_bonus = 0.0000 
		type = infrastructure 
		} 
	province_development = { 
		id = { type = 13500 id = 154 } 
		name = "" 
		progress = 0.0000 
		location = 360 
		cost = 2.0000 
		date = { 
			year = 1942 
			month = may 
			day = 24 
			hour = 0 
			} 
		manpower = 0.1000 
		close_when_finished = yes 
		waitingforclosure = no 
		total_progress = 0.0000 
		size = 20 
		done = 0 
		days = 1536 
		days_for_first = 144 
		gearing_bonus = 0.0000 
		type = infrastructure 
		} 
	province_development = { 
		id = { type = 13500 id = 173 } 
		name = "" 
		progress = 0.0000 
		location = 43 
		cost = 2.0000 
		date = { 
			year = 1940 
			month = april 
			day = 6 
			hour = 0 
			} 
		manpower = 0.1000 
		close_when_finished = yes 
		waitingforclosure = no 
		total_progress = 0.0000 
		size = 20 
		done = 0 
		days = 1536 
		days_for_first = 96 
		gearing_bonus = 0.0000 
		type = infrastructure 
		} 
	brigade_development = { 
		id = { type = 13500 id = 181 } 
		name = "36' Capital AA" 
		progress = 0.0000 
		location = 56 
		cost = 0.8000 
		date = { 
			year = 1936 
			month = november 
			day = 24 
			hour = 0 
			} 
		manpower = 0.1000 
		close_when_finished = yes 
		waitingforclosure = no 
		retooling_time = 36.0000 
		total_progress = 0.0000 
		size = 5 
		done = 0 
		days = 182 
		days_for_first = 64 
		gearing_bonus = 0.0000 
		type = naval_anti_air_l 
		model = 1 
		} 
	brigade_development = { 
		id = { type = 13500 id = 182 } 
		name = "24' Capital Spotter" 
		progress = 0.0000 
		location = 56 
		cost = 0.8000 
		date = { 
			year = 1936 
			month = october 
			day = 0 
			hour = 0 
			} 
		manpower = 0.1000 
		close_when_finished = yes 
		waitingforclosure = no 
		retooling_time = 36.0000 
		total_progress = 0.0000 
		size = 5 
		done = 0 
		days = 234 
		days_for_first = 52 
		gearing_bonus = 0.0000 
		type = naval_spotter_l 
		model = 1 
		} 
	division_development = { 
		id = { type = 13500 id = 140 } 
		name = "Jean-Bart" 
		progress = 0.0000 
		location = 56 
		cost = 6.6918 
		date = { 
			year = 1937 
			month = may 
			day = 0 
			hour = 0 
			} 
		manpower = 2.5000 
		close_when_finished = yes 
		waitingforclosure = no 
		total_progress = 0.0000 
		size = 1 
		done = 0 
		days = 408 
		days_for_first = 408 
		gearing_bonus = 0.0000 
		type = battleship 
		extra = naval_improved_hull_l 
		extra1 = naval_sa_l 
		extra2 = naval_fire_controll_l 
		extra3 = naval_spotter_l 
		extra4 = naval_anti_air_l 
		model = 3 
		brigade_model = 0 
		brigade_model1 = 1 
		brigade_model2 = 1 
		brigade_model3 = 1 
		brigade_model4 = 1 
		} 
	division_development = { 
		id = { type = 13500 id = 141 } 
		name = "Strasbourg" 
		progress = 0.0000 
		location = 56 
		cost = 5.1382 
		date = { 
			year = 1937 
			month = march 
			day = 4 
			hour = 0 
			} 
		manpower = 1.5000 
		close_when_finished = yes 
		waitingforclosure = no 
		total_progress = 0.0000 
		size = 1 
		done = 0 
		days = 352 
		days_for_first = 352 
		gearing_bonus = 0.0000 
		type = battlecruiser 
		extra = naval_anti_air_l 
		extra1 = naval_sa_l 
		extra2 = naval_fire_controll_l 
		extra3 = naval_improved_hull_l 
		extra4 = none 
		model = 4
		brigade_model = 1 
		brigade_model1 = 1 
		brigade_model2 = 1 
		brigade_model3 = 0 
		brigade_model4 = 0 
		} 
	division_development = { 
		id = { type = 13500 id = 152 } 
		name = "Richelieu" 
		progress = 0.0000 
		location = 0 
		cost = 6.6918 
		date = { 
			year = 1937 
			month = february 
			day = 1 
			hour = 0 
			} 
		manpower = 2.5000 
		close_when_finished = yes 
		waitingforclosure = no 
		total_progress = 0.0412 
		size = 1 
		done = 0 
		days = 1 
		days_for_first = 408 
		gearing_bonus = 0.0000 
		type = battleship 
		extra = naval_improved_hull_l 
		extra1 = naval_sa_l 
		extra2 = naval_fire_controll_l 
		extra3 = naval_spotter_l 
		extra4 = naval_anti_air_l 
		model = 4
		brigade_model = 0 
		brigade_model1 = 1 
		brigade_model2 = 1 
		brigade_model3 = 1 
		brigade_model4 = 1 
		} 
	division_development = { 
		id = { type = 13500 id = 150 } 
		name = "Dunkerque" 
		progress = 0.0000 
		location = 0 
		cost = 5.1382 
		date = { 
			year = 1936 
			month = january 
			day = 19 
			hour = 0 
			} 
		manpower = 1.5000 
		close_when_finished = yes 
		waitingforclosure = no 
		total_progress = 0.9458 
		size = 1 
		done = 0 
		days = 1 
		days_for_first = 352 
		gearing_bonus = 0.0000 
		type = battlecruiser 
		extra = naval_anti_air_l 
		extra1 = naval_sa_l 
		extra2 = naval_fire_controll_l 
		extra3 = naval_improved_hull_l 
		extra4 = none 
		model = 4
		brigade_model = 1 
		brigade_model1 = 1 
		brigade_model2 = 1 
		brigade_model3 = 0 
		brigade_model4 = 0 
		}
	division_development = { 
		id = { type = 13500 id = 300 } 
		name = "Jean de Vienne" 
		progress = 0.0000 
		location = 0 
		cost = 4.3459 
		date = { 
			year = 1936 
			month = june 
			day = 23 
			hour = 0 
			} 
		manpower = 1.4000 
		close_when_finished = yes 
		waitingforclosure = no 
		total_progress = 0.9162 # 0.7843
		size = 2 
		done = 0 
		days = 1 
		days_for_first = 168 
		gearing_bonus = 0.0000 
		type = light_cruiser 
		extra = naval_improved_hull_s
		extra1 = naval_fire_controll_s
		extra2 = none
		extra3 = none 
		extra4 = none 
		model = 3 
		brigade_model = 0 
		brigade_model1 = 1 
		brigade_model2 = 0
		brigade_model3 = 0 
		brigade_model4 = 0 
		} 
	division_development = { 
		id = { type = 13500 id = 301 } 
		name = "Gloire" 
		progress = 0.0000 
		location = 0 
		cost = 4.3459 
		date = { 
			year = 1936 
			month = march 
			day = 18 
			hour = 0 
			} 
		manpower = 1.4000 
		close_when_finished = yes 
		waitingforclosure = no 
		total_progress = 0.5326 
		size = 1 
		done = 0 
		days = 1 
		days_for_first = 168 
		gearing_bonus = 0.0000 
		type = light_cruiser 
		extra = naval_improved_hull_s
		extra1 = naval_fire_controll_s
		extra2 = none
		extra3 = none 
		extra4 = none 
		model = 3 
		brigade_model = 0 
		brigade_model1 = 1 
		brigade_model2 = 0
		brigade_model3 = 0 
		brigade_model4 = 0 
		} 
	division_development = { 
		id = { type = 13500 id = 302 } 
		name = "Georges Leygues" 
		progress = 0.0000 
		location = 0 
		cost = 4.3459 
		date = { 
			year = 1936 
			month = february 
			day = 12 
			hour = 0 
			} 
		manpower = 1.4000 
		close_when_finished = yes 
		waitingforclosure = no 
		total_progress = 0.7489 # 0.5489
		size = 1 
		done = 0 
		days = 1 
		days_for_first = 168 
		gearing_bonus = 0.0000 
		type = light_cruiser 
		extra = naval_improved_hull_s
		extra1 = naval_fire_controll_s
		extra2 = none
		extra3 = none 
		extra4 = none 
		model = 3 
		brigade_model = 0 
		brigade_model1 = 1 
		brigade_model2 = 0
		brigade_model3 = 0 
		brigade_model4 = 0 
		} 
	division_development = { 
		id = { type = 13500 id = 303 } 
		name = "Marseillaise" 
		progress = 0.0000 
		location = 0 
		cost = 4.3459 
		date = { 
			year = 1936 
			month = february 
			day = 11 
			hour = 0 
			} 
		manpower = 1.4000 
		close_when_finished = yes 
		waitingforclosure = no 
		total_progress = 0.7522 # 0.5522
		size = 1 
		done = 0 
		days = 1 
		days_for_first = 168 
		gearing_bonus = 0.0000 
		type = light_cruiser 
		extra = naval_improved_hull_s
		extra1 = naval_fire_controll_s
		extra2 = none
		extra3 = none 
		extra4 = none 
		model = 3 
		brigade_model = 0 
		brigade_model1 = 1 
		brigade_model2 = 0
		brigade_model3 = 0 
		brigade_model4 = 0 
		} 
	division_development = { 
		id = { type = 13500 id = 162 } 
		name = "27e Div. d'Infanterie de Montagne" 
		progress = 0.0000 
		location = 56 
		cost = 7.2613 
		date = { 
			year = 1936 
			month = november 
			day = 6 
			hour = 0 
			} 
		manpower = 14.5000 
		close_when_finished = yes 
		waitingforclosure = no 
		retooling_time = 72.0000 
		total_progress = 0.0000 
		size = 2 
		done = 0 
		days = 234 
		days_for_first = 120 
		gearing_bonus = 0.0000 
		type = bergsjaeger 
		extra = engineer 
		extra1 = none 
		extra2 = none 
		extra3 = none 
		extra4 = none 
		model = 0 
		brigade_model = 0 
		brigade_model1 = 0 
		brigade_model2 = 0 
		brigade_model3 = 0 
		brigade_model4 = 0 
		} 
}