
##############################
# Country definition for GER #
##############################

province = { id = 304 supplypool = 100 } # Elbing

#####################
# Country main data #
#####################

country =
{ tag                    = GER
  peacetime_ic_mod       = 0.90
  capital                = 300
  manpower               = 1789.9000 # 1800 - building queue
  transports             = 744 #X2.5
  escorts                = 22
  # Resource Reserves
  energy                 = 23112
  metal                  = 16536
  rare_materials         = 7413
  oil                    = 2944
  supplies               = 23050
  money                  = 200
  consumer = 0.1500 
  supply = 0.1130 
  production = 0.7370 
  reinforcement = 0.0000 
  upgrading = 0.0000
  expense_synthetic = 0.0000 
  expense_synthetic_rares = 0.0000 

	diplomacy = {
		relation = { tag = AFG value = 50 }
		relation = { tag = ALB value = -5 }
		relation = { tag = ARG value = 45 }
		relation = { tag = AST value = 15 }
		relation = { tag = AUS value = 65 }
		relation = { tag = BEL value = 30 }
		relation = { tag = BHU value = 1 }
		relation = { tag = BOL value = 15 }
		relation = { tag = BRA value = 35 }
		relation = { tag = BUL value = 45 guaranteed = { day = 30 month = december year = 1935 } }
		relation = { tag = CAN value = 30 }
		relation = { tag = CGX value = 25 }
		relation = { tag = CHC value = -25 }
		relation = { tag = CHI value = 50 }
		relation = { tag = CHL value = 40 }
		relation = { tag = COL value = 15 }
		relation = { tag = COS value = 1 }
		relation = { tag = CSX value = 40 }
		relation = { tag = CUB value = 25 }
		relation = { tag = CXB value = 40 }
		relation = { tag = CYN value = 20 }
		relation = { tag = CZE value = 30 }
		relation = { tag = DEN value = 45 guaranteed = { day = 30 month = december year = 1932 } }
		relation = { tag = DOM value = 15 }
		relation = { tag = ECU value = 35 }
		relation = { tag = EGY value = 50 }
		relation = { tag = ENG value = 35 }
		relation = { tag = EST value = 45 }
		relation = { tag = ETH value = 10 }
		relation = { tag = FIN value = 45 guaranteed = { day = 22 month = august year = 1934 }}
		relation = { tag = FRA value = 15 }
		relation = { tag = GRE value = 45 }
		relation = { tag = GUA value = 1 }
		relation = { tag = HAI value = 1 }
		relation = { tag = HOL value = 45 }
		relation = { tag = HON value = 10 }
		relation = { tag = HUN value = 50 }
		relation = { tag = IND value = 1 }
		relation = { tag = IRE value = 30 }
		relation = { tag = IRQ value = 50 }
		relation = { tag = ITA value = 45 guaranteed = { day = 30 month = december year = 1935 } }
		relation = { tag = JAP value = 45 }
		relation = { tag = LAT value = 50 }
		relation = { tag = LIB value = 1 }
		relation = { tag = LIT value = 30 }
		relation = { tag = LUX value = 35 }
		relation = { tag = MAN value = 30 }
		relation = { tag = MEX value = 30 }
		relation = { tag = MLY value = 1 }
		relation = { tag = MON value = -15 }
		relation = { tag = NEP value = 10 }
		relation = { tag = NIC value = 15 }
		relation = { tag = NOR value = 30 }
		relation = { tag = NZL value = 25 }
		relation = { tag = OMN value = 20 }
		relation = { tag = PAN value = 15 }
		relation = { tag = PAR value = 30 }
		relation = { tag = PER value = 45 }
		relation = { tag = PHI value = 10 }
		relation = { tag = POL value = 25 guaranteed = { day = 30 month = december year = 1932 } }
		relation = { tag = POR value = 40 }
		relation = { tag = PRU value = 35 }
		relation = { tag = ROM value = 35 guaranteed = { day = 30 month = december year = 1935 } }
		relation = { tag = SAF value = 45 }
		relation = { tag = SAL value = 15 }
		relation = { tag = SAU value = 20 }
		relation = { tag = SIA value = 10 }
		relation = { tag = SIK value = 5 }
		relation = { tag = SOV value = 35 }
		relation = { tag = SPA value = 30 }
		relation = { tag = SPR value = 10 }
		relation = { tag = SWE value = 45 guaranteed = { day = 30 month = december year = 1935 } }
		relation = { tag = SCH value = 50 }
		relation = { tag = TAN value = -15 }
		relation = { tag = TIB value = 10 }
		relation = { tag = TUR value = 40 guaranteed = { day = 30 month = december year = 1935 } }
		relation = { tag = U27 value = 1 }
		relation = { tag = URU value = 35 }
		relation = { tag = USA value = 25 }
		relation = { tag = VEN value = 25 }
		relation = { tag = YEM value = 15 }
		relation = { tag = YUG value = 40 guaranteed = { day = 30 month = december year = 1932 } }
	}

	SpyInfo = { country = "GER" NumberOfSpies = 8 }
	SpyInfo = { country = "AFG" NumberOfSpies = 1 }
	SpyInfo = { country = "ARG" NumberOfSpies = 3 }
	SpyInfo = { country = "AST" NumberOfSpies = 1 }
	SpyInfo = { country = "AUS" NumberOfSpies = 6 }
	SpyInfo = { country = "BEL" NumberOfSpies = 2 }
	SpyInfo = { country = "BOL" NumberOfSpies = 1 }
	SpyInfo = { country = "BRA" NumberOfSpies = 2 }
	SpyInfo = { country = "BUL" NumberOfSpies = 1 }
	SpyInfo = { country = "CAN" NumberOfSpies = 2 }
	SpyInfo = { country = "CGX" NumberOfSpies = 2 }
	SpyInfo = { country = "CHI" NumberOfSpies = 4 }
	SpyInfo = { country = "CHL" NumberOfSpies = 1 }
	SpyInfo = { country = "CSX" NumberOfSpies = 1 }
	SpyInfo = { country = "CYN" NumberOfSpies = 1 }
	SpyInfo = { country = "CZE" NumberOfSpies = 6 }
	SpyInfo = { country = "DEN" NumberOfSpies = 2 }
	SpyInfo = { country = "EGY" NumberOfSpies = 2 }
	SpyInfo = { country = "ENG" NumberOfSpies = 6 }
	SpyInfo = { country = "EST" NumberOfSpies = 1 }
	SpyInfo = { country = "FIN" NumberOfSpies = 2 }
	SpyInfo = { country = "FRA" NumberOfSpies = 6 }
	SpyInfo = { country = "GRE" NumberOfSpies = 2 }
	SpyInfo = { country = "HAI" NumberOfSpies = 1 }
	SpyInfo = { country = "HOL" NumberOfSpies = 5 }
	SpyInfo = { country = "HUN" NumberOfSpies = 4 }
	SpyInfo = { country = "IND" NumberOfSpies = 1 }
	SpyInfo = { country = "IRE" NumberOfSpies = 2 }
	SpyInfo = { country = "IRQ" NumberOfSpies = 2 }
	SpyInfo = { country = "ITA" NumberOfSpies = 4 }
	SpyInfo = { country = "JAP" NumberOfSpies = 1 }
	SpyInfo = { country = "LAT" NumberOfSpies = 1 }
	SpyInfo = { country = "LIT" NumberOfSpies = 1 }
	SpyInfo = { country = "LUX" NumberOfSpies = 1 }
	SpyInfo = { country = "MAN" NumberOfSpies = 1 }
	SpyInfo = { country = "MEX" NumberOfSpies = 1 }
	SpyInfo = { country = "NOR" NumberOfSpies = 2 }
	SpyInfo = { country = "PAN" NumberOfSpies = 1 }
	SpyInfo = { country = "PER" NumberOfSpies = 3 }
	SpyInfo = { country = "POL" NumberOfSpies = 4 }
	SpyInfo = { country = "POR" NumberOfSpies = 3 }
	SpyInfo = { country = "ROM" NumberOfSpies = 3 }
	SpyInfo = { country = "SAF" NumberOfSpies = 2 }
	SpyInfo = { country = "SAU" NumberOfSpies = 1 }
	SpyInfo = { country = "SOV" NumberOfSpies = 6 }
	SpyInfo = { country = "SPR" NumberOfSpies = 4 }
	SpyInfo = { country = "SWE" NumberOfSpies = 2 }
	SpyInfo = { country = "SCH" NumberOfSpies = 2 }
	SpyInfo = { country = "TIB" NumberOfSpies = 1 }
	SpyInfo = { country = "TUR" NumberOfSpies = 3 }
	SpyInfo = { country = "URU" NumberOfSpies = 1 }
	SpyInfo = { country = "USA" NumberOfSpies = 4 }
	SpyInfo = { country = "VEN" NumberOfSpies = 1 }
	SpyInfo = { country = "YUG" NumberOfSpies = 3 }

	SpyInfo = { country = "SPA" NumberOfSpies = 4 }
	SpyInfo = { country = "CRO" NumberOfSpies = 2 }
	SpyInfo = { country = "VIC" NumberOfSpies = 5 }
	SpyInfo = { country = "SLO" NumberOfSpies = 2 }

  nationalprovinces      = { 66  67  74  75  76  80  81  82  83  84  85  86  87  88  89  90  296 297 298 299 300 301 302 304 308 309 310 311 312 313
                             314 315 374 375 376 473 482 510 72  73  316 71 
                           }
  ownedprovinces         = { 66  67  74  75  76  80  81  82  83  84  85  86  87  88  89  90  296 297 298 299 300 301 302 304 308 309 310 311 312 313
                             314 315 374 375 376 473 482 510
                           }
  controlledprovinces    = { 66  67  74  75  76  80  81  82  83  84  85  86  87  88  89  90  296 297 298 299 300 301 302 304 308 309 310 311 312 313
                             314 315 374 375 376 473 482 510
                           }
  # Germany 1936 techs
  # ######################
  techapps               = { 1010 1020 1110 1190 1200 1210 1220 1310 1380
			2010 2020 2030   2150 2290 2300 2310 2320 2400 2450 2460 2510
                        3010 3020 3030 3070 3080 3090 3130 3140 3150 3160 3170 3190 3200 3210 3220 3230 3250 3260 3270 3280 3290 3320 3400 3410 3420 3430
                        4010 4020 4120 4130 4250
			5010 5020 5080 5090 5100 5190 5310 5470 5480 5490 5410 5290 5550
			6210 6220 6230 6240 6250 14000
			8010 8020 8030 8040 8050 8080 8150 8160 8170
			9010 9020 9030 9040 9050 9090
			5300 #Adv. Synth rares
			5200 5210 #Adv. Oil Ref
			1070 #Paratroopers
                           }
  blueprints             = { 4170 }
  policy =
  { date              = { year = 0 month = january day = 0 }
    democratic        = 1
    political_left    = 1
    free_market       = 5
    freedom           = 2
    professional_army = 7
    defense_lobby     = 7
    interventionism   = 5
  }
  headofstate            = { type = 9 id = 1 }
  headofgovernment       = { type = 9 id = 2 }
  foreignminister        = { type = 9 id = 3 }
  armamentminister       = { type = 9 id = 77 }
  ministerofsecurity     = { type = 9 id = 5 }
  ministerofintelligence = { type = 9 id = 6 }
  chiefofstaff           = { type = 9 id = 7 }
  chiefofarmy            = { type = 9 id = 8 }
  chiefofnavy            = { type = 9 id = 9 }
  chiefofair             = { type = 9 id = 374 }
  dormant_leaders        = {  293 579 } #544 545 546 547 548 549 550 551 552 553 554 555 556 557 558 559 560 561 562 563 564 565 566 567 568 569 570 571 572 573
                               #574 575 576 577 578 579
  nationalidentity = "policy_identity_frustrated" 
	socialpolicy = "policy_social_ethnic" 
	nationalculture = "policy_culture_ethnic" 
    
	### Germany Land OOB ###
  landunit =
  { location = 302
    name     = "II. Armeekorps"
    id       = { type = 14500 id = 37 }
    division =
    { id       = { type = 14500 id = 38 }
      name     = "2. Infanterie-Division"
      type     = infantry
      model    = 1
      strength = 100
    }
    division =
    { id       = { type = 14500 id = 39 }
      name     = "12. Infanterie-Division"
      type     = infantry
      model    = 1
      strength = 100
    }
    division =
    { id       = { type = 14500 id = 40 }
      name     = "32. Infanterie-Division"
      type     = infantry
      model    = 1
      strength = 100
      extra    = anti_tank
    }
  }
  landunit =
  { location = 300
    name     = "III. Armeekorps"
    id       = { type = 14500 id = 41 }
    division =
    { id       = { type = 14500 id = 42 }
      name     = "Heeresgruppe A"
      type     = hq
      model    = 0
      strength = 100
    }
    division =
    { id       = { type = 14500 id = 43 }
      name     = "3. Infanterie-Division"
      type     = infantry
      model    = 1
      strength = 100
    }
    division =
    { id       = { type = 14500 id = 44 }
      name     = "23. Infanterie-Division"
      type     = infantry
      model    = 1
      strength = 100
    }
  }
  landunit =
  { location = 300
    name     = "VIII. Armeekorps"
    id       = { type = 14500 id = 45 }
    division =
    { id       = { type = 14500 id = 46 }
      name     = "8. Infanterie-Division"
      type     = infantry
      model    = 1
      strength = 100
    }
    division =
    { id       = { type = 14500 id = 47 }
      name     = "18. Infanterie-Division"
      type     = infantry
      model    = 1
      strength = 100
    }
    division =
    { id       = { type = 14500 id = 48 }
      name     = "28. Infanterie-Division"
      type     = infantry
      model    = 1
      strength = 100
      extra    = engineer
    }
  }
  landunit =
  { location = 314
    name     = "V. Armeekorps"
    id       = { type = 14500 id = 49 }
    division =
    { id       = { type = 14500 id = 50 }
      name     = "5. Infanterie-Division"
      type     = infantry
      model    = 1
      strength = 100
    }
    division =
    { id            = { type = 14500 id = 51 }
      name          = "25. Infanterie-Division"
      type          = infantry
      model         = 1
      strength      = 100
      extra         = artillery
      brigade_model = 3
    }
    division =
    { id       = { type = 14500 id = 52 }
      name     = "35. Infanterie-Division"
      type     = infantry
      model    = 1
      strength = 100
    }
  }
  landunit =
  { location = 81
    name     = "VI. Armeekorps"
    id       = { type = 14500 id = 53 }
    division =
    { id       = { type = 14500 id = 54 }
      name     = "6. Infanterie-Division"
      type     = infantry
      model    = 1
      strength = 100
    }
    division =
    { id       = { type = 14500 id = 55 }
      name     = "16. Infanterie-Division"
      type     = infantry
      model    = 1
      strength = 100
      extra    = anti_tank
    }
    division =
    { id       = { type = 14500 id = 56 }
      name     = "26. Infanterie-Division"
      type     = infantry
      model    = 1
      strength = 100
    }
  }
  landunit =
  { location = 313
    name     = "IX. Armeekorps"
    id       = { type = 14500 id = 57 }
    division =
    { id       = { type = 14500 id = 58 }
      name     = "9. Infanterie-Division"
      type     = infantry
      model    = 1
      strength = 100
    }
    division =
    { id       = { type = 14500 id = 59 }
      name     = "15. Infanterie-Division"
      type     = infantry
      model    = 1
      strength = 100
      extra    = anti_air
    }
    division =
    { id       = { type = 14500 id = 60 }
      name     = "29. Infanterie-Division"
      type     = infantry
      model    = 1
      strength = 100
    }
  }
  landunit =
  { location = 76
    name     = "XII. Armeekorps"
    id       = { type = 14500 id = 61 }
    division =
    { id       = { type = 14500 id = 62 }
      name     = "33. Infanterie-Division"
      type     = infantry
      model    = 1
      strength = 100
    }
    division =
    { id       = { type = 14500 id = 63 }
      name     = "34. Infanterie-Division"
      type     = infantry
      model    = 1
      strength = 100
      extra    = engineer
    }
    division =
    { id       = { type = 14500 id = 64 }
      name     = "36. Infanterie-Division"
      type     = infantry
      model    = 1
      strength = 100
    }
  }
  landunit =
  { location = 311
    name     = "IV. Armeekorps"
    id       = { type = 14500 id = 65 }
    division =
    { id       = { type = 14500 id = 66 }
      name     = "4. Infanterie-Division"
      type     = infantry
      model    = 1
      strength = 100
    }
    division =
    { id            = { type = 14500 id = 67 }
      name          = "14. Infanterie-Division"
      type          = infantry
      model         = 1
      strength      = 100
      extra         = artillery
      brigade_model = 3
    }
    division =
    { id       = { type = 14500 id = 68 }
      name     = "24. Infanterie-Division"
      type     = infantry
      model    = 1
      strength = 100
    }
  }
  landunit =
  { location = 376
    name     = "VII. Armeekorps"
    id       = { type = 14500 id = 69 }
    division =
    { id       = { type = 14500 id = 70 }
      name     = "7. Infanterie-Division"
      type     = infantry
      model    = 1
      strength = 100
    }
    division =
    { id       = { type = 14500 id = 71 }
      name     = "10. Infanterie-Division"
      type     = infantry
      model    = 1
      strength = 100
      extra    = anti_tank
    }
    division =
    { id       = { type = 14500 id = 72 }
      name     = "17. Infanterie-Division"
      type     = infantry
      model    = 1
      strength = 100
    }
    division =
    { id       = { type = 14500 id = 73 }
      name     = "27. Infanterie-Division"
      type     = infantry
      model    = 1
      strength = 100
    }
  }
  landunit =
  { location = 88
    name     = "X. Armeekorps"
    id       = { type = 14500 id = 74 }
    division =
    { id       = { type = 14500 id = 75 }
      name     = "20. Infanterie-Division"
      type     = infantry
      model    = 1
      strength = 100
    }
    division =
    { id            = { type = 14500 id = 76 }
      name          = "22. Infanterie-Division"
      type          = infantry
      model         = 1
      strength      = 100
      extra         = artillery
      brigade_model = 3
    }
    division =
    { id       = { type = 14500 id = 77 }
      name     = "30. Infanterie-Division"
      type     = infantry
      model    = 1
      strength = 100
    }
  }
  landunit =
  { location = 86
    name     = "XI. Armeekorps"
    id       = { type = 14500 id = 78 }
    division =
    { id       = { type = 14500 id = 79 }
      name     = "13. Infanterie-Division"
      type     = infantry
      model    = 1
      strength = 100
    }
    division =
    { id       = { type = 14500 id = 80 }
      name     = "19. Infanterie-Division"
      type     = infantry
      model    = 1
      strength = 100
      extra    = anti_air
    }
    division =
    { id       = { type = 14500 id = 81 }
      name     = "31. Infanterie-Division"
      type     = infantry
      model    = 1
      strength = 100
    }
  }
  landunit =
  { location = 300
    name     = "I. Panzerarmee"
    id       = { type = 14500 id = 82 }
    division =
    { id       = { type = 14500 id = 83 }
      name     = "1. Panzer-Division"
      type     = light_armor
      model    = 0
      strength = 100
    }
    division =
    { id       = { type = 14500 id = 84 }
      name     = "2. Panzer-Division"
      type     = light_armor
      model    = 0
      strength = 100
    }
    division =
    { id           = { type = 14500 id = 85 }
      name         = "3. Panzer-Division"
      type         = light_armor
      model        = 0
      strength     = 100
      organisation = 30
    }
  }
  landunit =
  { location = 510
    name     = "I. Armeekorps"
    id       = { type = 14500 id = 86 }
    division =
    { id       = { type = 14500 id = 87 }
      name     = "1. Infanterie-Division"
      type     = infantry
      model    = 1
      strength = 100
    }
    division =
    { id            = { type = 14500 id = 88 }
      name          = "11. Infanterie-Division"
      type          = infantry
      model         = 1
      extra         = artillery
      brigade_model = 3
      strength      = 100
      organisation  = 30
    }
    division =
    { id       = { type = 14500 id = 89 }
      name     = "21. Infanterie-Division"
      type     = infantry
      model    = 1
      strength = 100
    }
  }
	### Germany Navy OOB ###
  navalunit =
  { name     = "Kriegsmarine"
    id       = { type = 14500 id = 1 }
    location = 80
    base     = 80
    division =
    { id    = { type = 14500 id = 2 }
      name  = "Deutschland"
      type  = heavy_cruiser
      model = 3
      extra1 = naval_sa_l
      extra2 = naval_fire_controll_l
      extra3 = naval_anti_air_l
      brigade_model1 = 1
      brigade_model2 = 0
      brigade_model3 = 0
    }
    division =
    { id    = { type = 14500 id = 3 }
      name  = "Admiral Scheer"
      type  = heavy_cruiser
      model = 3
      extra1 = naval_sa_l
      extra2 = naval_fire_controll_l
      extra3 = naval_anti_air_l
      brigade_model1 = 1
      brigade_model2 = 0
      brigade_model3 = 0
    }
    division =
    { id    = { type = 14500 id = 4 }
      name  = "Nürnberg"
      type  = light_cruiser
      model = 2
      extra1 = naval_fire_controll_s
      extra2 = naval_spotter_s
      brigade_model1 = 0
      brigade_model2 = 0
    }
    division =
    { id    = { type = 14500 id = 5 }
      name  = "Leipzig"
      type  = light_cruiser
      model = 2
      extra1 = naval_mines
      extra2 = naval_spotter_s
      brigade_model1 = 0
      brigade_model2 = 0
    }
    division =
    { id    = { type = 14500 id = 6 }
      name  = "Königsberg"
      type  = light_cruiser
      model = 1
      extra1 = naval_spotter_s
      extra2 = naval_anti_air_s
      brigade_model1 = 0
      brigade_model2 = 1
    }
    division =
    { id    = { type = 14500 id = 7 }
      name  = "Karlsruhe"
      type  = light_cruiser
      model = 1
      extra1 = naval_fire_controll_s
      extra2 = naval_spotter_s
      brigade_model1 = 0
      brigade_model2 = 0
    }
    division =
    { id    = { type = 14500 id = 8 }
      name  = "Köln"
      type  = light_cruiser
      model = 1
      extra1 = naval_fire_controll_s
      extra2 = naval_spotter_s
      brigade_model1 = 0
      brigade_model2 = 0
    }
    division =
    { id    = { type = 14500 id = 9 }
      name  = "Emden"
      type  = light_cruiser
      model = 0
      extra1 = naval_fire_controll_s
      brigade_model1 = 0
    }
    division = 
    { id = { type = 14500 id = 10 }
      name = "1. Torpedobootsflottille"
      type = destroyer
      model = 0
    }
  }
  navalunit =
  { name     = "II. Unterseebootsflotte"
    id       = { type = 14500 id = 11 }
    location = 80
    base     = 80
    division =
    { id    = { type = 14500 id = 12 }
      name  = "2. Unterseebootsflottille"
      type  = submarine
      model = 1
    }
    division =
    { id    = { type = 14500 id = 13 }
      name  = "3. Unterseebootsflottille"
      type  = submarine
      model = 1
    }
  }
  navalunit =
  { name     = "I. Unterseebootsflotte"
    id       = { type = 14500 id = 14 }
    location = 90
    base     = 90
    division =
    { id    = { type = 14500 id = 15 }
      name  = "1. Unterseebootsflottille"
      type  = submarine
      model = 0
    }
  }
  navalunit =
  { name     = "Baltische Flotte"
    id       = { type = 14500 id = 16 }
    location = 510
    base     = 510
    division =
    { id    = { type = 14500 id = 17 }
      name  = "Schleswig-Holstein"
      type  = battlecruiser
      model = 0
      extra1 = naval_sa_l
      extra2 = naval_fire_controll_l
      extra3 = naval_anti_air_l
      brigade_model1 = 0
      brigade_model2 = 0
      brigade_model3 = 1
    }
    division =
    { id    = { type = 14500 id = 18 }
      name  = "Schlesien"
      type  = battlecruiser
      model = 0
      extra1 = naval_sa_l
      extra2 = naval_fire_controll_l
      extra3 = naval_anti_air_l
      brigade_model1 = 0
      brigade_model2 = 0
      brigade_model3 = 1
    }
   division = 
    { id = { type = 14500 id = 19 }
      name = "2. Torpedobootsflottille"
      type = destroyer
      model = 0
    }
  }

####################################
# German 1936 Air OOB
# CORE2 Ver 0.60 (AoD)
# by dec152000
####################################

airunit = {
	location = 300 # Berlin
	id = { type = 14500 id = 2001 }
	name = "I. Fliegerkorps"
	base = 300

	division = {
		id = { type = 14500 id = 2002 }
		name = "KG 2"
		strength = 40
		experience = 18
		type = tactical_bomber
		model = 0
		extra = escort
		brigade_model = 0
		}
	division = {
		id = { type = 14500 id = 2003 }
		name = "KG 3"
		strength = 40
		experience = 18
		type = tactical_bomber
		model = 0
		extra = escort
		brigade_model = 0
		}
	division = {
		id = { type = 14500 id = 2004 }
		name = "StG 51"
		strength = 80
		experience = 12
		type = cas
		model = 0
		}
	division = {
		id = { type = 14500 id = 2005 }
		name = "JG 2"
		strength = 80
		experience = 12
		type = interceptor
		model = 1
		}
	}

airunit = {
	location = 473 # Breslau
	id = { type = 14500 id = 2006 }
	name = "II. Fliegerkorps"
	base = 473

	division = {
		id = { type = 14500 id = 2007 }
		name = "KG 53"
		strength = 40
		experience = 18
		type = tactical_bomber
		model = 0
		extra = escort
		brigade_model = 0
		}
	division = {
		id = { type = 14500 id = 2008 }
		name = "KG 25"
		strength = 40
		experience = 18
		type = tactical_bomber
		model = 0
		extra = escort
		brigade_model = 0
		}
	division = {
		id = { type = 14500 id = 2009 }
		name = "KG 30"
		strength = 40
		experience = 18
		type = tactical_bomber
		model = 0
		extra = escort
		brigade_model = 0
		}
	division = {
		id = { type = 14500 id = 2010 }
		name = "JG 26"
		strength = 80
		experience = 12
		type = interceptor
		model = 0
		}
	}

airunit = {
	location = 82 # Kassel
	id = { type = 14500 id = 2011 }
	name = "III. Fliegerkorps"
	base = 82

	division = {
		id = { type = 14500 id = 2012 }
		name = "KG 1"
		strength = 40
		experience = 18
		type = tactical_bomber
		model = 0
		extra = escort
		brigade_model = 0
		}
	division = {
		id = { type = 14500 id = 2013 }
		name = "JG 3"
		strength = 80
		experience = 12
		type = interceptor
		model = 0
		}
	}

airunit = {
	location = 376 # Munich
	id = { type = 14500 id = 2014 }
	name = "IV. Fliegerkorps"
	base = 376

	division = {
		id = { type = 14500 id = 2015 }
		name = "KG 4"
		strength = 40
		experience = 18
		type = tactical_bomber
		model = 0
		extra = escort
		brigade_model = 0
		}
	}

airunit = {
	location = 300 # Berlin
	id = { type = 14500 id = 2021 } # out of order d2 Dormant Units
	name = "KG zbV 1"
	base = 300

	division = {
		id = { type = 14500 id = 2022 }
		name = "KG zbV 1"
		strength = 40
		experience = 18
		type = transport_plane
		model = 0
		}
	}

  # ####under developement#####
	province_development = { 
		id = { type = 14500 id = 100 } 
		name = "" 
		progress = 0.0000 
		location = 300 
		cost = 2.0000 
		date = { 
			year = 1945 
			month = august 
			day = 10 
			hour = 0 
			} 
		manpower = 1.0000 
		close_when_finished = yes 
		waitingforclosure = no 
		total_progress = 0.0000 
		size = 10 
		done = 0 
		days = 346 
		days_for_first = 346 
		gearing_bonus = 0.0000 
		type = synthetic_oil 
		} 
	province_development = { 
		id = { type = 14500 id = 101 } 
		name = "" 
		progress = 0.0000 
		location = 67 
		cost = 2.0000 
		date = { 
			year = 1939 
			month = november 
			day = 4 
			hour = 0 
			} 
		manpower = 1.0000 
		close_when_finished = yes 
		waitingforclosure = no 
		total_progress = 0.0000 
		size = 4 
		done = 0 
		days = 346 
		days_for_first = 346 
		gearing_bonus = 0.0000 
		type = synthetic_oil 
		} 
	province_development = { 
		id = { type = 14500 id = 102 }
		name = "" 
		progress = 0.0000 
		location = 482 
		cost = 5.0000 
		date = { 
			year = 1938 
			month = november 
			day = 18 
			hour = 0 
			} 
		manpower = 1.0000 
		close_when_finished = yes 
		waitingforclosure = no 
		total_progress = 0.0000 
		size = 3 
		done = 0 
		days = 1037 
		days_for_first = 346 
		gearing_bonus = 0.0000 
		type = ic 
		} 
	province_development = { 
		id = { type = 14500 id = 103 } 
		name = "" 
		progress = 0.0000 
		location = 309 
		cost = 5.0000 
		date = { 
			year = 1938 
			month = november 
			day = 18 
			hour = 0 
			} 
		manpower = 1.0000 
		close_when_finished = yes 
		waitingforclosure = no 
		total_progress = 0.0000 
		size = 3 
		done = 0 
		days = 1037 
		days_for_first = 346 
		gearing_bonus = 0.0000 
		type = ic 
		} 
	province_development = { 
		id = { type = 14500 id = 104 } 
		name = "" 
		progress = 0.0000 
		location = 300 
		cost = 5.0000 
		date = { 
			year = 1938 
			month = november 
			day = 18 
			hour = 0 
			} 
		manpower = 1.0000 
		close_when_finished = yes 
		waitingforclosure = no 
		total_progress = 0.0000 
		size = 3 
		done = 0 
		days = 1037 
		days_for_first = 346 
		gearing_bonus = 0.0000 
		type = ic 
		} 
	province_development = { 
		id = { type = 14500 id = 105 } 
		name = "" 
		progress = 0.0000 
		location = 473 
		cost = 5.0000 
		date = { 
			year = 1938 
			month = november 
			day = 18 
			hour = 0 
			} 
		manpower = 1.0000 
		close_when_finished = yes 
		waitingforclosure = no 
		total_progress = 0.0000 
		size = 3 
		done = 0 
		days = 1037 
		days_for_first = 346 
		gearing_bonus = 0.0000 
		type = ic 
		} 
	province_development = { 
		id = { type = 14500 id = 106 } 
		name = "" 
		progress = 0.0000 
		location = 81 
		cost = 5.0000 
		date = { 
			year = 1938 
			month = november 
			day = 18 
			hour = 0 
			} 
		manpower = 1.0000 
		close_when_finished = yes 
		waitingforclosure = no 
		total_progress = 0.0000 
		size = 3 
		done = 0 
		days = 1037 
		days_for_first = 346 
		gearing_bonus = 0.0000 
		type = ic 
		} 
	province_development = { 
		id = { type = 14500 id = 107 } 
		name = "" 
		progress = 0.0000 
		location = 66 
		cost = 5.0000 
		date = { 
			year = 1938 
			month = november 
			day = 18 
			hour = 0 
			} 
		manpower = 1.0000 
		close_when_finished = yes 
		waitingforclosure = no 
		total_progress = 0.0000 
		size = 3 
		done = 0 
		days = 1037 
		days_for_first = 346 
		gearing_bonus = 0.0000 
		type = ic 
		} 
	province_development = { 
		id = { type = 14500 id = 108 } 
		name = "" 
		progress = 0.0000 
		location = 298 
		cost = 5.0000 
		date = { 
			year = 1938 
			month = november 
			day = 18 
			hour = 0 
			} 
		manpower = 1.0000 
		close_when_finished = yes 
		waitingforclosure = no 
		total_progress = 0.0000 
		size = 3 
		done = 0 
		days = 1037 
		days_for_first = 346 
		gearing_bonus = 0.0000 
		type = ic 
		} 
	province_development = { 
		id = { type = 14500 id = 109 } 
		name = "" 
		progress = 0.0000 
		location = 83 
		cost = 5.0000 
		date = { 
			year = 1938 
			month = november 
			day = 18 
			hour = 0 
			} 
		manpower = 1.0000 
		close_when_finished = yes 
		waitingforclosure = no 
		total_progress = 0.0000 
		size = 3 
		done = 0 
		days = 1037 
		days_for_first = 346 
		gearing_bonus = 0.0000 
		type = ic 
		} 
	province_development = { 
		id = { type = 14500 id = 110 } 
		name = "" 
		progress = 0.0000 
		location = 297 
		cost = 5.0000 
		date = { 
			year = 1938 
			month = november 
			day = 18 
			hour = 0 
			} 
		manpower = 1.0000 
		close_when_finished = yes 
		waitingforclosure = no 
		total_progress = 0.0000 
		size = 3 
		done = 0 
		days = 1037 
		days_for_first = 346 
		gearing_bonus = 0.0000 
		type = ic 
		} 
	province_development = { 
		id = { type = 14500 id = 111 } 
		name = "" 
		progress = 0.0000 
		location = 67 
		cost = 5.0000 
		date = { 
			year = 1938 
			month = november 
			day = 18 
			hour = 0 
			} 
		manpower = 1.0000 
		close_when_finished = yes 
		waitingforclosure = no 
		total_progress = 0.0000 
		size = 3 
		done = 0 
		days = 3802 
		days_for_first = 346 
		gearing_bonus = 0.0000 
		type = ic 
		} 
	province_development = { 
		id = { type = 14500 id = 112 } 
		name = "" 
		progress = 0.0000 
		location = 76 
		cost = 5.0000 
		date = { 
			year = 1938 
			month = november 
			day = 18 
			hour = 0 
			} 
		manpower = 1.0000 
		close_when_finished = yes 
		waitingforclosure = no 
		total_progress = 0.0000 
		size = 3 
		done = 0 
		days = 3802 
		days_for_first = 346 
		gearing_bonus = 0.0000 
		type = ic 
		} 
	province_development = { 
		id = { type = 14500 id = 113 } 
		name = "" 
		progress = 0.0000 
		location = 82 
		cost = 5.0000 
		date = { 
			year = 1938 
			month = november 
			day = 18 
			hour = 0 
			} 
		manpower = 1.0000 
		close_when_finished = yes 
		waitingforclosure = no 
		total_progress = 0.0000 
		size = 3 
		done = 0 
		days = 3802 
		days_for_first = 346 
		gearing_bonus = 0.0000 
		type = ic 
		} 
	province_development = { 
		id = { type = 14500 id = 114 } 
		name = "" 
		progress = 0.0000 
		location = 74 
		cost = 5.0000 
		date = { 
			year = 1938 
			month = november 
			day = 18 
			hour = 0 
			} 
		manpower = 1.0000 
		close_when_finished = yes 
		waitingforclosure = no 
		total_progress = 0.0000 
		size = 3 
		done = 0 
		days = 3802 
		days_for_first = 346 
		gearing_bonus = 0.0000 
		type = ic 
		} 
	province_development = { 
		id = { type = 14500 id = 115 } 
		name = "" 
		progress = 0.0000 
		location = 310 
		cost = 5.0000 
		date = { 
			year = 1938 
			month = november 
			day = 18 
			hour = 0 
			} 
		manpower = 1.0000 
		close_when_finished = yes 
		waitingforclosure = no 
		total_progress = 0.0000 
		size = 3 
		done = 0 
		days = 3802 
		days_for_first = 346 
		gearing_bonus = 0.0000 
		type = ic 
		} 
	province_development = { 
		id = { type = 14500 id = 116 } 
		name = "" 
		progress = 0.0000 
		location = 75 
		cost = 5.0000 
		date = { 
			year = 1938 
			month = november 
			day = 18 
			hour = 0 
			} 
		manpower = 1.0000 
		close_when_finished = yes 
		waitingforclosure = no 
		total_progress = 0.0000 
		size = 3 
		done = 0 
		days = 3802 
		days_for_first = 346 
		gearing_bonus = 0.0000 
		type = ic 
		} 
	province_development = { 
		id = { type = 14500 id = 117 } 
		name = "" 
		progress = 0.0000 
		location = 86 
		cost = 5.0000 
		date = { 
			year = 1938 
			month = november 
			day = 18 
			hour = 0 
			} 
		manpower = 1.0000 
		close_when_finished = yes 
		waitingforclosure = no 
		total_progress = 0.0000 
		size = 3 
		done = 0 
		days = 2074 
		days_for_first = 346 
		gearing_bonus = 0.0000 
		type = ic 
		} 
	province_development = { 
		id = { type = 14500 id = 118 } 
		name = "" 
		progress = 0.0000 
		location = 84 
		cost = 5.0000 
		date = { 
			year = 1938 
			month = november 
			day = 18 
			hour = 0 
			} 
		manpower = 1.0000 
		close_when_finished = yes 
		waitingforclosure = no 
		total_progress = 0.0000 
		size = 3 
		done = 0 
		days = 1382 
		days_for_first = 346 
		gearing_bonus = 0.0000 
		type = ic 
		} 
	province_development = { 
		id = { type = 14500 id = 119 } 
		name = "" 
		progress = 0.0000 
		location = 300 
		cost = 2.0000 
		date = { 
			year = 1939 
			month = july 
			day = 21 
			hour = 0 
			} 
		manpower = 0.1000 
		close_when_finished = yes 
		waitingforclosure = no 
		total_progress = 0.0000 
		size = 20 
		done = 0 
		days = 985 
		days_for_first = 109 
		gearing_bonus = 0.0000 
		speed_step = 1 
		type = infrastructure 
		} 
	province_development = { 
		id = { type = 14500 id = 120 } 
		name = "" 
		progress = 0.0000 
		location = 75 
		cost = 2.0000 
		date = { 
			year = 1939 
			month = july 
			day = 21 
			hour = 0 
			} 
		manpower = 0.1000 
		close_when_finished = yes 
		waitingforclosure = no 
		total_progress = 0.0000 
		size = 20 
		done = 0 
		days = 985 
		days_for_first = 109 
		gearing_bonus = 0.0000 
		speed_step = 1 
		type = infrastructure 
		} 
	province_development = { 
		id = { type = 14500 id = 121 } 
		name = "" 
		progress = 0.0000 
		location = 314 
		cost = 2.0000 
		date = { 
			year = 1939 
			month = july 
			day = 21 
			hour = 0 
			} 
		manpower = 0.1000 
		close_when_finished = yes 
		waitingforclosure = no 
		total_progress = 0.0000 
		size = 20 
		done = 0 
		days = 985 
		days_for_first = 109 
		gearing_bonus = 0.0000 
		speed_step = 1 
		type = infrastructure 
		} 
	province_development = { 
		id = { type = 14500 id = 122 } 
		name = "" 
		progress = 0.0000 
		location = 482 
		cost = 2.0000 
		date = { 
			year = 1940 
			month = april 
			day = 0 
			hour = 0 
			} 
		manpower = 0.1000 
		close_when_finished = yes 
		waitingforclosure = no 
		total_progress = 0.0000 
		size = 24 
		done = 0 
		days = 1357 
		days_for_first = 109 
		gearing_bonus = 0.0000 
		speed_step = 1 
		type = infrastructure 
		} 
	province_development = { 
		id = { type = 14500 id = 123 } 
		name = "" 
		progress = 0.0000 
		location = 76 
		cost = 2.0000 
		date = { 
			year = 1939 
			month = july 
			day = 21 
			hour = 0 
			} 
		manpower = 0.1000 
		close_when_finished = yes 
		waitingforclosure = no 
		total_progress = 0.0000 
		size = 20 
		done = 0 
		days = 985 
		days_for_first = 109 
		gearing_bonus = 0.0000 
		speed_step = 1 
		type = infrastructure 
		} 
	province_development = { 
		id = { type = 14500 id = 124 } 
		name = "" 
		progress = 0.0000 
		location = 86 
		cost = 2.0000 
		date = { 
			year = 1941 
			month = january 
			day = 12 
			hour = 0 
			} 
		manpower = 0.1000 
		close_when_finished = yes 
		waitingforclosure = no 
		total_progress = 0.0000 
		size = 20 
		done = 0 
		days = 985 
		days_for_first = 109 
		gearing_bonus = 0.0000 
		type = infrastructure 
		} 
	province_development = { 
		id = { type = 14500 id = 125 } 
		name = "" 
		progress = 0.0000 
		location = 67 
		cost = 2.0000 
		date = { 
			year = 1939 
			month = july 
			day = 21 
			hour = 0 
			} 
		manpower = 0.1000 
		close_when_finished = yes 
		waitingforclosure = no 
		total_progress = 0.0000 
		size = 20 
		done = 0 
		days = 985 
		days_for_first = 109 
		gearing_bonus = 0.0000 
		speed_step = 1 
		type = infrastructure 
		} 
	province_development = { 
		id = { type = 14500 id = 126 } 
		name = "" 
		progress = 0.0000 
		location = 310 
		cost = 2.0000 
		date = { 
			year = 1939 
			month = july 
			day = 21 
			hour = 0 
			} 
		manpower = 0.1000 
		close_when_finished = yes 
		waitingforclosure = no 
		total_progress = 0.0000 
		size = 20 
		done = 0 
		days = 985 
		days_for_first = 109 
		gearing_bonus = 0.0000 
		speed_step = 1 
		type = infrastructure 
		} 
	province_development = { 
		id = { type = 14500 id = 127 } 
		name = "" 
		progress = 0.0000 
		location = 473 
		cost = 2.0000 
		date = { 
			year = 1941 
			month = january 
			day = 12 
			hour = 0 
			} 
		manpower = 0.1000 
		close_when_finished = yes 
		waitingforclosure = no 
		total_progress = 0.0000 
		size = 20 
		done = 0 
		days = 1916 
		days_for_first = 109 
		gearing_bonus = 0.0000 
		type = infrastructure 
		} 
	province_development = { 
		id = { type = 14500 id = 128 } 
		name = "" 
		progress = 0.0000 
		location = 74 
		cost = 2.0000 
		date = { 
			year = 1939 
			month = july 
			day = 21 
			hour = 0 
			} 
		manpower = 0.1000 
		close_when_finished = yes 
		waitingforclosure = no 
		total_progress = 0.0000 
		size = 20 
		done = 0 
		days = 1916 
		days_for_first = 109 
		gearing_bonus = 0.0000 
		speed_step = 1 
		type = infrastructure 
		} 
	province_development = { 
		id = { type = 14500 id = 129 } 
		name = "" 
		progress = 0.0000 
		location = 309 
		cost = 2.0000 
		date = { 
			year = 1941 
			month = january 
			day = 12 
			hour = 0 
			} 
		manpower = 0.1000 
		close_when_finished = yes 
		waitingforclosure = no 
		total_progress = 0.0000 
		size = 20 
		done = 0 
		days = 1916 
		days_for_first = 109 
		gearing_bonus = 0.0000 
		type = infrastructure 
		} 
	province_development = { 
		id = { type = 14500 id = 130 } 
		name = "" 
		progress = 0.0000 
		location = 313 
		cost = 2.0000 
		date = { 
			year = 1939 
			month = july 
			day = 21 
			hour = 0 
			} 
		manpower = 0.1000 
		close_when_finished = yes 
		waitingforclosure = no 
		total_progress = 0.0000 
		size = 20 
		done = 0 
		days = 1916 
		days_for_first = 109 
		gearing_bonus = 0.0000 
		speed_step = 1 
		type = infrastructure 
		} 
	province_development = { 
		id = { type = 14500 id = 131 } 
		name = "" 
		progress = 0.0000 
		location = 299 
		cost = 2.0000 
		date = { 
			year = 1941 
			month = january 
			day = 12 
			hour = 0 
			} 
		manpower = 0.1000 
		close_when_finished = yes 
		waitingforclosure = no 
		total_progress = 0.0000 
		size = 20 
		done = 0 
		days = 1916 
		days_for_first = 109 
		gearing_bonus = 0.0000 
		type = infrastructure 
		} 
	province_development = { 
		id = { type = 14500 id = 132 } 
		name = "" 
		progress = 0.0000 
		location = 66 
		cost = 2.0000 
		date = { 
			year = 1939 
			month = july 
			day = 21 
			hour = 0 
			} 
		manpower = 0.1000 
		close_when_finished = yes 
		waitingforclosure = no 
		total_progress = 0.0000 
		size = 20 
		done = 0 
		days = 1916 
		days_for_first = 109 
		gearing_bonus = 0.0000 
		speed_step = 1 
		type = infrastructure 
		} 
	province_development = { 
		id = { type = 14500 id = 133 } 
		name = "" 
		progress = 0.0000 
		location = 88 
		cost = 2.0000 
		date = { 
			year = 1941 
			month = january 
			day = 12 
			hour = 0 
			} 
		manpower = 0.1000 
		close_when_finished = yes 
		waitingforclosure = no 
		total_progress = 0.0000 
		size = 20 
		done = 0 
		days = 1916 
		days_for_first = 109 
		gearing_bonus = 0.0000 
		type = infrastructure 
		} 
	province_development = { 
		id = { type = 14500 id = 134 } 
		name = "" 
		progress = 0.0000 
		location = 298 
		cost = 2.0000 
		date = { 
			year = 1941 
			month = january 
			day = 12 
			hour = 0 
			} 
		manpower = 0.1000 
		close_when_finished = yes 
		waitingforclosure = no 
		total_progress = 0.0000 
		size = 20 
		done = 0 
		days = 1916 
		days_for_first = 109 
		gearing_bonus = 0.0000 
		type = infrastructure 
		} 
	province_development = { 
		id = { type = 14500 id = 135 } 
		name = "" 
		progress = 0.0000 
		location = 82 
		cost = 2.0000 
		date = { 
			year = 1939 
			month = july 
			day = 21 
			hour = 0 
			} 
		manpower = 0.1000 
		close_when_finished = yes 
		waitingforclosure = no 
		total_progress = 0.0000 
		size = 20 
		done = 0 
		days = 1916 
		days_for_first = 109 
		gearing_bonus = 0.0000 
		speed_step = 1 
		type = infrastructure 
		} 
	province_development = { 
		id = { type = 14500 id = 136 } 
		name = "" 
		progress = 0.0000 
		location = 81 
		cost = 2.0000 
		date = { 
			year = 1941 
			month = january 
			day = 12 
			hour = 0 
			} 
		manpower = 0.1000 
		close_when_finished = yes 
		waitingforclosure = no 
		total_progress = 0.0000 
		size = 20 
		done = 0 
		days = 1916 
		days_for_first = 109 
		gearing_bonus = 0.0000 
		type = infrastructure 
		} 
	province_development = { 
		id = { type = 14500 id = 137 } 
		name = "" 
		progress = 0.0000 
		location = 84 
		cost = 2.0000 
		date = { 
			year = 1939 
			month = july 
			day = 21 
			hour = 0 
			} 
		manpower = 0.1000 
		close_when_finished = yes 
		waitingforclosure = no 
		total_progress = 0.0000 
		size = 20 
		done = 0 
		days = 1916 
		days_for_first = 109 
		gearing_bonus = 0.0000 
		speed_step = 1 
		type = infrastructure 
		} 
	province_development = { 
		id = { type = 14500 id = 138 } 
		name = "" 
		progress = 0.0000 
		location = 297 
		cost = 2.0000 
		date = { 
			year = 1941 
			month = january 
			day = 12 
			hour = 0 
			} 
		manpower = 0.1000 
		close_when_finished = yes 
		waitingforclosure = no 
		total_progress = 0.0000 
		size = 20 
		done = 0 
		days = 1916 
		days_for_first = 109 
		gearing_bonus = 0.0000 
		type = infrastructure 
		} 
	province_development = { 
		id = { type = 14500 id = 139 } 
		name = "" 
		progress = 0.0000 
		location = 83 
		cost = 2.0000 
		date = { 
			year = 1941 
			month = january 
			day = 12 
			hour = 0 
			} 
		manpower = 0.1000 
		close_when_finished = yes 
		waitingforclosure = no 
		total_progress = 0.0000 
		size = 20 
		done = 0 
		days = 1916 
		days_for_first = 109 
		gearing_bonus = 0.0000 
		type = infrastructure 
		} 
	province_development = { 
		id = { type = 14500 id = 140 } 
		name = "" 
		progress = 0.0000 
		location = 311 
		cost = 2.0000 
		date = { 
			year = 1939 
			month = july 
			day = 21 
			hour = 0 
			} 
		manpower = 0.1000 
		close_when_finished = yes 
		waitingforclosure = no 
		total_progress = 0.0000 
		size = 20 
		done = 0 
		days = 1916 
		days_for_first = 109 
		gearing_bonus = 0.0000 
		speed_step = 1 
		type = infrastructure 
		} 
	province_development = { 
		id = { type = 14500 id = 141 } 
		name = "" 
		progress = 0.0000 
		location = 312 
		cost = 2.0000 
		date = { 
			year = 1939 
			month = july 
			day = 21 
			hour = 0 
			} 
		manpower = 0.1000 
		close_when_finished = yes 
		waitingforclosure = no 
		total_progress = 0.0000 
		size = 20 
		done = 0 
		days = 1916 
		days_for_first = 109 
		gearing_bonus = 0.0000 
		speed_step = 1 
		type = infrastructure 
		} 
	province_development = { 
		id = { type = 14500 id = 142 } 
		name = "" 
		progress = 0.0000 
		location = 376 
		cost = 2.0000 
		date = { 
			year = 1939 
			month = july 
			day = 21 
			hour = 0 
			} 
		manpower = 0.1000 
		close_when_finished = yes 
		waitingforclosure = no 
		total_progress = 0.0000 
		size = 20 
		done = 0 
		days = 1916 
		days_for_first = 109 
		gearing_bonus = 0.0000 
		speed_step = 1 
		type = infrastructure 
		} 
	province_development = { 
		id = { type = 14500 id = 143 } 
		name = "" 
		progress = 0.0000 
		location = 510 
		cost = 2.0000 
		date = { 
			year = 1939 
			month = july 
			day = 21 
			hour = 0 
			} 
		manpower = 0.1000 
		close_when_finished = yes 
		waitingforclosure = no 
		total_progress = 0.0000 
		size = 20 
		done = 0 
		days = 1916 
		days_for_first = 109 
		gearing_bonus = 0.0000 
		speed_step = 1 
		type = infrastructure 
		} 
	province_development = { 
		id = { type = 14500 id = 144 } 
		name = "" 
		progress = 0.0000 
		location = 80 
		cost = 2.0000 
		date = { 
			year = 1941 
			month = january 
			day = 12 
			hour = 0 
			} 
		manpower = 0.1000 
		close_when_finished = yes 
		waitingforclosure = no 
		total_progress = 0.0000 
		size = 20 
		done = 0 
		days = 1916 
		days_for_first = 109 
		gearing_bonus = 0.0000 
		type = infrastructure 
		} 
	province_development = { 
		id = { type = 14500 id = 145 } 
		name = "" 
		progress = 0.0000 
		location = 90 
		cost = 2.0000 
		date = { 
			year = 1941 
			month = january 
			day = 12 
			hour = 0 
			} 
		manpower = 0.1000 
		close_when_finished = yes 
		waitingforclosure = no 
		total_progress = 0.0000 
		size = 20 
		done = 0 
		days = 1916 
		days_for_first = 109 
		gearing_bonus = 0.0000 
		type = infrastructure 
		} 
	brigade_development = { 
		id = { type = 14500 id = 146 } 
		name = "Basic Camouflage Equipment" 
		progress = 0.0000 
		location = 300 
		cost = 1.0560 
		date = { 
			year = 1936 
			month = june 
			day = 1 
			hour = 0 
			} 
		manpower = 0.1000 
		close_when_finished = yes 
		waitingforclosure = no 
		retooling_time = 38.0000 
		total_progress = 0.0000 
		size = 2 
		done = 0 
		days = 112 
		days_for_first = 58 
		gearing_bonus = 0.0000 
		type = b_u6 
		model = 0 
		} 
	brigade_development = { 
		id = { type = 14500 id = 147 } 
		name = "37' ASW" 
		progress = 0.0000 
		location = 300 
		cost = 1.4400 
		date = { 
			year = 1936 
			month = july 
			day = 17 
			hour = 0 
			} 
		manpower = 0.1000 
		close_when_finished = yes 
		waitingforclosure = no 
		retooling_time = 38.0000 
		total_progress = 0.0000 
		size = 2 
		done = 0 
		days = 159 
		days_for_first = 82 
		gearing_bonus = 0.0000 
		type = naval_asw 
		model = 0 
		} 
	brigade_development = { 
		id = { type = 14500 id = 148 } 
		name = "36' AA" 
		progress = 0.0000 
		location = 300 
		cost = 0.7680 
		date = { 
			year = 1936 
			month = may 
			day = 9 
			hour = 0 
			} 
		manpower = 0.1000 
		close_when_finished = yes 
		waitingforclosure = no 
		retooling_time = 38.0000 
		total_progress = 0.0000 
		size = 1 
		done = 0 
		days = 91 
		days_for_first = 91 
		gearing_bonus = 0.0000 
		type = naval_anti_air_s 
		model = 1 
		} 
	division_development = { 
		id = { type = 14500 id = 149 } 
		name = "Bismarck" 
		progress = 0.0000 
		location = 300 
		cost = 8.1668 
		date = { 
			year = 1938 
			month = august 
			day = 25 
			hour = 0 
			} 
		manpower = 2.1000 
		close_when_finished = yes 
		waitingforclosure = no 
		total_progress = 0.0000 
		size = 2 
		done = 0 
		days = 469 
		days_for_first = 490 
		gearing_bonus = 0.0000 
		type = battleship 
		extra = naval_anti_air_l 
		extra1 = naval_torpedoes_l 
		extra2 = naval_fire_controll_l 
		extra3 = naval_sa_l 
		extra4 = naval_improved_hull_l 
		model = 4
		brigade_model = 1 
		brigade_model1 = 0 
		brigade_model2 = 0 
		brigade_model3 = 1 
		brigade_model4 = 0 
		} 
	division_development = { 
		id = { type = 14500 id = 150 } 
		name = "Scharnhorst" 
		progress = 0.0000 
		location = 0 
		cost = 6.1570 
		date = { 
			year = 1938 
			month = april 
			day = 12 
			hour = 0 
			} 
		manpower = 1.5000 
		close_when_finished = yes 
		waitingforclosure = no 
		total_progress = 0.0000 
		size = 2 
		done = 0 
		days = 1 
		days_for_first = 422 
		gearing_bonus = 0.0000 
		type = battlecruiser 
		extra = none 
		extra1 = naval_sa_l 
		extra2 = naval_fire_controll_l 
		extra3 = naval_torpedoes_l 
		extra4 = naval_anti_air_l 
		model = 4
		brigade_model = 0 
		brigade_model1 = 1 
		brigade_model2 = 0 
		brigade_model3 = 0 
		brigade_model4 = 1 
		} 
	division_development = { 
		id = { type = 14500 id = 151 } 
		name = "Admiral Graf Spee" 
		progress = 0.0000 
		location = 0 
		cost = 4.5845 
		date = { 
			year = 1936 
			month = january 
			day = 1 
			hour = 0 
			} 
		manpower = 1.4000 
		close_when_finished = yes 
		waitingforclosure = no 
		total_progress = 0.9967 
		size = 1 
		done = 0 
		days = 1 
		days_for_first = 307 
		gearing_bonus = 0.0000 
		type = heavy_cruiser 
		extra = none 
		extra1 = naval_sa_l 
		extra2 = naval_fire_controll_l 
		extra3 = naval_radar_l 
		extra4 = none 
		model = 3 
		brigade_model = 0 
		brigade_model1 = 1 
		brigade_model2 = 0 
		brigade_model3 = 0 
		brigade_model4 = 0 
		} 
	division_development = { 
		id = { type = 14500 id = 152 } 
		name = "2. Zerstörerflottille" 
		progress = 0.0000 
		location = 0 
		cost = 3.9291 
		date = { 
			year = 1936 
			month = february 
			day = 15 
			hour = 0 
			} 
		manpower = 0.7000 
		close_when_finished = yes 
		waitingforclosure = no 
		total_progress = 0.6250 
		size = 1 
		done = 0 
		days = 1 
		days_for_first = 120 
		gearing_bonus = 0.0000 
		type = destroyer 
		extra = none 
		extra1 = naval_fire_controll_s 
		extra2 = none 
		extra3 = none 
		extra4 = none 
		model = 1 
		brigade_model = 0 
		brigade_model1 = 0 
		brigade_model2 = 0 
		brigade_model3 = 0 
		brigade_model4 = 0 
		} 
	division_development = { 
		id = { type = 14500 id = 153 } 
		name = "2. Zerstörerflottille" 
		progress = 0.0000 
		location = 0 
		cost = 3.9291 
		date = { 
			year = 1936 
			month = february 
			day = 15 
			hour = 0 
			} 
		manpower = 0.7000 
		close_when_finished = yes 
		waitingforclosure = no 
		total_progress = 0.6250 
		size = 1 
		done = 0 
		days = 1 
		days_for_first = 120 
		gearing_bonus = 0.0000 
		type = destroyer 
		extra = none 
		extra1 = naval_fire_controll_s 
		extra2 = none 
		extra3 = none 
		extra4 = none 
		model = 1 
		brigade_model = 0 
		brigade_model1 = 0 
		brigade_model2 = 0 
		brigade_model3 = 0 
		brigade_model4 = 0 
		} 
	division_development = { 
		id = { type = 14500 id = 154 } 
		name = "4. Unterseebootsflottille" 
		progress = 0.0000 
		location = 0 
		cost = 1.9200 
		date = { 
			year = 1936 
			month = march 
			day = 1 
			hour = 0 
			} 
		manpower = 0.3000 
		close_when_finished = yes 
		waitingforclosure = no 
		total_progress = 0.4245 
		size = 1 
		done = 0 
		days = 1 
		days_for_first = 106 
		gearing_bonus = 0.0000 
		type = submarine 
		extra = none 
		extra1 = none 
		extra2 = none 
		extra3 = none 
		extra4 = none 
		model = 1 
		brigade_model = 0 
		brigade_model1 = 0 
		brigade_model2 = 0 
		brigade_model3 = 0 
		brigade_model4 = 0 
		} 
}