###################
# Anti Aircraft
###################

province = { id = 16   anti_air = { type = flak size = 1.0000 current_size = 1.0000 } } # Birmingham
province = { id = 19   anti_air = { type = flak size = 1.0000 current_size = 1.0000 } } # London
province = { id = 20   anti_air = { type = flak size = 1.0000 current_size = 1.0000 } } # Dover
province = { id = 46   anti_air = { type = flak size = 1.0000 current_size = 1.0000 } } # Rotterdam
province = { id = 47   anti_air = { type = flak size = 1.0000 current_size = 1.0000 } } # Amsterdam
province = { id = 51   anti_air = { type = flak size = 1.0000 current_size = 1.0000 } } # Brussels
province = { id = 56   anti_air = { type = flak size = 1.0000 current_size = 1.0000 } } # Paris
province = { id = 80   anti_air = { type = flak size = 1.0000 current_size = 1.0000 } } # Wilhelmshafen
province = { id = 90   anti_air = { type = flak size = 1.0000 current_size = 1.0000 } } # Kiel
province = { id = 101  anti_air = { type = flak size = 1.0000 current_size = 1.0000 } } # Stockholm
province = { id = 107  anti_air = { type = flak size = 1.0000 current_size = 1.0000 } } # Oslo
province = { id = 110  anti_air = { type = flak size = 1.0000 current_size = 1.0000 } } # Bergen
province = { id = 142  anti_air = { type = flak size = 1.0000 current_size = 1.0000 } } # Helsinki
province = { id = 175  anti_air = { type = flak size = 2.0000 current_size = 2.0000 } } # Moscow
province = { id = 187  anti_air = { type = flak size = 2.0000 current_size = 2.0000 } } # Leningrad
province = { id = 194  anti_air = { type = flak size = 1.0000 current_size = 1.0000 } } # Tallinn
province = { id = 238  anti_air = { type = flak size = 1.0000 current_size = 1.0000 } } # Kiev
#province = { 
#id = 253  
#anti_air = { type = flak size = 1.0000 current_size = 1.0000 } 
#coastalfort = { type = coastal_fort size = 5.0000 current_size = 5.0000 }
#landfort = { type = land_fort size = 3.0000 current_size = 3.0000 }
#} # Sevastopol
province = { id = 300  anti_air = { type = flak size = 2.0000 current_size = 2.0000 } } # Berlin
province = { id = 303  anti_air = { type = flak size = 1.0000 current_size = 1.0000 } } # Danzig
province = { id = 336  anti_air = { type = flak size = 1.0000 current_size = 1.0000 } } # Lissabon
province = { id = 341  anti_air = { type = flak size = 1.0000 current_size = 1.0000 } } # Madrid
province = { id = 347  anti_air = { type = flak size = 1.0000 current_size = 1.0000 } } # Seville
province = { id = 348  anti_air = { type = flak size = 4.0000 current_size = 4.0000 } } # Gibraltar
province = { id = 364  anti_air = { type = flak size = 1.0000 current_size = 1.0000 } } # Marseille
province = { id = 368  anti_air = { type = flak size = 1.0000 current_size = 1.0000 } } # Genoa
province = { id = 369  anti_air = { type = flak size = 1.0000 current_size = 1.0000 } } # La Spezia
province = { id = 409  anti_air = { type = flak size = 1.0000 current_size = 1.0000 } } # Istanbul
province = { id = 417  anti_air = { type = flak size = 1.0000 current_size = 1.0000 } } # Sofia
province = { id = 422  anti_air = { type = flak size = 1.0000 current_size = 1.0000 } } # Varna
province = { id = 423  anti_air = { type = flak size = 1.0000 current_size = 1.0000 } } # Constanta
province = { id = 424  anti_air = { type = flak size = 1.0000 current_size = 1.0000 } } # Bucharest
province = { id = 431  anti_air = { type = flak size = 1.0000 current_size = 1.0000 } } # Ploesti
province = { id = 453  anti_air = { type = flak size = 1.0000 current_size = 1.0000 } } # Belgrade
province = { id = 457  anti_air = { type = flak size = 1.0000 current_size = 1.0000 } } # Budapest
province = { id = 463  anti_air = { type = flak size = 1.0000 current_size = 1.0000 } } # Vienna
province = { id = 469  anti_air = { type = flak size = 1.0000 current_size = 1.0000 } } # Prague
province = { id = 479  anti_air = { type = flak size = 1.0000 current_size = 1.0000 } } # Cracow
province = { id = 485  anti_air = { type = flak size = 1.0000 current_size = 1.0000 } } # Warsaw
province = { id = 515  anti_air = { type = flak size = 1.0000 current_size = 1.0000 } } # Rome
province = { id = 523  anti_air = { type = flak size = 1.0000 current_size = 1.0000 } } # Taranto
province = { id = 602  anti_air = { type = flak size = 1.0000 current_size = 1.0000 } } # New York
province = { id = 633  anti_air = { type = flak size = 1.0000 current_size = 1.0000 } } # Norfolk
province = { id = 663  anti_air = { type = flak size = 2.0000 current_size = 2.0000 } } # Pearl Harbor
province = { id = 667  anti_air = { type = flak size = 1.0000 current_size = 1.0000 } } # Buenos Aires
province = { id = 752  anti_air = { type = flak size = 1.0000 current_size = 1.0000 } } # Mexico City
province = { id = 761  anti_air = { type = flak size = 1.0000 current_size = 1.0000 } } # San Diego
province = { id = 762  anti_air = { type = flak size = 1.0000 current_size = 1.0000 } } # Los Angeles
province = { id = 765  anti_air = { type = flak size = 1.0000 current_size = 1.0000 } } # San Francisco
province = { id = 849  anti_air = { type = flak size = 1.0000 current_size = 1.0000 } } # Montevideo
province = { id = 885  anti_air = { type = flak size = 1.0000 current_size = 1.0000 } } # Rio de Janeiro
province = { id = 889  anti_air = { type = flak size = 2.0000 current_size = 2.0000 } } # Canal Zone
province = { id = 1184 anti_air = { type = flak size = 2.0000 current_size = 2.0000 } } # Tokyo
province = { id = 1185 anti_air = { type = flak size = 1.0000 current_size = 1.0000 } } # Nagoya
province = { id = 1187 anti_air = { type = flak size = 1.0000 current_size = 1.0000 } } # Osaka
province = { id = 1188 anti_air = { type = flak size = 1.0000 current_size = 1.0000 } } # Hiroshima
province = { id = 1190 anti_air = { type = flak size = 1.0000 current_size = 1.0000 } } # Fukuoka
province = { id = 1202 anti_air = { type = flak size = 1.0000 current_size = 1.0000 } } # Dalian
province = { id = 1345 anti_air = { type = flak size = 1.0000 current_size = 1.0000 } } # Thom Buri
province = { id = 1372 anti_air = { type = flak size = 1.0000 current_size = 1.0000 } } # Vladivostok
province = { id = 1613 anti_air = { type = flak size = 1.0000 current_size = 1.0000 } } # Truk
province = { id = 1632 anti_air = { type = flak size = 1.0000 current_size = 1.0000 } } # Soerabaja
province = { id = 1727 anti_air = { type = flak size = 1.0000 current_size = 1.0000 } } # Sydney
province = { id = 1737 anti_air = { type = flak size = 1.0000 current_size = 1.0000 } } # Manila

##################################
# Coastal Forts
##################################

province = { id = 5    coastalfort = { type = coastal_fort size = 1.0000 current_size = 1.0000 } } # Scapa Flow
province = { id = 9    coastalfort = { type = coastal_fort size = 1.0000 current_size = 1.0000 } } # Glasgow
province = { id = 10   coastalfort = { type = coastal_fort size = 2.0000 current_size = 2.0000 } } # Edinburgh
province = { id = 11   coastalfort = { type = coastal_fort size = 2.0000 current_size = 2.0000 } } # Sunderland
province = { id = 14   coastalfort = { type = coastal_fort size = 1.0000 current_size = 1.0000 } } # Liverpool
province = { id = 17   coastalfort = { type = coastal_fort size = 1.0000 current_size = 1.0000 } } # Norfolk
province = { id = 20   coastalfort = { type = coastal_fort size = 3.0000 current_size = 3.0000 } } # Dover
province = { id = 21   coastalfort = { type = coastal_fort size = 1.0000 current_size = 1.0000 } } # Portsmouth
province = { id = 23   coastalfort = { type = coastal_fort size = 2.0000 current_size = 2.0000 } } # Plymouth
province = { id = 28   coastalfort = { type = coastal_fort size = 1.0000 current_size = 1.0000 } } # Belfast
province = { id = 31   coastalfort = { type = coastal_fort size = 4.0000 current_size = 4.0000 } } # Malta
province = { id = 32   coastalfort = { type = coastal_fort size = 1.0000 current_size = 1.0000 } } # Brest
province = { id = 45   coastalfort = { type = coastal_fort size = 1.0000 current_size = 1.0000 } } # Ghent
province = { id = 46   coastalfort = { type = coastal_fort size = 1.0000 current_size = 1.0000 } } # Rotterdam
province = { id = 47   coastalfort = { type = coastal_fort size = 1.0000 current_size = 1.0000 } } # Amsterdam
province = { id = 95   coastalfort = { type = coastal_fort size = 3.0000 current_size = 3.0000 } } # Karlskrona
province = { id = 98   coastalfort = { type = coastal_fort size = 1.0000 current_size = 1.0000 } } # Göteborg
province = { id = 101  coastalfort = { type = coastal_fort size = 3.0000 current_size = 3.0000 } } # Stockholm
province = { id = 107  coastalfort = { type = coastal_fort size = 3.0000 current_size = 3.0000 } } # Oslo
province = { id = 108  coastalfort = { type = coastal_fort size = 1.0000 current_size = 1.0000 } } # Kristiansand
province = { id = 110  coastalfort = { type = coastal_fort size = 3.0000 current_size = 3.0000 } } # Bergen
province = { id = 118  coastalfort = { type = coastal_fort size = 2.0000 current_size = 2.0000 } } # Trondheim
province = { id = 133  coastalfort = { type = coastal_fort size = 2.0000 current_size = 2.0000 } } # Murmansk
province = { id = 141  coastalfort = { type = coastal_fort size = 1.0000 current_size = 1.0000 } } # Turku
province = { id = 142  coastalfort = { type = coastal_fort size = 2.0000 current_size = 2.0000 } } # Helsinki
province = { id = 145  coastalfort = { type = coastal_fort size = 1.0000 current_size = 1.0000 } } # Viipuri
province = { id = 187  coastalfort = { type = coastal_fort size = 4.0000 current_size = 4.0000 } } # Leningrad
province = { id = 194  coastalfort = { type = coastal_fort size = 3.0000 current_size = 3.0000 } } # Tallinn
province = { id = 197  coastalfort = { type = coastal_fort size = 3.0000 current_size = 3.0000 } } # Riga
#province = { id = 253  coastalfort = { type = coastal_fort size = 5.0000 current_size = 5.0000 } } # Sevastopol
province = { id = 255  coastalfort = { type = coastal_fort size = 1.0000 current_size = 1.0000 } } # Novorossisk
province = { id = 294  coastalfort = { type = coastal_fort size = 2.0000 current_size = 2.0000 } } # Copenhagen
province = { id = 303  coastalfort = { type = coastal_fort size = 1.0000 current_size = 1.0000 } } # Danzig
province = { id = 336  coastalfort = { type = coastal_fort size = 1.0000 current_size = 1.0000 } } # Lissabon
province = { id = 347  coastalfort = { type = coastal_fort size = 1.0000 current_size = 1.0000 } } # Seville
province = { id = 348  coastalfort = { type = coastal_fort size = 6.0000 current_size = 6.0000 } } # Gibraltar
province = { id = 352  coastalfort = { type = coastal_fort size = 1.0000 current_size = 1.0000 } } # Murcia
province = { id = 365  coastalfort = { type = coastal_fort size = 1.0000 current_size = 1.0000 } } # Toulon
province = { id = 399  coastalfort = { type = coastal_fort size = 1.0000 current_size = 1.0000 } } # Rhodes
province = { id = 401  coastalfort = { type = coastal_fort size = 1.0000 current_size = 1.0000 } } # Athens
province = { id = 513  coastalfort = { type = coastal_fort size = 1.0000 current_size = 1.0000 } } # Florence - Livorno
province = { id = 523  coastalfort = { type = coastal_fort size = 1.0000 current_size = 1.0000 } } # Taranto
province = { id = 524  coastalfort = { type = coastal_fort size = 1.0000 current_size = 1.0000 } } # Reggio di Calabria
province = { id = 525  coastalfort = { type = coastal_fort size = 1.0000 current_size = 1.0000 } } # Palermo
province = { id = 526  coastalfort = { type = coastal_fort size = 1.0000 current_size = 1.0000 } } # Catania
province = { id = 534  coastalfort = { type = coastal_fort size = 1.0000 current_size = 1.0000 } } # Sardinia
province = { id = 536  coastalfort = { type = coastal_fort size = 1.0000 current_size = 1.0000 } } # Menorca
province = { id = 663  coastalfort = { type = coastal_fort size = 1.0000 current_size = 1.0000 } } # Pearl Harbor
province = { id = 765  coastalfort = { type = coastal_fort size = 1.0000 current_size = 1.0000 } } # San Francisco
province = { id = 889  coastalfort = { type = coastal_fort size = 2.0000 current_size = 2.0000 } } # Canal Zone
province = { id = 891  coastalfort = { type = coastal_fort size = 1.0000 current_size = 1.0000 } } # Jamaica
province = { id = 901  coastalfort = { type = coastal_fort size = 1.0000 current_size = 1.0000 } } # Port Said
province = { id = 988  coastalfort = { type = coastal_fort size = 1.0000 current_size = 1.0000 } } # Freetown
province = { id = 1184 coastalfort = { type = coastal_fort size = 2.0000 current_size = 2.0000 } } # Tokyo
province = { id = 1187 coastalfort = { type = coastal_fort size = 1.0000 current_size = 1.0000 } } # Osaka
province = { id = 1188 coastalfort = { type = coastal_fort size = 1.0000 current_size = 1.0000 } } # Hiroshima
province = { id = 1190 coastalfort = { type = coastal_fort size = 2.0000 current_size = 2.0000 } } # Fukuoka
province = { id = 1196 coastalfort = { type = coastal_fort size = 1.0000 current_size = 1.0000 } } # Busan
province = { id = 1299 coastalfort = { type = coastal_fort size = 1.0000 current_size = 1.0000 } } # Rangoon
province = { id = 1315 coastalfort = { type = coastal_fort size = 1.0000 current_size = 1.0000 } } # Hong Kong
province = { id = 1322 coastalfort = { type = coastal_fort size = 1.0000 current_size = 1.0000 } } # Kaohsiung
province = { id = 1353 coastalfort = { type = coastal_fort size = 2.0000 current_size = 2.0000 } } # Singapore
province = { id = 1366 coastalfort = { type = coastal_fort size = 1.0000 current_size = 1.0000 } } # Bogorodskoe
province = { id = 1372 coastalfort = { type = coastal_fort size = 4.0000 current_size = 4.0000 } } # Vladivostok
province = { id = 1505 coastalfort = { type = coastal_fort size = 1.0000 current_size = 1.0000 } } # Bombay
province = { id = 1517 coastalfort = { type = coastal_fort size = 1.0000 current_size = 1.0000 } } # Colombo
province = { id = 1527 coastalfort = { type = coastal_fort size = 1.0000 current_size = 1.0000 } } # Nikolayevsk-na-Amure
province = { id = 1613 coastalfort = { type = coastal_fort size = 3.0000 current_size = 3.0000 } } # Truk
province = { id = 1628 coastalfort = { type = coastal_fort size = 1.0000 current_size = 1.0000 } } # Batavia
province = { id = 1630 coastalfort = { type = coastal_fort size = 1.0000 current_size = 1.0000 } } # Semarang
province = { id = 1632 coastalfort = { type = coastal_fort size = 2.0000 current_size = 2.0000 } } # Soerabaja
province = { id = 1712 coastalfort = { type = coastal_fort size = 1.0000 current_size = 1.0000 } } # Perth
province = { id = 1722 coastalfort = { type = coastal_fort size = 1.0000 current_size = 1.0000 } } # Brisbane
province = { id = 1727 coastalfort = { type = coastal_fort size = 2.0000 current_size = 2.0000 } } # Sydney
province = { id = 1730 coastalfort = { type = coastal_fort size = 1.0000 current_size = 1.0000 } } # Melbourne
province = { id = 1737 coastalfort = { type = coastal_fort size = 2.0000 current_size = 2.0000 } } # Manila
province = { id = 895  coastalfort = { type = coastal_fort size = 1.0000 current_size = 1.0000 } } # Puerto Rico

##################################
# Land Forts
##################################

province = { id = 48   	landfort = { type = land_fort size = 2.0000 current_size = 2.0000 } } # Utrecht
province = { id = 65   	landfort = { type = land_fort size = 1.0000 current_size = 1.0000 } } # Namur
province = { id = 68   	landfort = { type = land_fort size = 2.0000 current_size = 2.0000 } } # Liège
province = { id = 72   	landfort = { type = land_fort size = 8.0000 current_size = 8.0000 } } # Metz
province = { id = 73   	landfort = { type = land_fort size = 9.0000 current_size = 9.0000 } } # Strasbourg
province = { id = 127  	landfort = { type = land_fort size = 3.0000 current_size = 3.0000 } } # Luleå
province = { id = 133 	landfort = { type = land_fort size = 1.0000 current_size = 1.0000 } } # Murmansk
province = { id = 145  	landfort = { type = land_fort size = 2.0000 current_size = 2.0000 } } # Viipuri
province = { id = 163  	landfort = { type = land_fort size = 4.0000 current_size = 4.0000 } } # Stalingrad
province = { id = 175  	landfort = { type = land_fort size = 4.0000 current_size = 4.0000 } } # Moscow
province = { id = 187  	landfort = { type = land_fort size = 4.0000 current_size = 4.0000 } } # Leningrad
province = { id = 64  	landfort = { type = land_fort size = 2.0000 current_size = 2.0000 } } # Reims
#province = { id = 253  	landfort = { type = land_fort size = 3.0000 current_size = 3.0000 } } # Sevastopol
province = { id = 314  	landfort = { type = land_fort size = 1.0000 current_size = 1.0000 } } # Stuttgart
province = { id = 315  	landfort = { type = land_fort size = 1.0000 current_size = 1.0000 } } # Freiburg
province = { id = 316  	landfort = { type = land_fort size = 6.0000 current_size = 6.0000 } } # Mulhouse
province = { id = 317  	landfort = { type = land_fort size = 1.0000 current_size = 1.0000 } } # Chaumont 
province = { id = 318  	landfort = { type = land_fort size = 1.0000 current_size = 1.0000 } } # Dijon 
province = { id = 348  	landfort = { type = land_fort size = 9.0000 current_size = 9.0000 } } # Gibraltar
province = { id = 366  	landfort = { type = land_fort size = 3.0000 current_size = 3.0000 } } # Nice 
province = { id = 368  	landfort = { type = land_fort size = 2.0000 current_size = 2.0000 } } # Genoa
province = { id = 370  	landfort = { type = land_fort size = 1.0000 current_size = 1.0000 } } # Milan
province = { id = 371  	landfort = { type = land_fort size = 1.0000 current_size = 1.0000 } } # Trento
province = { id = 372  	landfort = { type = land_fort size = 3.0000 current_size = 3.0000 } } # Chur
province = { id = 378  	landfort = { type = land_fort size = 2.0000 current_size = 2.0000 } } # Venice
province = { id = 392  	landfort = { type = land_fort size = 3.0000 current_size = 3.0000 } } # Ioannina
province = { id = 411  	landfort = { type = land_fort size = 3.0000 current_size = 3.0000 } } # Salonika
province = { id = 461  	landfort = { type = land_fort size = 2.0000 current_size = 2.0000 } } # Klagenfurt
province = { id = 462  	landfort = { type = land_fort size = 2.0000 current_size = 2.0000 } } # Salzburg
province = { id = 465  	landfort = { type = land_fort size = 2.0000 current_size = 2.0000 } } # Linz
province = { id = 466  	landfort = { type = land_fort size = 3.0000 current_size = 3.0000 } } # Strakonice
province = { id = 467  	landfort = { type = land_fort size = 2.0000 current_size = 2.0000 } } # Tábor
province = { id = 471  	landfort = { type = land_fort size = 3.0000 current_size = 3.0000 } } # Ústí
province = { id = 472  	landfort = { type = land_fort size = 3.0000 current_size = 3.0000 } } # Liberec
province = { id = 474  	landfort = { type = land_fort size = 3.0000 current_size = 3.0000 } } # Ostrava
province = { id = 479  	landfort = { type = land_fort size = 1.0000 current_size = 1.0000 } } # Cracow
province = { id = 485  	landfort = { type = land_fort size = 1.0000 current_size = 1.0000 } } # Warsaw
province = { id = 486  	landfort = { type = land_fort size = 1.0000 current_size = 1.0000 } } # Lomza
province = { id = 504  	landfort = { type = land_fort size = 2.0000 current_size = 2.0000 } } # Brest-Litovsk
province = { id = 510  	landfort = { type = land_fort size = 1.0000 current_size = 1.0000 } } # Königsberg
province = { id = 527  	landfort = { type = land_fort size = 3.0000 current_size = 3.0000 } } # Grenoble 
province = { id = 529 	landfort = { type = land_fort size = 1.0000 current_size = 1.0000 } } # Besançon
province = { id = 530  	landfort = { type = land_fort size = 4.0000 current_size = 4.0000 } } # Geneva
province = { id = 531  	landfort = { type = land_fort size = 2.0000 current_size = 2.0000 } } # Turin
province = { id = 532  	landfort = { type = land_fort size = 4.0000 current_size = 4.0000 } } # Bern
province = { id = 533  	landfort = { type = land_fort size = 4.0000 current_size = 4.0000 } } # Zürich
province = { id = 562  	landfort = { type = land_fort size = 1.0000 current_size = 1.0000 } } # Rowne
province = { id = 919  	landfort = { type = land_fort size = 2.0000 current_size = 2.0000 } } # Tobruk
province = { id = 1253 	landfort = { type = land_fort size = 1.0000 current_size = 1.0000 } } # Wuchang
province = { id = 1270 	landfort = { type = land_fort size = 2.0000 current_size = 2.0000 } } # Xianyang
province = { id = 1271 	landfort = { type = land_fort size = 3.0000 current_size = 3.0000 } } # Yan'an
province = { id = 1275 	landfort = { type = land_fort size = 2.0000 current_size = 2.0000 } } # Pinglian
province = { id = 1315  landfort = { type = land_fort size = 1.0000 current_size = 1.0000 } } # Hong Kong
province = { id = 1372 	landfort = { type = land_fort size = 2.0000 current_size = 2.0000 } } # Vladivostok
province = { id = 1737 	landfort = { type = land_fort size = 1.0000 current_size = 1.0000 } } # Manila
province = { id = 1738 	landfort = { type = land_fort size = 1.0000 current_size = 1.0000 } } # Bataan
province = { id = 358 	landfort = { type = land_fort size = 1.0000 current_size = 1.0000 } } # Perpignan
province = { id = 1822 	landfort = { type = land_fort size = 1.0000 current_size = 1.0000 } } # Kuweit