#####################
# Country main data #
#####################

country =
{ tag                    = MLY
  capital                = 1352
  puppet = ENG
  control = ENG
  manpower               = 1.6
  # Resource Reserves

  free                   = { }
  energy                 = 180
  metal                  = 594
  rare_materials         = 1000
  oil                    = 12
  supplies               = 218
  money                  = 8
  transports             = 40

	diplomacy = {
		relation = { tag = AFG value = 1 }
		relation = { tag = ALB value = 1 }
		relation = { tag = ARG value = 1 }
		relation = { tag = AST value = 50 }
		relation = { tag = AUS value = 1 }
		relation = { tag = BEL value = 1 }
		relation = { tag = BHU value = 50 }
		relation = { tag = BOL value = 1 }
		relation = { tag = BRA value = 1 }
		relation = { tag = BUL value = 1 }
		relation = { tag = CAN value = 50 }
		relation = { tag = CGX value = 1 }
		relation = { tag = CHC value = -15 }
		relation = { tag = CHI value = 30 }
		relation = { tag = CHL value = 1 }
		relation = { tag = COL value = 1 }
		relation = { tag = COS value = 1 }
		relation = { tag = CSX value = 1 }
		relation = { tag = CUB value = 1 }
		relation = { tag = CXB value = 1 }
		relation = { tag = CYN value = 20 }
		relation = { tag = CZE value = 1 }
		relation = { tag = DEN value = 1 }
		relation = { tag = DOM value = 1 }
		relation = { tag = ECU value = 1 }
		relation = { tag = EGY value = 50 }
		relation = { tag = ENG value = 150 }
		relation = { tag = EST value = 1 }
		relation = { tag = ETH value = 1 }
		relation = { tag = FIN value = 1 }
		relation = { tag = FRA value = 1 }
		relation = { tag = GER value = 1 }
		relation = { tag = GRE value = 15 }
		relation = { tag = GUA value = 1 }
		relation = { tag = HAI value = 1 }
		relation = { tag = HOL value = 20 }
		relation = { tag = HON value = 1 }
		relation = { tag = HUN value = 1 }
		relation = { tag = IND value = 75 }
		relation = { tag = IRE value = 1 }
		relation = { tag = IRQ value = 50 }
		relation = { tag = ITA value = 1 }
		relation = { tag = JAP value = -15 }
		relation = { tag = LAT value = 1 }
		relation = { tag = LIB value = 1 }
		relation = { tag = LIT value = 1 }
		relation = { tag = LUX value = 1 }
		relation = { tag = MAN value = 1 }
		relation = { tag = MEX value = 1 }
		relation = { tag = MON value = 1 }
		relation = { tag = NEP value = 50 }
		relation = { tag = NIC value = 1 }
		relation = { tag = NOR value = 1 }
		relation = { tag = NZL value = 50 }
		relation = { tag = OMN value = 50 }
		relation = { tag = PAN value = 1 }
		relation = { tag = PAR value = 1 }
		relation = { tag = PER value = 1 }
		relation = { tag = PHI value = 20 }
		relation = { tag = POL value = 1 }
		relation = { tag = POR value = 1 }
		relation = { tag = PRU value = 1 }
		relation = { tag = ROM value = 1 }
		relation = { tag = SAF value = 50 }
		relation = { tag = SAL value = 1 }
		relation = { tag = SAU value = 1 }
		relation = { tag = SIA value = -25 }
		relation = { tag = SIK value = 1 }
		relation = { tag = SOV value = 1 }
		relation = { tag = SPA value = 1 }
		relation = { tag = SPR value = 1 }
		relation = { tag = SWE value = 1 }
		relation = { tag = SCH value = 1 }
		relation = { tag = TAN value = 1 }
		relation = { tag = TIB value = 1 }
		relation = { tag = TUR value = 1 }
		relation = { tag = U27 value = 50 }
		relation = { tag = URU value = 1 }
		relation = { tag = USA value = 15 }
		relation = { tag = VEN value = 1 }
		relation = { tag = YEM value = 1 }
		relation = { tag = YUG value = 1 }
	}


	SpyInfo = { country = "MLY" NumberOfSpies = 2 }
	SpyInfo = { country = "AST" NumberOfSpies = 2 }
	SpyInfo = { country = "CGX" NumberOfSpies = 2 }
	SpyInfo = { country = "CHI" NumberOfSpies = 2 }
	SpyInfo = { country = "CYN" NumberOfSpies = 2 }
	SpyInfo = { country = "ENG" NumberOfSpies = 4 }
	SpyInfo = { country = "FRA" NumberOfSpies = 2 }
	SpyInfo = { country = "HOL" NumberOfSpies = 4 }
	SpyInfo = { country = "IND" NumberOfSpies = 4 }
	SpyInfo = { country = "JAP" NumberOfSpies = 1 }
	SpyInfo = { country = "NEP" NumberOfSpies = 1 }
	SpyInfo = { country = "NZL" NumberOfSpies = 1 }
	SpyInfo = { country = "PER" NumberOfSpies = 1 }
	SpyInfo = { country = "PHI" NumberOfSpies = 1 }
	SpyInfo = { country = "POR" NumberOfSpies = 1 }
	SpyInfo = { country = "SIA" NumberOfSpies = 4 }

  nationalprovinces      = { 1349 1350 1351 1352 1647 1644 1353 }

  ownedprovinces         = { 1349 1350 1351 1352 }

  controlledprovinces    = { 1349 1350 1351 1352 }

  techapps               = { 8050 1010 1190 2450 5080 5090 6010 6030 14000 9010 }
  policy =
  { date              = { year = 0 month = january day = 0 }
	democratic		= 4
	political_left		= 3
	freedom 		= 6
	free_market 		= 5
	professional_army	= 6
	defense_lobby		= 1
	interventionism 	= 2
  }
  headofstate            = { type = 9 id = 565001 }
  headofgovernment       = { type = 9 id = 565002 }
  foreignminister        = { type = 9 id = 565003 }
  armamentminister       = { type = 9 id = 565004 }
  ministerofsecurity     = { type = 9 id = 565005 }
  ministerofintelligence = { type = 9 id = 565006 }
  chiefofstaff           = { type = 9 id = 565007 }
  chiefofarmy            = { type = 9 id = 565008 }
  chiefofnavy            = { type = 9 id = 565009 }
  chiefofair             = { type = 9 id = 565010 }
  nationalidentity = "policy_identity_imperial" 
	socialpolicy = "policy_social_ethnic" 
	nationalculture = "policy_culture_enterprise"
	province_development = { 
		id = { type = 11014 id = 1 } 
		name = "" 
		progress = 0.0000 
		location = 1352 
		cost = 2.0000 
		date = { 
			year = 1943 
			month = august 
			day = 29 
			hour = 0 
			} 
		manpower = 0.1000 
		close_when_finished = yes 
		waitingforclosure = no 
		total_progress = 0.0000 
		size = 28 
		done = 0 
		days = 2704 
		days_for_first = 120 
		gearing_bonus = 0.0000 
		type = infrastructure 
		} 
	province_development = { 
		id = { type = 11014 id = 2 } 
		name = "" 
		progress = 0.0000 
		location = 1349 
		cost = 2.0000 
		date = { 
			year = 1943 
			month = august 
			day = 29 
			hour = 0 
			} 
		manpower = 0.1000 
		close_when_finished = yes 
		waitingforclosure = no 
		total_progress = 0.0000 
		size = 28 
		done = 0 
		days = 2704 
		days_for_first = 120 
		gearing_bonus = 0.0000 
		type = infrastructure 
		} 
	province_development = { 
		id = { type = 11014 id = 3 }
		name = "" 
		progress = 0.0000 
		location = 1350 
		cost = 2.0000 
		date = { 
			year = 1943 
			month = august 
			day = 29 
			hour = 0 
			} 
		manpower = 0.1000 
		close_when_finished = yes 
		waitingforclosure = no 
		total_progress = 0.0000 
		size = 28 
		done = 0 
		days = 2704 
		days_for_first = 120 
		gearing_bonus = 0.0000 
		type = infrastructure 
		} 
	province_development = { 
		id = { type = 11014 id = 4 }
		name = "" 
		progress = 0.0000 
		location = 1351 
		cost = 2.0000 
		date = { 
			year = 1943 
			month = august 
			day = 29 
			hour = 0 
			} 
		manpower = 0.1000 
		close_when_finished = yes 
		waitingforclosure = no 
		total_progress = 0.0000 
		size = 28 
		done = 0 
		days = 2704 
		days_for_first = 120 
		gearing_bonus = 0.0000 
		type = infrastructure 
		} 
}

