#####################
# Country main data #
#####################

country =
{ tag                    = MAN
  puppet                 = JAP
  control                = JAP
  # Resource Reserves
  energy                 = 1000
  metal                  = 738
  rare_materials         = 278
  oil                    = 24
  supplies               = 1000
  money                  = 30
  transports		 = 28
  consumer = 0.1667 
  supply = 0.0834 
  production = 0.6666 
  reinforcement = 0.0833 
  upgrading = 0.0000 
  manpower               = 84.6 # 100 - building queue
  capital                = 1390

	diplomacy = {
		relation = { tag = AFG value = 1 }
		relation = { tag = ALB value = 1 }
		relation = { tag = ARG value = 1 }
		relation = { tag = AST value = -10 }
		relation = { tag = AUS value = 1 }
		relation = { tag = BEL value = 1 }
		relation = { tag = BHU value = 1 }
		relation = { tag = BOL value = 1 }
		relation = { tag = BRA value = 1 }
		relation = { tag = BUL value = 1 }
		relation = { tag = CAN value = -10 }
		relation = { tag = CGX value = -25 }
		relation = { tag = CHC value = -75 }
		relation = { tag = CHI value = -100 }
		relation = { tag = CHL value = 1 }
		relation = { tag = COL value = 1 }
		relation = { tag = COS value = 1 }
		relation = { tag = CSX value = -100 }
		relation = { tag = CUB value = 1 }
		relation = { tag = CXB value = -75 }
		relation = { tag = CYN value = -30 }
		relation = { tag = CZE value = 1 }
		relation = { tag = DEN value = 1 }
		relation = { tag = DOM value = 1 }
		relation = { tag = ECU value = 1 }
		relation = { tag = EGY value = 1 }
		relation = { tag = ENG value = 10 }
		relation = { tag = EST value = 1 }
		relation = { tag = ETH value = 1 }
		relation = { tag = FIN value = 1 }
		relation = { tag = FRA value = -15 }
		relation = { tag = GER value = 30 }
		relation = { tag = GRE value = 1 }
		relation = { tag = GUA value = 1 }
		relation = { tag = HAI value = 1 }
		relation = { tag = HOL value = 1 }
		relation = { tag = HON value = 1 }
		relation = { tag = HUN value = 1 }
		relation = { tag = IND value = 1 }
		relation = { tag = IRE value = 1 }
		relation = { tag = IRQ value = 1 }
		relation = { tag = ITA value = 25 }
		relation = { tag = JAP value = 175 }
		relation = { tag = LAT value = 1 }
		relation = { tag = LIB value = 1 }
		relation = { tag = LIT value = 1 }
		relation = { tag = LUX value = 1 }
		relation = { tag = MEX value = 1 }
		relation = { tag = MLY value = 1 }
		relation = { tag = MON value = -30 }
		relation = { tag = NEP value = 1 }
		relation = { tag = NIC value = 1 }
		relation = { tag = NOR value = 1 }
		relation = { tag = NZL value = -10 }
		relation = { tag = OMN value = 1 }
		relation = { tag = PAN value = 1 }
		relation = { tag = PAR value = 1 }
		relation = { tag = PER value = 1 }
		relation = { tag = PHI value = 1 }
		relation = { tag = POL value = 1 }
		relation = { tag = POR value = 1 }
		relation = { tag = PRU value = 1 }
		relation = { tag = ROM value = 1 }
		relation = { tag = SAF value = 1 }
		relation = { tag = SAL value = 1 }
		relation = { tag = SAU value = 1 }
		relation = { tag = SIA value = 1 }
		relation = { tag = SIK value = -20 }
		relation = { tag = SOV value = 20 }
		relation = { tag = SPA value = 1 }
		relation = { tag = SPR value = 1 }
		relation = { tag = SWE value = 1 }
		relation = { tag = SCH value = 30 }
		relation = { tag = TAN value = -20 }
		relation = { tag = TIB value = -20 }
		relation = { tag = TUR value = 1 }
		relation = { tag = U27 value = 1 }
		relation = { tag = URU value = 1 }
		relation = { tag = USA value = -15 }
		relation = { tag = VEN value = 1 }
		relation = { tag = YEM value = 1 }
		relation = { tag = YUG value = 1 }
	}

	SpyInfo = { country = "MAN" NumberOfSpies = 6 }
	SpyInfo = { country = "CGX" NumberOfSpies = 2 }
	SpyInfo = { country = "CHC" NumberOfSpies = 2 }
	SpyInfo = { country = "CHI" NumberOfSpies = 4 }
	SpyInfo = { country = "CSX" NumberOfSpies = 6 }
	SpyInfo = { country = "CXB" NumberOfSpies = 2 }
	SpyInfo = { country = "CYN" NumberOfSpies = 1 }
	SpyInfo = { country = "GER" NumberOfSpies = 1 }
	SpyInfo = { country = "IND" NumberOfSpies = 1 }
	SpyInfo = { country = "JAP" NumberOfSpies = 4 }
	SpyInfo = { country = "MON" NumberOfSpies = 4 }
	SpyInfo = { country = "SIK" NumberOfSpies = 1 }
	SpyInfo = { country = "SOV" NumberOfSpies = 2 }
	SpyInfo = { country = "SCH" NumberOfSpies = 1 }
	SpyInfo = { country = "TAN" NumberOfSpies = 1 }
	SpyInfo = { country = "TIB" NumberOfSpies = 1 }

  nationalprovinces      = { 1389 1390 1377 1378 1375 1374 1379 1530 1380 1387 1382 1381 1394 1395 1396 1388 1397 1202 }
  ownedprovinces         = { 1389 1390 1377 1378 1375 1374 1379 1530 1380 1387 1382 1381 1394 1395 1396 1388 1386 }
  controlledprovinces    = { 1389 1390 1377 1378 1375 1374 1379 1530 1380 1387 1382 1381 1394 1395 1396 1388 1386 }

  techapps               = { 1010 1020 1190 2290 4010 5080 6010 6030 }
  blueprints             = { 2300 2310 }

  policy =
  { date              = { year = 0 month = january day = 0 }
    democratic        = 1
    political_left    = 4
    freedom           = 3
    free_market       = 3
    professional_army = 3
    defense_lobby     = 8
    interventionism   = 8
  }

  headofstate            = { type = 9 id = 58001 }
  headofgovernment       = { type = 9 id = 58002 }
  foreignminister        = { type = 9 id = 58003 }
  armamentminister       = { type = 9 id = 58004 }
  ministerofsecurity     = { type = 9 id = 58005 }
  ministerofintelligence = { type = 9 id = 58006 }
  chiefofstaff           = { type = 9 id = 58007 }
  chiefofarmy            = { type = 9 id = 58008 }
  chiefofnavy            = { type = 9 id = 58009 }
  chiefofair             = { type = 9 id = 58010 }

  landunit =
  { location = 1389
    id       = { type = 28500 id = 1 }
    name     = "Di'1 Fang'tien Jüntuan"
    division =
    { id       = { type = 28500 id = 2 }
      name     = "7 Man'chu Lü"
      type     = militia
      strength = 90
    }
  }
  landunit =
  { location = 1382
    id       = { type = 28500 id = 3 }
    name     = "Di'3 Qiqihar Jüntuan"
    division =
    { id       = { type = 28500 id = 4 }
      name     = "9 Man'chu Lü"
      type     = militia
      strength = 75
    }
  }
  landunit =
  { location = 1379
    id       = { type = 28500 id = 5 }
    name     = "Di'4 Harbin Jüntuan"
    division =
    { id       = { type = 28500 id = 6 }
      name     = "10 Man'chu Lü"
      type     = militia
      strength = 15
    }
  }
  landunit =
  { location = 1374
    id       = { type = 28500 id = 7 }
    name     = "Di'5 Chengde Jüntuan"
    division =
    { id       = { type = 28500 id = 8 }
      name     = "12 Man'chu Lü"
      type     = militia
      strength = 45
    }
  }
  landunit =
  { location = 1389
    id       = { type = 28500 id = 9 }
    name     = "Di'2 Ji'lin Jüntuan"
    division =
    { id       = { type = 28500 id = 10 }
      name     = "8 Man'chu Lü"
      type     = militia
      strength = 60
    }
    division =
    { id       = { type = 28500 id = 11 }
      name     = "2 Man'chu Qi'Bing"
      type     = cavalry
      strength = 45
    }
  } 
	province_development = { 
		id = { type = 28500 id = 12 } 
		name = "" 
		progress = 0.0000 
		location = 1390 
		cost = 2.0000 
		date = { 
			year = 1941 
			month = september 
			day = 24 
			hour = 0 
			} 
		manpower = 0.1000 
		close_when_finished = yes 
		waitingforclosure = no 
		total_progress = 0.0000 
		size = 24 
		done = 0 
		days = 1953 
		days_for_first = 106 
		gearing_bonus = 0.0000 
		type = infrastructure 
		} 
	province_development = { 
		id = { type = 28500 id = 13 } 
		name = "" 
		progress = 0.0000 
		location = 1395 
		cost = 2.0000 
		date = { 
			year = 1941 
			month = september 
			day = 24 
			hour = 0 
			} 
		manpower = 0.1000 
		close_when_finished = yes 
		waitingforclosure = no 
		total_progress = 0.0000 
		size = 24 
		done = 0 
		days = 1953 
		days_for_first = 106 
		gearing_bonus = 0.0000 
		type = infrastructure 
		} 
	province_development = { 
		id = { type = 28500 id = 14 } 
		name = "" 
		progress = 0.0000 
		location = 1390 
		cost = 5.0000 
		date = { 
			year = 1937 
			month = october 
			day = 4 
			hour = 0 
			} 
		manpower = 1.0000 
		close_when_finished = yes 
		waitingforclosure = no 
		total_progress = 0.0000 
		size = 2 
		done = 0 
		days = 1267 
		days_for_first = 317 
		gearing_bonus = 0.0000 
		type = ic 
		} 
	province_development = { 
		id = { type = 28500 id = 15 } 
		name = "" 
		progress = 0.0000 
		location = 1389 
		cost = 5.0000 
		date = { 
			year = 1937 
			month = october 
			day = 4 
			hour = 0 
			} 
		manpower = 1.0000 
		close_when_finished = yes 
		waitingforclosure = no 
		total_progress = 0.0000 
		size = 2 
		done = 0 
		days = 634 
		days_for_first = 317 
		gearing_bonus = 0.0000 
		type = ic 
		} 
	province_development = { 
		id = { type = 28500 id = 16 } 
		name = "" 
		progress = 0.0000 
		location = 1389 
		cost = 2.0000 
		date = { 
			year = 1941 
			month = september 
			day = 24 
			hour = 0 
			} 
		manpower = 0.1000 
		close_when_finished = yes 
		waitingforclosure = no 
		total_progress = 0.0000 
		size = 24 
		done = 0 
		days = 1953 
		days_for_first = 106 
		gearing_bonus = 0.0000 
		type = infrastructure 
		} 
	division_development = { 
		id = { type = 28500 id = 17 } 
		name = "1 Man'chu Shi" 
		progress = 0.0000 
		location = 1390 
		cost = 7.8626 
		date = { 
			year = 1938 
			month = april 
			day = 29 
			hour = 0 
			} 
		manpower = 15.0000 
		close_when_finished = yes 
		waitingforclosure = no 
		retooling_time = 42.0000 
		total_progress = 0.0000 
		size = 12 
		done = 0 
		days = 795 
		days_for_first = 79 
		gearing_bonus = 0.0000 
		type = infantry 
		extra = artillery 
		extra1 = none 
		extra2 = none 
		extra3 = none 
		extra4 = none 
		model = 1 
		brigade_model = 0 
		brigade_model1 = 0 
		brigade_model2 = 0 
		brigade_model3 = 0 
		brigade_model4 = 0 
		} 
	province_development = { 
		id = { type = 28500 id = 18 } 
		name = "" 
		progress = 0.0000 
		location = 1394 
		cost = 2.0000 
		date = { 
			year = 1942 
			month = august 
			day = 28 
			hour = 0 
			} 
		manpower = 0.1000 
		close_when_finished = yes 
		waitingforclosure = no 
		total_progress = 0.0000 
		size = 28 
		done = 0 
		days = 2270 
		days_for_first = 106 
		gearing_bonus = 0.0000 
		type = infrastructure 
		} 
}