#####################
# Country main data #
#####################

country =
{ tag                    = MEX
  # Resource Reserves
  energy                 = 1000
  metal                  = 1000
  rare_materials         = 500
  oil                    = 500
  supplies               = 500
  money                  = 20
  free                   = { energy = 15 oil = -30 }
# Used oil to run the coal deficit

  consumer = 0.2500 
  supply = 0.0656 
  production = 0.6844 
  reinforcement = 0.0000 
  upgrading = 0.0000 
  capital                = 752
  manpower               = 3.6 # 60 - building queue
  transports             = 20
  policy =
  { date              = { year = 0 month = january day = 0 }
    democratic        = 8
    political_left    = 8
    freedom           = 6
    free_market       = 6
    professional_army = 4
    defense_lobby     = 4
    interventionism   = 3
  }
  nationalprovinces      = { 756 755 754 753 752 751 750 747 749 745 742 741 744 743 740 739 737 738 }
  ownedprovinces         = { 756 755 754 753 752 751 750 747 749 745 742 741 744 743 740 739 737 738 }
  controlledprovinces    = { 756 755 754 753 752 751 750 747 749 745 742 741 744 743 740 739 737 738 }
  # Semi-Major Tech '36
  # Group D 1936 techs
  # ######################
  # GW fighter
  techapps               = { 1010 1020 1110 1190  2290 2300 2310 2450 2460 2510 4010 5010 5080 5090 5190 6010 9010 }

	diplomacy = {
		relation = { tag = AFG value = 1 }
		relation = { tag = ALB value = 1 }
		relation = { tag = ARG value = 20 }
		relation = { tag = AST value = 20 }
		relation = { tag = AUS value = 15 }
		relation = { tag = BEL value = 20 }
		relation = { tag = BHU value = 1 }
		relation = { tag = BOL value = 15 }
		relation = { tag = BRA value = 30 }
		relation = { tag = BUL value = 10 }
		relation = { tag = CAN value = 30 }
		relation = { tag = CGX value = 1 }
		relation = { tag = CHC value = 1 }
		relation = { tag = CHI value = 30 }
		relation = { tag = CHL value = 15 }
		relation = { tag = COL value = 15 }
		relation = { tag = COS value = 20 }
		relation = { tag = CSX value = 1 }
		relation = { tag = CUB value = 30 }
		relation = { tag = CXB value = 1 }
		relation = { tag = CYN value = 1 }
		relation = { tag = CZE value = 20 }
		relation = { tag = DEN value = 15 }
		relation = { tag = DOM value = 20 }
		relation = { tag = ECU value = 20 }
		relation = { tag = EGY value = 1 }
		relation = { tag = ENG value = 40 }
		relation = { tag = EST value = 1 }
		relation = { tag = ETH value = 20 }
		relation = { tag = FIN value = 20 }
		relation = { tag = FRA value = 35 }
		relation = { tag = GER value = 30 }
		relation = { tag = GRE value = 10 }
		relation = { tag = GUA value = 30 }
		relation = { tag = HAI value = 30 }
		relation = { tag = HOL value = 20 }
		relation = { tag = HON value = 30 }
		relation = { tag = HUN value = 10 }
		relation = { tag = IND value = 1 }
		relation = { tag = IRE value = 35 }
		relation = { tag = IRQ value = 1 }
		relation = { tag = ITA value = 40 }
		relation = { tag = JAP value = 35 }
		relation = { tag = LAT value = 1 }
		relation = { tag = LIB value = 1 }
		relation = { tag = LIT value = 1 }
		relation = { tag = LUX value = 1 }
		relation = { tag = MAN value = 1 }
		relation = { tag = MLY value = 1 }
		relation = { tag = MON value = 1 }
		relation = { tag = NEP value = 1 }
		relation = { tag = NIC value = 30 }
		relation = { tag = NOR value = 1 }
		relation = { tag = NZL value = 20 }
		relation = { tag = OMN value = 1 }
		relation = { tag = PAN value = 30 }
		relation = { tag = PAR value = 10 }
		relation = { tag = PER value = 1 }
		relation = { tag = PHI value = 1 }
		relation = { tag = POL value = 25 }
		relation = { tag = POR value = 10 }
		relation = { tag = PRU value = 20 }
		relation = { tag = ROM value = 10 }
		relation = { tag = SAF value = 20 }
		relation = { tag = SAL value = 30 }
		relation = { tag = SAU value = 20 }
		relation = { tag = SIA value = 1 }
		relation = { tag = SIK value = 1 }
		relation = { tag = SOV value = 20 }
		relation = { tag = SPA value = 20 }
		relation = { tag = SPR value = 40 }
		relation = { tag = SWE value = 20 }
		relation = { tag = SCH value = 50 }
		relation = { tag = TAN value = 1 }
		relation = { tag = TIB value = 1 }
		relation = { tag = TUR value = 20 }
		relation = { tag = U27 value = 1 }
		relation = { tag = URU value = 10 }
		relation = { tag = USA value = 75 }
		relation = { tag = VEN value = 20 }
		relation = { tag = YEM value = 1 }
		relation = { tag = YUG value = 1 }
	}

	SpyInfo = { country = "MEX" NumberOfSpies = 3 }
	SpyInfo = { country = "ARG" NumberOfSpies = 1 }
	SpyInfo = { country = "BRA" NumberOfSpies = 1 }
	SpyInfo = { country = "CAN" NumberOfSpies = 1 }
	SpyInfo = { country = "COL" NumberOfSpies = 1 }
	SpyInfo = { country = "CUB" NumberOfSpies = 2 }
	SpyInfo = { country = "ENG" NumberOfSpies = 1 }
	SpyInfo = { country = "FRA" NumberOfSpies = 1 }
	SpyInfo = { country = "GER" NumberOfSpies = 1 }
	SpyInfo = { country = "GUA" NumberOfSpies = 4 }
	SpyInfo = { country = "HUN" NumberOfSpies = 1 }
	SpyInfo = { country = "NIC" NumberOfSpies = 1 }
	SpyInfo = { country = "PAN" NumberOfSpies = 1 }
	SpyInfo = { country = "SAL" NumberOfSpies = 1 }
	SpyInfo = { country = "SPR" NumberOfSpies = 1 }
	SpyInfo = { country = "SCH" NumberOfSpies = 1 }
	SpyInfo = { country = "USA" NumberOfSpies = 2 }
	SpyInfo = { country = "VEN" NumberOfSpies = 2 }
	SpyInfo = { country = "SPA" NumberOfSpies = 1 }

  headofstate            = { type = 9 id = 36001 }
  headofgovernment       = { type = 9 id = 36002 }
  foreignminister        = { type = 9 id = 36003 }
  armamentminister       = { type = 9 id = 36004 }
  ministerofsecurity     = { type = 9 id = 36005 }
  ministerofintelligence = { type = 9 id = 36006 }
  chiefofstaff           = { type = 9 id = 36007 }
  chiefofarmy            = { type = 9 id = 36008 }
  chiefofnavy            = { type = 9 id = 36009 }
  chiefofair             = { type = 9 id = 36010 }
  # Firepower
  landunit =
  { id       = { type = 29500 id = 1 }
    name     = "Ejercito de Mexico"
    location = 752
    division =
    { id       = { type = 29500 id = 2 }
      name     = "Guardia del Presidente"
      strength = 100
      type     = infantry
      model    = 1 # Special trained w. foreign eq.
    }
    division =
    { id       = { type = 29500 id = 3 }
      name     = "I División de Infantería"
      strength = 100
      type     = infantry
    }
    division =
    { id       = { type = 29500 id = 4 }
      name     = "II División de Infantería"
      strength = 100
      type     = infantry
    }
    division =
    { id       = { type = 29500 id = 5 }
      name     = "III División de Infantería"
      strength = 100
      type     = infantry
      extra    = artillery
    }
  }
  landunit =
  { id       = { type = 29500 id = 6 }
    name     = "Caballería de Mexico"
    location = 742
    division =
    { id       = { type = 29500 id = 7 }
      name     = "I División de Caballería"
      strength = 100
      type     = cavalry
    }
    division =
    { id       = { type = 29500 id = 8 }
      name     = "II División de Caballería"
      strength = 100
      type     = cavalry
    }
  }
  # navalunit = {
  # id = { type = 29500 id = 11 }
  # name = "Armada de Mexico"
  # location = 754
  # base = 754
  # division = { 
  # id = { type = 29500 id = 12 } 
  # name = "1a Flotilla de Destructores" 
  # type = destroyer 
  # model = 0 
  # }
  # }
  airunit =
  { id       = { type = 29500 id = 9 }
    name     = "Fuerza Aérea Mexicana"
    location = 754
    base     = 754
    division =
    { id       = { type = 29500 id = 10 }
      name     = "1a Grupo Aéreo de Caza"
      type     = interceptor
      model    = 0
      strength = 50
    }
  } 

#########################################################################
# Navy
#########################################################################

navalunit = {
	id = { type = 29500 id = 3000 }
	name = "Flota De Carribean"
	location = 755
	base = 755

	division = {
		id = { type = 29500 id = 3001 }
		name = "1a Flotilla de Destructores"
		type = destroyer
		model = 0
		extra = naval_anti_air_s
		brigade_model = 0
		}
	}

navalunit = {
	id = { type = 29500 id = 3003 }
	name = "Flota Pacífica"
	location = 754
	base = 754

	division = {
		id = { type = 29500 id = 3004 }
		name = "2a Flotilla de Destructores"
		type = destroyer
		strength = 70
		max_strength = 70
		model = 0
		extra = naval_anti_air_s
		brigade_model = 0
		}
	}

	division_development = { 
		id = { type = 29500 id = 20 } 
		name = "IV División de Infantería" 
		progress = 0.0000 
		location = 752 
		cost = 8.0851 
		date = { 
			year = 1939 
			month = december 
			day = 5 
			hour = 0 
			} 
		manpower = 13.0000 
		close_when_finished = yes 
		waitingforclosure = no 
		retooling_time = 72.0000 
		total_progress = 0.0000 
		size = 20 
		done = 0 
		days = 1344 
		days_for_first = 82 
		gearing_bonus = 0.0000 
		type = infantry 
		extra = armored_car 
		extra1 = none 
		extra2 = none 
		extra3 = none 
		extra4 = none 
		model = 1 
		brigade_model = 0 
		brigade_model1 = 0 
		brigade_model2 = 0 
		brigade_model3 = 0 
		brigade_model4 = 0 
		} 
	province_development = { 
		id = { type = 29500 id = 19 } 
		name = "" 
		progress = 0.0000 
		location = 752 
		cost = 5.0000 
		date = { 
			year = 1939 
			month = november 
			day = 4 
			hour = 0 
			} 
		manpower = 1.0000 
		close_when_finished = yes 
		waitingforclosure = no 
		total_progress = 0.0000 
		size = 4 
		done = 0 
		days = 1382 
		days_for_first = 346 
		gearing_bonus = 0.0000 
		type = ic 
		} 
	province_development = { 
		id = { type = 29500 id = 13 } 
		name = "" 
		progress = 0.0000 
		location = 752 #Mexico city
		cost = 2.0000 
		date = { 
			year = 1941 
			month = february 
			day = 17 
			hour = 0 
			} 
		manpower = 0.1000 
		close_when_finished = yes 
		waitingforclosure = no 
		total_progress = 0.0000 
		size = 28 
		done = 0 
		days = 2617 
		days_for_first = 115 
		gearing_bonus = 0.0000 
		speed_step = 1 
		type = infrastructure 
		} 
	province_development = { 
		id = { type = 29500 id = 17 } 
		name = "" 
		progress = 0.0000 
		location = 755 #37 oil prov
		cost = 2.0000 
		date = { 
			year = 1958 
			month = april 
			day = 26 
			hour = 0 
			} 
		manpower = 0.1000 
		close_when_finished = yes 
		waitingforclosure = no 
		total_progress = 0.0000 
		size = 28 
		done = 0 
		days = 2617 
		days_for_first = 287 
		gearing_bonus = 0.0000 
		type = infrastructure
 		speed_step = 1 
		} 

	province_development = { 
		id = { type = 29500 id = 16 } 
		name = "" 
		progress = 0.0000 
		location = 749 #Tampico
		cost = 2.0000 
		date = { 
			year = 1944 
			month = december 
			day = 10 
			hour = 0 
			} 
		manpower = 0.1000 
		close_when_finished = yes 
		waitingforclosure = no 
		total_progress = 0.0000 
		size = 28 
		done = 0 
		days = 2617 
		days_for_first = 115 
		gearing_bonus = 0.0000 
		type = infrastructure 
		} 
	province_development = { 
		id = { type = 29500 id = 15 } 
		name = "" 
		progress = 0.0000 
		location = 753 #Puebla
		cost = 2.0000 
		date = { 
			year = 1958 
			month = april 
			day = 26 
			hour = 0 
			} 
		manpower = 0.1000 
		close_when_finished = yes 
		waitingforclosure = no 
		total_progress = 0.0000 
		size = 28 
		done = 0 
		days = 2617 
		days_for_first = 287 
		gearing_bonus = 0.0000 
		type = infrastructure 
		} 
	province_development = { 
		id = { type = 29500 id = 18 } 
		name = "" 
		progress = 0.0000 
		location = 747 #Monterrey
		cost = 2.0000 
		date = { 
			year = 1958 
			month = april 
			day = 26 
			hour = 0 
			} 
		manpower = 0.1000 
		close_when_finished = yes 
		waitingforclosure = no 
		total_progress = 0.0000 
		size = 28 
		done = 0 
		days = 2617 
		days_for_first = 287 
		gearing_bonus = 0.0000 
		type = infrastructure 
		} 
}
