#####################
# Country main data #
#####################

country =
{ tag                    = CHI
  capital                = 1235 # Nanjing
  # Resource Reserves
  energy                 = 3041
  metal                  = 1362
  rare_materials         = 1320
  oil                    = 24
  supplies               = 5082
  money                  = 10
  consumer = 0.0000 
  supply = 0.0000 
  production = 0.9090 
  reinforcement = 0.0910 
  upgrading = 0.0000 
  manpower = 2569.8000   # 3600 - building queue -1000
  dissent                = 15
  transports             = 68
  escorts                = 6

	diplomacy = {
		relation = { tag = AFG value = 15 }
		relation = { tag = ALB value = 1 }
		relation = { tag = ARG value = 15 }
		relation = { tag = AST value = 35 }
		relation = { tag = AUS value = 20 }
		relation = { tag = BEL value = 25 }
		relation = { tag = BHU value = 5 }
		relation = { tag = BOL value = 1 }
		relation = { tag = BRA value = 1 }
		relation = { tag = BUL value = 10 }
		relation = { tag = CAN value = 30 }
		relation = { tag = CGX value = 1 }
		relation = { tag = CHC value = -75 }
		relation = { tag = CHL value = 15 }
		relation = { tag = COL value = 15 }
		relation = { tag = COS value = 1 }
		relation = { tag = CSX value = 50 access = yes }
		relation = { tag = CUB value = 5 }
		relation = { tag = CXB value = 175 access = yes }
		relation = { tag = CYN value = 45 }
		relation = { tag = CZE value = 15 }
		relation = { tag = DEN value = 10 }
		relation = { tag = DOM value = 1 }
		relation = { tag = ECU value = 15 }
		relation = { tag = EGY value = 1 }
		relation = { tag = ENG value = 35 }
		relation = { tag = EST value = 1 }
		relation = { tag = ETH value = 1 }
		relation = { tag = FIN value = 5 }
		relation = { tag = FRA value = 40 }
		relation = { tag = GER value = 50 }
		relation = { tag = GRE value = 1 }
		relation = { tag = GUA value = 1 }
		relation = { tag = HAI value = 1 }
		relation = { tag = HOL value = 30 }
		relation = { tag = HON value = 1 }
		relation = { tag = HUN value = 10 }
		relation = { tag = IND value = 5 }
		relation = { tag = IRE value = 1 }
		relation = { tag = IRQ value = 1 }
		relation = { tag = ITA value = 40 }
		relation = { tag = JAP value = -30 }
		relation = { tag = LAT value = 1 }
		relation = { tag = LIB value = 1 }
		relation = { tag = LIT value = 1 }
		relation = { tag = LUX value = 1 }
		relation = { tag = MAN value = -100 }
		relation = { tag = MEX value = 30 }
		relation = { tag = MLY value = 30 }
		relation = { tag = MON value = -25 }
		relation = { tag = NEP value = -10 }
		relation = { tag = NIC value = 1 }
		relation = { tag = NOR value = 1 }
		relation = { tag = NZL value = 25 }
		relation = { tag = OMN value = 5 }
		relation = { tag = PAN value = 5 }
		relation = { tag = PAR value = 1 }
		relation = { tag = PER value = 25 }
		relation = { tag = PHI value = 20 }
		relation = { tag = POL value = 5 }
		relation = { tag = POR value = 35 }
		relation = { tag = PRU value = 25 }
		relation = { tag = ROM value = 15 }
		relation = { tag = SAF value = 10 }
		relation = { tag = SAL value = 1 }
		relation = { tag = SAU value = 15 }
		relation = { tag = SIA value = 25 }
		relation = { tag = SIK value = 40 }
		relation = { tag = SOV value = 40 }
		relation = { tag = SPA value = 1 }
		relation = { tag = SPR value = 1 }
		relation = { tag = SWE value = 10 }
		relation = { tag = SCH value = 50 }
		relation = { tag = TAN value = -25 }
		relation = { tag = TIB value = 25 }
		relation = { tag = TUR value = 20 }
		relation = { tag = U27 value = 1 }
		relation = { tag = URU value = 1 }
		relation = { tag = USA value = 75 }
		relation = { tag = VEN value = 30 }
		relation = { tag = YEM value = 1 }
		relation = { tag = YUG value = 10 }
	}

	SpyInfo = { country = "CHI" NumberOfSpies = 5 }
	SpyInfo = { country = "AST" NumberOfSpies = 1 }
	SpyInfo = { country = "CGX" NumberOfSpies = 6 }
	SpyInfo = { country = "CHC" NumberOfSpies = 4 }
	SpyInfo = { country = "CSX" NumberOfSpies = 6 }
	SpyInfo = { country = "CXB" NumberOfSpies = 8 }
	SpyInfo = { country = "CYN" NumberOfSpies = 4 }
	SpyInfo = { country = "ENG" NumberOfSpies = 2 }
	SpyInfo = { country = "FRA" NumberOfSpies = 2 }
	SpyInfo = { country = "GER" NumberOfSpies = 1 }
	SpyInfo = { country = "HOL" NumberOfSpies = 1 }
	SpyInfo = { country = "IND" NumberOfSpies = 2 }
	SpyInfo = { country = "ITA" NumberOfSpies = 1 }
	SpyInfo = { country = "JAP" NumberOfSpies = 2 }
	SpyInfo = { country = "MAN" NumberOfSpies = 4 }
	SpyInfo = { country = "MLY" NumberOfSpies = 2 }
	SpyInfo = { country = "MON" NumberOfSpies = 4 }
	SpyInfo = { country = "NEP" NumberOfSpies = 1 }
	SpyInfo = { country = "NZL" NumberOfSpies = 1 }
	SpyInfo = { country = "PHI" NumberOfSpies = 2 }
	SpyInfo = { country = "POR" NumberOfSpies = 1 }
	SpyInfo = { country = "SAF" NumberOfSpies = 1 }
	SpyInfo = { country = "SIA" NumberOfSpies = 3 }
	SpyInfo = { country = "SIK" NumberOfSpies = 4 }
	SpyInfo = { country = "SOV" NumberOfSpies = 2 }
	SpyInfo = { country = "SCH" NumberOfSpies = 1 }
	SpyInfo = { country = "TAN" NumberOfSpies = 4 }
	SpyInfo = { country = "TIB" NumberOfSpies = 4 }
	SpyInfo = { country = "USA" NumberOfSpies = 2 }

  # Fujian		
  nationalprovinces      = { 1275 1276 1277 1440 1441 1267 1268 1269 1270 1271 1278 1222 1223 1224 1227 1228 1229 1230 1273 1274 1439 1207 1208 1272
                             1209 1225 1226 1203 1204 1205 1206 1210 1211 1212 1213 1214 1215 1216 1386 1398 1388 1397 1202 1377 1387 1389 1390 1394
                             1395 1396 1374 1375 1378 1379 1380 1381 1382 1530 1218 1221 1233 1234 1217 1219 1220 1235 1236 1237 1263 1265 1279 1280
                             1360 1361 1231 1232 1253 1264 1266 1238 1239 1240 1241 1262 1363 1364 1365 1255 1256 1257 1259 1260 1261 1242 1250 1251
                             1252 1254 1243 1244 1245 1246 1247 1293 1294 1305 1307 1308 1327 1362 1281 1282 1283 1448 1450 1451 1452 1453 1442 1443
                             1444 1421 1430 1431 1432 1433 1435 1445 1446 1447 1258 1309 1310 1311 1319 1325 1248 1249 1312 1313 1314 1317 1318 1320
                             1321 1322 1323 1324 1385 1399 1404 1419 1420 1434 1436 1437 1438
                           }
  ownedprovinces         = { 1204 1205 1206 1210 1211 1212 1213 1216 1281 1276 1277 1267 1268 1269 1278 1222 1223 1224 1227 1228 1229 1230 1214 1215 1218 1221 1233 1234 1217 1219 1220 1235 1236
                             1237 1263 1265 1279 1280 1360 1361 1231 1232 1253 1264 1266 1238 1239 1240 1241 1262 1363 1364 1365 1255 1256 1257 1259
                             1260 1261 1242 1250 1251 1252 1254 1243 1244 1245 1246 1247
                           }
  # Fujian		
  controlledprovinces    = { 1204 1205 1206 1210 1211 1212 1213 1216 1281 1276 1277 1267 1268 1269 1278 1222 1223 1224 1227 1228 1229 1230 1214 1215 1218 1221 1233 1234 1217 1219 1220 1235 1236
                             1237 1263 1265 1279 1280 1360 1361 1231 1232 1253 1264 1266 1238 1239 1240 1241 1262 1363 1364 1365 1255 1256 1257 1259
                             1260 1261 1242 1250 1251 1252 1254 1243 1244 1245 1246 1247
                           }
  # ROTW Minor Tech '36
  # Group E 1936 techs
  # ######################
  # GW fighter
  techapps               = { 1010 1190 2290 3010 3070 4010 5080 5090 8050 9010 6210 1020 } # German Mission
  blueprints             = { 1310 2300 2310 2320 1200 1210 1220 6300 1110 4120 2400 2450 } # German Mission+Soviet advisors
  policy =
  { date              = { year = 0 month = january day = 0 }
    democratic        = 3
    political_left    = 4
    free_market       = 9
    freedom           = 4
    professional_army = 4
    defense_lobby     = 9
    interventionism   = 8
  }
  headofstate            = { type = 9 id = 52001 }
  headofgovernment       = { type = 9 id = 52002 }
  foreignminister        = { type = 9 id = 52003 }
  armamentminister       = { type = 9 id = 52004 }
  ministerofsecurity     = { type = 9 id = 52005 }
  ministerofintelligence = { type = 9 id = 52006 }
  chiefofstaff           = { type = 9 id = 52007 }
  chiefofarmy            = { type = 9 id = 52008 }
  chiefofnavy            = { type = 9 id = 52009 }
  chiefofair             = { type = 9 id = 52010 }
  dormant_leaders        = { 50370 50377 }

  nationalidentity = "policy_identity_parochial" 
	socialpolicy = "policy_social_conformism" 
	nationalculture = "policy_culture_enterprise"

###########################################
# Land OOB
###########################################

landunit = {
	id = { type = 22000 id = 1001 }
	name = "1. Jun"
	location = 1276 #Lanzhou

	division = {
		id = { type = 22000 id = 1002 }
		name = "1. Jun"
		type = infantry
		model = 0
		experience = 5
	}
}

landunit = {
	id = { type = 22000 id = 1003 }
	name = "7. Jun"
	location = 1269 #Xi'an
	leader = 50082 #Zeng Wanzhong

	division = {
		id = { type = 22000 id = 1004 }
		name = "7. Jun"
		type = infantry
		model = 0
		experience = 5
	}
}

landunit = {
	id = { type = 22000 id = 1005 }
	name = "14. Jun"
	location = 1244 #Fuzhou
	leader = 50329 #Wei Lihuang

	division = {
		id = { type = 22000 id = 1006 }
		name = "14. Jun"
		type = infantry
		model = 0
		experience = 5
	}
}

landunit = {
	id = { type = 22000 id = 1007 }
	name = "22. Jun"
	location = 1254 #Pingxiang

	division = {
		id = { type = 22000 id = 1008 }
		name = "22. Jun"
		type = infantry
		model = 0
		experience = 5
	}
}

landunit = {
	id = { type = 22000 id = 1009 }
	name = "27. Jun"
	location = 1254 #Pingxiang
	leader = 50208 #Liu Xing

	division = {
		id = { type = 22000 id = 1010 }
		name = "27. Jun"
		type = infantry
		model = 0
		experience = 5
	}
}

landunit = {
	id = { type = 22000 id = 1011 }
	name = "30. Jun"
	location = 1227 # Luoyang
	leader = 50266 # Sun Lianzhong

	division = {
		id = { type = 22000 id = 1012 }
		name = "30. Jun"
		type = infantry
		model = 0
		experience = 5
	}
}

landunit = {
	id = { type = 22000 id = 1013 }
	name = "37. Jun"
	location = 1269 # Xi'an
	leader = 50241 # Mao Pingwen

	division = {
		id = { type = 22000 id = 1014 }
		name = "37. Jun"
		type = infantry
		model = 0
		experience = 5
	}
}

landunit = {
	location = 1278 # Baoji
	name = "38. Jun"
	leader = 50270 # Sun Weiru
	id = { type = 22000 id = 1015 }

	division = {
		id = { type = 22000 id = 1016 }
		name = "38. Jun"
		type = infantry
		model = 0
		experience = 5
	}
}

landunit = {
	location = 1240 # Wenzhou
	name = "39. Jun"
	leader = 50206 # Liu Heding
	id = { type = 22000 id = 1017 }

	division = {
		id = { type = 22000 id = 1018 }
		name = "39. Jun"
		type = infantry
		model = 0
		experience = 5
	}
}

landunit = {
	location = 1224 # Anyang
	name = "40. Jun"
	leader = 50250 # Pang Bingxun
	id = { type = 22000 id = 1019 }

	division = {
		id = { type = 22000 id = 1020 }
		name = "40. Jun"
		type = infantry
		model = 0
		experience = 5
	}
}

landunit = {
	location = 1269 # Xi'an
	name = "46. Jun"
	id = { type = 22000 id = 1021 }

	division = {
		id = { type = 22000 id = 1022 }
		name = "46. Jun"
		type = infantry
		model = 0
		experience = 5
	}
}

landunit = {
	location = 1269 # Xi'an
	name = "51. Jun"
	leader = 50010 # Yu Xuezhong (Zhang Xuezhong substituted)
	id = { type = 22000 id = 1023 }

	division = {
		id = { type = 22000 id = 1024 }
		name = "51. Jun"
		type = infantry
		model = 0
		experience = 5
	}
}

landunit = {
	location = 1269 # Xi'an
	name = "57. Jun"
	id = { type = 22000 id = 1025 }

	division = {
		id = { type = 22000 id = 1026 }
		name = "57. Jun"
		type = infantry
		model = 0
		experience = 5
	}
}

landunit = {
	location = 1269 # Xi'an
	name = "67. Jun"
	leader = 50319 # Wang Yizhe
	id = { type = 22000 id = 1027 }

	division = {
		id = { type = 22000 id = 1028 }
		name = "67. Jun"
		type = infantry
		model = 0
		experience = 5
	}
}

landunit = {
	location = 1276 # Lanzhou
	name = "1. Xin Jun"
	leader = 50285 # Deng Baoshan
	id = { type = 22000 id = 1029 }

	division = {
		id = { type = 22000 id = 1030 }
		name = "1. Xin Jun"
		type = infantry
		model = 0
		experience = 5
	}
}

landunit = {
	location = 1269 # Xi'an
	name = "4. Lujun"
	leader = 50340 # Yang Hucheng
	id = { type = 22000 id = 1033 }

	division = {
		id = { type = 22000 id = 1034 }
		name = "4. Lujun"
		type = infantry
		model = 0
		experience = 5
	}
}

landunit = {
	location = 1251 # Nanchang
	name = "20. Lujun"
	leader = 50007 # Zhang Fang
	id = { type = 22000 id = 1035 }

	division = {
		id = { type = 22000 id = 1036 }
		name = "20. Lujun"
		type = infantry
		model = 0
		experience = 5
	}
}

landunit = {
	location = 1220 # Yangzhou
	name = "26. Lujun"
	id = { type = 22000 id = 1037 }

	division = {
		id = { type = 22000 id = 7038 }
		name = "26. Lujun"
		type = infantry
		model = 0
		experience = 5
	}
}

landunit = {
	location = 1241 # Quzhou
	name = "2. Bubing Shi"
	leader = 50043 # Zheng Dongguo
	id = { type = 22000 id = 1039 }

	division = {
		id = { type = 22000 id = 1040 }
		name = "2. Bubing Shi"
		type = infantry
		strength = 80
		model = 0
		experience = 5
	}
}

landunit = {
	location = 1238 # Hangzhou
	name = "21. Bubing Shi"
	leader = 50176 # Li Xianzhou
	id = { type = 22000 id = 1041 }

	division = {
		id = { type = 22000 id = 1042 }
		name = "21. Bubing Shi"
		type = infantry
		strength = 50
		model = 0
		experience = 5
	}
}

landunit = {
	location = 1231 # Xiangfan
	name = "Jiangxi Silingbu"
	id = { type = 22000 id = 1045 }

	division = {
		id = { type = 22000 id = 1046 }
		name = "Jiangxi Silingbu"
		type = militia
		model = 0
	}
}

landunit = {
	location = 1244 # Fuzhou
	name = "Fujian Silingbu"
	id = { type = 22000 id = 1047 }

	division = {
		id = { type = 22000 id = 1048 }
		name = "Fujian Silingbu"
		type = militia
		model = 0
	}
}

landunit = {
	location = 1222 # Fuyang
	name = "Anhui Silingbu"
	id = { type = 22000 id = 1049 }

	division = {
		id = { type = 22000 id = 1050 }
		name = "Anhui Silingbu"
		type = militia
		model = 0
	}
}

landunit = {
	location = 1223 # Kaifeng
	name = "Henan Silingbu"
	id = { type = 22000 id = 1051 }

	division = {
		id = { type = 22000 id = 1052 }
		name = "Henan Silingbu"
		type = militia
		model = 0
	}
}

landunit = {
	location = 1232 # Hankou
	name = "Hubei Silingbu"
	id = { type = 22000 id = 1053 }

	division = {
		id = { type = 22000 id = 1054 }
		name = "Hubei Silingbu"
		type = militia
		model = 0
	}
}

landunit = {
	location = 1232 # Hankou
	name = "Xibei Silingbu"
	id = { type = 22000 id = 1055 }

	division = {
		id = { type = 22000 id = 1056 }
		name = "Xibei Silingbu"
		type = militia
		model = 0
	}
}

landunit = {
	location = 1235 # Nanjing
	name = "Jiaodao Zongdui"
	leader = 50156 # Gui Yongqing
	id = { type = 22000 id = 1057 }

	division = {
		id = { type = 22000 id = 1058 }
		name = "Jiaodao Zongdui"
		type = militia
		model = 0
	}
}

landunit = {
	location = 1217 # Lianyungang
	name = "Suijing Zongtuan"
	leader = 50125 # Huang Jie
	id = { type = 22000 id = 1059 }

	division = {
		id = { type = 22000 id = 1060 }
		name = "Customs Police 1st Detachment"
		type = militia
	model = 0
	}
	division = {
		id = { type = 22000 id = 1061 }
		name = "Customs Police 2nd Detachment"
		type = militia
		model = 0
	}
}

landunit = {
	location = 1237 # Shanghai
	name = "Shanghai Jingbei"
	leader = 50339 # Yang Hu
	id = { type = 22000 id = 1062 }

	division = {
		id = { type = 22000 id = 1063 }
		name = "Shanghai Jingbei"
		type = militia
		model = 0
	}
}

landunit = {
	location = 1237 # Ningbo
	name = "Marine Brigade"
	id = { type = 22000 id = 1064 }

	division = {
		id = { type = 22000 id = 1065 }
		name = "Marine Brigade"
		type = militia
		model = 0
	}
}

landunit = {
	location = 1235 # Nanjing
	name = "Jiangsu Baoantui"
	id = { type = 22000 id = 1066 }

	division = {
		id = { type = 22000 id = 1067 }
		name = "Jiangsu Baoantui"
		type = militia
		model = 0
	}
}

landunit = {
	location = 1233 # Anqing
	name = "Anhui Baoantui"
	id = { type = 22000 id = 1068 }

	division = {
		id = { type = 22000 id = 1069 }
		name = "Anhui Baoantui"
		type = militia
		model = 0
	}
}

landunit = {
	location = 1238 # Hangzhou
	name = "Zhejiang Baoantui"
	id = { type = 22000 id = 1070 }

	division = {
		id = { type = 22000 id = 1071 }
		name = "Zhejiang Baoantui"
		type = militia
		model = 0
	}
}

landunit = {
	location = 1255 # Changsha
	name = "Hunan Baoantui"
	id = { type = 22000 id = 1072 }

	division = {
		id = { type = 22000 id = 1073 }
		name = "Hunan Baoantui"
		type = militia
		model = 0
	}
}

landunit = {
	location = 1253 # Wuchang
	name = "Hubei Baoantui"
	id = { type = 22000 id = 1074 }

	division = {
		id = { type = 22000 id = 1075 }
		name = "Hubei Baoantui"
		type = militia
		model = 0
	}
}

landunit = {
	location = 1223 # Kaifeng
	name = "Henan Baoantui"
	id = { type = 22000 id = 1076 }

	division = {
		id = { type = 22000 id = 1077 }
		name = "Henan Baoantui"
		type = militia
		model = 0
	}
}

landunit = {
	location = 1276 # Lanzhou
	name = "Gansu Baoantui"
	id = { type = 22000 id = 268 }

	division = {
		id = { type = 22000 id = 1078 }
		name = "Gansu Baoantui"
		type = militia
		model = 0
	}
}

landunit = {
	location = 1251 # Nanchang
	name = "Jiangxi Baoantui"
	id = { type = 22000 id = 1079 }

	division = {
		id = { type = 22000 id = 1080 }
		name = "Jiangxi Baoantui"
		type = militia
		model = 0
	}
}

landunit = {
	location = 1244 # Fuzhou
	name = "Fujian Baoantui"
	id = { type = 22000 id = 1081 }

	division = {
		id = { type = 22000 id = 1082 }
		name = "Fujian Baoantui"
		type = militia
		model = 0
	}
}

landunit = {
	location = 1235 # Nanjing
	name = "KMT HQ"
	leader = 50048 # Chiang Kai Shek
	id = { type = 22000 id = 1083 }

	division = {
		id = { type = 22000 id = 1084 }
		name = "KMT HQ"
		type = hq
		model = 0
		experience = 20
	}
	dig_in = 20.000 
}

# German trained divisions

landunit = {
	location = 1235 # Nanjing
	name = "3. Bubing Shi"
	id = { type = 22000 id = 1100 }

	division = {
		id = { type = 22000 id = 1101 }
		name = "3. Bubing Shi"
		type = infantry
		model = 1
		experience = 10
      		extra         = armored_car
      		brigade_model = 0
	}
}

landunit = {
	location = 1235 # Nanjing
	name = "6. Bubing Shi"
	id = { type = 22000 id = 1102 }

	division = {
		id = { type = 22000 id = 1103 }
		name = "6. Bubing Shi"
		type = infantry
		model = 1
		experience = 10
      		extra         = engineer
      		brigade_model = 0
	}
}

landunit = {
	location = 1236 # Suzhou
	name = "9. Bubing Shi"
	id = { type = 22000 id = 1104 }

	division = {
		id = { type = 22000 id = 1105 }
		name = "9. Bubing Shi"
		type = infantry
		model = 1
		experience = 10
      		extra         = anti_tank
      		brigade_model = 0
	}
}

landunit = {
	location = 1237 # Shanghai
	name = "14. Bubing Shi"
	id = { type = 22000 id = 1106 }

	division = {
		id = { type = 22000 id = 1107 }
		name = "14. Bubing Shi"
		type = infantry
		model = 1
		experience = 10
      		extra         = anti_air
      		brigade_model = 0
	}
}

landunit = {
	location = 1221 # Hefei
	name = "36. Bubing Shi"
	id = { type = 22000 id = 1108 }

	division = {
		id = { type = 22000 id = 1109 }
		name = "36. Bubing Shi"
		type = infantry
		model = 1
		experience = 10
      		extra         = artillery
      		brigade_model = 0
	}
}

landunit = {
	location = 1234 # Wuhu
	name = "87. Bubing Shi"
	id = { type = 22000 id = 1110 }

	division = {
		id = { type = 22000 id = 1111 }
		name = "87. Bubing Shi"
		type = infantry
		model = 1
		experience = 10
      		extra         = artillery
      		brigade_model = 0
	}
}

landunit = {
	location = 1239 # Ningpo
	name = "88. Bubing Shi"
	id = { type = 22000 id = 1112 }

	division = {
		id = { type = 22000 id = 1113 }
		name = "88. Bubing Shi"
		type = infantry
		model = 1
		experience = 10
      		extra         = artillery
      		brigade_model = 0
	}
}

landunit = {
	location = 1235 # Nanjing
	name = "Bubing Shi"
	id = { type = 22000 id = 1114 }

	division = {
		id = { type = 22000 id = 1115 }
		name = "Training Division"
		type = infantry
		model = 1
		experience = 10
	}
}

  # #####################################
  # China 1936 Naval OOB  ###############
  # #####################################
  navalunit =
  { location = 1237 # Shanghai
    base     = 1237
    name     = "1st Fleet"
    id       = { type = 22000 id = 87 }
    division =
    { id    = { type = 22000 id = 88 }
      name  = "Ninghai"
      type  = light_cruiser
      model = 1
      extra1 = naval_anti_air_s
      extra2 = naval_spotter_s
      brigade_model1 = 0
      brigade_model2 = 0
    }
    division =
    { id    = { type = 22000 id = 300 }
      name  = "Pinghai"
      type  = light_cruiser
      model = 1
      extra1 = naval_anti_air_s
      extra2 = none
      brigade_model1 = 0
      brigade_model2 = 0
    }
    division =
    { id    = { type = 22000 id = 89 }
      name  = "Yingrui"
      type  = light_cruiser
      model = 0
      extra1 = naval_fire_controll_s
      extra2 = none
      brigade_model1 = 0
      brigade_model2 = 0
    }
    division =
    { id    = { type = 22000 id = 90 }
      name  = "Zhaohe"
      type  = light_cruiser
      model = 0
      extra1 = naval_fire_controll_s
      extra2 = none
      brigade_model1 = 0
      brigade_model2 = 0
    }
    division =
    { id    = { type = 22000 id = 91 }
      name  = "Haichen"
      type  = light_cruiser
      model = 0
      extra1 = naval_fire_controll_s
      extra2 = none
      brigade_model1 = 0
      brigade_model2 = 0
      max_strength = 75
      strength     = 75
    }
    division =
    { id    = { type = 22000 id = 301 }
      name  = "Hairong"
      type  = light_cruiser
      model = 0
      extra1 = naval_fire_controll_s
      extra2 = none
      brigade_model1 = 0
      brigade_model2 = 0
      max_strength = 75
      strength     = 75
    }
    division =
    { id    = { type = 22000 id = 302 }
      name  = "Haichou"
      type  = light_cruiser
      model = 0
      extra1 = naval_fire_controll_s
      extra2 = none
      brigade_model1 = 0
      brigade_model2 = 0
      max_strength = 75
      strength     = 75
    }
    division =
    { id    = { type = 22000 id = 303 }
      name  = "Tongji"
      type  = light_cruiser
      model = 0
      extra1 = naval_anti_air_s
      extra2 = none
      brigade_model1 = 0
      brigade_model2 = 0
      max_strength = 50
      strength     = 50
    }
    division =
    { id    = { type = 22000 id = 304 }
      name  = "Haiqi"
      type  = light_cruiser
      model = 0
      max_strength = 25
      strength     = 25
    }
    division =
    { id    = { type = 22000 id = 92 }
      name  = "1. Quzujian Dadui"
      type  = destroyer
      model = 0
    }
    division =
    { id    = { type = 22000 id = 93 }
      name  = "2. Quzujian Dadui"
      type  = destroyer
      model = 0
    }
    division =
    { id    = { type = 22000 id = 94 }
      name  = "1. Yunshujian Dadui"
      type  = transport
      model = 0
    }
  }
  # ###############################
  # China 1936 Airforce OOB  ######
  # ###############################
  airunit =
  { location = 1251 # Nanchang
    id       = { type = 22000 id = 95 }
    name     = "1. Kongjun"
    base     = 1251 # Nanchang
    division =
    { id           = { type = 22000 id = 96 }
      name         = "1. Kongjun"
      #max_strength = 60
      strength     = 54
      type         = tactical_bomber
      model        = 0
    }
  }
  airunit =
  { location = 1251 # Nanchang
    id       = { type = 22000 id = 97 }
    name     = "2. Kongjun"
    base     = 1251 # Nanchang
    division =
    { id           = { type = 22000 id = 98 }
      name         = "2. Kongjun"
      #max_strength = 60
      strength     = 52
      type         = interceptor
      model        = 0
    }
  } 

	province_development = { 
		id = { type = 22000 id = 201 } 
		name = "" 
		progress = 0.0000 
		location = 1280 
		cost = 2.0000 
		date = { 
			year = 1939 
			month = september 
			day = 20 
			hour = 0 
			} 
		manpower = 0.1000 
		close_when_finished = yes 
		waitingforclosure = no 
		total_progress = 0.0000 
		size = 30 
		done = 0 
		days = 1884 
		days_for_first = 78 
		gearing_bonus = 0.0000 
		speed_step = 1 
		type = infrastructure 
		} 
	province_development = { 
		id = { type = 22000 id = 202 } 
		name = "" 
		progress = 0.0000 
		location = 1235 
		cost = 2.0000 
		date = { 
			year = 1941 
			month = april 
			day = 5 
			hour = 0 
			} 
		manpower = 0.1000 
		close_when_finished = yes 
		waitingforclosure = no 
		total_progress = 0.0000 
		size = 30 
		done = 0 
		days = 1884 
		days_for_first = 78 
		gearing_bonus = 0.0000 
		type = infrastructure 
		} 
	province_development = { 
		id = { type = 22000 id = 203 } 
		name = "" 
		progress = 0.0000 
		location = 1280 
		cost = 5.0000 
		date = { 
			year = 2003 
			month = may 
			day = 15 
			hour = 0 
			} 
		manpower = 1.0000 
		close_when_finished = yes 
		waitingforclosure = no 
		total_progress = 0.0000 
		size = 99 
		done = 0 
		days = 12240 
		days_for_first = 245 
		gearing_bonus = 0.0000 
		type = ic 
		} 
	province_development = { 
		id = { type = 22000 id = 204 } 
		name = "" 
		progress = 0.0000 
		location = 1235 
		cost = 5.0000 
		date = { 
			year = 1936 
			month = september 
			day = 5 
			hour = 0 
			} 
		manpower = 1.0000 
		close_when_finished = yes 
		waitingforclosure = no 
		total_progress = 0.0000 
		size = 1 
		done = 0 
		days = 245 
		days_for_first = 245 
		gearing_bonus = 0.0000 
		type = ic 
		} 
	province_development = { 
		id = { type = 22000 id = 205 } 
		name = "" 
		progress = 0.0000 
		location = 1237 
		cost = 5.0000 
		date = { 
			year = 1936 
			month = september 
			day = 5 
			hour = 0 
			} 
		manpower = 1.0000 
		close_when_finished = yes 
		waitingforclosure = no 
		total_progress = 0.0000 
		size = 1 
		done = 0 
		days = 245 
		days_for_first = 245 
		gearing_bonus = 0.0000 
		type = ic 
		} 
	province_development = { 
		id = { type = 22000 id = 206 } 
		name = "" 
		progress = 0.0000 
		location = 1236 
		cost = 5.0000 
		date = { 
			year = 1936 
			month = september 
			day = 5 
			hour = 0 
			} 
		manpower = 1.0000 
		close_when_finished = yes 
		waitingforclosure = no 
		total_progress = 0.0000 
		size = 1 
		done = 0 
		days = 245 
		days_for_first = 245 
		gearing_bonus = 0.0000 
		type = ic 
		} 
	province_development = { 
		id = { type = 22000 id = 207 } 
		name = "" 
		progress = 0.0000 
		location = 1253 
		cost = 5.0000 
		date = { 
			year = 1936 
			month = september 
			day = 5 
			hour = 0 
			} 
		manpower = 1.0000 
		close_when_finished = yes 
		waitingforclosure = no 
		total_progress = 0.0000 
		size = 1 
		done = 0 
		days = 245 
		days_for_first = 245 
		gearing_bonus = 0.0000 
		type = ic 
		} 
	province_development = { 
		id = { type = 22000 id = 208 } 
		name = "" 
		progress = 0.0000 
		location = 1360 
		cost = 5.0000 
		date = { 
			year = 1936 
			month = september 
			day = 5 
			hour = 0 
			} 
		manpower = 1.0000 
		close_when_finished = yes 
		waitingforclosure = no 
		total_progress = 0.0000 
		size = 1 
		done = 0 
		days = 245 
		days_for_first = 245 
		gearing_bonus = 0.0000 
		type = ic 
		} 
	province_development = { 
		id = { type = 22000 id = 209 } 
		name = "" 
		progress = 0.0000 
		location = 1361 
		cost = 5.0000 
		date = { 
			year = 1936 
			month = september 
			day = 5 
			hour = 0 
			} 
		manpower = 1.0000 
		close_when_finished = yes 
		waitingforclosure = no 
		total_progress = 0.0000 
		size = 1 
		done = 0 
		days = 245 
		days_for_first = 245 
		gearing_bonus = 0.0000 
		type = ic 
		} 
	division_development = { 
		id = { type = 22000 id = 210 } 
		name = "Jiangsu Sheng Baoan Zongdui" 
		progress = 0.0000 
		location = 1235 
		cost = 1.9380 
		date = { 
			year = 1937 
			month = september 
			day = 12 
			hour = 0 
			} 
		manpower = 5.0000 
		close_when_finished = yes 
		waitingforclosure = no 
		total_progress = 0.0000 
		size = 40 
		done = 0 
		days = 778 
		days_for_first = 19 
		gearing_bonus = 0.0000 
		type = militia 
		extra = none 
		extra1 = none 
		extra2 = none 
		extra3 = none 
		extra4 = none 
		model = 0 
		brigade_model = 0 
		brigade_model1 = 0 
		brigade_model2 = 0 
		brigade_model3 = 0 
		brigade_model4 = 0 
		} 
	division_development = { 
		id = { type = 22000 id = 211 } 
		name = "Zhejiang Sheng Baoan Zongdui" 
		progress = 0.0000 
		location = 1235 
		cost = 1.9380 
		date = { 
			year = 1937 
			month = september 
			day = 12 
			hour = 0 
			} 
		manpower = 6.0000 
		close_when_finished = yes 
		waitingforclosure = no 
		total_progress = 0.0000 
		size = 40 
		done = 0 
		days = 778 
		days_for_first = 19 
		gearing_bonus = 0.0000 
		type = militia 
		extra = none 
		extra1 = none 
		extra2 = none 
		extra3 = none 
		extra4 = none 
		model = 0 
		brigade_model = 0 
		brigade_model1 = 0 
		brigade_model2 = 0 
		brigade_model3 = 0 
		brigade_model4 = 0 
		} 
	division_development = { 
		id = { type = 22000 id = 212 } 
		name = "Qibing Di 1 Shi" 
		progress = 0.0000 
		location = 1235 
		cost = 5.8140 
		date = { 
			year = 1938 
			month = june 
			day = 10 
			hour = 0 
			} 
		manpower = 15.0000 
		close_when_finished = yes 
		waitingforclosure = no 
		retooling_time = 68.0000 
		total_progress = 0.0000 
		size = 17 
		done = 0 
		days = 4590 
		days_for_first = 58 
		gearing_bonus = 0.0000 
		type = cavalry 
		extra = b_u9 
		extra1 = none 
		extra2 = none 
		extra3 = none 
		extra4 = none 
		model = 0 
		brigade_model = 0 
		brigade_model1 = 0 
		brigade_model2 = 0 
		brigade_model3 = 0 
		brigade_model4 = 0 
		}
}