##############################
# Country definition for HOL #
##############################

province = { id = 874 supplypool = 1 metalpool = 132 } # Paramaribo
province =
{ id         = 1628
  rarematerialspool = 226
  oilpool    = 1
  supplypool = 100
}              # Batavia
province = { id = 1641 supplypool = 1 } # Bandjermasin

#####################
# Country main data #
#####################

country =
{ tag                    = HOL
  capital                = 47
  manpower               = 38.2700  # 40 - building queue
  # Resource Reserves
  energy                 = 2782
  metal                  = 2104
  rare_materials         = 2740
  oil                    = 916
  supplies               = 476
  money                  = 200
  consumer = 0.0900 
  supply = 0.0900 
  production = 0.8200 
  reinforcement = 0.0000 
  upgrading = 0.0000 
  transports             = 502
  escorts                = 8

	diplomacy = {
		relation = { tag = AFG value = 1 }
		relation = { tag = ALB value = 15 }
		relation = { tag = ARG value = 20 }
		relation = { tag = AST value = 30 }
		relation = { tag = AUS value = 20 }
		relation = { tag = BEL value = 45 }
		relation = { tag = BHU value = 1 }
		relation = { tag = BOL value = 1 }
		relation = { tag = BRA value = 20 }
		relation = { tag = BUL value = 20 }
		relation = { tag = CAN value = 30 }
		relation = { tag = CGX value = 10 }
		relation = { tag = CHC value = 1 }
		relation = { tag = CHI value = 30 }
		relation = { tag = CHL value = 20 }
		relation = { tag = COL value = 20 }
		relation = { tag = COS value = 1 }
		relation = { tag = CSX value = 1 }
		relation = { tag = CUB value = 1 }
		relation = { tag = CXB value = 1 }
		relation = { tag = CYN value = 1 }
		relation = { tag = CZE value = 30 }
		relation = { tag = DEN value = 30 }
		relation = { tag = DOM value = 1 }
		relation = { tag = ECU value = 20 }
		relation = { tag = EGY value = 1 }
		relation = { tag = ENG value = 45 }
		relation = { tag = EST value = 20 }
		relation = { tag = ETH value = 20 }
		relation = { tag = FIN value = 35 }
		relation = { tag = FRA value = 45 }
		relation = { tag = GER value = 45 }
		relation = { tag = GRE value = 30 }
		relation = { tag = GUA value = 1 }
		relation = { tag = HAI value = 1 }
		relation = { tag = HON value = 1 }
		relation = { tag = HUN value = 20 }
		relation = { tag = IND value = 1 }
		relation = { tag = IRE value = 40 }
		relation = { tag = IRQ value = 1 }
		relation = { tag = ITA value = 30 }
		relation = { tag = JAP value = 20 }
		relation = { tag = LAT value = 20 }
		relation = { tag = LIB value = 1 }
		relation = { tag = LIT value = 20 }
		relation = { tag = LUX value = 20 }
		relation = { tag = MAN value = 1 }
		relation = { tag = MEX value = 20 }
		relation = { tag = MLY value = 20 }
		relation = { tag = MON value = 1 }
		relation = { tag = NEP value = 1 }
		relation = { tag = NIC value = 1 }
		relation = { tag = NOR value = 30 }
		relation = { tag = NZL value = 35 }
		relation = { tag = OMN value = 1 }
		relation = { tag = PAN value = 35 }
		relation = { tag = PAR value = 1 }
		relation = { tag = PER value = 25 }
		relation = { tag = PHI value = 30 }
		relation = { tag = POL value = 30 }
		relation = { tag = POR value = 20 }
		relation = { tag = PRU value = 20 }
		relation = { tag = ROM value = 20 }
		relation = { tag = SAF value = 40 }
		relation = { tag = SAL value = 1 }
		relation = { tag = SAU value = 25 }
		relation = { tag = SIA value = -10 }
		relation = { tag = SIK value = 1 }
		relation = { tag = SOV value = 25 }
		relation = { tag = SPA value = 25 }
		relation = { tag = SPR value = 25 }
		relation = { tag = SWE value = 40 }
		relation = { tag = SCH value = 50 }
		relation = { tag = TAN value = 1 }
		relation = { tag = TIB value = 1 }
		relation = { tag = TUR value = 30 }
		relation = { tag = U27 value = 1 }
		relation = { tag = URU value = 1 }
		relation = { tag = USA value = 50 }
		relation = { tag = VEN value = 25 }
		relation = { tag = YEM value = 1 }
		relation = { tag = YUG value = 20 }
	}

	SpyInfo = { country = "HOL" NumberOfSpies = 10 }
	SpyInfo = { country = "ARG" NumberOfSpies = 1 }
	SpyInfo = { country = "AST" NumberOfSpies = 1 }
	SpyInfo = { country = "BEL" NumberOfSpies = 4 }
	SpyInfo = { country = "BRA" NumberOfSpies = 1 }
	SpyInfo = { country = "CAN" NumberOfSpies = 1 }
	SpyInfo = { country = "CHI" NumberOfSpies = 1 }
	SpyInfo = { country = "COL" NumberOfSpies = 1 }
	SpyInfo = { country = "CUB" NumberOfSpies = 1 }
	SpyInfo = { country = "DEN" NumberOfSpies = 1 }
	SpyInfo = { country = "DOM" NumberOfSpies = 1 }
	SpyInfo = { country = "ENG" NumberOfSpies = 2 }
	SpyInfo = { country = "FRA" NumberOfSpies = 3 }
	SpyInfo = { country = "GER" NumberOfSpies = 4 }
	SpyInfo = { country = "IND" NumberOfSpies = 1 }
	SpyInfo = { country = "JAP" NumberOfSpies = 2 }
	SpyInfo = { country = "LUX" NumberOfSpies = 1 }
	SpyInfo = { country = "MAN" NumberOfSpies = 1 }
	SpyInfo = { country = "MLY" NumberOfSpies = 1 }
	SpyInfo = { country = "NZL" NumberOfSpies = 1 }
	SpyInfo = { country = "PAN" NumberOfSpies = 2 }
	SpyInfo = { country = "PER" NumberOfSpies = 1 }
	SpyInfo = { country = "PHI" NumberOfSpies = 1 }
	SpyInfo = { country = "POR" NumberOfSpies = 2 }
	SpyInfo = { country = "SAF" NumberOfSpies = 2 }
	SpyInfo = { country = "SAU" NumberOfSpies = 1 }
	SpyInfo = { country = "SIA" NumberOfSpies = 2 }
	SpyInfo = { country = "SOV" NumberOfSpies = 1 }
	SpyInfo = { country = "SPR" NumberOfSpies = 1 }
	SpyInfo = { country = "SCH" NumberOfSpies = 1 }
	SpyInfo = { country = "TUR" NumberOfSpies = 1 }
	SpyInfo = { country = "USA" NumberOfSpies = 1 }
	SpyInfo = { country = "VEN" NumberOfSpies = 2 }

  # Homeland
  nationalprovinces      = { 46   47   48   49   77   78   79   1354 1355 1356 1357 1358 1359 1628 1629 1630 1631 1632 1633 1634 1635 1636 1637 1638
                             1639 1640 1641 1642 1643 1645 1648 1649 1650 1651 1652 1653 1654 1655 1656 1657 1659 1660 1661 1662 1663 1664 1665 1673
                             1674 801  874 
                           }
  # Homeland
  ownedprovinces         = { 46   47   48   49   77   78   79   1354 1355 1356 1357 1358 1359 1628 1629 1630 1631 1632 1633 1634 1635 1636 1637 1638
                             1639 1640 1641 1642 1643 1645 1648 1649 1650 1651 1652 1653 1654 1655 1656 1657 1659 1660 1661 1662 1663 1664 1665 1673
                             1674 801  874 
                           }
  # Homeland
  controlledprovinces    = { 46   47   48   49   77   78   79   1354 1355 1356 1357 1358 1359 1628 1629 1630 1631 1632 1633 1634 1635 1636 1637 1638
                             1639 1640 1641 1642 1643 1645 1648 1649 1650 1651 1652 1653 1654 1655 1656 1657 1659 1660 1661 1662 1663 1664 1665 1673
                             1674 801  874 
                           }
  # Semi-Major Tech '36
  # Group C 1936 techs
  # ######################
  techapps               = { 4010  4020  4120     2010  2290  2300  2310  2450  2460  2510  1010  1190  1110  9010  5010  5020  5080  5090  5190 
                             5200  5470  6010  6020  3010  3020  3070  3080  3130  3140  3190  3200  3250  3400  3410  3420  8010  8020  8030  8040 
                             8050  8080  8160  14000 5410
                           }
  blueprints             = { 2150 }
  policy =
  { date              = { year = 0 month = january day = 0 }
    democratic        = 10
    political_left    = 2
    free_market       = 9
    freedom           = 10
    professional_army = 5
    defense_lobby     = 1
    interventionism   = 1
  }
  headofstate            = { type = 9 id = 8001 }
  headofgovernment       = { type = 9 id = 8002 }
  foreignminister        = { type = 9 id = 8003 }
  armamentminister       = { type = 9 id = 8004 }
  ministerofsecurity     = { type = 9 id = 8005 }
  ministerofintelligence = { type = 9 id = 8006 }
  chiefofstaff           = { type = 9 id = 8007 }
  chiefofarmy            = { type = 9 id = 8008 }
  chiefofnavy            = { type = 9 id = 8009 }
  chiefofair             = { type = 9 id = 8010 }
  landunit =
  { id       = { type = 18500 id = 1 }
    location = 47
    name     = "1e Legerkorps"
    division =
    { id    = { type = 18500 id = 2 }
      name  = "1e Divisie"
      type  = infantry
      extra = artillery
    }
    division =
    { id   = { type = 18500 id = 3 }
      name = "2e Divisie"
      type = infantry
    }
  }
  landunit =
  { id       = { type = 18500 id = 4 }
    location = 77
    name     = "2e Legerkorps"
    division =
    { id    = { type = 18500 id = 5 }
      name  = "3e Divisie"
      type  = infantry
      extra = artillery
    }
    division =
    { id   = { type = 18500 id = 6 }
      name = "4e Divisie"
      type = infantry
    }
  }
  landunit =
  { id       = { type = 18500 id = 7 }
    location = 49
    name     = "3e Legerkorps"
    division =
    { id    = { type = 18500 id = 8 }
      name  = "5e Divisie"
      type  = infantry
      extra = artillery
    }
    division =
    { id   = { type = 18500 id = 9 }
      name = "6e Divisie"
      type = infantry
    }
  }
  landunit =
  { id       = { type = 18500 id = 10 }
    location = 79
    name     = "4e Legerkorps"
    division =
    { id    = { type = 18500 id = 11 }
      name  = "7e Divisie"
      type  = infantry
      extra = artillery
    }
    division =
    { id   = { type = 18500 id = 12 }
      name = "8e Divisie"
      type = infantry
    }
  }
  landunit =
  { id       = { type = 18500 id = 13 }
    location = 1628
    name     = "Koninklijk Nederlands Indisch Leger"
    division =
    { id   = { type = 18500 id = 14 }
      name = "Ie Divisie 'Java'"
      type = infantry
    }
    division =
    { id   = { type = 18500 id = 15 }
      name = "IIe Divisie 'Java'"
      type = infantry
    }
    division =
    { id   = { type = 18500 id = 16 }
      name = "IIIe Divisie 'Java'"
      type = infantry
    }
  }
  # ################################################################
  navalunit =
  { id       = { type = 18500 id = 17 }
    location = 47
    base     = 47
    name     = "Koninklijke Vloot"
    division =
    { id    = { type = 18500 id = 18 }
      name  = "HrMs De Ruyter"
      type  = light_cruiser
      model = 1
      extra1 = naval_fire_controll_s
      extra2 = naval_anti_air_s
      brigade_model1 = 0
      brigade_model2 = 1
    }
    division =
    { id    = { type = 18500 id = 19 }
      name  = "HrMs Java"
      type  = light_cruiser
      model = 1
      extra1 = naval_fire_controll_s
      extra2 = naval_anti_air_s
      brigade_model1 = 0
      brigade_model2 = 1
    }
    division =
    { id    = { type = 18500 id = 20 }
      name  = "HrMs Sumatra"
      type  = light_cruiser
      model = 1
      extra1 = naval_fire_controll_s
      extra2 = naval_anti_air_s
      brigade_model1 = 0
      brigade_model2 = 1
    }
    division =
    { id    = { type = 18500 id = 21 }
      name  = "1e Torpedobootjager Smaldeel"
      type  = destroyer
      model = 1
      extra1 = naval_fire_controll_s
      brigade_model1 = 1
    }
    division =
    { id    = { type = 18500 id = 22 }
      name  = "2e Torpedobootjager Smaldeel"
      type  = destroyer
      model = 1
      extra1 = naval_anti_air_s
      brigade_model1 = 1
    }
    division =
    { id    = { type = 18500 id = 23 }
      name  = "1e Onderzeeboot Smaldeel"
      type  = submarine
      model = 0
    }
    division =
    { id    = { type = 18500 id = 24 }
      name  = "2e Onderzeeboot Smaldeel"
      type  = submarine
      model = 1
    }
    division =
    { id    = { type = 18500 id = 25 }
      name  = "3e Onderzeeboot Smaldeel"
      type  = submarine
      model = 2
    }
    division =
    { id   = { type = 18500 id = 26 }
      name = "1e Transport Smaldeel"
      type = transport
    }
    division =
    { id   = { type = 18500 id = 27 }
      name = "2e Transport Smaldeel"
      type = transport
    }
    division =
    { id   = { type = 18500 id = 28 }
      name = "3e Transport Smaldeel"
      type = transport
    }
    division =
    { id   = { type = 18500 id = 29 }
      name = "4e Transport Smaldeel"
      type = transport
    }
  } 

#########################################################################
# Airforce
#########################################################################

  airunit =
  { id       = { type = 18500 id = 30 }
    name = "Luchtvaartafdeeling"
    location = 47
    base     = 47
    division =
    { id       = { type = 18500 id = 31 }
      name = "Luchtvaartafdeeling"
      strength = 40
      model    = 0
      type     = interceptor
    }
  }

  airunit =
  { id       = { type = 18500 id = 32 }
    name = "Marine Luchtvaartdienst"
    location = 1628
    base     = 1628
    division =
    { id       = { type = 18500 id = 33 }
      name = "Marine Luchtvaartdienst"
      strength = 100
      model    = 0
      type     = naval_bomber
    }
  }

#########################################################################
# Constructions
#########################################################################

	province_development = { 
		id = { type = 18500 id = 34 } 
		name = "" 
		progress = 0.0000 
		location = 49 
		cost = 2.0000 
		date = { 
			year = 1939 
			month = april 
			day = 4 
			hour = 0 
			} 
		manpower = 0.1000 
		close_when_finished = yes 
		waitingforclosure = no 
		total_progress = 0.0000 
		size = 20 
		done = 0 
		days = 1657 
		days_for_first = 101 
		gearing_bonus = 0.0000 
		speed_step = 1 
		type = infrastructure 
		} 
	province_development = { 
		id = { type = 18500 id = 35 } 
		name = "" 
		progress = 0.0000 
		location = 47 
		cost = 2.0000 
		date = { 
			year = 1940 
			month = august 
			day = 10 
			hour = 0 
			} 
		manpower = 0.1000 
		close_when_finished = yes 
		waitingforclosure = no 
		total_progress = 0.0000 
		size = 20 
		done = 0 
		days = 1657 
		days_for_first = 101 
		gearing_bonus = 0.0000 
		type = infrastructure 
		} 
	province_development = { 
		id = { type = 18500 id = 36 } 
		name = "" 
		progress = 0.0000 
		location = 1628 
		cost = 5.0000 
		date = { 
			year = 2018 
			month = march 
			day = 16 
			hour = 0 
			} 
		manpower = 1.0000 
		close_when_finished = yes 
		waitingforclosure = no 
		total_progress = 0.0000 
		size = 98 
		done = 0 
		days = 29635 
		days_for_first = 302 
		gearing_bonus = 0.0000 
		type = ic 
		} 
	province_development = { 
		id = { type = 18500 id = 37 } 
		name = "" 
		progress = 0.0000 
		location = 1628 
		cost = 2.0000 
		date = { 
			year = 1942 
			month = may 
			day = 23 
			hour = 0 
			} 
		manpower = 0.1000 
		close_when_finished = yes 
		waitingforclosure = no 
		total_progress = 0.0000 
		size = 28 
		done = 0 
		days = 2299 
		days_for_first = 101 
		gearing_bonus = 0.0000 
		type = infrastructure 
		} 
	province_development = { 
		id = { type = 18500 id = 38 } 
		name = "" 
		progress = 0.0000 
		location = 874 
		cost = 2.0000 
		date = { 
			year = 1939 
			month = september 
			day = 9 
			hour = 0 
			} 
		manpower = 0.1000 
		close_when_finished = yes 
		waitingforclosure = no 
		total_progress = 0.0000 
		size = 28 
		done = 0 
		days = 2299 
		days_for_first = 101 
		gearing_bonus = 0.0000 
		speed_step = 2 
		type = infrastructure 
		} 
	province_development = { 
		id = { type = 18500 id = 39 } 
		name = "" 
		progress = 0.0000 
		location = 1354 
		cost = 2.0000 
		date = { 
			year = 1939 
			month = september 
			day = 9 
			hour = 0 
			} 
		manpower = 0.1000 
		close_when_finished = yes 
		waitingforclosure = no 
		total_progress = 0.0000 
		size = 28 
		done = 0 
		days = 2299 
		days_for_first = 101 
		gearing_bonus = 0.0000 
		speed_step = 2 
		type = infrastructure 
		} 
	province_development = { 
		id = { type = 18500 id = 40 } 
		name = "" 
		progress = 0.0000 
		location = 1642 
		cost = 2.0000 
		date = { 
			year = 1943 
			month = april 
			day = 15 
			hour = 0 
			} 
		manpower = 0.1000 
		close_when_finished = yes 
		waitingforclosure = no 
		total_progress = 0.0000 
		size = 32 
		done = 0 
		days = 2620 
		days_for_first = 101 
		gearing_bonus = 0.0000 
		type = infrastructure 
		} 
	province_development = { 
		id = { type = 18500 id = 41 } 
		name = "" 
		progress = 0.0000 
		location = 1358 
		cost = 2.0000 
		date = { 
			year = 1943 
			month = december 
			day = 23 
			hour = 0 
			} 
		manpower = 0.1000 
		close_when_finished = yes 
		waitingforclosure = no 
		total_progress = 0.0000 
		size = 28 
		done = 0 
		days = 2299 
		days_for_first = 126 
		gearing_bonus = 0.0000 
		type = infrastructure 
		} 
	province_development = { 
		id = { type = 18500 id = 42 } 
		name = "" 
		progress = 0.0000 
		location = 1649 
		cost = 2.0000 
		date = { 
			year = 1954 
			month = march 
			day = 9 
			hour = 0 
			} 
		manpower = 0.1000 
		close_when_finished = yes 
		waitingforclosure = no 
		total_progress = 0.0000 
		size = 32 
		done = 0 
		days = 2620 
		days_for_first = 252 
		gearing_bonus = 0.0000 
		type = infrastructure 
		} 
	brigade_development = { 
		id = { type = 18500 id = 43 } 
		name = "Improved Sea Mines" 
		progress = 0.0000 
		location = 47 
		cost = 0.3024 
		date = { 
			year = 1937 
			month = october 
			day = 26 
			hour = 0 
			} 
		manpower = 0.0500 
		close_when_finished = yes 
		waitingforclosure = no 
		retooling_time = 30.0000 
		total_progress = 0.0000 
		size = 8 
		done = 0 
		days = 114 
		days_for_first = 91 
		gearing_bonus = 0.0000 
		type = naval_mines 
		model = 1 
		} 
	convoy_development = { 
		id = { type = 18500 id = 44 } 
		name = "" 
		progress = 0.0000 
		location = 0 
		cost = 3.0000 
		date = { 
			year = 1969 
			month = june 
			day = 7 
			hour = 0 
			} 
		manpower = 1.0000 
		close_when_finished = yes 
		waitingforclosure = no 
		retooling_time = 60.0000 
		total_progress = 0.0000 
		size = 99 
		done = 0 
		days = 5997 
		days_for_first = 151 
		gearing_bonus = 0.0000 
		type = transports 
		} 
}
