##############################
# Country definition for NZL #
##############################

province = { id = 1872 supplypool = 50 } # Christchurch

#####################
# Country main data #
#####################

country =
{ tag                    = NZL
  # Resource Reserves
  energy                 = 1000
  metal                  = 1000
  rare_materials         = 500
  oil                    = 500
  supplies               = 450
  money                  = 10
  consumer = 0.3500 
  supply = 0.1000 
  production = 0.5000 
  reinforcement = 0.0500 
  upgrading = 0.0000 
  transports             = 24
  capital                = 1871
  manpower               = 17.9000 # 18 - building queue no more

	diplomacy = {
		relation = { tag = AFG value = 1 }
		relation = { tag = ALB value = 10 }
		relation = { tag = ARG value = 20 }
		relation = { tag = AST value = 100 }
		relation = { tag = AUS value = 10 }
		relation = { tag = BEL value = 30 }
		relation = { tag = BHU value = 50 }
		relation = { tag = BOL value = 1 }
		relation = { tag = BRA value = 15 }
		relation = { tag = BUL value = 10 }
		relation = { tag = CAN value = 50 }
		relation = { tag = CGX value = 10 }
		relation = { tag = CHC value = -10 }
		relation = { tag = CHI value = 25 }
		relation = { tag = CHL value = 20 }
		relation = { tag = COL value = 20 }
		relation = { tag = COS value = 15 }
		relation = { tag = CSX value = 1 }
		relation = { tag = CUB value = 1 }
		relation = { tag = CXB value = 1 }
		relation = { tag = CYN value = 1 }
		relation = { tag = CZE value = 30 }
		relation = { tag = DEN value = 20 }
		relation = { tag = DOM value = 1 }
		relation = { tag = ECU value = 20 }
		relation = { tag = EGY value = 50 }
		relation = { tag = ENG value = 150 }
		relation = { tag = EST value = 10 }
		relation = { tag = ETH value = 20 }
		relation = { tag = FIN value = 15 }
		relation = { tag = FRA value = 40 }
		relation = { tag = GER value = 25 }
		relation = { tag = GRE value = 30 }
		relation = { tag = GUA value = 10 }
		relation = { tag = HAI value = 1 }
		relation = { tag = HOL value = 35 }
		relation = { tag = HON value = 10 }
		relation = { tag = HUN value = 10 }
		relation = { tag = IND value = 50 }
		relation = { tag = IRE value = 40 }
		relation = { tag = IRQ value = 50 }
		relation = { tag = ITA value = 30 }
		relation = { tag = JAP value = 20 }
		relation = { tag = LAT value = 10 }
		relation = { tag = LIB value = 1 }
		relation = { tag = LIT value = 10 }
		relation = { tag = LUX value = 10 }
		relation = { tag = MAN value = -10 }
		relation = { tag = MEX value = 20 }
		relation = { tag = MLY value = 50 }
		relation = { tag = MON value = 1 }
		relation = { tag = NEP value = 50 }
		relation = { tag = NIC value = 10 }
		relation = { tag = NOR value = 10 }
		relation = { tag = OMN value = 50 }
		relation = { tag = PAN value = 20 }
		relation = { tag = PAR value = 1 }
		relation = { tag = PER value = 25 }
		relation = { tag = PHI value = 30 }
		relation = { tag = POL value = 25 }
		relation = { tag = POR value = 35 }
		relation = { tag = PRU value = 20 }
		relation = { tag = ROM value = 15 }
		relation = { tag = SAF value = 50 }
		relation = { tag = SAL value = 10 }
		relation = { tag = SAU value = 15 }
		relation = { tag = SIA value = 1 }
		relation = { tag = SIK value = 1 }
		relation = { tag = SOV value = 20 }
		relation = { tag = SPA value = 20 }
		relation = { tag = SPR value = 20 }
		relation = { tag = SWE value = 15 }
		relation = { tag = SCH value = 50 }
		relation = { tag = TAN value = 1 }
		relation = { tag = TIB value = 1 }
		relation = { tag = TUR value = 20 }
		relation = { tag = U27 value = 50 }
		relation = { tag = URU value = 1 }
		relation = { tag = USA value = 65 }
		relation = { tag = VEN value = 25 }
		relation = { tag = YEM value = 50 }
		relation = { tag = YUG value = 10 }
	}

	SpyInfo = { country = "NZL" NumberOfSpies = 3 }
	SpyInfo = { country = "AST" NumberOfSpies = 4 }
	SpyInfo = { country = "CAN" NumberOfSpies = 2 }
	SpyInfo = { country = "CGX" NumberOfSpies = 1 }
	SpyInfo = { country = "CHI" NumberOfSpies = 2 }
	SpyInfo = { country = "CSX" NumberOfSpies = 1 }
	SpyInfo = { country = "CYN" NumberOfSpies = 1 }
	SpyInfo = { country = "EGY" NumberOfSpies = 1 }
	SpyInfo = { country = "ENG" NumberOfSpies = 1 }
	SpyInfo = { country = "GRE" NumberOfSpies = 1 }
	SpyInfo = { country = "HOL" NumberOfSpies = 1 }
	SpyInfo = { country = "IND" NumberOfSpies = 2 }
	SpyInfo = { country = "IRE" NumberOfSpies = 1 }
	SpyInfo = { country = "IRQ" NumberOfSpies = 1 }
	SpyInfo = { country = "JAP" NumberOfSpies = 1 }
	SpyInfo = { country = "MLY" NumberOfSpies = 4 }
	SpyInfo = { country = "OMN" NumberOfSpies = 1 }
	SpyInfo = { country = "PHI" NumberOfSpies = 1 }
	SpyInfo = { country = "POR" NumberOfSpies = 1 }
	SpyInfo = { country = "SAF" NumberOfSpies = 1 }
	SpyInfo = { country = "SIA" NumberOfSpies = 1 }
	SpyInfo = { country = "SCH" NumberOfSpies = 1 }
	SpyInfo = { country = "USA" NumberOfSpies = 1 }

  nationalprovinces      = { 1868 1869 1870 1871 1872 1873 }
  ownedprovinces         = { 1868 1869 1870 1871 1872 1873 }
  controlledprovinces    = { 1868 1869 1870 1871 1872 1873 }
  # Commonwealth Tech '36
  # UK 1936 techs
  # ######################
  techapps               = { 1010  1020  1190  1200  1210  1220  1310  14000 2010  2290  2300  2310  2450  2460  2510  3010  3020  3070  3080  4010 
                             4020  4120  4130  5010  5020  5080  5090  5190  5310  6010  6030  6120  8010  8020  8030  8040  8050  8070  8100 
                             8120  9010  9020  9030  9140 
                           }
  policy =
  { date              = { year = 0 month = january day = 0 }
    democratic        = 10
    political_left    = 10
    freedom           = 10
    free_market       = 8
    professional_army = 5
    defense_lobby     = 2
    interventionism   = 6
  }
  headofstate            = { type = 9 id = 55001 }
  headofgovernment       = { type = 9 id = 55002 }
  foreignminister        = { type = 9 id = 55003 }
  armamentminister       = { type = 9 id = 55004 }
  ministerofsecurity     = { type = 9 id = 55005 }
  ministerofintelligence = { type = 9 id = 55006 }
  chiefofstaff           = { type = 9 id = 55007 }
  chiefofarmy            = { type = 9 id = 55008 }
  chiefofnavy            = { type = 9 id = 55009 }
  chiefofair             = { type = 9 id = 55010 }
  landunit =
  { name     = "I New Zealand Corps"
    location = 1871
    id       = { type = 10600 id = 100 }
    division =
    { id       = { type = 10600 id = 101 }
      name     = "New Zealand Territorial Force"
      type     = hq
      strength = 100
      extra = engineer
    }
  }
  landunit =
  { id       = { type = 10600 id = 1 }
    name     = "New Zealand Expeditionary Force"
    location = 1871
    division =
    { id       = { type = 10600 id = 2 }
      name     = "2nd NZ Infantry Division"
      strength = 100
      type     = infantry
      extra    = engineer
    }
  }
  landunit =
  { id       = { type = 10600 id = 3 }
    name     = "Northern Military District"
    location = 1869
    division =
    { id       = { type = 10600 id = 4 }
      name     = "1st Mounted Rifles Division"
      strength = 30
      type     = cavalry
    }
    division =
    { id       = { type = 10600 id = 5 }
      name     = "3rd NZ Infantry Division"
      strength = 30
      type     = infantry
    }
  }
  landunit =
  { id       = { type = 10600 id = 6 }
    name     = "Central Military District"
    location = 1872
    division =
    { id       = { type = 10600 id = 7 }
      name     = "2nd Mounted Rifles Division"
      strength = 30
      type     = cavalry
    }
    division =
    { id       = { type = 10600 id = 8 }
      name     = "1st NZ Infantry Division"
      strength = 30
      type     = infantry
    }
  }
  landunit =
  { id       = { type = 10600 id = 9 }
    name     = "Southern Military District"
    location = 1873
    division =
    { id       = { type = 10600 id = 10 }
      name     = "3rd Mounted Rifles Division"
      strength = 30
      type     = cavalry
    }
    division =
    { id       = { type = 10600 id = 11 }
      name     = "4th NZ Infantry Division"
      strength = 30
      type     = infantry
      extra    = anti_air
    }
  }

#NAVAL OOB

navalunit = {
	id = { type = 10600 id = 3000 }
	name = "HM New Zealand Squadron"
	location = 1871
	base = 1871

	division = {
		id = { type = 10600 id = 3001 }
		name = "HMNZS Dunedin"
		type = light_cruiser
		model = 0
	}

	division = {
		id = { type = 10600 id = 3002 }
		name = "HMNZS Diomede"
		type = light_cruiser
		model = 0
	}
}

navalunit = {
	id = { type = 10600 id = 3004 }
	name = "HM South Pacific Squadron"
	location = 1871
	base = 1871

	division = {
		id = { type = 10600 id = 3005 }
		name = "Destroyer Division 1"
		type = destroyer
		model = 0
	}
}

navalunit = {
	id = { type = 10600 id = 3007 }
	name = "HM New Zealand Transport Flotilla"
	location = 1871
	base = 1871

	division = { 
		id = { type = 10600 id = 3008 }
		name = "HM New Zealand Transport Flotilla"
		type = transport
		model = 0
	}
}
	province_development = { 
		id = { type = 10600 id = 19 } 
		name = "" 
		progress = 0.0000 
		location = 1871 
		cost = 2.0000 
		date = { 
			year = 1943 
			month = march 
			day = 10 
			hour = 0 
			} 
		manpower = 0.1000 
		close_when_finished = yes 
		waitingforclosure = no 
		total_progress = 0.0000 
		size = 24 
		done = 0 
		days = 2072 
		days_for_first = 132 
		gearing_bonus = 0.0000 
		type = infrastructure 
		} 
	brigade_development = { 
		id = { type = 10600 id = 20 } 
		name = "36' AA" 
		progress = 0.0000 
		location = 1871 
		cost = 0.7040 
		date = { 
			year = 1937 
			month = january 
			day = 16 
			hour = 0 
			} 
		manpower = 0.1000 
		close_when_finished = yes 
		waitingforclosure = no 
		retooling_time = 36.0000 
		total_progress = 0.0000 
		size = 4 
		done = 0 
		days = 238 
		days_for_first = 92 
		gearing_bonus = 0.0000 
		type = naval_anti_air_s 
		model = 1 
		} 
	brigade_development = { 
		id = { type = 10600 id = 21 } 
		name = "20' Fire Control" 
		progress = 0.0000 
		location = 1871 
		cost = 0.1760 
		date = { 
			year = 1936 
			month = june 
			day = 23 
			hour = 0 
			} 
		manpower = 0.1000 
		close_when_finished = yes 
		waitingforclosure = no 
		retooling_time = 22.5000 
		total_progress = 0.0000 
		size = 3 
		done = 0 
		days = 103 
		days_for_first = 53 
		gearing_bonus = 0.0000 
		type = naval_fire_controll_s 
		model = 0 
		} 
}
