#####################
# Country main data #
#####################

country =
{ tag                    = NOR
  energy                 = 1000
  metal                  = 1000
  rare_materials         = 500
  oil                    = 500
  supplies               = 500
  money                  = 10
  consumer = 0.2416 
  supply = 0.0716 
  production = 0.6868 
  reinforcement = 0.0000 
  upgrading = 0.0000 
  manpower               = 31.5500 # 32 - building queue
  capital                = 107
  # Norwegian merchant marine is INSANE!
  transports             = 810
  escorts                = 6

	diplomacy = {
		relation = { tag = AFG value = 1 }
		relation = { tag = ALB value = 15 }
		relation = { tag = ARG value = 1 }
		relation = { tag = AST value = 10 }
		relation = { tag = AUS value = 20 }
		relation = { tag = BEL value = 20 }
		relation = { tag = BHU value = 1 }
		relation = { tag = BOL value = 1 }
		relation = { tag = BRA value = 15 }
		relation = { tag = BUL value = 20 }
		relation = { tag = CAN value = 20 }
		relation = { tag = CGX value = 1 }
		relation = { tag = CHC value = 1 }
		relation = { tag = CHI value = 1 }
		relation = { tag = CHL value = 1 }
		relation = { tag = COL value = 1 }
		relation = { tag = COS value = 1 }
		relation = { tag = CSX value = 1 }
		relation = { tag = CUB value = 1 }
		relation = { tag = CXB value = 1 }
		relation = { tag = CYN value = 1 }
		relation = { tag = CZE value = 25 }
		relation = { tag = DEN value = 40 }
		relation = { tag = DOM value = 1 }
		relation = { tag = ECU value = 1 }
		relation = { tag = EGY value = 1 }
		relation = { tag = ENG value = 40 }
		relation = { tag = EST value = 25 }
		relation = { tag = ETH value = 1 }
		relation = { tag = FIN value = 35 }
		relation = { tag = FRA value = 35 }
		relation = { tag = GER value = 20 }
		relation = { tag = GRE value = 30 }
		relation = { tag = GUA value = 1 }
		relation = { tag = HAI value = 1 }
		relation = { tag = HOL value = 30 }
		relation = { tag = HON value = 1 }
		relation = { tag = HUN value = 20 }
		relation = { tag = IND value = 1 }
		relation = { tag = IRE value = 30 }
		relation = { tag = IRQ value = 1 }
		relation = { tag = ITA value = 30 }
		relation = { tag = JAP value = 20 }
		relation = { tag = LAT value = 30 }
		relation = { tag = LIB value = 1 }
		relation = { tag = LIT value = 30 }
		relation = { tag = LUX value = 20 }
		relation = { tag = MAN value = 1 }
		relation = { tag = MEX value = 1 }
		relation = { tag = MLY value = 1 }
		relation = { tag = MON value = 1 }
		relation = { tag = NEP value = 1 }
		relation = { tag = NIC value = 1 }
		relation = { tag = NZL value = 10 }
		relation = { tag = OMN value = 1 }
		relation = { tag = PAN value = 25 }
		relation = { tag = PAR value = 1 }
		relation = { tag = PER value = 10 }
		relation = { tag = PHI value = 1 }
		relation = { tag = POL value = 20 }
		relation = { tag = POR value = 20 }
		relation = { tag = PRU value = 1 }
		relation = { tag = ROM value = 20 }
		relation = { tag = SAF value = 10 }
		relation = { tag = SAL value = 1 }
		relation = { tag = SAU value = 10 }
		relation = { tag = SIA value = 1 }
		relation = { tag = SIK value = 1 }
		relation = { tag = SOV value = 20 }
		relation = { tag = SPA value = 20 }
		relation = { tag = SPR value = 20 }
		relation = { tag = SWE value = 50 }
		relation = { tag = SCH value = 50 }
		relation = { tag = TAN value = 1 }
		relation = { tag = TIB value = 1 }
		relation = { tag = TUR value = 15 }
		relation = { tag = U27 value = 1 }
		relation = { tag = URU value = 1 }
		relation = { tag = USA value = 45 }
		relation = { tag = VEN value = 1 }
		relation = { tag = YEM value = 1 }
		relation = { tag = YUG value = 20 }
	}

	SpyInfo = { country = "NOR" NumberOfSpies = 2 }
	SpyInfo = { country = "CAN" NumberOfSpies = 1 }
	SpyInfo = { country = "DEN" NumberOfSpies = 2 }
	SpyInfo = { country = "ENG" NumberOfSpies = 1 }
	SpyInfo = { country = "FIN" NumberOfSpies = 4 }
	SpyInfo = { country = "FRA" NumberOfSpies = 2 }
	SpyInfo = { country = "GER" NumberOfSpies = 1 }
	SpyInfo = { country = "JAP" NumberOfSpies = 2 }
	SpyInfo = { country = "PAN" NumberOfSpies = 1 }
	SpyInfo = { country = "POR" NumberOfSpies = 1 }
	SpyInfo = { country = "SAF" NumberOfSpies = 1 }
	SpyInfo = { country = "SOV" NumberOfSpies = 1 }
	SpyInfo = { country = "SWE" NumberOfSpies = 4 }
	SpyInfo = { country = "SCH" NumberOfSpies = 1 }
	SpyInfo = { country = "TUR" NumberOfSpies = 1 }
	SpyInfo = { country = "USA" NumberOfSpies = 1 }
	SpyInfo = { country = "VEN" NumberOfSpies = 1 }

  nationalprovinces      = { 107 108 109 110 111 116 117 118 124 125 128 129 }
  ownedprovinces         = { 107 108 109 110 111 116 117 118 124 125 128 129 }
  controlledprovinces    = { 107 108 109 110 111 116 117 118 124 125 128 129 }
  # Western Minor Tech '36
  # Group C 1936 techs
  # ######################
  techapps               = { 4010 4020 4120  2290 2300 2310 2450 2460 3130 2510 1010 1190 1110 9010 5010 5020 5080 5090 5190 6010 6020
                             3010 3070 3250 3400 3410 8020 8040 8050
                           }
  policy =
  { date              = { year = 0 month = january day = 0 }
    democratic        = 9
    political_left    = 9
    freedom           = 7
    free_market       = 7
    professional_army = 3
    defense_lobby     = 5
    interventionism   = 2
  }
  headofstate            = { type = 9 id = 14001 }
  headofgovernment       = { type = 9 id = 14002 }
  foreignminister        = { type = 9 id = 14003 }
  armamentminister       = { type = 9 id = 14004 }
  ministerofsecurity     = { type = 9 id = 14005 }
  ministerofintelligence = { type = 9 id = 14006 }
  chiefofstaff           = { type = 9 id = 14007 }
  chiefofarmy            = { type = 9 id = 14008 }
  chiefofnavy            = { type = 9 id = 14009 }
  chiefofair             = { type = 9 id = 14010 }
  landunit =
  { location = 107
    name     = "Den Norske Hær"
    id       = { type = 12600 id = 1 }
    division =
    { id       = { type = 12600 id = 2 }
      name     = "1. Infanteridivisjon"
      type     = infantry
      strength = 60
    }
  }
  landunit =
  { location = 125
    name     = "6. Hærkorps"
    id       = { type = 12600 id = 3 }
    division =
    { id       = { type = 12600 id = 4 }
      name     = "6. Infanteridivisjon"
      type     = infantry
      strength = 35
    }
  }

#########################################################################
# Navy
#########################################################################

navalunit = {
	id = { type = 12051 id = 3000 }
	name = "1. Kystvaktdistrikt"
	location = 107
	base = 107

	division = {
		id = { type = 12051 id = 3001 }
		name = "1. Destroyereskadre"
		type = destroyer
		strength = 80
		max_strength = 80
		model = 0
		extra = naval_anti_air_s
		brigade_model = 0
		}
	}

navalunit = {
	id = { type = 12051 id = 3002 }
	name = "2. Kystvaktdistrikt"
	location = 125
	base = 125

	division = {
		id = { type = 12051 id = 3003 }
		name = "Norge"
		type = heavy_cruiser
		model = 0
		extra1 = naval_sa_l
		extra2 = naval_anti_air_l
		brigade_model1 = 0
		brigade_model2 = 0
		}
	division = {
		id = { type = 12051 id = 3004 }
		name = "Eidsvold"
		type = heavy_cruiser
		model = 0
		extra1 = naval_sa_l
		extra2 = naval_anti_air_l
		brigade_model1 = 0
		brigade_model2 = 0
		}
	division = {
		id = { type = 12051 id = 3012 }
		name = "KNM Tordenskjold"
		type = light_cruiser
		model = 0
		}
	division = {
		id = { type = 12051 id = 3013 }
		name = "KNM Harald Haarfagre"
		type = light_cruiser
		model = 0
		}
	division = {
		id = { type = 12051 id = 3005 }
		name = "2. Destroyereskadre"
		type = destroyer
		model = 0
		extra1 = naval_anti_air_s
		brigade_model1 = 0
		}
	}

navalunit = {
	id = { type = 12051 id = 3006 }
	name = "3. Kystvaktdistrikt"
	location = 108
	base = 108

	division = {
		id = { type = 12051 id = 3007 }
		name = "3. Destroyereskadre"
		type = destroyer
		strength = 50
		max_strength = 50
		model = 0
		extra = naval_anti_air_s
		brigade_model = 0
		}
	}

navalunit = {
	id = { type = 12051 id = 3008 }
	name = "4. Kystvaktdistrikt"
	location = 110 # Bergen
	base = 110

	division = {
		id = { type = 12051 id = 3009 }
		name = "4. Destroyereskadre"
		type = destroyer
		strength = 50
		max_strength = 50
		model = 0
		extra1 = naval_anti_air_s
		brigade_model1 = 0
		}
	}

navalunit = {
	id = { type = 12051 id = 3010 }
	name = "1. Undervannsbåteskadre"
	location = 107
	base = 107

	division = {
		id = { type = 12051 id = 3011 }
		name = "1. Undervannsbåteskadre"
		type = submarine
		model = 0
		extra = naval_torpedoes_s
		brigade_model = 0
		}
	}

#########################################################################
# Airforce
#########################################################################

  airunit =
  { id       = { type = 12600 id = 13 }
    name = "Flyregimentet"
    location = 107
    base     = 107
    division =
    { id       = { type = 12600 id = 14 }
      name = "Speidervingen" 
      strength = 30
      model    = 0
      type     = interceptor
    }
  }

#########################################################################
# Constructions
#########################################################################

	province_development = { 
		id = { type = 12600 id = 15 } 
		name = "" 
		progress = 0.0000 
		location = 107 
		cost = 2.0000 
		date = { 
			year = 1941 
			month = december 
			day = 11 
			hour = 0 
			} 
		manpower = 0.1000 
		close_when_finished = yes 
		waitingforclosure = no 
		total_progress = 0.0000 
		size = 24 
		done = 0 
		days = 2150 
		days_for_first = 110 
		gearing_bonus = 0.0000 
		type = infrastructure 
		} 
	province_development = { 
		id = { type = 12600 id = 16 } 
		name = "" 
		progress = 0.0000 
		location = 118 
		cost = 2.0000 
		date = { 
			year = 1945 
			month = february 
			day = 18 
			hour = 0 
			} 
		manpower = 0.1000 
		close_when_finished = yes 
		waitingforclosure = no 
		total_progress = 0.0000 
		size = 24 
		done = 0 
		days = 2150 
		days_for_first = 137 
		gearing_bonus = 0.0000 
		type = infrastructure 
		} 
	province_development = { 
		id = { type = 12600 id = 17 } 
		name = "" 
		progress = 0.0000 
		location = 129 
		cost = 2.0000 
		date = { 
			year = 1945 
			month = october 
			day = 10 
			hour = 0 
			} 
		manpower = 0.1000 
		close_when_finished = yes 
		waitingforclosure = no 
		total_progress = 0.0000 
		size = 32 
		done = 0 
		days = 2846 
		days_for_first = 110 
		gearing_bonus = 0.0000 
		type = infrastructure 
		} 
	brigade_development = { 
		id = { type = 12600 id = 18 } 
		name = "36' AA" 
		progress = 0.0000 
		location = 107 
		cost = 0.7360 
		date = { 
			year = 1936 
			month = august 
			day = 19 
			hour = 0 
			} 
		manpower = 0.1000 
		close_when_finished = yes 
		waitingforclosure = no 
		retooling_time = 40.0000 
		total_progress = 0.0000 
		size = 2 
		done = 0 
		days = 170 
		days_for_first = 97 
		gearing_bonus = 0.0000 
		type = naval_anti_air_s 
		model = 1 
		} 
	brigade_development = { 
		id = { type = 12600 id = 19 } 
		name = "Capital Torpedoes" 
		progress = 0.0000 
		location = 107 
		cost = 0.5520 
		date = { 
			year = 1936 
			month = may 
			day = 17 
			hour = 0 
			} 
		manpower = 0.0500 
		close_when_finished = yes 
		waitingforclosure = no 
		retooling_time = 30.0000 
		total_progress = 0.0000 
		size = 2 
		done = 0 
		days = 108 
		days_for_first = 55 
		gearing_bonus = 0.0000 
		type = naval_torpedoes_l 
		model = 0 
		} 
	brigade_development = { 
		id = { type = 12600 id = 20 } 
		name = "Torpedoes" 
		progress = 0.0000 
		location = 107 
		cost = 0.5520 
		date = { 
			year = 1936 
			month = november 
			day = 20 
			hour = 0 
			} 
		manpower = 0.0500 
		close_when_finished = yes 
		waitingforclosure = no 
		retooling_time = 30.0000 
		total_progress = 0.0000 
		size = 6 
		done = 0 
		days = 55 
		days_for_first = 55 
		gearing_bonus = 0.0000 
		type = naval_torpedoes_s 
		model = 0 
		} 
}
