#####################
# Country main data #
#####################

country =
{ tag                    = PER
  # Resource Reserves
  energy                 = 1000
  metal                  = 1000
  rare_materials         = 500
  oil                    = 500
  supplies               = 500
  money                  = 10
  capital                = 1502
  manpower               = 95.8 # 96 - building queue
  consumer = 0.0000 
  supply = 0.0000 
  production = 1.0000 
  reinforcement = 0.0000 
  upgrading = 0.0000 
  transports             = 16
  policy =
  { date              = { year = 0 month = january day = 0 }
    democratic        = 3
    political_left    = 4
    freedom           = 3
    free_market       = 5
    professional_army = 3
    defense_lobby     = 5
    interventionism   = 5
  }
  nationalprovinces      = { 1859 1787 1503 1502 1788 1789 1825 1498 1497 1499 1826 1501 1500 1496 1495 }
  ownedprovinces         = { 1859 1787 1503 1502 1788 1789 1825 1498 1497 1499 1826 1501 1500 1496 1495 }
  controlledprovinces    = { 1859 1787 1503 1502 1788 1789 1825 1498 1497 1499 1826 1501 1500 1496 1495 }
  # ROTW Minor Tech '36
  # Group E 1936 techs
  # ######################
  # GW fighter
  techapps               = { 4010  2290 1010 1190 5080 }

	diplomacy = {
		relation = { tag = AFG value = 45 }
		relation = { tag = ALB value = 1 }
		relation = { tag = ARG value = 1 }
		relation = { tag = AST value = 20 }
		relation = { tag = AUS value = 30 }
		relation = { tag = BEL value = 20 }
		relation = { tag = BHU value = 1 }
		relation = { tag = BOL value = 1 }
		relation = { tag = BRA value = 15 }
		relation = { tag = BUL value = 10 }
		relation = { tag = CAN value = 25 }
		relation = { tag = CGX value = 10 }
		relation = { tag = CHC value = 1 }
		relation = { tag = CHI value = 25 }
		relation = { tag = CHL value = 1 }
		relation = { tag = COL value = 1 }
		relation = { tag = COS value = 1 }
		relation = { tag = CSX value = 1 }
		relation = { tag = CUB value = 1 }
		relation = { tag = CXB value = 1 }
		relation = { tag = CYN value = 1 }
		relation = { tag = CZE value = 20 }
		relation = { tag = DEN value = 20 }
		relation = { tag = DOM value = 1 }
		relation = { tag = ECU value = 1 }
		relation = { tag = EGY value = 40 }
		relation = { tag = ENG value = 40 }
		relation = { tag = EST value = 1 }
		relation = { tag = ETH value = 1 }
		relation = { tag = FIN value = 1 }
		relation = { tag = FRA value = 40 }
		relation = { tag = GER value = 45 }
		relation = { tag = GRE value = 30 }
		relation = { tag = GUA value = 1 }
		relation = { tag = HAI value = 1 }
		relation = { tag = HOL value = 25 }
		relation = { tag = HON value = 1 }
		relation = { tag = HUN value = 10 }
		relation = { tag = IND value = -20 }
		relation = { tag = IRE value = 25 }
		relation = { tag = IRQ value = -35 }
		relation = { tag = ITA value = 40 }
		relation = { tag = JAP value = 35 }
		relation = { tag = LAT value = 1 }
		relation = { tag = LIB value = 1 }
		relation = { tag = LIT value = 1 }
		relation = { tag = LUX value = 1 }
		relation = { tag = MAN value = 1 }
		relation = { tag = MEX value = 1 }
		relation = { tag = MLY value = 1 }
		relation = { tag = MON value = 1 }
		relation = { tag = NEP value = 1 }
		relation = { tag = NIC value = 1 }
		relation = { tag = NOR value = 10 }
		relation = { tag = NZL value = 25 }
		relation = { tag = OMN value = 25 }
		relation = { tag = PAN value = 1 }
		relation = { tag = PAR value = 1 }
		relation = { tag = PHI value = 1 }
		relation = { tag = POL value = 15 }
		relation = { tag = POR value = 15 }
		relation = { tag = PRU value = 1 }
		relation = { tag = ROM value = 1 }
		relation = { tag = SAF value = 30 }
		relation = { tag = SAL value = 1 }
		relation = { tag = SAU value = 35 }
		relation = { tag = SIA value = 1 }
		relation = { tag = SIK value = 1 }
		relation = { tag = SOV value = 25 }
		relation = { tag = SPA value = 1 }
		relation = { tag = SPR value = 1 }
		relation = { tag = SWE value = 1 }
		relation = { tag = SCH value = 50 }
		relation = { tag = TAN value = 1 }
		relation = { tag = TIB value = 1 }
		relation = { tag = TUR value = 40 }
		relation = { tag = U27 value = 1 }
		relation = { tag = URU value = 1 }
		relation = { tag = USA value = 40 }
		relation = { tag = VEN value = 1 }
		relation = { tag = YEM value = 20 }
		relation = { tag = YUG value = 1 }
	}

	SpyInfo = { country = "PER" NumberOfSpies = 6 }
	SpyInfo = { country = "AFG" NumberOfSpies = 4 }
	SpyInfo = { country = "EGY" NumberOfSpies = 2 }
	SpyInfo = { country = "ENG" NumberOfSpies = 1 }
	SpyInfo = { country = "ETH" NumberOfSpies = 1 }
	SpyInfo = { country = "FRA" NumberOfSpies = 1 }
	SpyInfo = { country = "GER" NumberOfSpies = 1 }
	SpyInfo = { country = "IND" NumberOfSpies = 4 }
	SpyInfo = { country = "IRQ" NumberOfSpies = 4 }
	SpyInfo = { country = "ITA" NumberOfSpies = 1 }
	SpyInfo = { country = "SAU" NumberOfSpies = 2 }
	SpyInfo = { country = "SIK" NumberOfSpies = 1 }
	SpyInfo = { country = "SOV" NumberOfSpies = 2 }
	SpyInfo = { country = "SCH" NumberOfSpies = 1 }
	SpyInfo = { country = "TUR" NumberOfSpies = 2 }
	SpyInfo = { country = "USA" NumberOfSpies = 1 }
	SpyInfo = { country = "YEM" NumberOfSpies = 1 }

  headofstate            = { type = 9 id = 53001 }
  headofgovernment       = { type = 9 id = 53002 }
  foreignminister        = { type = 9 id = 53003 }
  armamentminister       = { type = 9 id = 53004 }
  ministerofsecurity     = { type = 9 id = 53005 }
  ministerofintelligence = { type = 9 id = 53006 }
  chiefofstaff           = { type = 9 id = 53007 }
  chiefofarmy            = { type = 9 id = 53008 }
  chiefofnavy            = { type = 9 id = 53009 }
  chiefofair             = { type = 9 id = 53010 }
  landunit =
  { location = 1502
    name     = "Lasgar Parsi"
    id       = { type = 16600 id = 1 }
    division =
    { id    = { type = 16600 id = 2 }
      name  = "1. Dastebandi Sarbaze Piyade"
      type  = infantry
      extra = artillery
    }
    division =
    { id   = { type = 16600 id = 3 }
      name = "1. Dastebandi Savareh"
      type = cavalry
    }
  } 

navalunit = {
	id = { type = 16600 id = 30 }
	name = "Persian Navy"
	location = 1497
	base = 1497

	division = {
		id = { type = 16600 id = 31 }
		name = "1. Kabud Azdar"
		type = destroyer
		model = 0
		extra = naval_anti_air_s
		brigade_model = 0
		}
	}

	province_development = { 
		id = { type = 16600 id = 4 } 
		name = "" 
		progress = 0.0000 
		location = 1502 
		cost = 2.0000 
		date = { 
			year = 1943 
			month = july 
			day = 14 
			hour = 0 
			} 
		manpower = 0.1000 
		close_when_finished = yes 
		waitingforclosure = no 
		total_progress = 0.0000 
		size = 28 
		done = 0 
		days = 2715 
		days_for_first = 120 
		gearing_bonus = 0.0000 
		type = infrastructure 
		} 
	province_development = { 
		id = { type = 16600 id = 5 }
		name = "" 
		progress = 0.0000 
		location = 1825 
		cost = 2.0000 
		date = { 
			year = 1945 
			month = may 
			day = 0 
			hour = 0 
			} 
		manpower = 0.1000 
		close_when_finished = yes 
		waitingforclosure = no 
		total_progress = 0.0000 
		size = 28 
		done = 0 
		days = 2715 
		days_for_first = 120 
		gearing_bonus = 0.0000 
		type = infrastructure 
		} 
}
