#####################
# Country main data #
#####################

country =
{ tag                    = PRU
  # Resource Reserves
  energy                 = 390
  metal                  = 216
  rare_materials         = 216
  oil                    = 252
  supplies               = 632
  money                  = 20
  consumer = 0.2373 
  supply = 0.0991 
  production = 0.6636 
  reinforcement = 0.0000 
  upgrading = 0.0000 
  capital                = 830
  manpower               = 5.65 # 22 - building queue
  transports             = 16
  escorts                = 1

	diplomacy = {
		relation = { tag = AFG value = 1 }
		relation = { tag = ALB value = 1 }
		relation = { tag = ARG value = 20 }
		relation = { tag = AST value = 20 }
		relation = { tag = AUS value = 15 }
		relation = { tag = BEL value = 20 }
		relation = { tag = BHU value = 1 }
		relation = { tag = BOL value = -30 }
		relation = { tag = BRA value = -5 }
		relation = { tag = BUL value = 1 }
		relation = { tag = CAN value = 30 }
		relation = { tag = CGX value = 1 }
		relation = { tag = CHC value = 1 }
		relation = { tag = CHI value = 25 }
		relation = { tag = CHL value = 20 }
		relation = { tag = COL value = -10 }
		relation = { tag = COS value = 15 }
		relation = { tag = CSX value = 1 }
		relation = { tag = CUB value = 15 }
		relation = { tag = CXB value = 1 }
		relation = { tag = CYN value = 1 }
		relation = { tag = CZE value = 15 }
		relation = { tag = DEN value = 15 }
		relation = { tag = DOM value = 10 }
		relation = { tag = ECU value = -30 }
		relation = { tag = EGY value = 1 }
		relation = { tag = ENG value = 30 }
		relation = { tag = EST value = 10 }
		relation = { tag = ETH value = 1 }
		relation = { tag = FIN value = 15 }
		relation = { tag = FRA value = 20 }
		relation = { tag = GER value = 35 }
		relation = { tag = GRE value = 20 }
		relation = { tag = GUA value = 10 }
		relation = { tag = HAI value = 10 }
		relation = { tag = HOL value = 20 }
		relation = { tag = HON value = 10 }
		relation = { tag = HUN value = 10 }
		relation = { tag = IND value = 1 }
		relation = { tag = IRE value = 30 }
		relation = { tag = IRQ value = 1 }
		relation = { tag = ITA value = 30 }
		relation = { tag = JAP value = 40 }
		relation = { tag = LAT value = 1 }
		relation = { tag = LIB value = 1 }
		relation = { tag = LIT value = 1 }
		relation = { tag = LUX value = 1 }
		relation = { tag = MAN value = 1 }
		relation = { tag = MEX value = 20 }
		relation = { tag = MLY value = 1 }
		relation = { tag = MON value = 1 }
		relation = { tag = NEP value = 1 }
		relation = { tag = NIC value = 10 }
		relation = { tag = NOR value = 1 }
		relation = { tag = NZL value = 20 }
		relation = { tag = OMN value = 1 }
		relation = { tag = PAN value = 10 }
		relation = { tag = PAR value = 20 }
		relation = { tag = PER value = 1 }
		relation = { tag = PHI value = 1 }
		relation = { tag = POL value = 15 }
		relation = { tag = POR value = 10 }
		relation = { tag = ROM value = 1 }
		relation = { tag = SAF value = 20 }
		relation = { tag = SAL value = 10 }
		relation = { tag = SAU value = 20 }
		relation = { tag = SIA value = 1 }
		relation = { tag = SIK value = 1 }
		relation = { tag = SOV value = 10 }
		relation = { tag = SPA value = 15 }
		relation = { tag = SPR value = 15 }
		relation = { tag = SWE value = 10 }
		relation = { tag = SCH value = 50 }
		relation = { tag = TAN value = 1 }
		relation = { tag = TIB value = 1 }
		relation = { tag = TUR value = 15 }
		relation = { tag = U27 value = 1 }
		relation = { tag = URU value = 20 }
		relation = { tag = USA value = 50 }
		relation = { tag = VEN value = 20 }
		relation = { tag = YEM value = 1 }
		relation = { tag = YUG value = 1 }
}

	SpyInfo = { country = "PRU" NumberOfSpies = 4 }
	SpyInfo = { country = "ARG" NumberOfSpies = 2 }
	SpyInfo = { country = "BOL" NumberOfSpies = 4 }
	SpyInfo = { country = "BRA" NumberOfSpies = 4 }
	SpyInfo = { country = "ECU" NumberOfSpies = 6 }
	SpyInfo = { country = "ENG" NumberOfSpies = 1 }
	SpyInfo = { country = "JAP" NumberOfSpies = 2 }
	SpyInfo = { country = "PAR" NumberOfSpies = 4 }
	SpyInfo = { country = "URU" NumberOfSpies = 1 }
	SpyInfo = { country = "USA" NumberOfSpies = 1 }

  nationalprovinces      = { 831 829 830 821 816 818 }
  ownedprovinces         = { 831 829 830 821 816 }
  controlledprovinces    = { 831 829 830 821 816 }
  # ROTW Minor Tech '36
  # Group D 1936 techs
  # ######################
  # GW fighter
  techapps               = {  2290 2300 2310 1010 1190 1110 2450 2460 2510 5010 5080 5090 3130 3410 6010 3010 3070 3400 8020 8040 8050 }
  policy =
  { date              = { year = 0 month = january day = 0 }
    democratic        = 5
    political_left    = 2
    freedom           = 4
    free_market       = 4
    professional_army = 3
    defense_lobby     = 5
    interventionism   = 5
  }
  headofstate            = { type = 9 id = 39001 }
  headofgovernment       = { type = 9 id = 39002 }
  foreignminister        = { type = 9 id = 39003 }
  armamentminister       = { type = 9 id = 39004 }
  ministerofsecurity     = { type = 9 id = 39005 }
  ministerofintelligence = { type = 9 id = 39006 }
  chiefofstaff           = { type = 9 id = 39007 }
  chiefofarmy            = { type = 9 id = 39008 }
  chiefofnavy            = { type = 9 id = 39009 }
  chiefofair             = { type = 9 id = 39010 }
  landunit =
  { id       = { type = 17600 id = 1 }
    name     = "Ejercito del Peru"
    location = 830
    division =
    { id       = { type = 17600 id = 2 }
      name     = "1a Div. de Inf. del Peru 'Bolognesi'"
      strength = 100
      type     = infantry
    }
    division =
    { id       = { type = 17600 id = 3 }
      name     = "2a Div. de Infantería del Peru"
      strength = 100
      type     = infantry
    }
    division =
    { id       = { type = 17600 id = 4 }
      name     = "3a Div. de Infantería del Peru"
      strength = 100
      type     = infantry
    }
    division =
    { id       = { type = 17600 id = 5 }
      name     = "1a Brigada Fuerzas Especiales"
      strength = 100
      type     = bergsjaeger
    }
  }
  navalunit =
  { id       = { type = 17600 id = 6 }
    name     = "Marina del Guerra del Peru"
    location = 830
    base     = 830
    # Two DDs:
    division =
    { id    = { type = 17600 id = 7 }
      name  = "Suliana é Flotilla"
      type  = destroyer
      model = 0
    }
    # Built 1907:
    division =
    { id    = { type = 17600 id = 8 }
      name  = "ARP Almirante Grau"
      type  = heavy_cruiser
      model = 0
      extra1 = naval_sa_l
      extra2 = naval_anti_air_l
      extra3 = none
      brigade_model1 = 0
      brigade_model2 = 0
      brigade_model3 = 0
    }
    division =
    { id    = { type = 17600 id = 9 }
      name  = "ARP Coronel Bolognesi"
      type  = heavy_cruiser
      model = 0
      extra1 = naval_sa_l
      extra2 = naval_anti_air_l
      extra3 = none
      brigade_model1 = 0
      brigade_model2 = 0
      brigade_model3 = 0
    }
    # Submarine division:
    division =
    { id    = { type = 17600 id = 10 }
      name  = "Tacna é Flotilla"
      type  = submarine
      model = 1
    }
  } 
	province_development = { 
		id = { type = 17600 id = 11 } 
		name = "" 
		progress = 0.0000 
		location = 830 
		cost = 2.0000 
		date = { 
			year = 1943 
			month = july 
			day = 14 
			hour = 0 
			} 
		manpower = 0.1000 
		close_when_finished = yes 
		waitingforclosure = no 
		total_progress = 0.0000 
		size = 28 
		done = 0 
		days = 2715 
		days_for_first = 120 
		gearing_bonus = 0.0000 
		type = infrastructure 
		} 
	province_development = { 
		id = { type = 17600 id = 12 } 
		name = "" 
		progress = 0.0000 
		location = 816 
		cost = 2.0000 
		date = { 
			year = 1943 
			month = july 
			day = 14 
			hour = 0 
			} 
		manpower = 0.1000 
		close_when_finished = yes 
		waitingforclosure = no 
		total_progress = 0.0000 
		size = 28 
		done = 0 
		days = 2715 
		days_for_first = 120 
		gearing_bonus = 0.0000 
		type = infrastructure 
		} 
	province_development = { 
		id = { type = 17600 id = 13 } 
		name = "" 
		progress = 0.0000 
		location = 831 
		cost = 2.0000 
		date = { 
			year = 1954 
			month = november 
			day = 7 
			hour = 0 
			} 
		manpower = 0.1000 
		close_when_finished = yes 
		waitingforclosure = no 
		total_progress = 0.0000 
		size = 28 
		done = 0 
		days = 2715 
		days_for_first = 300 
		gearing_bonus = 0.0000 
		type = infrastructure 
		} 
	brigade_development = { 
		id = { type = 17600 id = 14 } 
		name = "Capital Torpedoes" 
		progress = 0.0000 
		location = 830 
		cost = 0.6000 
		date = { 
			year = 1936 
			month = may 
			day = 24 
			hour = 0 
			} 
		manpower = 0.0500 
		close_when_finished = yes 
		waitingforclosure = no 
		retooling_time = 27.0000 
		total_progress = 0.0000 
		size = 2 
		done = 0 
		days = 117 
		days_for_first = 60 
		gearing_bonus = 0.0000 
		type = naval_torpedoes_l 
		model = 0 
		} 
	brigade_development = { 
		id = { type = 17600 id = 15 } 
		name = "Basic Sea Mines" 
		progress = 0.0000 
		location = 830 
		cost = 0.3000 
		date = { 
			year = 1936 
			month = may 
			day = 24 
			hour = 0 
			} 
		manpower = 0.0500 
		close_when_finished = yes 
		waitingforclosure = no 
		retooling_time = 27.0000 
		total_progress = 0.0000 
		size = 2 
		done = 0 
		days = 117 
		days_for_first = 60 
		gearing_bonus = 0.0000 
		type = naval_mines 
		model = 0 
		} 
	brigade_development = { 
		id = { type = 17600 id = 16 } 
		name = "Torpedoes" 
		progress = 0.0000 
		location = 830 
		cost = 0.6000 
		date = { 
			year = 1936 
			month = may 
			day = 24 
			hour = 0 
			} 
		manpower = 0.0500 
		close_when_finished = yes 
		waitingforclosure = no 
		retooling_time = 27.0000 
		total_progress = 0.0000 
		size = 2 
		done = 0 
		days = 117 
		days_for_first = 60 
		gearing_bonus = 0.0000 
		type = naval_torpedoes_s 
		model = 0 
		} 
}
