#####################
# Country main data #
#####################

country =
{ tag                    = POL
  capital                = 485
  manpower               = 275.4000 # 275 - building queue
  transports             = 32
  escorts                = 2
  # Resource Reserves
  energy                 = 6030
  metal                  = 1666
  rare_materials         = 701
  oil                    = 192
  supplies               = 1986
  money                  = 80
  consumer = 0.2280 
  supply = 0.1550 
  production = 0.6170 
  reinforcement = 0.0000 
  upgrading = 0.0000 

	diplomacy = {
		relation = { tag = AFG value = 1 }
		relation = { tag = ALB value = 15 }
		relation = { tag = ARG value = 10 }
		relation = { tag = AST value = 25 }
		relation = { tag = AUS value = 25 }
		relation = { tag = BEL value = 30 }
		relation = { tag = BHU value = 1 }
		relation = { tag = BOL value = 1 }
		relation = { tag = BRA value = 15 }
		relation = { tag = BUL value = 25 }
		relation = { tag = CAN value = 35 }
		relation = { tag = CGX value = 1 }
		relation = { tag = CHC value = 1 }
		relation = { tag = CHI value = 5 }
		relation = { tag = CHL value = 1 }
		relation = { tag = COL value = 10 }
		relation = { tag = COS value = 1 }
		relation = { tag = CSX value = 1 }
		relation = { tag = CUB value = 1 }
		relation = { tag = CXB value = 1 }
		relation = { tag = CYN value = 1 }
		relation = { tag = CZE value = 50 }
		relation = { tag = DEN value = 35 }
		relation = { tag = DOM value = 1 }
		relation = { tag = ECU value = 10 }
		relation = { tag = EGY value = 1 }
		relation = { tag = ENG value = 45 }
		relation = { tag = EST value = 25 }
		relation = { tag = ETH value = 5 }
		relation = { tag = FIN value = 30 }
		relation = { tag = FRA value = 50 }
		relation = { tag = GER value = 25 }
		relation = { tag = GRE value = 5 }
		relation = { tag = GUA value = 1 }
		relation = { tag = HAI value = 1 }
		relation = { tag = HOL value = 30 }
		relation = { tag = HON value = 1 }
		relation = { tag = HUN value = 30 }
		relation = { tag = IND value = 1 }
		relation = { tag = IRE value = 15 }
		relation = { tag = IRQ value = 1 }
		relation = { tag = ITA value = 30 }
		relation = { tag = JAP value = 15 }
		relation = { tag = LAT value = 20 }
		relation = { tag = LIB value = 1 }
		relation = { tag = LIT value = -25 }
		relation = { tag = LUX value = 10 }
		relation = { tag = MAN value = 1 }
		relation = { tag = MEX value = 25 }
		relation = { tag = MLY value = 1 }
		relation = { tag = MON value = 1 }
		relation = { tag = NEP value = 1 }
		relation = { tag = NIC value = 1 }
		relation = { tag = NOR value = 20 }
		relation = { tag = NZL value = 25 }
		relation = { tag = OMN value = 1 }
		relation = { tag = PAN value = 1 }
		relation = { tag = PAR value = 1 }
		relation = { tag = PER value = 15 }
		relation = { tag = PHI value = 1 }
		relation = { tag = POR value = 20 }
		relation = { tag = PRU value = 15 }
		relation = { tag = ROM value = 45 guaranteed = { day = 30 month = december year = 1934 } }
		relation = { tag = SAF value = 30 }
		relation = { tag = SAL value = 1 }
		relation = { tag = SAU value = 10 }
		relation = { tag = SIA value = 1 }
		relation = { tag = SIK value = 1 }
		relation = { tag = SOV value = 35 }
		relation = { tag = SPA value = 10 }
		relation = { tag = SPR value = 30 }
		relation = { tag = SWE value = 30 }
		relation = { tag = SCH value = 50 }
		relation = { tag = TAN value = 1 }
		relation = { tag = TIB value = 1 }
		relation = { tag = TUR value = 45 }
		relation = { tag = U27 value = 1 }
		relation = { tag = URU value = 1 }
		relation = { tag = USA value = 25 }
		relation = { tag = VEN value = 30 }
		relation = { tag = YEM value = 1 }
		relation = { tag = YUG value = 30 }
	}

	SpyInfo = { country = "POL" NumberOfSpies = 6 }
	SpyInfo = { country = "AUS" NumberOfSpies = 1 }
	SpyInfo = { country = "BUL" NumberOfSpies = 2 }
	SpyInfo = { country = "CAN" NumberOfSpies = 1 }
	SpyInfo = { country = "CZE" NumberOfSpies = 4 }
	SpyInfo = { country = "DEN" NumberOfSpies = 1 }
	SpyInfo = { country = "EGY" NumberOfSpies = 1 }
	SpyInfo = { country = "ENG" NumberOfSpies = 2 }
	SpyInfo = { country = "EST" NumberOfSpies = 2 }
	SpyInfo = { country = "FRA" NumberOfSpies = 4 }
	SpyInfo = { country = "GER" NumberOfSpies = 4 }
	SpyInfo = { country = "HUN" NumberOfSpies = 4 }
	SpyInfo = { country = "LAT" NumberOfSpies = 2 }
	SpyInfo = { country = "LIT" NumberOfSpies = 2 }
	SpyInfo = { country = "POR" NumberOfSpies = 3 }
	SpyInfo = { country = "ROM" NumberOfSpies = 2 }
	SpyInfo = { country = "SOV" NumberOfSpies = 6 }
	SpyInfo = { country = "SPR" NumberOfSpies = 2 }
	SpyInfo = { country = "SWE" NumberOfSpies = 1 }
	SpyInfo = { country = "SCH" NumberOfSpies = 1 }
	SpyInfo = { country = "USA" NumberOfSpies = 1 }
	SpyInfo = { country = "BRA" NumberOfSpies = 1 }
	SpyInfo = { country = "PRU" NumberOfSpies = 1 }
	SpyInfo = { country = "JAP" NumberOfSpies = 1 }
	SpyInfo = { country = "CHI" NumberOfSpies = 1 }

  nationalprovinces      = { 303 306 307 479 480 481 483 484 305 485 486 487 489 488 500 501 502 503 504 505 506 507 508 509 209 208 213 211 210 222
                             229 562 214 212 221 225 226 227 228 231 218
                           }
  ownedprovinces         = { 303 306 307 479 480 481 483 484 305 485 486 487 489 488 500 501 502 503 504 505 506 507 508 509 209 208 213 211 210 222
                             229 562 214
                           }
  controlledprovinces    = { 303 306 307 479 480 481 483 484 305 485 486 487 489 488 500 501 502 503 504 505 506 507 508 509 209 208 213 211 210 222
                             229 562 214
                           }
  # Air Doctrines
  techapps               = { 1010  1020  1110  1190  1200  1310  14000 2010  2020     2290  2300  2310  2400  2450  2460  2510  3010  3020  3400 
                             3410  4010  4020  4120  4130  5010  5080  5090  5190  6010  6030  8040  8050  9010  9020  1210  5310
                           }
  blueprints             = { 5360 5380 5400 2150 }
  policy =
  { date              = { year = 0 month = january day = 0 }
    democratic        = 7
    political_left    = 1
    freedom           = 4
    free_market       = 5
    professional_army = 3
    defense_lobby     = 8
    interventionism   = 6
  }
  headofstate            = { type = 9 id = 13001 }
  headofgovernment       = { type = 9 id = 13002 }
  foreignminister        = { type = 9 id = 13003 }
  armamentminister       = { type = 9 id = 13004 }
  ministerofsecurity     = { type = 9 id = 13005 }
  ministerofintelligence = { type = 9 id = 13006 }
  chiefofstaff           = { type = 9 id = 13007 }
  chiefofarmy            = { type = 9 id = 13008 }
  chiefofnavy            = { type = 9 id = 13009 }
  chiefofair             = { type = 9 id = 13010 }
  landunit =
  { id       = { type = 18600 id = 1 }
    location = 479
    name     = "Armia Krakow"
    division =
    { id   = { type = 18600 id = 2 }
      name = "6 Dywizja Piechoty"
      type = infantry
    }
    division =
    { id    = { type = 18600 id = 3 }
      name  = "7 Dywizja Piechoty"
      type  = infantry
      extra = artillery
    }
    division =
    { id   = { type = 18600 id = 4 }
      name = "22 Dywizja Piechoty Górskiej"
      type = bergsjaeger
    }
    division =
    { id   = { type = 18600 id = 5 }
      name = "21 Dywizja Piechoty Górskiej"
      type = bergsjaeger
    }
    division =
    { id   = { type = 18600 id = 6 }
      name = "23 Dywizja Piechoty"
      type = infantry
    }
  }
  landunit =
  { id       = { type = 18600 id = 7 }
    location = 483
    name     = "Armia Lodz"
    division =
    { id   = { type = 18600 id = 8 }
      name = "2 Dywizja Piechoty"
      type = infantry
    }
    division =
    { id    = { type = 18600 id = 9 }
      name  = "10 Dywizja Piechoty"
      type  = infantry
      extra = anti_air
    }
    division =
    { id   = { type = 18600 id = 10 }
      name = "29 Dywizja Piechoty"
      type = infantry
    }
  }
  landunit =
  { id       = { type = 18600 id = 11 }
    location = 487
    name     = "Armia Lublin"
    division =
    { id   = { type = 18600 id = 12 }
      name = "18 Dywizja Piechoty"
      type = infantry
    }
    division =
    { id   = { type = 18600 id = 13 }
      name = "28 Dywizja Piechoty"
      type = infantry
    }
    division =
    { id    = { type = 18600 id = 14 }
      name  = "30 Dywizja Piechoty"
      type  = infantry
      extra = anti_tank
    }
  }
  landunit =
  { id       = { type = 18600 id = 15 }
    location = 486
    name     = "Armia Modlin"
    division =
    { id   = { type = 18600 id = 16 }
      name = "8 Dywizja Piechoty"
      type = infantry
    }
    division =
    { id    = { type = 18600 id = 17 }
      name  = "20 Dywizja Piechoty"
      type  = infantry
      extra = engineer
    }
  }
  landunit =
  { id       = { type = 18600 id = 18 }
    location = 303
    name     = "Armia Pomorze"
    division =
    { id   = { type = 18600 id = 19 }
      name = "4 Dywizja Piechoty"
      type = infantry
    }
    division =
    { id   = { type = 18600 id = 20 }
      name = "16 Dywizja Piechoty"
      type = infantry
    }
    division =
    { id    = { type = 18600 id = 21 }
      name  = "9 Dywizja Piechoty"
      type  = infantry
      extra = artillery
    }
    division =
    { id   = { type = 18600 id = 22 }
      name = "15 Dywizja Piechoty"
      type = infantry
    }
    division =
    { id   = { type = 18600 id = 23 }
      name = "27 Dywizja Piechoty"
      type = infantry
    }
    division =
    { id   = { type = 18600 id = 58 }
      name = "Nowogródzka B.K."
      type = cavalry
    }
  }
  landunit =
  { id       = { type = 18600 id = 24 }
    location = 307
    name     = "Armia Poznan"
    division =
    { id   = { type = 18600 id = 25 }
      name = "14 Dywizja Piechoty"
      type = infantry
    }
    division =
    { id   = { type = 18600 id = 26 }
      name = "17 Dywizja Piechoty"
      type = infantry
    }
    division =
    { id   = { type = 18600 id = 27 }
      name = "25 Dywizja Piechoty"
      type = infantry
    }
    division =
    { id    = { type = 18600 id = 28 }
      name  = "26 Dywizja Piechoty"
      type  = infantry
      extra = anti_air
    }
    division =
    { id   = { type = 18600 id = 57 }
      name = "Krakowska B.K."
      type = cavalry
    }
  }
  landunit =
  { id       = { type = 18600 id = 29 }
    location = 305
    name     = "Armia Prusy"
    division =
    { id   = { type = 18600 id = 30 }
      name = "3 Dywizja Piechoty Legionów"
      type = infantry
    }
    division =
    { id   = { type = 18600 id = 31 }
      name = "12 Dywizja Piechoty"
      type = infantry
    }
    division =
    { id    = { type = 18600 id = 32 }
      name  = "13 Dywizja Piechoty"
      type  = infantry
      extra = anti_tank
    }
    division =
    { id   = { type = 18600 id = 33 }
      name = "19 Dywizja Piechoty"
      type = infantry
    }
    division =
    { id   = { type = 18600 id = 56 }
      name = "Kresowa B.K."
      type = cavalry
    }
  }
  landunit =
  { id       = { type = 18600 id = 34 }
    location = 485
    name     = "Armia Warszawa"
    division =
    { id       = { type = 18600 id = 63 }
      name     = "Army HQ"
      type     = hq
      model    = 0
      strength = 100
      extra    = anti_air
    }
    division =
    { id    = { type = 18600 id = 35 }
      name  = "Mazowiecka B.K."
      type  = cavalry
      extra = engineer
    }
    division =
    { id   = { type = 18600 id = 36 }
      name = "1 DP Legionów im. Pilsudskiego"
      type = infantry
    }
    division =
    { id   = { type = 18600 id = 37 }
      name = "5 Dywizja Piechoty"
      type = infantry
    }
    division =
    { id   = { type = 18600 id = 38 }
      name = "11 Karpacka Dywizja Piechoty"
      type = infantry
    }
    division =
    { id   = { type = 18600 id = 39 }
      name = "24 Dywizja Piechoty"
      type = infantry
    }
  }
  landunit =
  { id       = { type = 18600 id = 40 }
    name     = "Armia Rezerwa"
    location = 487
    division =
    { id       = { type = 18600 id = 41 }
      name     = "31 D. Piechoty (Rezerwowa)"
      strength = 30
      type     = infantry
    }
    division =
    { id       = { type = 18600 id = 42 }
      name     = "33 D. Piechoty (Rezerwowa)"
      strength = 30
      type     = infantry
    }
    division =
    { id       = { type = 18600 id = 43 }
      name     = "35 D. Piechoty (Rezerwowa)"
      strength = 30
      type     = infantry
      extra    = artillery
    }
    division =
    { id       = { type = 18600 id = 44 }
      name     = "36 D. Piechoty (Rezerwowa)"
      strength = 30
      type     = infantry
    }
    division =
    { id       = { type = 18600 id = 45 }
      name     = "38 D. Piechoty (Rezerwowa)"
      strength = 30
      type     = infantry
    }
    division =
    { id       = { type = 18600 id = 46 }
      name     = "39 D. Piechoty (Rezerwowa)"
      strength = 30
      type     = infantry
    }
    division =
    { id       = { type = 18600 id = 47 }
      name     = "41 D. Piechoty (Rezerwowa)"
      strength = 30
      type     = infantry
    }
    division =
    { id       = { type = 18600 id = 48 }
      name     = "44 D. Piechoty (Rezerwowa)"
      strength = 30
      type     = infantry
    }
    division =
    { id       = { type = 18600 id = 49 }
      name     = "45 D. Piechoty (Rezerwowa)"
      strength = 30
      type     = infantry
    }
    division =
    { id       = { type = 18600 id = 50 }
      name     = "55 D. Piechoty (Rezerwowa)"
      strength = 30
      type     = infantry
    }
    division =
    { id       = { type = 18600 id = 51 }
      name     = "53 D. Piechoty (Rezerwowa)"
      strength = 30
      type     = infantry
    }
    division =
    { id       = { type = 18600 id = 52 }
      name     = "54 D. Piechoty (Rezerwowa)"
      strength = 30
      type     = infantry
    }
  }

#########################################################################
# Navy
#########################################################################

navalunit = {
	id = { type = 18600 id = 3000 }
	name = "Marynarka Wojenna"
	location = 303
	base = 303

	division = {
		id = { type = 18600 id = 3001 }
		name = "1 Flota Niszczycieli"
		type = destroyer
		strength = 65
		max_strength = 65
		model = 0
		extra = naval_torpedoes_s
		brigade_model = 0
		}
	division = {
		id = { type = 18600 id = 3002 }
		name = "2 Flota Niszczycieli"
		type = destroyer
		model = 0
		extra = naval_mines
		brigade_model = 0
		}
	}

navalunit = {
	id = { type = 18600 id = 3003 }
	name = "1. Flotylla Okretów Podwodnych"
	location = 303
	base = 303

	division = {
		id = { type = 18600 id = 3004 }
		name = "1. Flotylla Okretów Podwodnych" # ORP Rys, Wilk & Zbik
		type = submarine
		strength = 75
		max_strength = 75
		model = 0
		}
	}

#########################################################################
# Air Force
#########################################################################

  airunit =
  { id       = { type = 18600 id = 59 }
    name     = "III/1 Dyon Brygady Poscigowej"
    location = 485
    base     = 485
    division =
    { id    = { type = 18600 id = 60 }
      name  = "III/1 Dyon Brygady Poscigowej"
      type  = interceptor
      model = 0
    }
    division =
    { id    = { type = 18600 id = 61 }
      name  = "IV/1 Dyon Brygady Poscigowej"
      type  = interceptor
      model = 0
    }
    division =
    { id    = { type = 18600 id = 62 }
      name  = "1 Dywizjon Bombowców Ciezkich"
      type  = tactical_bomber
      model = 0
    }
  } 

#########################################################################
# Constructions
#########################################################################

	province_development = { 
		id = { type = 18600 id = 64 } 
		name = "" 
		progress = 0.0000 
		location = 485 
		cost = 2.0000 
		date = { 
			year = 1939 
			month = may 
			day = 23 
			hour = 0 
			} 
		manpower = 0.1000 
		close_when_finished = yes 
		waitingforclosure = no 
		total_progress = 0.0000 
		size = 20 
		done = 0 
		days = 1953 
		days_for_first = 106 
		gearing_bonus = 0.0000 
		speed_step = 1 
		type = infrastructure 
		} 
	province_development = { 
		id = { type = 18600 id = 65 } 
		name = "" 
		progress = 0.0000 
		location = 479 
		cost = 2.0000 
		date = { 
			year = 1939 
			month = may 
			day = 23 
			hour = 0 
			} 
		manpower = 0.1000 
		close_when_finished = yes 
		waitingforclosure = no 
		total_progress = 0.0000 
		size = 20 
		done = 0 
		days = 1953 
		days_for_first = 106 
		gearing_bonus = 0.0000 
		speed_step = 1 
		type = infrastructure 
		} 
	province_development = { 
		id = { type = 18600 id = 67 } 
		name = "" 
		progress = 0.0000 
		location = 487 
		cost = 2.0000 
		date = { 
			year = 1940 
			month = january 
			day = 19 
			hour = 0 
			} 
		manpower = 0.1000 
		close_when_finished = yes 
		waitingforclosure = no 
		total_progress = 0.0000 
		size = 24 
		done = 0 
		days = 1874 
		days_for_first = 106 
		gearing_bonus = 0.0000 
		speed_step = 1 
		type = infrastructure 
		} 
	province_development = { 
		id = { type = 18600 id = 70 } 
		name = "" 
		progress = 0.0000 
		location = 481 
		cost = 2.0000 
		date = { 
			year = 1941 
			month = september 
			day = 24 
			hour = 0 
			} 
		manpower = 0.1000 
		close_when_finished = yes 
		waitingforclosure = no 
		total_progress = 0.0000 
		size = 24 
		done = 0 
		days = 1953 
		days_for_first = 106 
		gearing_bonus = 0.0000 
		type = infrastructure 
		} 
	province_development = { 
		id = { type = 18600 id = 68 } 
		name = "" 
		progress = 0.0000 
		location = 488 
		cost = 2.0000 
		date = { 
			year = 1941 
			month = september 
			day = 24 
			hour = 0 
			} 
		manpower = 0.1000 
		close_when_finished = yes 
		waitingforclosure = no 
		total_progress = 0.0000 
		size = 24 
		done = 0 
		days = 1953 
		days_for_first = 106 
		gearing_bonus = 0.0000 
		type = infrastructure 
		} 
#	province_development = { 
#		id = { type = 18600 id = 69 } 
#		name = "" 
#		progress = 0.0000 
#		location = 307 
#		cost = 2.0000 
#		date = { 
#			year = 1940 
#			month = october 
#			day = 19 
#			hour = 0 
#			} 
#		manpower = 0.1000 
#		close_when_finished = yes 
#		waitingforclosure = no 
#		total_progress = 0.0000 
#		size = 20 
#		done = 0 
#		days = 1637 
#		days_for_first = 106 
#		gearing_bonus = 0.0000 
#		type = infrastructure 
#		} 
#	province_development = { 
#		id = { type = 18600 id = 66 } 
#		name = "" 
#		progress = 0.0000 
#		location = 480 
#		cost = 2.0000 
#		date = { 
#			year = 1941 
#			month = september 
#			day = 24 
#			hour = 0 
#			} 
#		manpower = 0.1000 
#		close_when_finished = yes 
#		waitingforclosure = no 
#		total_progress = 0.0000 
#		size = 24 
#		done = 0 
#		days = 1874 
#		days_for_first = 106 
#		gearing_bonus = 0.0000 
#		type = infrastructure 
#		} 
	province_development = { 
		id = { type = 18600 id = 71 } 
		name = "" 
		progress = 0.0000 
		location = 500 
		cost = 2.0000 
		date = { 
			year = 1941 
			month = september 
			day = 24 
			hour = 0 
			} 
		manpower = 0.1000 
		close_when_finished = yes 
		waitingforclosure = no 
		total_progress = 0.0000 
		size = 24 
		done = 0 
		days = 1953 
		days_for_first = 106 
		gearing_bonus = 0.0000 
		type = infrastructure 
		} 
}
