#####################
# Country main data #
#####################

country =
{ tag                    = POR
  # Resource Reserves
  energy                 = 1000
  metal                  = 1000
  rare_materials         = 500
  oil                    = 500
  supplies               = 500
  money                  = 15
  consumer = 0.2111 
  supply = 0.0556 
  production = 0.7333 
  reinforcement = 0.0000 
  upgrading = 0.0000 
  capital                = 336
  manpower               = 68.4500 # 70 - building queue
  transports             = 62

	diplomacy = {
		relation = { tag = AFG value = 1 }
		relation = { tag = ALB value = 15 }
		relation = { tag = ARG value = 10 }
		relation = { tag = AST value = 30 }
		relation = { tag = AUS value = 20 }
		relation = { tag = BEL value = 30 }
		relation = { tag = BHU value = 1 }
		relation = { tag = BOL value = 1 }
		relation = { tag = BRA value = 50 }
		relation = { tag = BUL value = 20 }
		relation = { tag = CAN value = 30 }
		relation = { tag = CGX value = 25 }
		relation = { tag = CHC value = -10 }
		relation = { tag = CHI value = 35 }
		relation = { tag = CHL value = 10 }
		relation = { tag = COL value = 10 }
		relation = { tag = COS value = 1 }
		relation = { tag = CSX value = 1 }
		relation = { tag = CUB value = 1 }
		relation = { tag = CXB value = 1 }
		relation = { tag = CYN value = 1 }
		relation = { tag = CZE value = 20 }
		relation = { tag = DEN value = 20 }
		relation = { tag = DOM value = 1 }
		relation = { tag = ECU value = 10 }
		relation = { tag = EGY value = 1 }
		relation = { tag = ENG value = 45 }
		relation = { tag = EST value = 20 }
		relation = { tag = ETH value = 20 }
		relation = { tag = FIN value = 20 }
		relation = { tag = FRA value = 35 }
		relation = { tag = GER value = 40 }
		relation = { tag = GRE value = 25 }
		relation = { tag = GUA value = 1 }
		relation = { tag = HAI value = 1 }
		relation = { tag = HOL value = 20 }
		relation = { tag = HON value = 1 }
		relation = { tag = HUN value = 20 }
		relation = { tag = IND value = 20 }
		relation = { tag = IRE value = 35 }
		relation = { tag = IRQ value = 1 }
		relation = { tag = ITA value = 35 }
		relation = { tag = JAP value = 25 }
		relation = { tag = LAT value = 20 }
		relation = { tag = LIB value = 1 }
		relation = { tag = LIT value = 20 }
		relation = { tag = LUX value = 20 }
		relation = { tag = MAN value = 1 }
		relation = { tag = MEX value = 10 }
		relation = { tag = MLY value = 1 }
		relation = { tag = MON value = 1 }
		relation = { tag = NEP value = 1 }
		relation = { tag = NIC value = 1 }
		relation = { tag = NOR value = 20 }
		relation = { tag = NZL value = 35 }
		relation = { tag = OMN value = 1 }
		relation = { tag = PAN value = 25 }
		relation = { tag = PAR value = 1 }
		relation = { tag = PER value = 15 }
		relation = { tag = PHI value = 20 }
		relation = { tag = POL value = 20 }
		relation = { tag = PRU value = 10 }
		relation = { tag = ROM value = 25 }
		relation = { tag = SAF value = 35 }
		relation = { tag = SAL value = 1 }
		relation = { tag = SAU value = 15 }
		relation = { tag = SIA value = -10 }
		relation = { tag = SIK value = 1 }
		relation = { tag = SOV value = 20 }
		relation = { tag = SPA value = 15 }
		relation = { tag = SPR value = -15 }
		relation = { tag = SWE value = 20 }
		relation = { tag = SCH value = 50 }
		relation = { tag = TAN value = 1 }
		relation = { tag = TIB value = 1 }
		relation = { tag = TUR value = 25 }
		relation = { tag = U27 value = 1 }
		relation = { tag = URU value = 1 }
		relation = { tag = USA value = 35 }
		relation = { tag = VEN value = 10 }
		relation = { tag = YEM value = 1 }
		relation = { tag = YUG value = 20 }
}

	SpyInfo = { country = "POR" NumberOfSpies = 2 }
	SpyInfo = { country = "AST" NumberOfSpies = 1 }
	SpyInfo = { country = "BEL" NumberOfSpies = 2 }
	SpyInfo = { country = "BRA" NumberOfSpies = 4 }
	SpyInfo = { country = "CAN" NumberOfSpies = 1 }
	SpyInfo = { country = "CGX" NumberOfSpies = 2 }
	SpyInfo = { country = "CHI" NumberOfSpies = 2 }
	SpyInfo = { country = "CSX" NumberOfSpies = 2 }
	SpyInfo = { country = "CYN" NumberOfSpies = 1 }
	SpyInfo = { country = "ECU" NumberOfSpies = 1 }
	SpyInfo = { country = "ENG" NumberOfSpies = 4 }
	SpyInfo = { country = "FRA" NumberOfSpies = 2 }
	SpyInfo = { country = "GER" NumberOfSpies = 1 }
	SpyInfo = { country = "HOL" NumberOfSpies = 2 }
	SpyInfo = { country = "IND" NumberOfSpies = 1 }
	SpyInfo = { country = "IRE" NumberOfSpies = 1 }
	SpyInfo = { country = "JAP" NumberOfSpies = 1 }
	SpyInfo = { country = "MAN" NumberOfSpies = 1 }
	SpyInfo = { country = "MEX" NumberOfSpies = 1 }
	SpyInfo = { country = "MLY" NumberOfSpies = 1 }
	SpyInfo = { country = "PAN" NumberOfSpies = 1 }
	SpyInfo = { country = "PHI" NumberOfSpies = 1 }
	SpyInfo = { country = "SAF" NumberOfSpies = 2 }
	SpyInfo = { country = "SIA" NumberOfSpies = 1 }
	SpyInfo = { country = "SOV" NumberOfSpies = 1 }
	SpyInfo = { country = "SPR" NumberOfSpies = 6 }
	SpyInfo = { country = "SCH" NumberOfSpies = 1 }
	SpyInfo = { country = "TUR" NumberOfSpies = 1 }
	SpyInfo = { country = "USA" NumberOfSpies = 1 }

  nationalprovinces      = { 335 336 337 344 345 1867
 #1090 # Sao Tome
 #983 1096 1097 1101 1100 1102 1103 1122 1123 1130 1131 1133 1138 1316 1094 # All but East Timor
 #1146 Cape Verde
 }
  ownedprovinces         = { 335 336 337 344 345 1867 1146 983 1090 1096 1097 1101 1100 1102 1103 1122 1123 1130 1131 1133 1138 1658 1316 1094 }
  # Cabinda
  controlledprovinces    = { 335 336 337 344 345 1867 1146 983 1090 1096 1097 1101 1100 1102 1103 1122 1123 1130 1131 1133 1138 1658 1316 1094 }
  # Western Minor Tech '36
  # Group C 1936 techs
  # ######################
  techapps               = { 1010 1110 1190 2010 2020   2290 2300 2310 2450 2460 2510 3010 3020 3070 3400 3410 4010 4020 4120 5010 5080 5090 5190
                             6010 6020 8040 8050 9010
                           }
  policy =
  { date              = { year = 0 month = january day = 0 }
    democratic        = 3
    political_left    = 4
    freedom           = 4
    free_market       = 5
    professional_army = 4
    defense_lobby     = 5
    interventionism   = 3
  }
  headofstate            = { type = 9 id = 9001 }
  headofgovernment       = { type = 9 id = 9002 }
  foreignminister        = { type = 9 id = 9003 }
  armamentminister       = { type = 9 id = 9004 }
  ministerofsecurity     = { type = 9 id = 9005 }
  ministerofintelligence = { type = 9 id = 9006 }
  chiefofstaff           = { type = 9 id = 9007 }
  chiefofarmy            = { type = 9 id = 9008 }
  chiefofnavy            = { type = 9 id = 9009 }
  chiefofair             = { type = 9 id = 9010 }

#ARMY OOB

landunit = {
	id = { type = 19600 id = 1000 }
	location = 336
	name = "Governo Militar de Lisboa"

	division = {
		id = { type = 19600 id = 1001 }
		name = "Governo Militar de Lisboa"
		type = militia
		model = 0
		strength = 60
		}

	division = {
		id = { type = 19600 id = 1002 }
		name = "1o Batalhão de Cavalaria"
		type = cavalry
		model = 0
		strength = 60
		extra = armored_car
		brigade_model = 0
		}
	}

landunit = {
	id = { type = 19600 id = 1003 }
	location = 335
	name = "1a Região"

	division = {
		id = { type = 19600 id = 1004 }
		name = "1a Região"
		type = militia
		model = 0
		strength = 60
		}
	}

landunit = {
	id = { type = 19600 id = 1005 }
	location = 337
	name = "2a Região"

	division = {
		id = { type = 19600 id = 1006 }
		name = "2a Região"
		type = militia
		model = 0
		strength = 60
		extra = b_u9
		brigade_model = 0
		}
	}

landunit = {
	id = { type = 19600 id = 1007 }
	location = 336
	name = "3a Região"

	division = {
		id = { type = 19600 id = 1008 }
		name = "3a Região"
		type = militia
		model = 0
		strength = 60
		extra = b_u9
		brigade_model = 0
		}
	}

landunit = {
	id = { type = 19600 id = 1009 }
	location = 344
	name = "4a Região"

	division = {
		id = { type = 19600 id = 1010 }
		name = "4a Região"
		type = militia
		model = 0
		strength = 60
		extra = b_u9
		brigade_model = 0
		}
	}

landunit = {
	id = { type = 19600 id = 1110 }
	name = "Comando Militar de Angola"
	location = 1096

	division = {
		id = { type = 19600 id = 1111 }
		name = "Comando Militar de Angola"
		type = garrison
		model = 0
		strength = 40
		extra = police
		brigade_model = 0
		}
	}

landunit = {
	id = { type = 19600 id = 1112 }
	name = "Comando Militar de Mocambique"
	location = 1122 # Lourenço Marques

	division = {
		id = { type = 19600 id = 1113 }
		name = "Comando Militar de Mocambique"
		type = garrison
		model = 0
		strength = 40
		extra = police
		brigade_model = 0
		}
	}

#NAVY OOB

navalunit = {
	id = { type = 19600 id = 3000 }
	name = "Flotilla Claro"
	location = 336
	base = 336

	division = {
		id = { type = 19600 id = 3001 }
		name = "Douro Flotilha"
		type = destroyer
		model = 0
		}

	division = {
		id = { type = 19600 id = 3002 }
		name = "Viana do Castello Flotilha"
		type = destroyer
		model = 0
		}
	}

navalunit = {
	id = { type = 19600 id = 3003 }
	name = "1a Divisão de Submersiveis"
	location = 336 # Lissabon
	base = 336

	division = {
		id = { type = 19600 id = 3004 }
		name = "1a Divisão de Submersiveis"
		type = submarine
		strength = 75
		max_strength = 75
		model = 0
		}
	}

navalunit = {
	id = { type = 12059 id = 3005 }
	name = "Esquadrão Africano"
	location = 1096
	base = 1096

	division = {
		id = { type = 12059 id = 3006 }
		name = "Esquadrão Africano"
		type = destroyer
		model = 0
		}
	}

navalunit = {
	id = { type = 19600 id = 3007 }
	name = "Esquadrão De Zanzibar"
	location = 1122
	base = 1122

	division = {
		id = { type = 19600 id = 3008 }
		name = "Esquadrão De Zanzibar"
		type = destroyer
		strength = 75
		model = 0
		}
	}

navalunit = {
	id = { type = 19600 id = 3009 }
	name = "Esquadrão Do leste Distante"
	location = 1316
	base = 1316

	division = {
		id = { type = 19600 id = 3010 }
		name = "Esquadrão Do leste Distante"
		type = destroyer
		strength = 80
		max_strength = 80
		model = 0
		}
	}

navalunit = {
	id = { type = 19600 id = 3011 }
	name = "Esquadrão Do leste De Timor"
	location = 1658
	base = 1658

	division = {
		id = { type = 19600 id = 3012 }
		name = "Esquadrão Do leste De Timor"
		type = destroyer
		strength = 60
		max_strength = 60
		model = 0
		}
	}

navalunit = {
	id = { type = 19600 id = 3013 }
	name = "Navios de Transporte"
	location = 336
	base = 336

	division = {
		id = { type = 19600 id = 3014 }
		name = "1a Divisão de Navios de Transporte"
		type = transport
		model = 0
		}
	}

#AIR OOB

airunit = {
	id = { type = 19600 id = 2000 }
	name = "Arma da Aeronáutica"
	location = 336
	base = 336

	division = {
		id = { type = 19600 id = 2001 }
		name = "Arma da Aeronáutica"
		type = interceptor
		strength = 40
		model = 0
		}
	}

	province_development = { 
		id = { type = 19600 id = 1015 } 
		name = "" 
		progress = 0.0000 
		location = 336 
		cost = 2.0000 
		date = { 
			year = 1942 
			month = july 
			day = 5 
			hour = 0 
			} 
		manpower = 0.1000 
		close_when_finished = yes 
		waitingforclosure = no 
		total_progress = 0.0000 
		size = 24 
		done = 0 
		days = 2228 
		days_for_first = 120 
		gearing_bonus = 0.0000 
		type = infrastructure 
		} 
	province_development = { 
		id = { type = 19600 id = 1016 } 
		name = "" 
		progress = 0.0000 
		location = 335 
		cost = 2.0000 
		date = { 
			year = 1943 
			month = january 
			day = 15 
			hour = 0 
			} 
		manpower = 0.1000 
		close_when_finished = yes 
		waitingforclosure = no 
		total_progress = 0.0000 
		size = 26 
		done = 0 
		days = 2319 
		days_for_first = 120 
		gearing_bonus = 0.0000 
		type = infrastructure 
		} 
	province_development = { 
		id = { type = 19600 id = 1017 } 
		name = "" 
		progress = 0.0000 
		location = 345 
		cost = 2.0000 
		date = { 
			year = 1943 
			month = march 
			day = 9 
			hour = 0 
			} 
		manpower = 0.1000 
		close_when_finished = yes 
		waitingforclosure = no 
		total_progress = 0.0000 
		size = 28 
		done = 0 
		days = 2580 
		days_for_first = 120 
		gearing_bonus = 0.0000 
		type = infrastructure 
		} 
	province_development = { 
		id = { type = 19600 id = 1018 } 
		name = "" 
		progress = 0.0000 
		location = 337 
		cost = 2.0000 
		date = { 
			year = 1948 
			month = may 
			day = 6 
			hour = 0 
			} 
		manpower = 0.1000 
		close_when_finished = yes 
		waitingforclosure = no 
		total_progress = 0.0000 
		size = 26 
		done = 0 
		days = 2409 
		days_for_first = 120 
		gearing_bonus = 0.0000 
		type = infrastructure 
		} 
	province_development = { 
		id = { type = 19600 id = 1019 } 
		name = "" 
		progress = 0.0000 
		location = 336 
		cost = 5.0000 
		date = { 
			year = 1939 
			month = october 
			day = 0 
			hour = 0 
			} 
		manpower = 1.0000 
		close_when_finished = yes 
		waitingforclosure = no 
		total_progress = 0.0000 
		size = 3 
		done = 0 
		days = 1350 
		days_for_first = 450 
		gearing_bonus = 0.0000 
		type = ic 
		} 

	brigade_development = { 
		id = { type = 19600 id = 1020 } 
		name = "36' AA" 
		progress = 0.0000 
		location = 336 
		cost = 0.8000 
		date = { 
			year = 1937 
			month = november 
			day = 6 
			hour = 0 
			} 
		manpower = 0.1000 
		close_when_finished = yes 
		waitingforclosure = no 
		retooling_time = 28.0000 
		total_progress = 0.0000 
		size = 7 
		done = 0 
		days = 95 
		days_for_first = 105 
		gearing_bonus = 0.0000 
		type = naval_anti_air_s 
		model = 1 
		} 
	brigade_development = { 
		id = { type = 19600 id = 1021 } 
		name = "Basic Sea Mines" 
		progress = 0.0000 
		location = 336 
		cost = 0.3000 
		date = { 
			year = 1937 
			month = january 
			day = 27 
			hour = 0 
			} 
		manpower = 0.0500 
		close_when_finished = yes 
		waitingforclosure = no 
		retooling_time = 22.5000 
		total_progress = 0.0000 
		size = 7 
		done = 0 
		days = 365 
		days_for_first = 60 
		gearing_bonus = 0.0000 
		type = naval_mines 
		model = 0 
		} 
}
