#####################
# Country main data #
#####################

country =
{ tag                    = REB
	capital = 399 
	ownedprovinces = { } 
	controlledprovinces = { } 
	nationalprovinces = { } 
	policy = { 
		date = { 
			year = 0 
			month = january 
			day = 0 
			hour = 0 
			} 
		democratic = 5 
		political_left = 5 
		freedom = 5 
		free_market = 5 
		professional_army = 5 
		defense_lobby = 5 
		interventionism = 5 
		} 
techapps               = { 14080 }
}
