##############################
# Country definition for SPR #
##############################

province =
{ id         = 535
  supplypool = 50
}              # Mallorca
province = { id = 957 supplypool = 50 } # Ceuta
province =
{ id         = 963
  oilpool    = 50
  supplypool = 50
}              # Gran Canaria
province =
{ id         = 972
  supplypool = 50
}              # Villa Cisneros
province = { id = 1091 supplypool = 50 } # Bata

#####################
# Country main data #
#####################

country =
{ tag                    = SPR
  regular_id             = SPA
  intrinsic_gov_type     = left_wing_radical
  manpower               = 247.9000 # 250 - building queue
  # Resource Reserves
  energy                 = 2378
  metal                  = 1738
  rare_materials         = 821
  oil                    = 272
  supplies               = 1500
  money                  = 500
  consumer = 0.3000 
  supply = 0.2000 
  production = 0.5000 
  reinforcement = 0.0000 
  upgrading = 0.0000 
  dissent                = 30
  capital                = 341
  transports             = 232
  escorts                = 9

	diplomacy = {
		relation = { tag = AFG value = 1 }
		relation = { tag = ALB value = 15 }
		relation = { tag = ARG value = 15 }
		relation = { tag = AST value = 25 }
		relation = { tag = AUS value = 20 }
		relation = { tag = BEL value = 35 }
		relation = { tag = BHU value = 1 }
		relation = { tag = BOL value = 15 }
		relation = { tag = BRA value = 30 }
		relation = { tag = BUL value = 20 }
		relation = { tag = CAN value = 30 }
		relation = { tag = CGX value = 1 }
		relation = { tag = CHC value = 1 }
		relation = { tag = CHI value = 1 }
		relation = { tag = CHL value = 15 }
		relation = { tag = COL value = 15 }
		relation = { tag = COS value = 10 }
		relation = { tag = CSX value = 1 }
		relation = { tag = CUB value = -10 }
		relation = { tag = CXB value = 1 }
		relation = { tag = CYN value = 1 }
		relation = { tag = CZE value = 45 }
		relation = { tag = DEN value = 20 }
		relation = { tag = DOM value = 1 }
		relation = { tag = ECU value = 15 }
		relation = { tag = EGY value = 1 }
		relation = { tag = ENG value = 45 }
		relation = { tag = EST value = 20 }
		relation = { tag = ETH value = 30 }
		relation = { tag = FIN value = 20 }
		relation = { tag = FRA value = 45 }
		relation = { tag = GER value = 10 }
		relation = { tag = GRE value = 30 }
		relation = { tag = GUA value = 15 }
		relation = { tag = HAI value = 1 }
		relation = { tag = HOL value = 25 }
		relation = { tag = HON value = 15 }
		relation = { tag = HUN value = 20 }
		relation = { tag = IND value = 1 }
		relation = { tag = IRE value = 35 }
		relation = { tag = IRQ value = 1 }
		relation = { tag = ITA value = 15 }
		relation = { tag = JAP value = 15 }
		relation = { tag = LAT value = 20 }
		relation = { tag = LIB value = 1 }
		relation = { tag = LIT value = 20 }
		relation = { tag = LUX value = 20 }
		relation = { tag = MAN value = 1 }
		relation = { tag = MEX value = 20 }
		relation = { tag = MLY value = 1 }
		relation = { tag = MON value = 10 }
		relation = { tag = NEP value = 1 }
		relation = { tag = NIC value = 15 }
		relation = { tag = NOR value = 20 }
		relation = { tag = NZL value = 20 }
		relation = { tag = OMN value = 1 }
		relation = { tag = PAN value = 15 }
		relation = { tag = PAR value = 15 }
		relation = { tag = PER value = 1 }
		relation = { tag = PHI value = 1 }
		relation = { tag = POL value = 30 }
		relation = { tag = POR value = -15 }
		relation = { tag = PRU value = 15 }
		relation = { tag = ROM value = 20 }
		relation = { tag = SAF value = 15 }
		relation = { tag = SAL value = 15 }
		relation = { tag = SAU value = 1 }
		relation = { tag = SIA value = 1 }
		relation = { tag = SIK value = 1 }
		relation = { tag = SOV value = 65 }
		relation = { tag = SPA value = 1 }
		relation = { tag = SWE value = 30 }
		relation = { tag = SCH value = 50 }
		relation = { tag = TAN value = 15 }
		relation = { tag = TIB value = 1 }
		relation = { tag = TUR value = 15 }
		relation = { tag = U27 value = 1 }
		relation = { tag = URU value = 15 }
		relation = { tag = USA value = 45 }
		relation = { tag = VEN value = 15 }
		relation = { tag = YEM value = 1 }
		relation = { tag = YUG value = 20 }
	}

	SpyInfo = { country = "SPR" NumberOfSpies = 4 }
	SpyInfo = { country = "ARG" NumberOfSpies = 2 }
	SpyInfo = { country = "BOL" NumberOfSpies = 1 }
	SpyInfo = { country = "CAN" NumberOfSpies = 1 }
	SpyInfo = { country = "CHL" NumberOfSpies = 1 }
	SpyInfo = { country = "COL" NumberOfSpies = 1 }
	SpyInfo = { country = "COS" NumberOfSpies = 1 }
	SpyInfo = { country = "CUB" NumberOfSpies = 2 }
	SpyInfo = { country = "DOM" NumberOfSpies = 1 }
	SpyInfo = { country = "ECU" NumberOfSpies = 1 }
	SpyInfo = { country = "ENG" NumberOfSpies = 2 }
	SpyInfo = { country = "FRA" NumberOfSpies = 4 }
	SpyInfo = { country = "GER" NumberOfSpies = 2 }
	SpyInfo = { country = "GUA" NumberOfSpies = 1 }
	SpyInfo = { country = "HON" NumberOfSpies = 1 }
	SpyInfo = { country = "IRE" NumberOfSpies = 1 }
	SpyInfo = { country = "ITA" NumberOfSpies = 2 }
	SpyInfo = { country = "MEX" NumberOfSpies = 2 }
	SpyInfo = { country = "NIC" NumberOfSpies = 1 }
	SpyInfo = { country = "PAN" NumberOfSpies = 2 }
	SpyInfo = { country = "PAR" NumberOfSpies = 1 }
	SpyInfo = { country = "PHI" NumberOfSpies = 2 }
	SpyInfo = { country = "POL" NumberOfSpies = 1 }
	SpyInfo = { country = "POR" NumberOfSpies = 4 }
	SpyInfo = { country = "PRU" NumberOfSpies = 1 }
	SpyInfo = { country = "SAL" NumberOfSpies = 1 }
	SpyInfo = { country = "SOV" NumberOfSpies = 2 }
	SpyInfo = { country = "SCH" NumberOfSpies = 1 }
	SpyInfo = { country = "TUR" NumberOfSpies = 1 }
	SpyInfo = { country = "URU" NumberOfSpies = 1 }
	SpyInfo = { country = "USA" NumberOfSpies = 2 }
	SpyInfo = { country = "VEN" NumberOfSpies = 2 }

	SpyInfo = { country = "SPA" NumberOfSpies = 4 }


  nationalprovinces      = { 334 332 333 339 338 341 343 346 347 349 350 351 352 353 354 342 355 340 330 331 356 329 357 535 536 537 961 962 963 964
                             965 348
                           }
  ownedprovinces         = { 334  332  333  339  338  341  343  346  347  349  350  351  352  353  354  342  355  340  330  331  356  329  357  535 
                             536  537  961  962  963  964  965  957  955  954  967  971  972  1091
                           }

  controlledprovinces    = { 334  332  333  339  338  341  343  346  347  349  350  351  352  353  354  342  355  340  330  331  356  329  357  535 
                             536  537  961  962  963  964  965  957  955  954  967  971  972  1091
                           }
  # Semi-Major Tech '36
  # Group C 1936 techs
  # ######################
  techapps               = { 4010 4020 4120   2010 2020 2400 2290 2300 2310 4220 2450 2460 4130 2510 3260 1010 1190 1110 9010 5010 5080 5090 5190
                             6010 6020 3010 3020 3070 3080 3130 3140 3250 3400 3410 8010 8020 8040 8050
                           }
  policy =
  { date              = { year = 0 month = january day = 0 }
    democratic        = 9
    political_left    = 1
    freedom           = 7
    free_market       = 4
    professional_army = 3
    defense_lobby     = 4
    interventionism   = 5
  }
  headofstate            = { type = 9 id = 11001 }
  headofgovernment       = { type = 9 id = 11002 }
  foreignminister        = { type = 9 id = 11003 }
  armamentminister       = { type = 9 id = 11004 }
  ministerofsecurity     = { type = 9 id = 11005 }
  ministerofintelligence = { type = 9 id = 11006 }
  chiefofstaff           = { type = 9 id = 11007 }
  chiefofarmy            = { type = 9 id = 11008 }
  chiefofnavy            = { type = 9 id = 11009 }
  chiefofair             = { type = 9 id = 11010 }
  dormant_leaders        = { 3007 3050 }
  ### Spanish land OOB ###
  landunit =
  { id       = { type = 27600 id = 1 }
    location = 971
    name     = "Fuerzas del Sahara"
    division =
    { id       = { type = 27600 id = 2 }
      name     = "Legión del Sahara"
      type     = infantry
      strength = 30
    }
  }
  landunit =
  { id       = { type = 27600 id = 3 }
    location = 1091
    name     = "Guardias Coloniales"
    division =
    { id       = { type = 27600 id = 4 }
      name     = "Guardias Coloniales"
      type     = militia
      strength = 30
    }
  }
  landunit =
  { id       = { type = 27600 id = 5 }
    location = 341
    name     = "1a Cuerpo de Ejército"
    division =
    { id   = { type = 27600 id = 6 }
      name = "1a División Orgánica"
      type = infantry
    }
    division =
    { id    = { type = 27600 id = 7 }
      name  = "2a División Orgánica"
      type  = infantry
      extra = artillery
    }
    division =
    { id   = { type = 27600 id = 8 }
      name = "1a División de Caballería"
      type = cavalry
    }
    division =
    { id       = { type = 27600 id = 9 }
      name     = "Brigada Blindada"
      type     = light_armor
      model    = 0
      strength = 30
    }
  }
  landunit =
  { id       = { type = 27600 id = 10 }
    location = 356
    name     = "2o Cuerpo del Ejército"
    division =
    { id    = { type = 27600 id = 11 }
      name  = "3a División Orgánica"
      type  = infantry
      extra = anti_tank
    }
    division =
    { id   = { type = 27600 id = 12 }
      name = "4a División Orgánica"
      type = infantry
    }
    division =
    { id   = { type = 27600 id = 13 }
      name = "5a División Orgánica"
      type = infantry
    }
    division =
    { id   = { type = 27600 id = 14 }
      name = "Brigadas de Montaña"
      type = bergsjaeger
    }
  }
  landunit =
  { id       = { type = 27600 id = 15 }
    location = 354
    name     = "3er Cuerpo de Ejército"
    division =
    { id    = { type = 27600 id = 16 }
      name  = "6a División Orgánica"
      type  = infantry
      extra = anti_air
    }
    division =
    { id   = { type = 27600 id = 17 }
      name = "7a División Orgánica"
      type = infantry
    }
    division =
    { id    = { type = 27600 id = 18 }
      name  = "8a División Orgánica"
      type  = infantry
      extra = artillery
    }
  }
  landunit =
  { id       = { type = 27600 id = 19 }
    location = 535
    name     = "Comandancia de Baleares"
    division =
    { id       = { type = 27600 id = 20 }
      name     = "Comandancia de Baleares"
      type     = infantry
      strength = 30
    }
  }
  landunit =
  { id       = { type = 27600 id = 21 }
    location = 963
    name     = "Comandancia de Canarias"
    division =
    { id       = { type = 27600 id = 22 }
      name     = "Comandancia de Canarias"
      type     = infantry
      strength = 30
    }
  }
  landunit =
  { id       = { type = 27600 id = 23 }
    location = 957
    name     = "Ejército de África"
    division =
    { id   = { type = 27600 id = 24 }
      name = "Circunscripción Occidental"
      type = infantry
    }
    division =
    { id   = { type = 27600 id = 25 }
      name = "Circunscripción Oriental"
      type = infantry
    }
  }
	### Spanish Navy OOB ###
  # Some naval units were clearly outdated or in bad fighting shape. Strength has been reduced in those cases.
    
  navalunit =
  { location = 352
    base     = 352
    id       = { type = 27600 id = 26 }
    name     = "Grupo C"
    division =
    { id       = { type = 27600 id = 27 }
      name     = "S101 Flotilla"
      strength = 100
      type     = submarine
      model    = 0
    }
  }
  navalunit =
  { location = 352
    base     = 352
    id       = { type = 27600 id = 28 }
    name     = "Grupo B"
    division =
    { id       = { type = 27600 id = 29 }
      name     = "S103 Flotilla"
      strength = 75
      type     = submarine
      model    = 1
    }
  }
navalunit =
  { location = 347
    base     = 347
    id       = { type = 27600 id = 30 }
    name     = "Base Naval Cádiz"
    division =
    { id       = { type = 27600 id = 31 }
      name     = "República"
      strength = 60
      type     = light_cruiser
      model    = 0
      extra1 = naval_anti_air_s
      extra2 = none
      brigade_model1 = 0
      brigade_model2 = 0
    }
    division =
    { id       = { type = 27600 id = 32 }
      name     = "Flotilla de Escolta"
      strength = 100
      type     = destroyer
      model    = 1
    }
  }
  navalunit =
  { location = 334
    base     = 334
    id       = { type = 27600 id = 33 }
    name     = "Flotilla Méndez Núñez"
    division =
    { id       = { type = 27600 id = 34 }
      name     = "Méndez Núñez"
      strength = 100
      type     = light_cruiser
      model    = 0
      extra1 = naval_anti_air_s
      extra2 = none
      brigade_model1 = 0
      brigade_model2 = 0
    }
  }
  navalunit =
  { location = 352
    base     = 352
    id       = { type = 27600 id = 35 }
    name     = "Escuadrón de Batalla"
    division =
    { id       = { type = 27600 id = 36 }
      name     = "Jaime I"
      strength = 50
      type     = battleship
      model    = 0
      extra1 = naval_sa_l
      extra2 = naval_anti_air_l
      extra3 = none
      extra4 = none
      extra5 = none
      brigade_model1 = 0
      brigade_model2 = 1
      brigade_model3 = 0
      brigade_model4 = 0
      brigade_model5 = 0
    }
    division =
    { id       = { type = 27600 id = 37 }
      name     = "España"
      strength = 100
      type     = battleship
      model    = 0
      extra1 = naval_sa_l
      extra2 = naval_anti_air_l
      extra3 = none
      extra4 = none
      extra5 = none
      brigade_model1 = 0
      brigade_model2 = 1
      brigade_model3 = 0
      brigade_model4 = 0
      brigade_model5 = 0
    }
    division =
    { id       = { type = 27600 id = 38 }
      name     = "Miguel de Cervantes"
      strength = 100
      type     = light_cruiser
      model    = 1
      extra1 = naval_anti_air_s
      extra2 = none
      brigade_model1 = 1
      brigade_model2 = 0
    }
    division =
    { id       = { type = 27600 id = 39 }
      name     = "Almirante Cervera"
      strength = 100
      type     = light_cruiser
      model    = 1
      extra1 = naval_anti_air_s
      extra2 = none
      brigade_model1 = 1
      brigade_model2 = 0
    }
    division =
    { id       = { type = 27600 id = 40 }
      name     = "Flotilla de Torpederas No. 1"
      strength = 100
      type     = destroyer
      model    = 0
    }
    division =
    { id       = { type = 27600 id = 41 }
      name     = "Flotilla de Torpederas No. 2"
      strength = 100
      type     = destroyer
      model    = 1
    }
    division =
    { id       = { type = 27600 id = 42 }
      name     = "1a Flotilla de Transporte Naval"
      strength = 100
      type     = transport
    }
    division =
    { id       = { type = 27600 id = 43 }
      name     = "2a Flotilla de Transporte Naval"
      strength = 100
      type     = transport
    }
  }
  navalunit =
  { location = 963
    base     = 963
    id       = { type = 27600 id = 44 }
    name     = "Armada Colonial"
    division =
    { id       = { type = 27600 id = 45 }
      name     = "Flotilla de Torpederas No. 3"
      strength = 100
      type     = destroyer
      model    = 1
    }
    division =
    { id       = { type = 27600 id = 46 }
      name     = "3a Flotilla de Transporte Naval"
      strength = 100
      type     = transport
    }
    division =
    { id       = { type = 27600 id = 47 }
      name     = "4a Flotilla de Transporte Naval"
      strength = 100
      type     = transport
    }
  }
  navalunit =
  { id       = { type = 27600 id = 48 }
    name     = "Libertad"
    location = 352
    base     = 352
    division =
    { id       = { type = 27600 id = 49 }
      name     = "Libertad"
      type     = light_cruiser
      model    = 1
      extra1 = naval_anti_air_s
      extra2 = none
      brigade_model1 = 1
      brigade_model2 = 0
      strength = 100
    }
  }
	### Spain Air OOB ###
  airunit =
  { location = 341
    base     = 341
    id       = { type = 27600 id = 50 }
    name     = "1a Escuadra Aérea"
    division =
    { id       = { type = 27600 id = 51 }
      name     = "1er Grupo Táctico"
      strength = 30
      type     = tactical_bomber
    }
    division =
    { id       = { type = 27600 id = 52 }
      name     = "2o Grupo Táctico"
      strength = 30
      type     = tactical_bomber
    }
  }
  airunit =
  { location = 357
    base     = 357
    id       = { type = 27600 id = 53 }
    name     = "2a Escuadra Aérea"
    division =
    { id       = { type = 27600 id = 54 }
      name     = "1er Grupo de Caza"
      strength = 30
      type     = interceptor
    }
    division =
    { id       = { type = 27600 id = 55 }
      name     = "3er Grupo de Caza"
      strength = 30
      type     = interceptor
    }
  }
  airunit =
  { location = 352
    base     = 352
    id       = { type = 27600 id = 56 }
    name     = "3a Escuadra Aérea"
    division =
    { id       = { type = 27600 id = 57 }
      name     = "1er Grupo Estratégico"
      strength = 30
      type     = strategic_bomber
    }
    division =
    { id       = { type = 27600 id = 58 }
      name     = "2o Grupo Estratégico"
      strength = 30
      type     = strategic_bomber
    }
  }
  airunit =
  { location = 963
    base     = 963
    id       = { type = 27600 id = 59 }
    name     = "Fuerzas Aéreas del África"
    division =
    { id       = { type = 27600 id = 60 }
      name     = "1er Grupo de Bombardeo"
      strength = 30
      type     = tactical_bomber
    }
    division =
    { id       = { type = 27600 id = 61 }
      name     = "2o Grupo de Caza"
      strength = 30
      type     = interceptor
    }
  } 
	### Development ###
	province_development = { 
		id = { type = 27600 id = 64 } 
		name = "" 
		progress = 0.0000 
		location = 341 
		cost = 2.0000 
		date = { 
			year = 1939 
			month = september 
			day = 29 
			hour = 0 
			} 
		manpower = 0.1000 
		close_when_finished = yes 
		waitingforclosure = no 
		total_progress = 0.0000 
		size = 24 
		done = 0 
		days = 2103 
		days_for_first = 120 
		gearing_bonus = 0.0000 
		speed_step = 2 
		type = infrastructure 
		} 
	division_development = { 
		id = { type = 27600 id = 63 } 
		name = "Baleares" 
		progress = 0.0000 
		location = 0 
		cost = 2.5000 
		date = { 
			year = 1936 
			month = february 
			day = 4 
			hour = 0 
			} 
		manpower = 1.0000 
		close_when_finished = yes 
		waitingforclosure = no 
		total_progress = 0.8815 
		size = 1 
		done = 0 
		days = 1 
		days_for_first = 290 
		gearing_bonus = 0.0000 
		type = heavy_cruiser 
		extra = none 
		extra1 = none 
		extra2 = none 
		extra3 = none 
		extra4 = none 
		model = 1 
		brigade_model = 0 
		brigade_model1 = 0 
		brigade_model2 = 0 
		brigade_model3 = 0 
		brigade_model4 = 0 
		} 
	division_development = { 
		id = { type = 27600 id = 62 } 
		name = "Canarias" 
		progress = 0.0000 
		location = 0 
		cost = 2.5000 
		date = { 
			year = 1936 
			month = january 
			day = 26 
			hour = 0 
			} 
		manpower = 1.0000 
		close_when_finished = yes 
		waitingforclosure = no 
		total_progress = 0.9077 
		size = 1 
		done = 0 
		days = 1 
		days_for_first = 290 
		gearing_bonus = 0.0000 
		type = heavy_cruiser 
		extra = none 
		extra1 = none 
		extra2 = none 
		extra3 = none 
		extra4 = none 
		model = 1 
		brigade_model = 0 
		brigade_model1 = 0 
		brigade_model2 = 0 
		brigade_model3 = 0 
		brigade_model4 = 0 
		} 
}