#####################
# Country main data #
#####################

country =
{ tag                    = ROM
  capital                = 424
  manpower               = 468.4500 # 475 - building queue -5 for HQ
  transports             = 20
  # Resource Reserves
  energy                 = 1337
  metal                  = 768
  rare_materials         = 339
  oil                    = 1776
  supplies               = 1009
  money                  = 40
  consumer = 0.2250 
  supply = 0.1143 
  production = 0.6607 
  reinforcement = 0.0000 
  upgrading = 0.0000 

	diplomacy = {
		relation = { tag = AFG value = 1 }
		relation = { tag = ALB value = 15 }
		relation = { tag = ARG value = 10 }
		relation = { tag = AST value = 15 }
		relation = { tag = AUS value = 30 }
		relation = { tag = BEL value = 35 }
		relation = { tag = BHU value = 1 }
		relation = { tag = BOL value = 1 }
		relation = { tag = BRA value = 15 }
		relation = { tag = BUL value = 15 }
		relation = { tag = CAN value = 25 }
		relation = { tag = CGX value = 1 }
		relation = { tag = CHC value = 1 }
		relation = { tag = CHI value = 15 }
		relation = { tag = CHL value = 10 }
		relation = { tag = COL value = 10 }
		relation = { tag = COS value = 1 }
		relation = { tag = CSX value = 1 }
		relation = { tag = CUB value = 1 }
		relation = { tag = CXB value = 1 }
		relation = { tag = CYN value = 1 }
		relation = { tag = CZE value = 40 guaranteed = { day = 30 month = december year = 1935 } }
		relation = { tag = DEN value = 20 }
		relation = { tag = DOM value = 1 }
		relation = { tag = ECU value = 10 }
		relation = { tag = EGY value = 1 }
		relation = { tag = ENG value = 40 }
		relation = { tag = EST value = 25 }
		relation = { tag = ETH value = 1 }
		relation = { tag = FIN value = 25 }
		relation = { tag = FRA value = 45 }
		relation = { tag = GER value = 35 }
		relation = { tag = GRE value = 30 guaranteed = { day = 30 month = august year = 1934 } }
		relation = { tag = GUA value = 1 }
		relation = { tag = HAI value = 1 }
		relation = { tag = HOL value = 20 }
		relation = { tag = HON value = 1 }
		relation = { tag = HUN value = 30 }
		relation = { tag = IND value = 1 }
		relation = { tag = IRE value = 30 }
		relation = { tag = IRQ value = 1 }
		relation = { tag = ITA value = 35 }
		relation = { tag = JAP value = 35 }
		relation = { tag = LAT value = 30 }
		relation = { tag = LIB value = 1 }
		relation = { tag = LIT value = 30 }
		relation = { tag = LUX value = 20 }
		relation = { tag = MAN value = 1 }
		relation = { tag = MEX value = 10 }
		relation = { tag = MLY value = 1 }
		relation = { tag = MON value = 1 }
		relation = { tag = NEP value = 1 }
		relation = { tag = NIC value = 1 }
		relation = { tag = NOR value = 20 }
		relation = { tag = NZL value = 15 }
		relation = { tag = OMN value = 1 }
		relation = { tag = PAN value = 1 }
		relation = { tag = PAR value = 1 }
		relation = { tag = PER value = 1 }
		relation = { tag = PHI value = 1 }
		relation = { tag = POL value = 45 }
		relation = { tag = POR value = 25 }
		relation = { tag = PRU value = 10 }
		relation = { tag = SAF value = 20 }
		relation = { tag = SAL value = 1 }
		relation = { tag = SAU value = 20 }
		relation = { tag = SIA value = 1 }
		relation = { tag = SIK value = 1 }
		relation = { tag = SOV value = 30 }
		relation = { tag = SPA value = 20 }
		relation = { tag = SPR value = 20 }
		relation = { tag = SWE value = 20 }
		relation = { tag = SCH value = 50 }
		relation = { tag = TAN value = 1 }
		relation = { tag = TIB value = 1 }
		relation = { tag = TUR value = 25 guaranteed = { day = 30 month = august year = 1934 } }
		relation = { tag = U27 value = 1 }
		relation = { tag = URU value = 1 }
		relation = { tag = USA value = 25 }
		relation = { tag = VEN value = 10 }
		relation = { tag = YEM value = 1 }
		relation = { tag = YUG value = -10 guaranteed = { day = 30 month = december year = 1935 } }
	}

	SpyInfo = { country = "ROM" NumberOfSpies = 4 }
	SpyInfo = { country = "ALB" NumberOfSpies = 1 }
	SpyInfo = { country = "AUS" NumberOfSpies = 1 }
	SpyInfo = { country = "BUL" NumberOfSpies = 4 }
	SpyInfo = { country = "CZE" NumberOfSpies = 2 }
	SpyInfo = { country = "ENG" NumberOfSpies = 2 }
	SpyInfo = { country = "FRA" NumberOfSpies = 2 }
	SpyInfo = { country = "GER" NumberOfSpies = 2 }
	SpyInfo = { country = "GRE" NumberOfSpies = 2 }
	SpyInfo = { country = "HUN" NumberOfSpies = 4 }
	SpyInfo = { country = "ITA" NumberOfSpies = 2 }
	SpyInfo = { country = "POL" NumberOfSpies = 2 }
	SpyInfo = { country = "SOV" NumberOfSpies = 4 }
	SpyInfo = { country = "SPR" NumberOfSpies = 1 }
	SpyInfo = { country = "SCH" NumberOfSpies = 1 }
	SpyInfo = { country = "TUR" NumberOfSpies = 2 }
	SpyInfo = { country = "YUG" NumberOfSpies = 4 }

  nationalprovinces      = { 423 424 425 431 426 495 496 498 427 428 429 430 432 436 433 435 230 434 }
  ownedprovinces         = { 423 424 425 431 426 495 496 498 427 428 429 430 432 436 433 435 230 434 }
  controlledprovinces    = { 423 424 425 431 426 495 496 498 427 428 429 430 432 436 433 435 230 434 }
  # Eastern Minor Tech '36
  # Group C 1936 techs
  # ######################
  techapps               = { 4010 4020 4120 4130 4190   2010 2020 2290 2300 2310 2400 2450 2460 2510 1010 1190 1110 9010 5010 5080 5090 5190 6010
                             6030 3010 3020 3400 8040 8050
                           }
  policy =
  { date              = { year = 0 month = january day = 0 }
    democratic        = 6	#7
    political_left    = 5	#6
    freedom           = 4
    free_market       = 4
    professional_army = 3
    defense_lobby     = 5
    interventionism   = 6
  }
  headofstate            = { type = 9 id = 22001 }
  headofgovernment       = { type = 9 id = 22002 }
  foreignminister        = { type = 9 id = 22003 }
  armamentminister       = { type = 9 id = 22004 }
  ministerofsecurity     = { type = 9 id = 22005 }
  ministerofintelligence = { type = 9 id = 22006 }
  chiefofstaff           = { type = 9 id = 22007 }
  chiefofarmy            = { type = 9 id = 22008 }
  chiefofnavy            = { type = 9 id = 22009 }
  chiefofair             = { type = 9 id = 22010 }
  
  nationalidentity = "policy_identity_defensive"
	socialpolicy = "policy_social_religious"
	nationalculture = "policy_culture_libertarian"
  
  landunit =
  { location = 495 # Timisoara
    name     = "Corp 7 Armata"
    id       = { type = 20600 id = 1 }
    division =
    { id       = { type = 20600 id = 2 }
      name     = "Divizie 1 Infanterie" # Timisoara
      type     = infantry
      strength = 70
    }
    division =
    { id       = { type = 20600 id = 3 }
      name     = "Divizie 18 Infanterie" # Sibiu
      type     = infantry
      strength = 70
    }
    division =
    { id       = { type = 20600 id = 4 }
      name     = "Divizie 19 Infanterie"
      type     = infantry
      strength = 70
    }
  }
  landunit =
  { location = 426 # Craiova
    name     = "Corp 1 Armata"
    id       = { type = 20600 id = 5 }
    division =
    { id       = { type = 20600 id = 100 }
      name     = "1. Armat Romnesc"
      type     = hq
      strength = 100
      extra    = anti_air
    }
    division =
    { id       = { type = 20600 id = 6 }
      name     = "Divizie 2 Infanterie"
      type     = infantry
      strength = 70
      extra    = artillery
    }
    division =
    { id       = { type = 20600 id = 7 }
      name     = "Divizie 3 Infanterie"
      type     = infantry
      strength = 70
    }
    division =
    { id       = { type = 20600 id = 8 }
      name     = "Divizie 4 Infanterie"
      type     = infantry
      strength = 70
    }
    division =
    { id       = { type = 20600 id = 9 }
      name     = "Divizie 11 Infanterie"
      type     = infantry
      strength = 70
    }
  }
  landunit =
  { location = 430 # Brasov
    name     = "Corp 5 Armata"
    id       = { type = 20600 id = 10 }
    division =
    { id       = { type = 20600 id = 11 }
      name     = "Divizie 5 Infanterie"
      type     = infantry
      strength = 70
    }
    division =
    { id       = { type = 20600 id = 12 }
      name     = "Divizie 6 Infanterie"
      type     = infantry
      strength = 70
    }
    division =
    { id       = { type = 20600 id = 13 }
      name     = "Divizie 13 Infanterie"
      type     = infantry
      extra    = artillery
      strength = 70
    }
  }
  landunit =
  { location = 424 # Bucuresti
    name     = "Corp 4 Armata"
    id       = { type = 20600 id = 14 }
    division =
    { id       = { type = 20600 id = 15 }
      name     = "Divizie 7 Infanterie"
      type     = infantry
      strength = 70
      extra    = anti_air
    }
    division =
    { id       = { type = 20600 id = 16 }
      name     = "Divizie 8 Infanterie"
      type     = infantry
      strength = 70
    }
    division =
    { id       = { type = 20600 id = 17 }
      name     = "Divizie 14 Infanterie"
      type     = infantry
      strength = 70
    }
    division =
    { id       = { type = 20600 id = 47 }
      name     = "Divizie 1 Armura"
      type     = light_armor
      model    = 0
      strength = 60
    }
  }
  landunit =
  { location = 431
    name     = "Corp 2 Armata"
    id       = { type = 20600 id = 18 }
    division =
    { id       = { type = 20600 id = 19 }
      name     = "Divizie 9 Infanterie"
      type     = infantry
      strength = 70
    }
    division =
    { id       = { type = 20600 id = 20 }
      name     = "Divizie 10 Infanterie"
      type     = infantry
      extra    = anti_tank
      strength = 70
    }
  }
  landunit =
  { location = 435 # Chisinau
    name     = "Corp 3 Armata"
    id       = { type = 20600 id = 21 }
    division =
    { id       = { type = 20600 id = 22 }
      name     = "Divizie 12 Infanterie"
      type     = infantry
      strength = 70
      extra    = artillery
    }
    division =
    { id       = { type = 20600 id = 23 }
      name     = "Divizie 15 Infanterie"
      type     = infantry
      strength = 70
    }
    division =
    { id       = { type = 20600 id = 24 }
      name     = "Divizie 21 Infanterie"
      type     = infantry
      strength = 70
      extra    = anti_tank
    }
  }
  landunit =
  { location = 433
    name     = "Corp 6 Armata"
    id       = { type = 20600 id = 25 }
    division =
    { id       = { type = 20600 id = 26 }
      name     = "Divizie 16 Infanterie"
      type     = infantry
      strength = 70
    }
    division =
    { id       = { type = 20600 id = 27 }
      name     = "Divizie 17 Infanterie"
      type     = infantry
      strength = 70
    }
    division =
    { id       = { type = 20600 id = 28 }
      name     = "Divizie 20 Infanterie"
      type     = infantry
      strength = 70
    }
  }
  landunit =
  { location = 429
    name     = "Corp Alpinisti"
    id       = { type = 20600 id = 29 }
    division =
    { id       = { type = 20600 id = 30 }
      name     = "Div. 1 Infanterie Alpinisti"
      type     = bergsjaeger
      strength = 100
      extra    = artillery
    }
    division =
    { id       = { type = 20600 id = 31 }
      name     = "Div. 2 Infanterie Alpinisti"
      type     = bergsjaeger
      strength = 100
    }
    division =
    { id       = { type = 20600 id = 32 }
      name     = "Div. 3 Infanterie Alpinisti"
      type     = bergsjaeger
      strength = 100
    }
  }
  landunit =
  { location = 431 # Ploiesti
    name     = "Corp Cavalerie Romania"
    id       = { type = 20600 id = 33 }
    division =
    { id       = { type = 20600 id = 34 }
      name     = "Divizie 1 Cavalerie"
      type     = cavalry
      strength = 40
    }
    division =
    { id       = { type = 20600 id = 35 }
      name     = "Divizie 5 Cavalerie"
      type     = cavalry
      strength = 30
    }
    division =
    { id       = { type = 20600 id = 36 }
      name     = "Divizie 6 Cavalerie"
      type     = cavalry
      strength = 30
    }
    division =
    { id       = { type = 20600 id = 37 }
      name     = "Divizie 7 Cavalerie"
      type     = cavalry
      strength = 30
    }
    division =
    { id       = { type = 20600 id = 38 }
      name     = "Divizie 8 Cavalerie"
      type     = cavalry
      strength = 30
    }
    division =
    { id       = { type = 20600 id = 39 }
      name     = "Divizie 9 Cavalerie"
      type     = cavalry
      strength = 30
    }
  }

#########################################################################
# Navy
#########################################################################

navalunit = {
	id = { type = 20600 id = 3000 }
	name = "Divizia de Mare"
	location = 423
	base = 423

	division = {
		id = { type = 12061 id = 3001 }
		name = "'NMS Regele Ferdinand' Flotila"
		type = destroyer
		model = 0
		extra = naval_torpedoes_s
		brigade_model = 0
		}
	}

navalunit = {
	id = { type = 20600 id = 3002 }
	name = "1. Divizia de Torpiloare"
	location = 423 # Constanta
	base = 423

	division = {
		id = { type = 12061 id = 3003 }
		name = "1. Divizia de Torpiloare"
		type = destroyer
		strength = 60
		max_strength = 60
		model = 0
		}
	}

navalunit = {
	id = { type = 20600 id = 3004 }
	name = "Divizia de Canoniere"
	location = 423
	base = 423

	division = {
		id = { type = 12061 id = 3005 }
		name = "Divizia de Canoniere"
		type = destroyer
		strength = 80
		max_strength = 80
		model = 0
		extra = naval_anti_air_s
		brigade_model = 0
		}
	}

navalunit = {
	id = { type = 20600 id = 3006 }
	name = "Romanian Submarine Flotilla"
	location = 423
	base = 423

	division = {
		id = { type = 12061 id = 3007 }
		name = "Delfinul"
		type = submarine
		strength = 20
		max_strength = 20
		model = 0
		}
	}

  airunit =
  { location = 424 # Bucuresti
    base     = 424
    name     = "Gruparea Aeriana de Lupta"
    id       = { type = 20600 id = 42 }
    division =
    { id       = { type = 20600 id = 43 }
      name     = "Grup 1 Avion de Vanatoare"
      type     = interceptor
      model    = 0
      strength = 50
    }
    division =
    { id       = { type = 20600 id = 44 }
      name     = "Grup 1 Tactic Bombardier"
      type     = tactical_bomber
      model    = 0
      strength = 10
    }
    division =
    { id       = { type = 20600 id = 45 }
      name     = "Grup 1 Hidroavioane"
      type     = naval_bomber
      model    = 0
      strength = 28
    }
  } 
	province_development = { 
		id = { type = 20600 id = 201 } 
		name = "" 
		progress = 0.0000 
		location = 431 
		cost = 2.0000 
		date = { 
			year = 1939 
			month = september 
			day = 29 
			hour = 0 
			} 
		manpower = 0.1000 
		close_when_finished = yes 
		waitingforclosure = no 
		total_progress = 0.0000 
		size = 24 
		done = 0 
		days = 1391 
		days_for_first = 120 
		gearing_bonus = 0.0000 
		speed_step = 2 
		type = infrastructure 
		} 
	province_development = { 
		id = { type = 20600 id = 204 } 
		name = "" 
		progress = 0.0000 
		location = 431 
		cost = 5.0000 
		date = { 
			year = 1941 
			month = january 
			day = 0 
			hour = 0 
			} 
		manpower = 1.0000 
		close_when_finished = yes 
		waitingforclosure = no 
		total_progress = 0.0000 
		size = 5 
		done = 0 
		days = 1800 
		days_for_first = 360 
		gearing_bonus = 0.0000 
		type = ic 
		} 
	province_development = { 
		id = { type = 20600 id = 200 } 
		name = "" 
		progress = 0.0000 
		location = 424 
		cost = 2.0000 
		date = { 
			year = 1942 
			month = june 
			day = 26 
			hour = 0 
			} 
		manpower = 0.1000 
		close_when_finished = yes 
		waitingforclosure = no 
		total_progress = 0.0000 
		size = 24 
		done = 0 
		days = 1391 
		days_for_first = 120 
		gearing_bonus = 0.0000 
		type = infrastructure 
		} 
	province_development = { 
		id = { type = 20600 id = 205 } 
		name = "" 
		progress = 0.0000 
		location = 428 
		cost = 2.0000 
		date = { 
			year = 1942 
			month = june 
			day = 26 
			hour = 0 
			} 
		manpower = 0.1000 
		close_when_finished = yes 
		waitingforclosure = no 
		total_progress = 0.0000 
		size = 24 
		done = 0 
		days = 2337 
		days_for_first = 120 
		gearing_bonus = 0.0000 
		type = infrastructure 
		} 
	province_development = { 
		id = { type = 20600 id = 206 } 
		name = "" 
		progress = 0.0000 
		location = 495 
		cost = 2.0000 
		date = { 
			year = 1945 
			month = september 
			day = 24 
			hour = 0 
			} 
		manpower = 0.1000 
		close_when_finished = yes 
		waitingforclosure = no 
		total_progress = 0.0000 
		size = 24 
		done = 0 
		days = 2337 
		days_for_first = 180 
		gearing_bonus = 0.0000 
		type = infrastructure 
		} 
	brigade_development = { 
		id = { type = 20600 id = 207 } 
		name = "36' AA" 
		progress = 0.0000 
		location = 424 
		cost = 0.8000 
		date = { 
			year = 1936 
			month = september 
			day = 2 
			hour = 0 
			} 
		manpower = 0.1000 
		close_when_finished = yes 
		waitingforclosure = no 
		retooling_time = 38.0000 
		total_progress = 0.0000 
		size = 2 
		done = 0 
		days = 95 
		days_for_first = 105 
		gearing_bonus = 0.0000 
		type = naval_anti_air_s 
		model = 1 
		} 
	brigade_development = { 
		id = { type = 20600 id = 208 } 
		name = "Torpedoes" 
		progress = 0.0000 
		location = 424 
		cost = 0.6000 
		date = { 
			year = 1936 
			month = september 
			day = 10 
			hour = 0 
			} 
		manpower = 0.0500 
		close_when_finished = yes 
		waitingforclosure = no 
		retooling_time = 28.5000 
		total_progress = 0.0000 
		size = 4 
		done = 0 
		days = 222 
		days_for_first = 60 
		gearing_bonus = 0.0000 
		type = naval_torpedoes_s 
		model = 0 
		} 
}
