#####################
# Country main data #
#####################

country =
{ tag                    = SIA
  regular_id             = U64
  # Resource Reserves
  energy                 = 1000
  metal                  = 1000
  rare_materials         = 500
  oil                    = 500
  supplies               = 500
  money                  = 10
  consumer = 0.0000 
  supply = 0.1112 
  production = 0.8888 
  reinforcement = 0.0000 
  upgrading = 0.0000 
  capital                = 1343
  manpower               = 139.5 # 145 - building queue -5 for HQ
  transports             = 16
  escorts                = 1
  policy =
  { date              = { year = 0 month = january day = 0 }
    democratic        = 4
    political_left    = 3
    freedom           = 3
    free_market       = 3
    professional_army = 2
    defense_lobby     = 5
    interventionism   = 5
  }
  nationalprovinces      = { 1348 1347 1345 1343 1342 1331 1330 1344 1303 }
  ownedprovinces         = { 1348 1347 1345 1343 1342 1331 1330 1344 1303 }
  controlledprovinces    = { 1348 1347 1345 1343 1342 1331 1330 1344 1303 }
  # ROTW Minor Tech '36
  # Group D 1936 techs
  # ######################
  # GW fighter
  techapps               = { 4010  2290 2300 2310 1010 1020 1190 1110 2450 2460 2510 5080 5090 4120 6210 6300 3010 3070 3400 8050 }

	diplomacy = {
		relation = { tag = AFG value = 1 }
		relation = { tag = ALB value = 1 }
		relation = { tag = ARG value = 1 }
		relation = { tag = AST value = 25 }
		relation = { tag = AUS value = 1 }
		relation = { tag = BEL value = 15 }
		relation = { tag = BHU value = 1 }
		relation = { tag = BOL value = 1 }
		relation = { tag = BRA value = 10 }
		relation = { tag = BUL value = 1 }
		relation = { tag = CAN value = 10 }
		relation = { tag = CGX value = 15 }
		relation = { tag = CHC value = -10 }
		relation = { tag = CHI value = 25 }
		relation = { tag = CHL value = 1 }
		relation = { tag = COL value = 1 }
		relation = { tag = COS value = 1 }
		relation = { tag = CSX value = 1 }
		relation = { tag = CUB value = 1 }
		relation = { tag = CXB value = 1 }
		relation = { tag = CYN value = 15 }
		relation = { tag = CZE value = 10 }
		relation = { tag = DEN value = 1 }
		relation = { tag = DOM value = 1 }
		relation = { tag = ECU value = 1 }
		relation = { tag = EGY value = 1 }
		relation = { tag = ENG value = 30 }
		relation = { tag = EST value = 1 }
		relation = { tag = ETH value = 1 }
		relation = { tag = FIN value = 1 }
		relation = { tag = FRA value = 30 }
		relation = { tag = GER value = 10 }
		relation = { tag = GRE value = 10 }
		relation = { tag = GUA value = 1 }
		relation = { tag = HAI value = 1 }
		relation = { tag = HOL value = -10 }
		relation = { tag = HON value = 1 }
		relation = { tag = HUN value = 1 }
		relation = { tag = IND value = -15 }
		relation = { tag = IRE value = 10 }
		relation = { tag = IRQ value = 1 }
		relation = { tag = ITA value = 20 }
		relation = { tag = JAP value = 75 }
		relation = { tag = LAT value = 1 }
		relation = { tag = LIB value = 1 }
		relation = { tag = LIT value = 1 }
		relation = { tag = LUX value = 1 }
		relation = { tag = MAN value = 1 }
		relation = { tag = MEX value = 1 }
		relation = { tag = MLY value = -25 }
		relation = { tag = MON value = 1 }
		relation = { tag = NEP value = 1 }
		relation = { tag = NIC value = 1 }
		relation = { tag = NOR value = 1 }
		relation = { tag = NZL value = 1 }
		relation = { tag = OMN value = 1 }
		relation = { tag = PAN value = 1 }
		relation = { tag = PAR value = 1 }
		relation = { tag = PER value = 1 }
		relation = { tag = PHI value = 10 }
		relation = { tag = POL value = 1 }
		relation = { tag = POR value = -10 }
		relation = { tag = PRU value = 1 }
		relation = { tag = ROM value = 1 }
		relation = { tag = SAF value = 1 }
		relation = { tag = SAL value = 1 }
		relation = { tag = SAU value = 10 }
		relation = { tag = SIK value = 1 }
		relation = { tag = SOV value = 10 }
		relation = { tag = SPA value = 1 }
		relation = { tag = SPR value = 1 }
		relation = { tag = SWE value = 1 }
		relation = { tag = SCH value = 50 }
		relation = { tag = TAN value = 1 }
		relation = { tag = TIB value = 15 }
		relation = { tag = TUR value = 1 }
		relation = { tag = U27 value = 1 }
		relation = { tag = URU value = 1 }
		relation = { tag = USA value = 35 }
		relation = { tag = VEN value = 1 }
		relation = { tag = YEM value = 1 }
		relation = { tag = YUG value = 1 }
	}

	SpyInfo = { country = "SIA" NumberOfSpies = 4 }
	SpyInfo = { country = "AST" NumberOfSpies = 1 }
	SpyInfo = { country = "CGX" NumberOfSpies = 2 }
	SpyInfo = { country = "CHI" NumberOfSpies = 2 }
	SpyInfo = { country = "CYN" NumberOfSpies = 2 }
	SpyInfo = { country = "ENG" NumberOfSpies = 2 }
	SpyInfo = { country = "FRA" NumberOfSpies = 2 }
	SpyInfo = { country = "HOL" NumberOfSpies = 1 }
	SpyInfo = { country = "IND" NumberOfSpies = 4 }
	SpyInfo = { country = "JAP" NumberOfSpies = 2 }
	SpyInfo = { country = "MLY" NumberOfSpies = 4 }
	SpyInfo = { country = "NZL" NumberOfSpies = 1 }
	SpyInfo = { country = "PHI" NumberOfSpies = 2 }

  headofstate            = { type = 9 id = 62001 }
  headofgovernment       = { type = 9 id = 62002 }
  foreignminister        = { type = 9 id = 62003 }
  armamentminister       = { type = 9 id = 62004 }
  ministerofsecurity     = { type = 9 id = 62005 }
  ministerofintelligence = { type = 9 id = 62006 }
  chiefofstaff           = { type = 9 id = 62007 }
  chiefofarmy            = { type = 9 id = 62008 }
  chiefofnavy            = { type = 9 id = 62009 }
  chiefofair             = { type = 9 id = 62010 }

  nationalidentity = "policy_identity_defensive" 
  socialpolicy = "policy_social_religious" 
  nationalculture = "policy_culture_absolut"

  landunit =
  { location = 1345
    name     = "Royal Thai Army"
    id       = { type = 23600 id = 1 }
    division =
    { id       = { type = 23600 id = 100 }
      name     = "1st Thai Army"
      type     = hq
      strength = 100
      extra    = police
    }
    division =
    { id       = { type = 23600 id = 2 }
      name     = "1. Thai Infantry Div."
      type     = infantry
      strength = 90
    }
    division =
    { id       = { type = 23600 id = 3 }
      name     = "2. Thai Infantry Div."
      type     = infantry
      strength = 70
    }
  }
  landunit =
  { location = 1343
    name     = "Royal Thai Police Force"
    id       = { type = 23600 id = 4 }
    division =
    { id       = { type = 23600 id = 5 }
      name     = "1. Royal Thai Police Div."
      type     = garrison
      strength = 30
    }
  }
  navalunit =
  { location = 1345
    base     = 1345
    name     = "Royal Thai Navy"
    id       = { type = 23600 id = 6 }
    division =
    { id    = { type = 23600 id = 7 }
      name  = "HTMS Sri Ayuthia"
      type  = heavy_cruiser
      model = 0
    }
    division =
    { id    = { type = 23600 id = 8 }
      name  = "Phra Ruang Flotille"
      type  = destroyer
      model = 1
    }
  }
  airunit =
  { location = 1345
    base     = 1345
    name     = "Royal Thai Airforce"
    id       = { type = 23600 id = 9 }
    division =
    { id       = { type = 23600 id = 10 }
      name     = "1. RTAF Fighter Group"
      type     = interceptor
      model    = 0
      strength = 50
    }
    division =
    { id       = { type = 23600 id = 11 }
      name     = "1. RTAF Tactic Bomb Group"
      type     = tactical_bomber
      model    = 0
      strength = 44
    }
  } 
	province_development = { 
		id = { type = 23600 id = 12 } 
		name = "" 
		progress = 0.0000 
		location = 1343 
		cost = 2.0000 
		date = { 
			year = 1943 
			month = july 
			day = 3 
			hour = 0 
			} 
		manpower = 0.1000 
		close_when_finished = yes 
		waitingforclosure = no 
		total_progress = 0.0000 
		size = 28 
		done = 0 
		days = 2704 
		days_for_first = 120 
		gearing_bonus = 0.0000 
		type = infrastructure 
		} 
	brigade_development = { 
		id = { type = 23600 id = 14 } 
		name = "36' AA" 
		progress = 0.0000 
		location = 1343 
		cost = 0.8000 
		date = { 
			year = 1936 
			month = may 
			day = 9 
			hour = 0 
			} 
		manpower = 0.1000 
		close_when_finished = yes 
		waitingforclosure = no 
		retooling_time = 34.0000 
		total_progress = 0.0000 
		size = 1 
		done = 0 
		days = 185 
		days_for_first = 95 
		gearing_bonus = 0.0000 
		type = naval_anti_air_s 
		model = 1 
		} 
	brigade_development = { 
		id = { type = 23600 id = 15 } 
		name = "18' Secondary Armament" 
		progress = 0.0000 
		location = 1343 
		cost = 0.5000 
		date = { 
			year = 1936 
			month = july 
			day = 19 
			hour = 0 
			} 
		manpower = 0.2000 
		close_when_finished = yes 
		waitingforclosure = no 
		retooling_time = 34.0000 
		total_progress = 0.0000 
		size = 2 
		done = 0 
		days = 85 
		days_for_first = 85 
		gearing_bonus = 0.0000 
		type = naval_sa_l 
		model = 0 
		} 
	brigade_development = { 
		id = { type = 23600 id = 16 } 
		name = "36' Capital AA" 
		progress = 0.0000 
		location = 1343 
		cost = 1.0000 
		date = { 
			year = 1936 
			month = july 
			day = 10 
			hour = 0 
			} 
		manpower = 0.1000 
		close_when_finished = yes 
		waitingforclosure = no 
		retooling_time = 34.0000 
		total_progress = 0.0000 
		size = 2 
		done = 0 
		days = 80 
		days_for_first = 80 
		gearing_bonus = 0.0000 
		type = naval_anti_air_l 
		model = 1 
		} 
}
