#####################
# Country main data #
#####################

country =
{ tag                    = SAF
  # Resource Reserves
  energy                 = 1000
  metal                  = 1000
  rare_materials         = 500
  oil                    = 500
  supplies               = 500
  money                  = 10
  consumer = 0.1800 
  supply = 0.0533 
  production = 0.7667 
  reinforcement = 0.0000 
  upgrading = 0.0000 
  manpower               = 18 # 20 - building queue no more
  capital                = 1121
  transports             = 32

	diplomacy = {
		relation = { tag = AFG value = 1 }
		relation = { tag = ALB value = 10 }
		relation = { tag = ARG value = 10 }
		relation = { tag = AST value = 50 }
		relation = { tag = AUS value = 20 }
		relation = { tag = BEL value = 30 }
		relation = { tag = BHU value = 50 }
		relation = { tag = BOL value = 1 }
		relation = { tag = BRA value = 20 }
		relation = { tag = BUL value = 10 }
		relation = { tag = CAN value = 50 }
		relation = { tag = CGX value = 1 }
		relation = { tag = CHC value = 1 }
		relation = { tag = CHI value = 10 }
		relation = { tag = CHL value = 1 }
		relation = { tag = COL value = 20 }
		relation = { tag = COS value = 1 }
		relation = { tag = CSX value = 1 }
		relation = { tag = CUB value = 1 }
		relation = { tag = CXB value = 1 }
		relation = { tag = CYN value = 1 }
		relation = { tag = CZE value = 35 }
		relation = { tag = DEN value = 10 }
		relation = { tag = DOM value = 1 }
		relation = { tag = ECU value = 20 }
		relation = { tag = EGY value = 50 }
		relation = { tag = ENG value = 150 }
		relation = { tag = EST value = 1 }
		relation = { tag = ETH value = 1 }
		relation = { tag = FIN value = 10 }
		relation = { tag = FRA value = 50 }
		relation = { tag = GER value = 45 }
		relation = { tag = GRE value = 35 }
		relation = { tag = GUA value = 1 }
		relation = { tag = HAI value = 1 }
		relation = { tag = HOL value = 40 }
		relation = { tag = HON value = 1 }
		relation = { tag = HUN value = 10 }
		relation = { tag = IND value = 50 }
		relation = { tag = IRE value = 40 }
		relation = { tag = IRQ value = 50 }
		relation = { tag = ITA value = 35 }
		relation = { tag = JAP value = 25 }
		relation = { tag = LAT value = 1 }
		relation = { tag = LIB value = 1 }
		relation = { tag = LIT value = 1 }
		relation = { tag = LUX value = 1 }
		relation = { tag = MAN value = 1 }
		relation = { tag = MEX value = 20 }
		relation = { tag = MLY value = 50 }
		relation = { tag = MON value = 1 }
		relation = { tag = NEP value = 50 }
		relation = { tag = NIC value = 1 }
		relation = { tag = NOR value = 10 }
		relation = { tag = NZL value = 50 }
		relation = { tag = OMN value = 50 }
		relation = { tag = PAN value = 20 }
		relation = { tag = PAR value = 1 }
		relation = { tag = PER value = 30 }
		relation = { tag = PHI value = 1 }
		relation = { tag = POL value = 30 }
		relation = { tag = POR value = 35 }
		relation = { tag = PRU value = 20 }
		relation = { tag = ROM value = 20 }
		relation = { tag = SAL value = 1 }
		relation = { tag = SAU value = 10 }
		relation = { tag = SIA value = 1 }
		relation = { tag = SIK value = 1 }
		relation = { tag = SOV value = 20 }
		relation = { tag = SPA value = 15 }
		relation = { tag = SPR value = 15 }
		relation = { tag = SWE value = 10 }
		relation = { tag = SCH value = 50 }
		relation = { tag = TAN value = 1 }
		relation = { tag = TIB value = 1 }
		relation = { tag = TUR value = 20 }
		relation = { tag = U27 value = 50 }
		relation = { tag = URU value = 1 }
		relation = { tag = USA value = 25 }
		relation = { tag = VEN value = 30 }
		relation = { tag = YEM value = 50 }
		relation = { tag = YUG value = 10 }
	}

	SpyInfo = { country = "SAF" NumberOfSpies = 2 }
	SpyInfo = { country = "AST" NumberOfSpies = 2 }
	SpyInfo = { country = "BEL" NumberOfSpies = 1 }
	SpyInfo = { country = "CAN" NumberOfSpies = 2 }
	SpyInfo = { country = "EGY" NumberOfSpies = 2 }
	SpyInfo = { country = "ENG" NumberOfSpies = 4 }
	SpyInfo = { country = "ETH" NumberOfSpies = 2 }
	SpyInfo = { country = "FRA" NumberOfSpies = 2 }
	SpyInfo = { country = "GER" NumberOfSpies = 1 }
	SpyInfo = { country = "HOL" NumberOfSpies = 1 }
	SpyInfo = { country = "IND" NumberOfSpies = 1 }
	SpyInfo = { country = "IRE" NumberOfSpies = 1 }
	SpyInfo = { country = "ITA" NumberOfSpies = 1 }
	SpyInfo = { country = "LIB" NumberOfSpies = 2 }
	SpyInfo = { country = "MLY" NumberOfSpies = 1 }
	SpyInfo = { country = "NZL" NumberOfSpies = 1 }
	SpyInfo = { country = "PAN" NumberOfSpies = 1 }
	SpyInfo = { country = "POR" NumberOfSpies = 2 }
	SpyInfo = { country = "SOV" NumberOfSpies = 1 }
	SpyInfo = { country = "SCH" NumberOfSpies = 1 }
	SpyInfo = { country = "USA" NumberOfSpies = 1 }
	
  nationalprovinces      = { 1115 1116 1114 1117 1118 1120 1113 1121 1119 1109 1108 1107 1106 1110 }
  ownedprovinces         = { 1115 1116 1114 1117 1118 1120 1113 1121 1119 1109 1108 1107 1106 1110 }
  controlledprovinces    = { 1115 1116 1114 1117 1118 1120 1113 1121 1119 1109 1108 1107 1106 1110 }
  # Commonwealth Tech '36
  # UK 1936 techs
  # ######################
  techapps               = { 1110 4010  4020  4120  4130     2010  2290  2300  2310  2450  2460  2510  1010  1020  1190  1200  1210  5010  5020  5080 
                             5090  5190  5310  9010  9020  9030  9140  6010  6030  6120  8010  8020  8030  8040  8050  8070  8100  8120  3010 
                             14000 1310
                           }
  policy =
  { date              = { year = 0 month = january day = 0 }
    democratic        = 7
    political_left    = 5
    freedom           = 10
    free_market       = 8
    professional_army = 5
    defense_lobby     = 2
    interventionism   = 6
  }
  headofstate            = { type = 9 id = 70001 }
  headofgovernment       = { type = 9 id = 70002 }
  foreignminister        = { type = 9 id = 70003 }
  armamentminister       = { type = 9 id = 70004 }
  ministerofsecurity     = { type = 9 id = 70005 }
  ministerofintelligence = { type = 9 id = 70006 }
  chiefofstaff           = { type = 9 id = 70007 }
  chiefofarmy            = { type = 9 id = 70008 }
  chiefofnavy            = { type = 9 id = 70009 }
  chiefofair             = { type = 9 id = 70010 }
  landunit =
  { name     = "Cape Command"
    location = 1116
    id       = { type = 26600 id = 1 }
    division =
    { id       = { type = 26600 id = 2 }
      name     = "Cape Command Garrison"
      type     = garrison
      strength = 50
    }
  }
  landunit =
  { name     = "Witwatersrand Command"
    location = 1120
    id       = { type = 26600 id = 3 }
    division =
    { id       = { type = 26600 id = 4 }
      name     = "Witwatersrand Command Garrison"
      type     = garrison
      strength = 50
    }
  }
  landunit =
  { name     = "Natal Command"
    location = 1119
    id       = { type = 26600 id = 5 }
    division =
    { id       = { type = 26600 id = 6 }
      name     = "Natal Command Garrison"
      type     = garrison
      strength = 50
    }
  }
  landunit =
  { name     = "I South African Corps"
    location = 1121
    id       = { type = 26600 id = 100 }
    division =
    { id       = { type = 26600 id = 101 }
      name     = "Active Citizen Force"
      type     = hq
      strength = 100
      extra = engineer
    }
  }
  navalunit =
  { id       = { type = 26600 id = 7 }
    name     = "South African Navy"
    location = 1116
    base     = 1116
    # division = {
    # id = { type = 26600 id = 14 }
    # name = "1st SAN Destroyer Flotilla"
    # strength = 100
    # type = destroyer
    # model = 1
    # }
    # division = {
    # id = { type = 26600 id = 15 }
    # name = "2nd SAN Destroyer Flotilla"
    # strength = 100
    # type = destroyer
    # model = 1
    # }
    division =
    { id   = { type = 26600 id = 10 }
      name = "1st SAN Transport Flotilla"
      type = transport
    }
    division =
    { id   = { type = 26600 id = 11 }
      name = "2nd SAN Transport Flotilla"
      type = transport
    }
    division =
    { id   = { type = 26600 id = 12 }
      name = "3rd SAN Transport Flotilla"
      type = transport
    }
    division =
    { id   = { type = 26600 id = 13 }
      name = "4th SAN Transport Flotilla"
      type = transport
    }
    division =
    { id   = { type = 26600 id = 8 }
      name = "5th SAN Transport Flotilla"
      type = transport
    }
    division =
    { id   = { type = 26600 id = 9 }
      name = "6th SAN Transport Flotilla"
      type = transport
    }
  } 
	province_development = { 
		id = { type = 26600 id = 16 } 
		name = "" 
		progress = 0.0000 
		location = 1121 
		cost = 5.0000 
		date = { 
			year = 1936 
			month = november 
			day = 17 
			hour = 0 
			} 
		manpower = 1.0000 
		close_when_finished = yes 
		waitingforclosure = no 
		total_progress = 0.0000 
		size = 1 
		done = 0 
		days = 28591 
		days_for_first = 317 
		gearing_bonus = 0.0000 
		type = ic 
		} 
	province_development = { 
		id = { type = 26600 id = 17 } 
		name = "" 
		progress = 0.0000 
		location = 1119 
		cost = 5.0000 
		date = { 
			year = 1936 
			month = november 
			day = 1 
			hour = 0 
			} 
		manpower = 1.0000 
		close_when_finished = yes 
		waitingforclosure = no 
		total_progress = 0.0000 
		size = 1 
		done = 0 
		days = 301 
		days_for_first = 301 
		gearing_bonus = 0.0000 
		type = ic 
		} 
	province_development = { 
		id = { type = 26600 id = 18 } 
		name = "" 
		progress = 0.0000 
		location = 1120 
		cost = 5.0000 
		date = { 
			year = 1936 
			month = november 
			day = 1 
			hour = 0 
			} 
		manpower = 1.0000 
		close_when_finished = yes 
		waitingforclosure = no 
		total_progress = 0.0000 
		size = 1 
		done = 0 
		days = 301 
		days_for_first = 301 
		gearing_bonus = 0.0000 
		type = ic 
		} 
	province_development = { 
		id = { type = 26600 id = 19 } 
		name = "" 
		progress = 0.0000 
		location = 1121 
		cost = 2.0000 
		date = { 
			year = 1942 
			month = september 
			day = 17 
			hour = 0 
			} 
		manpower = 0.1000 
		close_when_finished = yes 
		waitingforclosure = no 
		total_progress = 0.0000 
		size = 28 
		done = 0 
		days = 2047 
		days_for_first = 106 
		gearing_bonus = 0.0000 
		type = infrastructure 
		} 
	province_development = { 
		id = { type = 26600 id = 20 } 
		name = "" 
		progress = 0.0000 
		location = 1120 
		cost = 2.0000 
		date = { 
			year = 1942 
			month = september 
			day = 17 
			hour = 0 
			} 
		manpower = 0.1000 
		close_when_finished = yes 
		waitingforclosure = no 
		total_progress = 0.0000 
		size = 28 
		done = 0 
		days = 2047 
		days_for_first = 106 
		gearing_bonus = 0.0000 
		type = infrastructure 
		} 
	province_development = { 
		id = { type = 26600 id = 21 } 
		name = "" 
		progress = 0.0000 
		location = 1119 
		cost = 2.0000 
		date = { 
			year = 1942 
			month = september 
			day = 17 
			hour = 0 
			} 
		manpower = 0.1000 
		close_when_finished = yes 
		waitingforclosure = no 
		total_progress = 0.0000 
		size = 28 
		done = 0 
		days = 2047 
		days_for_first = 106 
		gearing_bonus = 0.0000 
		type = infrastructure 
		} 
}
