#####################
# Country main data #
#####################

country =
{ tag                    = SWE
  # Resource Reserves
  energy                 = 2190
  metal                  = 3318
  rare_materials         = 324
  oil                    = 596
  supplies               = 861
  money                  = 80
  consumer = 0.1522 
  supply = 0.0652 
  production = 0.7826 
  reinforcement = 0.0000 
  upgrading = 0.0000 
  manpower               = 55.5  # 85 - building queue -5 for HQ
  capital                = 101
  transports             = 304
  escorts                = 6

	diplomacy = {
		relation = { tag = AFG value = 1 }
		relation = { tag = ALB value = 15 }
		relation = { tag = ARG value = 10 }
		relation = { tag = AST value = 15 }
		relation = { tag = AUS value = 30 }
		relation = { tag = BEL value = 40 }
		relation = { tag = BHU value = 1 }
		relation = { tag = BOL value = 10 }
		relation = { tag = BRA value = 30 }
		relation = { tag = BUL value = 20 }
		relation = { tag = CAN value = 30 }
		relation = { tag = CGX value = 1 }
		relation = { tag = CHC value = 1 }
		relation = { tag = CHI value = 10 }
		relation = { tag = CHL value = 10 }
		relation = { tag = COL value = 10 }
		relation = { tag = COS value = 1 }
		relation = { tag = CSX value = 1 }
		relation = { tag = CUB value = 1 }
		relation = { tag = CXB value = 1 }
		relation = { tag = CYN value = 1 }
		relation = { tag = CZE value = 40 }
		relation = { tag = DEN value = 40 }
		relation = { tag = DOM value = 1 }
		relation = { tag = ECU value = 10 }
		relation = { tag = EGY value = 1 }
		relation = { tag = ENG value = 40 }
		relation = { tag = EST value = 45 }
		relation = { tag = ETH value = 20 }
		relation = { tag = FIN value = 65 }
		relation = { tag = FRA value = 40 }
		relation = { tag = GER value = 45 }
		relation = { tag = GRE value = 35 }
		relation = { tag = GUA value = 1 }
		relation = { tag = HAI value = 1 }
		relation = { tag = HOL value = 40 }
		relation = { tag = HON value = 1 }
		relation = { tag = HUN value = 30 }
		relation = { tag = IND value = 1 }
		relation = { tag = IRE value = 40 }
		relation = { tag = IRQ value = 1 }
		relation = { tag = ITA value = 35 }
		relation = { tag = JAP value = 25 }
		relation = { tag = LAT value = 40 }
		relation = { tag = LIB value = 1 }
		relation = { tag = LIT value = 40 }
		relation = { tag = LUX value = 20 }
		relation = { tag = MAN value = 1 }
		relation = { tag = MEX value = 20 }
		relation = { tag = MLY value = 1 }
		relation = { tag = MON value = 1 }
		relation = { tag = NEP value = 1 }
		relation = { tag = NIC value = 1 }
		relation = { tag = NOR value = 50 }
		relation = { tag = NZL value = 15 }
		relation = { tag = OMN value = 1 }
		relation = { tag = PAN value = 20 }
		relation = { tag = PAR value = 1 }
		relation = { tag = PER value = 1 }
		relation = { tag = PHI value = 1 }
		relation = { tag = POL value = 30 }
		relation = { tag = POR value = 20 }
		relation = { tag = PRU value = 10 }
		relation = { tag = ROM value = 20 }
		relation = { tag = SAF value = 10 }
		relation = { tag = SAL value = 1 }
		relation = { tag = SAU value = 15 }
		relation = { tag = SIA value = 1 }
		relation = { tag = SIK value = 1 }
		relation = { tag = SOV value = 45 }
		relation = { tag = SPA value = 30 }
		relation = { tag = SPR value = 30 }
		relation = { tag = SCH value = 50 }
		relation = { tag = TAN value = 1 }
		relation = { tag = TIB value = 1 }
		relation = { tag = TUR value = 20 }
		relation = { tag = U27 value = 1 }
		relation = { tag = URU value = 1 }
		relation = { tag = USA value = 45 }
		relation = { tag = VEN value = 20 }
		relation = { tag = YEM value = 1 }
		relation = { tag = YUG value = 20 }
	}

	SpyInfo = { country = "SWE" NumberOfSpies = 1 }
	SpyInfo = { country = "DEN" NumberOfSpies = 2 }
	SpyInfo = { country = "ENG" NumberOfSpies = 1 }
	SpyInfo = { country = "EST" NumberOfSpies = 2 }
	SpyInfo = { country = "FIN" NumberOfSpies = 4 }
	SpyInfo = { country = "FRA" NumberOfSpies = 1 }
	SpyInfo = { country = "GER" NumberOfSpies = 1 }
	SpyInfo = { country = "IRE" NumberOfSpies = 1 }
	SpyInfo = { country = "JAP" NumberOfSpies = 1 }
	SpyInfo = { country = "LAT" NumberOfSpies = 2 }
	SpyInfo = { country = "LIT" NumberOfSpies = 2 }
	SpyInfo = { country = "NOR" NumberOfSpies = 4 }
	SpyInfo = { country = "PAN" NumberOfSpies = 1 }
	SpyInfo = { country = "POL" NumberOfSpies = 2 }
	SpyInfo = { country = "SOV" NumberOfSpies = 4 }
	SpyInfo = { country = "SCH" NumberOfSpies = 1 }
	SpyInfo = { country = "TUR" NumberOfSpies = 1 }
	SpyInfo = { country = "USA" NumberOfSpies = 1 }

  nationalprovinces      = { 112 126 127 123 122 121 120 119 115 113 114 106 105 104 102 101 100 99 98 97 93 95 96 }
  ownedprovinces         = { 112 126 127 123 122 121 120 119 115 113 114 106 105 104 102 101 100 99 98 97 93 95 96 }
  controlledprovinces    = { 112 126 127 123 122 121 120 119 115 113 114 106 105 104 102 101 100 99 98 97 93 95 96 }
  # Group C 1936 techs
  # ######################
  techapps               = { 1200 14000 8030 1310 4010 4020 4120   2150 4130 2010 3190 2290 2300 2310 3130 2450 2460 2510 1010 1190 1110 9010 5010 5020 5080 5090 5190
                             5470 6010 6020 3010 3020 3070 3080 3250 3400 3410 8010 8020 8040 8050
			2020 1020 2400 5310 8070
                           }
  policy =
  { date              = { year = 0 month = january day = 0 }
    democratic        = 10
    political_left    = 10
    freedom           = 6
    free_market       = 7
    professional_army = 3
    defense_lobby     = 5
    interventionism   = 4
  }
  headofstate            = { type = 9 id = 7001 }
  headofgovernment       = { type = 9 id = 7033 }
  foreignminister        = { type = 9 id = 7038 }
  armamentminister       = { type = 9 id = 7047 }
  ministerofsecurity     = { type = 9 id = 7058 }
  ministerofintelligence = { type = 9 id = 7006 }
  chiefofstaff           = { type = 9 id = 7007 }
  chiefofarmy            = { type = 9 id = 7008 }
  chiefofnavy            = { type = 9 id = 7009 }
  chiefofair             = { type = 9 id = 7010 }

# ARMY OOB

landunit = {
	name = "Sodra MILO"
	id = { type = 29600 id = 1 }
	location = 93

	division = {
		id = { type = 29600 id = 2 }
		name = "I. Infanterifördelningen"
		type = infantry
		model = 0
		strength = 100
		}
	}

landunit = {
	name = "Norra MILO"
	id = { type = 29600 id = 3 }
	location = 120

	division = {
		id = { type = 29600 id = 4 }
		name = "II. Infanterifördelningen"
		type = infantry
		model = 0
		strength = 100
		}
	}

landunit = {
	name = "Vestra MILO"
	id = { type = 29600 id = 5 }
	location = 98

	division = {
		id = { type = 29600 id = 6 }
		name = "III. Infanterifördelningen"
		type = infantry
		model = 0
		strength = 100
		}
	}

landunit = {
	name = "Ostra MILO"
	id = { type = 29600 id = 7 }
	location = 101 # Stockholm

	division = {
		id = { type = 29600 id = 8 }
		name = "IV. Infanterifördelningen"
		type = infantry
		model = 0
		strength = 100
		}
	}

landunit = {
	name = "V. Infanterifördelningen"
	id = { type = 29600 id = 9 }
	location = 105 # Karlstad

	division = {
		id = { type = 29600 id = 100 }
		name = "1. Armén"
		type = hq
		model = 0
		strength = 100
		extra = artillery
		}
	division = {
		id = { type = 29600 id = 10 }
		name = "V. Infanterifördelningen"
		type = infantry
		model = 0
		strength = 100
      		extra    = b_u10
		}
	}

landunit = {
	name = "Övre Norrlandstrupper"
	id = { type = 29600 id = 11 }
	location = 127

	division = {
		id = { type = 29600 id = 12 }
		name = "Bodens fästning"
		type = garrison
		model = 0
		locked = yes 
		}
	}

landunit = {
	name = "Vaxholms kustartilleriregemente"
	id = { type = 29600 id = 13 }
	location = 101

	division = {
		id = { type = 29600 id = 14 }
		name = "KA1"
		type = garrison
		model = 0
		locked = yes 
		extra = artillery
		brigade_model = 0
		}
	}

landunit = {
	name = "Karlskrona kustartilleriregemente"
	id = { type = 29600 id = 15 }
	location = 95 # Karlskrona

	division = {
		id = { type = 29600 id = 1015 }
		name = "KA2"
		type = garrison
		model = 0
		locked = yes 
		extra = artillery
		brigade_model = 0
		}
	}

landunit = {
	name = "Fårösund kustartilleriregemente"
	id = { type = 29600 id = 16 }
	location = 96

	division = {
		id = { type = 29600 id = 17 }
		name = "Fårösund Detachment"
		type = garrison
		model = 0
		strength = 100
		locked = yes 
		extra = artillery
		brigade_model = 0
		}
	}

	### SWE Navy OOB ###
  navalunit =
  { location = 101 # Berga/Muskö
    base     = 101
    name     = "Kustflottan"
    id       = { type = 29600 id = 18 }
    division =
    { id    = { type = 29600 id = 19 }
      name  = "HMS Sverige"
      type  = battlecruiser
      model = 0
      extra1 = naval_sa_l
      extra2 = naval_anti_air_l
      extra3 = naval_fire_controll_l
      extra4 = none
      brigade_model1 = 0
      brigade_model2 = 1
      brigade_model3 = 0
      brigade_model4 = 0
    }
    division =
    { id    = { type = 29600 id = 20 }
      name  = "HMS Drottning Victoria"
      type  = battlecruiser
      model = 0
      extra1 = naval_sa_l
      extra2 = naval_anti_air_l
      extra3 = naval_fire_controll_l
      extra4 = none
      brigade_model1 = 0
      brigade_model2 = 1
      brigade_model3 = 0
      brigade_model4 = 0
    }
    division =
    { id    = { type = 29600 id = 21 }
      name  = "HMS Gustav V"
      type  = battlecruiser
      model = 0
      extra1 = naval_sa_l
      extra2 = naval_anti_air_l
      extra3 = naval_fire_controll_l
      extra4 = none
      brigade_model1 = 0
      brigade_model2 = 1
      brigade_model3 = 0
      brigade_model4 = 0
    }
    division =
    { id    = { type = 29600 id = 22 }
      name  = "HMS Gotland"
      type  = light_cruiser
      model = 1
      extra1 = naval_anti_air_s
      extra2 = naval_spotter_s
      brigade_model1 = 1
      brigade_model2 = 0
    }
    division =
    { id    = { type = 29600 id = 23 }
      name  = "HMS Dristigheten"
      type  = light_cruiser
      model = 0
      extra1 = naval_anti_air_s
      extra2 = naval_spotter_s
      brigade_model1 = 1
      brigade_model2 = 0
    }
    division =
    { id    = { type = 29600 id = 24 }
      name  = "HMS Clas Fleming"
      type  = light_cruiser
      model = 0
      extra1 = naval_mines
      extra2 = none
      brigade_model1 = 0
      brigade_model2 = 0
    }
    division =
    { id    = { type = 29600 id = 25 }
      name  = "1. Jagarflottiljen"
      type  = destroyer
      model = 1
    }
    division =
    { id    = { type = 29600 id = 26 }
      name  = "2. Jagarflottiljen"
      type  = destroyer
      model = 0
    }
    division =
    { id    = { type = 29600 id = 27 }
      name  = "3. Jagarflottiljen"
      type  = destroyer
      model = 0
    }
    division =
    { id    = { type = 29600 id = 28 }
      name  = "1. Trängflottiljen"
      type  = transport
      model = 0
    }
  }
  navalunit =
  { location = 101 # Berga/Muskö
    base     = 101
    name     = "Ålandshavseskader"
    id       = { type = 29600 id = 29 }
    division =
    { id    = { type = 29600 id = 30 }
      name  = "HMS Äran"
      type  = heavy_cruiser
      model = 0
      extra1 = naval_sa_l
      extra2 = naval_anti_air_l
      extra3 = none
      brigade_model1 = 0
      brigade_model2 = 0
      brigade_model3 = 0
    }
    division =
    { id    = { type = 29600 id = 31 }
      name  = "HMS Fylgia"
      type  = light_cruiser
      model = 0
      extra1 = naval_improved_hull_s
      extra2 = naval_fire_controll_s
      brigade_model1 = 0
      brigade_model2 = 0
    }
    division =
    { id    = { type = 29600 id = 32 }
      name  = "HMS Tapperheten"
      type  = heavy_cruiser
      model = 0
      extra1 = naval_sa_l
      extra2 = naval_anti_air_l
      extra3 = none
      brigade_model1 = 0
      brigade_model2 = 0
      brigade_model3 = 0
    }
    division =
    { id    = { type = 29600 id = 33 }
      name  = "HMS Wasa"
      type  = heavy_cruiser
      model = 0
      extra1 = naval_sa_l
      extra2 = naval_anti_air_l
      extra3 = none
      brigade_model1 = 0
      brigade_model2 = 0
      brigade_model3 = 0
    }
  }
  navalunit =
  { location = 95 # Karlskronabasen
    base     = 95
    name     = "Karlskrona Avdelningen"
    id       = { type = 29600 id = 34 }
    division =
    { id    = { type = 29600 id = 35 }
      name  = "HMS Oscar II"
      type  = heavy_cruiser
      model = 0
      extra1 = naval_sa_l
      extra2 = naval_anti_air_l
      extra3 = naval_improved_hull_l
      brigade_model1 = 0
      brigade_model2 = 0
      brigade_model3 = 0
    }
    division =
    { id    = { type = 29600 id = 36 }
      name  = "1. Ubåtsflottiljen"
      type  = submarine
      model = 0
    }
  }
  navalunit =
  { location = 98 # Göteborgsbasen
    base     = 98
    name     = "Göteborgseskadern"
    id       = { type = 29600 id = 37 }
    division =
    { id    = { type = 29600 id = 38 }
      name  = "HMS Manligheten"
      type  = heavy_cruiser
      model = 0
      extra1 = naval_sa_l
      extra2 = naval_anti_air_l
      extra3 = naval_improved_hull_l
      brigade_model1 = 0
      brigade_model2 = 0
      brigade_model3 = 0
    }
    division =
    { id    = { type = 29600 id = 39 }
      name  = "2. Ubåtsflottiljen"
      type  = submarine
      model = 1
    }
    division =
    { id    = { type = 29600 id = 40 }
      name  = "3. Ubåtsflottiljen"
      type  = submarine
      model = 0
    }
  }
	### SWE Air OOB ###

  airunit =
  { location = 101
    base     = 101
    name     = "1a Flygkåren"
    id       = { type = 29600 id = 41 }
    division =
    { id    = { type = 29600 id = 42 }
      name  = "1a Flygkåren"
      type  = interceptor
      model = 0
    }
    division =
    { id    = { type = 29600 id = 43 }
      name  = "1. Taktiska Bombflyggruppen"
      type  = tactical_bomber
      model = 0
    }
  } 
	province_development = { 
		id = { type = 29600 id = 44 } 
		name = "" 
		progress = 0.0000 
		location = 126 
		cost = 5.0000 
		date = { 
			year = 2027 
			month = december 
			day = 10 
			hour = 0 
			} 
		manpower = 1.0000 
		close_when_finished = yes 
		waitingforclosure = no 
		total_progress = 0.0000 
		size = 100 
		done = 0 
		days = 33120 
		days_for_first = 331 
		gearing_bonus = 0.0000 
		type = ic 
		} 
	province_development = { 
		id = { type = 29600 id = 45 } 
		name = "" 
		progress = 0.0000 
		location = 126 
		cost = 2.0000 
		date = { 
			year = 1945 
			month = december 
			day = 22 
			hour = 0 
			} 
		manpower = 0.1000 
		close_when_finished = yes 
		waitingforclosure = no 
		total_progress = 0.0000 
		size = 28 
		done = 0 
		days = 2498 
		days_for_first = 275 
		gearing_bonus = 0.0000 
		speed_step = 2 
		type = infrastructure 
		} 
	province_development = { 
		id = { type = 29600 id = 46 } 
		name = "" 
		progress = 0.0000 
		location = 101 
		cost = 2.0000 
		date = { 
			year = 1941 
			month = december 
			day = 11 
			hour = 0 
			} 
		manpower = 0.1000 
		close_when_finished = yes 
		waitingforclosure = no 
		total_progress = 0.0000 
		size = 24 
		done = 0 
		days = 2150 
		days_for_first = 110 
		gearing_bonus = 0.0000 
		type = infrastructure 
		} 
	province_development = { 
		id = { type = 29600 id = 47 } 
		name = "" 
		progress = 0.0000 
		location = 113 
		cost = 2.0000 
		date = { 
			year = 1942 
			month = november 
			day = 28 
			hour = 0 
			} 
		manpower = 0.1000 
		close_when_finished = yes 
		waitingforclosure = no 
		total_progress = 0.0000 
		size = 28 
		done = 0 
		days = 2498 
		days_for_first = 110 
		gearing_bonus = 0.0000 
		type = infrastructure 
		} 
	province_development = { 
		id = { type = 29600 id = 48 } 
		name = "" 
		progress = 0.0000 
		location = 127 
		cost = 2.0000 
		date = { 
			year = 1943 
			month = may 
			day = 0 
			hour = 0 
			} 
		manpower = 0.1000 
		close_when_finished = yes 
		waitingforclosure = no 
		total_progress = 0.0000 
		size = 24 
		done = 0 
		days = 2150 
		days_for_first = 110 
		gearing_bonus = 0.0000 
		type = infrastructure 
		} 
	province_development = { 
		id = { type = 29600 id = 49 } 
		name = "" 
		progress = 0.0000 
		location = 122 
		cost = 2.0000 
		date = { 
			year = 1943 
			month = may 
			day = 0 
			hour = 0 
			} 
		manpower = 0.1000 
		close_when_finished = yes 
		waitingforclosure = no 
		total_progress = 0.0000 
		size = 24 
		done = 0 
		days = 2150 
		days_for_first = 110 
		gearing_bonus = 0.0000 
		type = infrastructure 
		} 
	brigade_development = { 
		id = { type = 29600 id = 50 } 
		name = "36' AA" 
		progress = 0.0000 
		location = 101 
		cost = 0.7360 
		date = { 
			year = 1937 
			month = april 
			day = 20 
			hour = 0 
			} 
		manpower = 0.1000 
		close_when_finished = yes 
		waitingforclosure = no 
		retooling_time = 34.0000 
		total_progress = 0.0000 
		size = 5 
		done = 0 
		days = 87 
		days_for_first = 97 
		gearing_bonus = 0.0000 
		type = naval_anti_air_s 
		model = 1 
		} 
	brigade_development = { 
		id = { type = 29600 id = 51 } 
		name = "20' Capital Fire Control" 
		progress = 0.0000 
		location = 101 
		cost = 1.3800 
		date = { 
			year = 1936 
			month = october 
			day = 11 
			hour = 0 
			} 
		manpower = 0.1000 
		close_when_finished = yes 
		waitingforclosure = no 
		retooling_time = 34.0000 
		total_progress = 0.0000 
		size = 5 
		done = 0 
		days = 55 
		days_for_first = 55 
		gearing_bonus = 0.0000 
		type = naval_fire_controll_l 
		model = 0 
		} 
}
