#####################
# Country main data #
#####################

country =
{ tag                    = SCH
  capital                = 532
  manpower               = 127.4 # 135 - building queue -5 for HQ
  # Resource Reserves
  energy                 = 1462
  metal                  = 743
  rare_materials         = 396
  oil                    = 72
  supplies               = 742
  money                  = 200
  consumer = 0.2750 
  supply = 0.1000 
  production = 0.6250 
  reinforcement = 0.0000 
  upgrading = 0.0000 
  policy =
  { date              = { year = 0 month = january day = 0 }
    democratic        = 10
    political_left    = 2
    freedom           = 7
    free_market       = 9
    professional_army = 2
    defense_lobby     = 8
    interventionism   = 1
  }
  nationalprovinces      = { 532 530 533 372 }
  ownedprovinces         = { 532 530 533 372 }
  controlledprovinces    = { 532 530 533 372 }
  # Western Minor Tech '36
  # Group C 1936 techs
  # ######################
  techapps               = { 4010 4020 4120 2400   2010 2290 2300 2310 2450 2460 2510 1010 1190 1310 1110 9010 5010 5020 5080 5090 5190 6010 6020
                           }
  blueprints             = { 2150 }
	diplomacy = {
		relation = { tag = AFG value = 50 }
		relation = { tag = ALB value = 50 }
		relation = { tag = ARG value = 50 }
		relation = { tag = AST value = 50 }
		relation = { tag = AUS value = 50 }
		relation = { tag = BEL value = 50 }
		relation = { tag = BHU value = 1 }
		relation = { tag = BOL value = 50 }
		relation = { tag = BRA value = 50 }
		relation = { tag = BUL value = 50 }
		relation = { tag = CAN value = 50 }
		relation = { tag = CGX value = 30 }
		relation = { tag = CHC value = 1 }
		relation = { tag = CHI value = 50 }
		relation = { tag = CHL value = 50 }
		relation = { tag = COL value = 50 }
		relation = { tag = COS value = 50 }
		relation = { tag = CSX value = 1 }
		relation = { tag = CUB value = 50 }
		relation = { tag = CXB value = 1 }
		relation = { tag = CYN value = 1 }
		relation = { tag = CZE value = 50 }
		relation = { tag = DEN value = 50 }
		relation = { tag = DOM value = 50 }
		relation = { tag = ECU value = 50 }
		relation = { tag = EGY value = 40 }
		relation = { tag = ENG value = 50 }
		relation = { tag = EST value = 50 }
		relation = { tag = ETH value = 30 }
		relation = { tag = FIN value = 50 }
		relation = { tag = FRA value = 50 }
		relation = { tag = GER value = 50 }
		relation = { tag = GRE value = 50 }
		relation = { tag = GUA value = 50 }
		relation = { tag = HAI value = 50 }
		relation = { tag = HOL value = 50 }
		relation = { tag = HON value = 50 }
		relation = { tag = HUN value = 50 }
		relation = { tag = IND value = 1 }
		relation = { tag = IRE value = 50 }
		relation = { tag = IRQ value = 40 }
		relation = { tag = ITA value = 50 }
		relation = { tag = JAP value = 50 }
		relation = { tag = LAT value = 50 }
		relation = { tag = LIB value = 50 }
		relation = { tag = LIT value = 50 }
		relation = { tag = LUX value = 50 }
		relation = { tag = MAN value = 30 }
		relation = { tag = MEX value = 50 }
		relation = { tag = MLY value = 1 }
		relation = { tag = MON value = 1 }
		relation = { tag = NEP value = 1 }
		relation = { tag = NIC value = 50 }
		relation = { tag = NOR value = 50 }
		relation = { tag = NZL value = 50 }
		relation = { tag = OMN value = 1 }
		relation = { tag = PAN value = 50 }
		relation = { tag = PAR value = 50 }
		relation = { tag = PER value = 50 }
		relation = { tag = PHI value = 50 }
		relation = { tag = POL value = 50 }
		relation = { tag = POR value = 50 }
		relation = { tag = PRU value = 50 }
		relation = { tag = ROM value = 50 }
		relation = { tag = SAF value = 50 }
		relation = { tag = SAL value = 50 }
		relation = { tag = SAU value = 50 }
		relation = { tag = SIA value = 50 }
		relation = { tag = SIK value = 1 }
		relation = { tag = SOV value = 50 }
		relation = { tag = SPA value = 30 }
		relation = { tag = SPR value = 50 }
		relation = { tag = SWE value = 50 }
		relation = { tag = TAN value = 50 }
		relation = { tag = TIB value = 50 }
		relation = { tag = TUR value = 50 }
		relation = { tag = U27 value = 50 }
		relation = { tag = URU value = 50 }
		relation = { tag = USA value = 65 }
		relation = { tag = VEN value = 50 }
		relation = { tag = YEM value = 1 }
		relation = { tag = YUG value = 50 }
	}

	SpyInfo = { country = "SCH" NumberOfSpies = 2 }
	SpyInfo = { country = "BEL" NumberOfSpies = 2 }
	SpyInfo = { country = "CZE" NumberOfSpies = 1 }
	SpyInfo = { country = "EGY" NumberOfSpies = 1 }
	SpyInfo = { country = "ENG" NumberOfSpies = 10 } # 1
	SpyInfo = { country = "FIN" NumberOfSpies = 1 }
	SpyInfo = { country = "FRA" NumberOfSpies = 10 } # 2
	SpyInfo = { country = "GER" NumberOfSpies = 10 } # 2
	SpyInfo = { country = "HOL" NumberOfSpies = 2 }
	SpyInfo = { country = "IRQ" NumberOfSpies = 1 }
	SpyInfo = { country = "ITA" NumberOfSpies = 10 } # 2
	SpyInfo = { country = "SAF" NumberOfSpies = 2 }
	SpyInfo = { country = "SOV" NumberOfSpies = 10 } # 2
	SpyInfo = { country = "TUR" NumberOfSpies = 2 }
	SpyInfo = { country = "USA" NumberOfSpies = 10 } # 2
	SpyInfo = { country = "JAP" NumberOfSpies = 10 } # 0

  headofstate            = { type = 9 id = 17001 }
  headofgovernment       = { type = 9 id = 17002 }
  foreignminister        = { type = 9 id = 17003 }
  armamentminister       = { type = 9 id = 17004 }
  ministerofsecurity     = { type = 9 id = 17005 }
  ministerofintelligence = { type = 9 id = 17006 }
  chiefofstaff           = { type = 9 id = 17007 }
  chiefofarmy            = { type = 9 id = 17008 }
  chiefofnavy            = { type = 9 id = 17009 }
  chiefofair             = { type = 9 id = 17010 }
  # Superior Firepower
  # ####################
  # ###Swiss 36OOB####
  # ####################
  landunit =
  { id       = { type = 30600 id = 1 }
    location = 532
    name     = "I Armeekorps"
    division =
    { id       = { type = 30600 id = 100 }
      name     = "1. Feldarmee"
      strength = 100
      type     = hq
      extra    = engineer
    }
    division =
    { id       = { type = 30600 id = 2 }
      name     = "1. Felddivision"
      strength = 100
      type     = infantry
      extra    = artillery
    }
  }
  # ############################
  # #############################
  landunit =
  { id       = { type = 30600 id = 3 }
    location = 533
    name     = "II Corps d' Armée"
    division =
    { id       = { type = 30600 id = 4 }
      name     = "2. Division d' Infanterie"
      strength = 100
      type     = infantry
      extra    = anti_air
    }
    division =
    { id       = { type = 30600 id = 5 }
      name     = "1. Alpenjägerdivision"
      strength = 30
      type     = bergsjaeger
    }
  }
  # ###########################
  # ############################
  landunit =
  { id       = { type = 30600 id = 6 }
    location = 530
    name     = "III Corpa di Armata"
    division =
    { id       = { type = 30600 id = 7 }
      name     = "3. Divisione di Fanteria"
      strength = 100
      type     = infantry
      extra    = anti_tank
    }
    division =
    { id       = { type = 30600 id = 8 }
      name     = "4. Felddivisionen"
      strength = 100
      type     = infantry
    }
    division =
    { id       = { type = 30600 id = 9 }
      name     = "2. Div. de Infanterie de Montagne"
      strength = 30
      type     = bergsjaeger
    }
  }
  # ###############################
  # ###############################
  landunit =
  { id       = { type = 30600 id = 10 }
    location = 372
    name     = "IV Armeekorps"
    division =
    { id       = { type = 30600 id = 11 }
      name     = "5. Division d' Infanterie"
      strength = 100
      type     = infantry
      extra    = engineer
    }
    division =
    { id       = { type = 30600 id = 12 }
      name     = "6. Divisione di Fanteria"
      strength = 100
      type     = infantry
    }
    division =
    { id       = { type = 30600 id = 13 }
      name     = "3. Divisione di Alpinisti"
      strength = 30
      type     = bergsjaeger
    }
  }
  airunit =
  { id       = { type = 30600 id = 14 }
    location = 532
    base     = 532
    name     = "Heeren Luftwaffe Abteilung 1"
    division =
    { id       = { type = 30600 id = 15 }
      name     = "Taktikkampfgeschwader 1"
      strength = 40
      type     = tactical_bomber
      model    = 0
    }
  } 
	province_development = { 
		id = { type = 30600 id = 16 } 
		name = "" 
		progress = 0.0000 
		location = 532 
		cost = 2.0000 
		date = { 
			year = 1939 
			month = april 
			day = 9 
			hour = 0 
			} 
		manpower = 0.1000 
		close_when_finished = yes 
		waitingforclosure = no 
		total_progress = 0.0000 
		size = 24 
		done = 0 
		days = 1676 
		days_for_first = 86 
		gearing_bonus = 0.0000 
		speed_step = 1 
		type = infrastructure 
		} 
}
