##############################
# Country definition for ENG #
##############################

province = { id = 28 oilpool = 200 supplypool = 200 } # Belfast # was 2000 supplies + 1000 oil before 1.09
province =
{ id          = 31
  oilpool     = 200 # was 1000 before 1.09
  supplypool  = 200 # was 1000 before 1.09
}               # Malta
province =
{ id          = 348
  oilpool     = 200 # was 1000 before 1.09
  supplypool  = 200 # was 1000 before 1.09
}               # Gibraltar
province =
{ id         = 538
  oilpool    = 100
  supplypool = 500
}              # Bermuda
province =
{ id         = 866
  oilpool    = 100
  supplypool = 100
}              # Falkland Islands
province = { id = 900 oilpool = 800 supplypool = 800 } # Suez
province =
{ id         = 988
  oilpool    = 200 # was 1000 before 1.09
  supplypool = 200 # was 2000 before 1.09
}              # Freetown
province =
{ id          = 1315
  oilpool     = 200 # was 1000 before 1.09
  supplypool  = 200 # was 1000 before 1.09
}               # Hong Kong
province =
{ id          = 1517
  rarematerialspool = 68
  oilpool     = 200 # was 1000 before 1.09
  supplypool  = 200 # was 2000 before 1.09
}               # Colombo
province =
{ id         = 1817
  oilpool    = 100
  supplypool = 100
}              # Diego Garcia Island
province =
{ id          = 1353
  rarematerialspool = 120
  metalpool = 80
  oilpool     = 200 # was 1000 before 1.09
  supplypool  = 200 # was 2000 before 1.09
}               # Singapore
province =
{ id         = 873
  supplypool = 50
}              # Georgetown
province =
{ id         = 809
  supplypool = 50
}              # Trinidad
province =
{ id         = 444
  supplypool = 50
}              # Cyprus
province =
{ id         = 891
  supplypool = 1
}              # Jamaica

#####################
# Country main data #
#####################

country =
{ tag                    = ENG
  capital                = 19
  peacetime_ic_mod       = 0.25
  manpower               = 28.8
  # Resource Reserves
  energy                 = 22478
  metal                  = 9501
  rare_materials         = 6195
  oil                    = 5139
  supplies               = 10781
  money                  = 600
  consumer = 0.2450 
  supply = 0.0884 
  production = 0.6666 
  reinforcement = 0.0000 
  upgrading = 0.0000 
  expense_synthetic = 0.0000 
  expense_synthetic_rares = 0.0000  
  transports             = 3348
  escorts                = 103

	diplomacy = {
		relation = { tag = AFG value = 25 guaranteed = { day = 30 month = december year = 1935 } }
		relation = { tag = ALB value = 5 }
		relation = { tag = ARG value = 25 }
		relation = { tag = AST value = 150 }
		relation = { tag = AUS value = 30 guaranteed = { day = 27 month = september year = 1934 } }
		relation = { tag = BEL value = 45 guaranteed = { day = 30 month = december year = 1935 } }
		relation = { tag = BHU value = 175 }
		relation = { tag = BOL value = 15 }
		relation = { tag = BRA value = 40 }
		relation = { tag = BUL value = 15 }
		relation = { tag = CAN value = 150 }
		relation = { tag = CGX value = 30 }
		relation = { tag = CHC value = -15 }
		relation = { tag = CHI value = 35 }
		relation = { tag = CHL value = 30 }
		relation = { tag = COL value = 40 }
		relation = { tag = COS value = 15 }
		relation = { tag = CSX value = 30 }
		relation = { tag = CUB value = 50 }
		relation = { tag = CXB value = 25 }
		relation = { tag = CYN value = 30 }
		relation = { tag = CZE value = 75 }
		relation = { tag = DEN value = 50 guaranteed = { day = 30 month = august year = 1934 } }
		relation = { tag = DOM value = 25 }
		relation = { tag = ECU value = 35 }
		relation = { tag = EGY value = 100 guaranteed = { day = 30 month = december year = 1935 } access = yes }
		relation = { tag = EST value = 20 }
		relation = { tag = ETH value = 65 }
		relation = { tag = FIN value = 50 }
		relation = { tag = FRA value = 50 }
		relation = { tag = GER value = 35 }
		relation = { tag = GRE value = 65 guaranteed = { day = 11 month = february year = 1934 } }
		relation = { tag = GUA value = 25 }
		relation = { tag = HAI value = 15 }
		relation = { tag = HOL value = 45 }
		relation = { tag = HON value = 25 }
		relation = { tag = HUN value = 10 }
		relation = { tag = IND value = 100 access = yes }
		relation = { tag = IRE value = 50 guaranteed = { day = 11 month = february year = 1934 } }
		relation = { tag = IRQ value = 100 guaranteed = { day = 11 month = february year = 1934 } }
		relation = { tag = ITA value = 40 }
		relation = { tag = JAP value = 40 }
		relation = { tag = LAT value = 20 }
		relation = { tag = LIB value = 40 }
		relation = { tag = LIT value = 20 }
		relation = { tag = LUX value = 40 }
		relation = { tag = MAN value = 10 }
		relation = { tag = MEX value = 40 }
		relation = { tag = MLY value = 150 }
		relation = { tag = MON value = -15 }
		relation = { tag = NEP value = 175 }
		relation = { tag = NIC value = 30 }
		relation = { tag = NOR value = 40 guaranteed = { day = 30 month = august year = 1934 } }
		relation = { tag = NZL value = 150 }
		relation = { tag = OMN value = 175 guaranteed = { day = 11 month = february year = 1934 } access = yes }
		relation = { tag = PAN value = 50 }
		relation = { tag = PAR value = 10 }
		relation = { tag = PER value = 40 guaranteed = { day = 11 month = february year = 1934 } }
		relation = { tag = PHI value = 45 }
		relation = { tag = POL value = 45 }
		relation = { tag = POR value = 45 guaranteed = { day = 30 month = december year = 1935 } }
		relation = { tag = PRU value = 30 }
		relation = { tag = ROM value = 40 }
		relation = { tag = SAF value = 150 }
		relation = { tag = SAL value = 30 }
		relation = { tag = SAU value = 35 guaranteed = { day = 11 month = february year = 1934 } }
		relation = { tag = SIA value = 30 }
		relation = { tag = SIK value = 20 }
		relation = { tag = SOV value = 25 }
		relation = { tag = SPA value = 25 }
		relation = { tag = SPR value = 45 }
		relation = { tag = SWE value = 40 guaranteed = { day = 30 month = august year = 1934 } }
		relation = { tag = SCH value = 50 }
		relation = { tag = TAN value = -15 }
		relation = { tag = TIB value = 15 }
		relation = { tag = TUR value = 40 guaranteed = { day = 11 month = february year = 1934 } }
		relation = { tag = U27 value = 175 guaranteed = { day = 30 month = december year = 1935 } access = yes }
		relation = { tag = URU value = 40 }
		relation = { tag = USA value = 100 }
		relation = { tag = VEN value = 65 }
		relation = { tag = YEM value = 175 guaranteed = { day = 11 month = february year = 1934 } }
		relation = { tag = YUG value = 40 }
		relation = { tag = JOR value = 200 access = yes }
		relation = { tag = SUD value = 200 access = yes }
		relation = { tag = MLY value = 200 access = yes }
		relation = { tag = SAR value = 200 access = yes }
		relation = { tag = BRU value = 200 access = yes }
		relation = { tag = PAL value = 200 access = yes }
		relation = { tag = U91 value = 200 access = yes }
		relation = { tag = U15 value = 200 access = yes }
		relation = { tag = U27 value = 200 access = yes }
		relation = { tag = U09 value = 200 access = yes }
	}

	SpyInfo = { country = "ENG" NumberOfSpies = 7 }
	SpyInfo = { country = "AFG" NumberOfSpies = 2 }
	SpyInfo = { country = "ARG" NumberOfSpies = 1 }
	SpyInfo = { country = "AST" NumberOfSpies = 5 }
	SpyInfo = { country = "AUS" NumberOfSpies = 1 }
	SpyInfo = { country = "BEL" NumberOfSpies = 2 }
	SpyInfo = { country = "BHU" NumberOfSpies = 4 }
	SpyInfo = { country = "BRA" NumberOfSpies = 2 }
	SpyInfo = { country = "CAN" NumberOfSpies = 5 }
	SpyInfo = { country = "CGX" NumberOfSpies = 2 }
	SpyInfo = { country = "CHI" NumberOfSpies = 4 }
	SpyInfo = { country = "CHL" NumberOfSpies = 1 }
	SpyInfo = { country = "COL" NumberOfSpies = 2 }
	SpyInfo = { country = "CSX" NumberOfSpies = 1 }
	SpyInfo = { country = "CUB" NumberOfSpies = 1 }
	SpyInfo = { country = "CYN" NumberOfSpies = 1 }
	SpyInfo = { country = "CZE" NumberOfSpies = 3 }
	SpyInfo = { country = "DEN" NumberOfSpies = 1 }
	SpyInfo = { country = "ECU" NumberOfSpies = 1 }
	SpyInfo = { country = "EGY" NumberOfSpies = 7 }
	SpyInfo = { country = "ETH" NumberOfSpies = 2 }
	SpyInfo = { country = "FIN" NumberOfSpies = 2 }
	SpyInfo = { country = "FRA" NumberOfSpies = 6 }
	SpyInfo = { country = "GER" NumberOfSpies = 5 }
	SpyInfo = { country = "GRE" NumberOfSpies = 3 }
	SpyInfo = { country = "GUA" NumberOfSpies = 1 }
	SpyInfo = { country = "HOL" NumberOfSpies = 2 }
	SpyInfo = { country = "HON" NumberOfSpies = 1 }
	SpyInfo = { country = "IND" NumberOfSpies = 6 }
	SpyInfo = { country = "IRE" NumberOfSpies = 4 }
	SpyInfo = { country = "IRQ" NumberOfSpies = 6 }
	SpyInfo = { country = "ITA" NumberOfSpies = 4 }
	SpyInfo = { country = "JAP" NumberOfSpies = 2 }
	SpyInfo = { country = "LIB" NumberOfSpies = 1 }
	SpyInfo = { country = "MAN" NumberOfSpies = 1 }
	SpyInfo = { country = "MEX" NumberOfSpies = 1 }
	SpyInfo = { country = "MLY" NumberOfSpies = 6 }
	SpyInfo = { country = "NEP" NumberOfSpies = 4 }
	SpyInfo = { country = "NOR" NumberOfSpies = 2 }
	SpyInfo = { country = "NZL" NumberOfSpies = 4 }
	SpyInfo = { country = "OMN" NumberOfSpies = 6 }
	SpyInfo = { country = "PER" NumberOfSpies = 4 }
	SpyInfo = { country = "PHI" NumberOfSpies = 1 }
	SpyInfo = { country = "POL" NumberOfSpies = 4 }
	SpyInfo = { country = "POR" NumberOfSpies = 2 }
	SpyInfo = { country = "PRU" NumberOfSpies = 1 }
	SpyInfo = { country = "ROM" NumberOfSpies = 1 }
	SpyInfo = { country = "SAF" NumberOfSpies = 4 }
	SpyInfo = { country = "SAU" NumberOfSpies = 2 }
	SpyInfo = { country = "SIA" NumberOfSpies = 1 }
	SpyInfo = { country = "SIK" NumberOfSpies = 1 }
	SpyInfo = { country = "SOV" NumberOfSpies = 4 }
	SpyInfo = { country = "SPR" NumberOfSpies = 4 }
	SpyInfo = { country = "SWE" NumberOfSpies = 1 }
	SpyInfo = { country = "SCH" NumberOfSpies = 2 }
	SpyInfo = { country = "TIB" NumberOfSpies = 1 }
	SpyInfo = { country = "TUR" NumberOfSpies = 3 }
	SpyInfo = { country = "U27" NumberOfSpies = 5 }
	SpyInfo = { country = "URU" NumberOfSpies = 1 }
	SpyInfo = { country = "USA" NumberOfSpies = 4 }
	SpyInfo = { country = "VEN" NumberOfSpies = 2 }
	SpyInfo = { country = "YEM" NumberOfSpies = 6 }
	SpyInfo = { country = "YUG" NumberOfSpies = 1 }

	SpyInfo = { country = "SPA" NumberOfSpies = 2 }

  # GREAT BRITAIN
	nationalprovinces =		{ 3 5 6 7 8 9 10 11 12 13 14 15 16 17 19 20 21 22 23 #GREAT BRITAIN
28 29 #Northern Ireland
348 #Gibraltar
				#31 #Malta
				#444 #Cyprus
				#SOUTHEAST ASIA
				#1353 #Singapore
				#1644 1646 1647 #Sarawak-Borneo
				#1315 #Hong Kong
				#CARRIBEAN
				#758 #Belize
				#891 #Jamaica
				#871 873 #British Guyana
				#806 807 808 809 896 897 #British West Indies
				896 #Virgin Islands
				#652 653 664 665 666 668 805 #The Bahamas
				#ATLANTIC OCEAN
				538 #Bermuda
				866 #Falkland Islands
				1147 #Ascension Island
				1148 #St.Helena
				#AFRICA
				#1132 #Malawi
				#1139 1062 1140 1141 1064 1060 1061 1059 #British East Africa
				#1035 1036 #British Somaliland
				#1112 1111 1105 #Bechuanaland
				#1124 1125 #South Rhodesia
				#1104 1099 1129 1126 1128 #North Rhodesia
				#1000 1001 1002 #Gold Coast
				#1008 1007 999 1009 1010 1011 1145 1085 1012 #Nigeria
				#988 #Sierra Leone
				#982 #Gambia
				#INDIAN OCEAN
#1516 1517 #Ceylon
				#1816 #Seychelles
				1817 #Diego Garcia
				#1136 #Mauritius
				#1815 #Sokotra
				#PACIFIC
				#1614 1622 1683 1684 1685 1686
				#1752 1753 1754 1755 1757 1758 1759 1760
				#1761 1763 1767 1768 1769 1770
}


  ownedprovinces         = { 1132 1112 1111 1105 901 3    5    6    7    8    9    10   11   12   13   14   15   16   17   19   20   21   22   23   28   29   348  31   444 1516
				1647 1353
                             1813 1814 900
                             
                             1315 758  891  871  873  806  807  808  809  897  538  652  653  664  665  666 
                             668  805  896  866  1147 1148 1816 1817 1136 1815 1139 1062 1140 1141 1064 1060 1061 1059 1035 1036 1000 1001 1002 1008 1007 999  1009 1010 1011 1145 1085 1012 988  982  1622 1683 1684
                             1517 1685 1686 1763 1761 1767 1768 1769 1770 1757 1759 1760 1752 1753 1754 1755 1758 1614
                           }
  # GREAT BRITAIN
  controlledprovinces    = { 1132 1112 1111 1105 901 3    5    6    7    8    9    10   11   12   13   14   15   16   17   19   20   21   22   23   28   29   348  31   444 1516
				1647 1353
                             1813 1814 900
                             
                             1315 758  891  871  873  806  807  808  809  897  538  652  653  664  665  666 
                             668  805  896  866  1147 1148 1816 1817 1136 1815 1139 1062 1140 1141 1064 1060 1061 1059 1035 1036 1000 1001 1002 1008 1007 999 1009 1010 1011 1145 1085 1012 988  982  1622 1683 1684
                             1517 1685 1686 1763 1761 1767 1768 1769 1770 1757 1759 1760 1752 1753 1754 1755 1758 1614
                           }
  # Commonwealth Tech '36
  # UK 1936 techs
  # ######################
  techapps               = { 4010  4020  4120  4130     2010  2020  2030  2290  2300  2310  2450  2460  2510  1010  1020  1190  1200  1210  1220 
                             4220  1110  2400  1150  1310  5010  5020  5080  5090  5190  5310  5320  5410  5470  5480  3420  9010  9020 
                             9030  9140  6010  6030  6120  8010  8020  8030  8040  8050  8070  8100  8120  3010  3020  3030  3070  3080  3090 
                             12100 12110 3100  3130  3140  3150  3190  3200  3210  3220  3250  3260  3270  3280  3290  3320  3330  3340  3400  3410  14000 3470
                             1380 4250 4190 2150
				5200 5210 #Adv. Oil Ref
                           }
  blueprints             = { }
  policy =
  { date              = { year = 0 month = january day = 0 }
    democratic        = 10
    political_left    = 2
    freedom           = 10
    free_market       = 8
    professional_army = 7
    defense_lobby     = 6
    interventionism   = 6
  }
  headofstate            = { type = 9 id = 1001 }
  headofgovernment       = { type = 9 id = 1002 }
  foreignminister        = { type = 9 id = 1003 }
  armamentminister       = { type = 9 id = 1004 }
  ministerofsecurity     = { type = 9 id = 1005 }
  ministerofintelligence = { type = 9 id = 1006 }
  chiefofstaff           = { type = 9 id = 1007 }
  chiefofarmy            = { type = 9 id = 1008 }
  chiefofnavy            = { type = 9 id = 1009 }
  chiefofair             = { type = 9 id = 1010 }

  nationalidentity = "policy_identity_imperial" 
	socialpolicy = "policy_social_liberal" 
	nationalculture = "policy_culture_libertarian"

#LAND OOB

landunit = {
	id = { type = 12700 id = 1000 }
	name = "Aldershot Command"
	location = 20 # Dover

	division = {
		id = { type = 12700 id = 1001 }
		name = "1st Infantry Division"
		type = infantry
		model = 1
		experience = 15
		extra = light_armor_brigade
		brigade_model = 0
	}
	division = {
		id = { type = 12700 id = 1002 }
		name = "2nd Infantry Division"
		type = infantry
		model = 1
		experience = 15
		extra = light_armor_brigade
		brigade_model = 0
	}
}

landunit = {
	id = { type = 12700 id = 1003 }
	name = "Eastern Command"
	location = 17 # Norwich

	division = {
		id = { type = 12700 id = 1004 }
		name = "4th Infantry Division"
		type = infantry
		model = 1
		experience = 15
		extra = artillery
		brigade_model = 0
	}
}

landunit = { 
	id = { type = 12700 id = 1005 }
	name = "East Anglia Area"
	location = 17 # Norwich

	division = {
		id = { type = 12700 id = 1007 }
		name = "54th 'East Anglia' Division"
		type = infantry
		model = 0
		strength = 40
		experience = 20
		extra = artillery
		brigade_model = 0
	}
}

landunit = {
	id = { type = 12700 id = 1008 }
	name = "Woolwich Area"
	location = 19 # London

	division = {
		id = { type = 12700 id = 10010 }
		name = "44th 'Home Counties' Division"
		type = infantry
		model = 0
		strength = 40
		experience = 20
		extra = artillery
		brigade_model = 0
	}
}

landunit = {
	id = { type = 12700 id = 1011 }
	name = "Northern Command"
	location = 11 # Sunderland

	division = {
		id = { type = 12700 id = 1012 }
		name = "5th Infantry Division"
		type = infantry
		model = 1
		strength = 100
		experience = 15
		extra = artillery
		brigade_model = 0
	}
}

landunit = {
	id = { type = 12700 id = 1013 }
	name = "Northumbrian Area"
	location = 11 #Sunderland

	division = {
		id = { type = 12700 id = 1015 }
		name = "50th 'Northumbrian' Division"
		type = infantry
		model = 0
		strength = 40
		experience = 20
		extra = b_u9
		brigade_model = 3
	}
}

landunit = {
	id = { type = 12700 id = 1016 }
	name = "West Riding Area"
	location = 12 # Blackpool

	division = {
		id = { type = 12700 id = 1017 }
		name = "1st Cavalry Division"
		type = cavalry
		model = 1
		strength = 40
		experience = 20
	}

	division = {
		id = { type = 12700 id = 1019 }
		name = "49th 'West Riding' Division"
		type = infantry
		model = 0
		strength = 40
		experience = 20
		extra = artillery
		brigade_model = 0
	}
}

landunit = {
	id = { type = 12700 id = 1020 }
	name = "Welsh Area"
	location = 15 # Cardiff

	division = {
		id = { type = 12700 id = 1022 }
		name = "53rd 'Welsh' Division"
		type = infantry
		model = 0
		strength = 40
		experience = 20
		extra = artillery
		brigade_model = 0
	}
}

landunit = {
	id = { type = 12700 id = 1023 }
	name = "West Lancashire Area"
	location = 14 # Liverpool

	division = {
		id = { type = 12700 id = 1025 }
		name = "55th 'West Lancashire' Division"
		type = infantry
		model = 0
		strength = 40
		experience = 20
		extra = artillery
		brigade_model = 0
	}
}

landunit = {
	id = { type = 12700 id = 1026 }
	name = "East Lancashire Area"
	location = 14 # Liverpool

	division = {
		id = { type = 12700 id = 1028 }
		name = "42nd 'East Lancashire' Division"
		type = infantry
		model = 0
		strength = 40
		experience = 20
		extra = anti_air
		brigade_model = 0
	}
}

landunit = {
	id = { type = 12700 id = 1029 }
	name = "Southern Command"
	location = 21 # Portsmouth

	division = {
		id = { type = 12700 id = 1030 }
		name = "3rd Infantry Division"
		type = infantry
		model = 0
		experience = 15
		extra = artillery
		brigade_model = 0
	}
}

landunit = {
	id = { type = 12700 id = 1031 }
	name = "South Midland Area"
	location = 22 # Bristol

	division = {
		id = { type = 12700 id = 1033 }
		name = "48th 'South Midland' Division"
		type = infantry
		model = 0
		strength = 40
		experience = 20
		extra = engineer
		brigade_model = 0
	}
}

landunit = {
	id = { type = 12700 id = 1034 }
	name = "South-Western Area"
	location = 21 # Portsmouth

	division = {
		id = { type = 12700 id = 1036 }
		name = "43rd 'Wessex' Division"
		type = infantry
		model = 0
		strength = 40
		experience = 20
		extra = anti_air
		brigade_model = 0
	}
}

landunit = {
	id = { type = 12700 id = 1037 }
	name = "Highland Area"
	location = 8 # Dunfermline

	division = {
		id = { type = 12700 id = 1039 }
		name = "51st 'Highland' Division"
		type = infantry
		model = 0
		strength = 40
		experience = 20
		extra = b_u9
		brigade_model = 3
	}
}

landunit = {
	id = { type = 12700 id = 1040 }
	name = "Lowland Area"
	location = 9 # Glasgow

	division = {
		id = { type = 12700 id = 1042 }
		name = "52nd 'Lowland' Division"
		type = infantry
		model = 0
		strength = 40
		experience = 20
		extra = b_u9
		brigade_model = 3
	}
}

landunit = {
	id = { type = 12700 id = 1043 }
	name = "London District"
	location = 19 # London

	division = {
		id = { type = 12700 id = 1044 }
		name = "G.H.Q."
		type = hq
		model = 0
		experience = 15
		extra = artillery
		brigade_model = 2
	}

	division = {
		id = { type = 12700 id = 1046 }
		name = "56th 'London' Division"
		type = infantry
		model = 0
		strength = 40
		experience = 20
		extra = b_u9
		brigade_model = 3
	}
}

landunit = {
	id = { type = 12700 id = 1047 }
	name = "Northern Ireland District"
	location = 28 # Belfast

	division = {
		id = { type = 12700 id = 1048 }
		name = "Northern Ireland District"
		type = garrison
		model = 0
		experience = 15
	}
}

landunit = {
	id = { type = 12700 id = 1049 }
	name = "Mechanised Force"
	location = 20 # Dover

	division = {
		id = { type = 12700 id = 1050 }
		name = "1st Armoured Division"
		type = armor
		model = 0
		strength = 40
		experience = 20
		extra = heavy_armor
		brigade_model = 0
	}
}

landunit = {
	id = { type = 12700 id = 1051 }
	name = "Home Fleet"
	location = 5 # Scapa Flow

	division = {
		id = { type = 12700 id = 1052 }
		name = "Home Fleet"
		type = garrison
		model = 0
		experience = 0
	}
}

landunit = {
	id = { type = 12700 id = 1053 }
	name = "Rosyth Command"
	location = 8 # Dunfermline

	division = {
		id = { type = 12700 id = 1054 }
		name = "Rosyth Command"
		type = garrison
		model = 0
		experience = 0
	}
}

landunit = {
	id = { type = 12700 id = 1055 }
	name = "Nore Command"
	location = 20 # Dover

	division = {
		id = { type = 12700 id = 1056 }
		name = "Nore Command"
		type = garrison
		model = 0
		experience = 0
	}
}

landunit = {
	id = { type = 12700 id = 1057 }
	name = "Portsmouth Command"
	location = 21 # Portsmouth

	division = {
		id = { type = 12700 id = 1058 }
		name = "Portsmouth Command"
		type = garrison
		model = 0
		strength = 100
		experience = 0
		}
	}

landunit = {
	id = { type = 12700 id = 1059 }
	name = "Western Approaches Command"
	location = 23 # Plymouth

	division = {
		id = { type = 12700 id = 1060 }
		name = "Western Approaches Command"
		type = garrison
		model = 0
		experience = 0
	}
}

#######################################
# OVerseas Garrisons
#######################################

landunit = {
	id = { type = 12700 id = 1100 }
	name = "Hong Kong Command"
	location = 1315 #Hong Kong

	division = {
		id = { type = 12700 id = 1101 }
		name = "Hong Kong Defence Force"
		type = garrison
		model = 0
		strength = 50

		extra = artillery
		brigade_model = 1
	}
}

landunit = {
	id = { type = 12700 id = 1102 }
	name = "Ceylon Command"
	location = 1517 #Colombo

	division = {
		id = { type = 12700 id = 1103 }
		name = "Ceylon Defence Force"
		type = garrison
		model = 0
		strength = 50

		extra = artillery
		brigade_model = 1
	}
}

landunit = {
	id = { type = 12700 id = 1104 }
	name = "Malaya Command"
	location = 1353 #Singapore

	division = {
		id = { type = 12700 id = 1105 }
		name = "Malaya Brigade"
		type = garrison
		model = 0

		extra = anti_air 
		brigade_model = 0
	}
	division = {
		id = { type = 12700 id = 1106 }
		name = "12th Indian Brigade"
		type = garrison
		model = 0

		extra = artillery
		brigade_model = 1
	}
	division = {
		id = { type = 12700 id = 1107 }
		name = "Volunteer Force"
		type = garrison
		model = 0
		strength = 50

		extra = police
		brigade_model = 0
	}
}

landunit = {
	id = { type = 12700 id = 1108 }
	name = "HQ British Troops - Aden"
	location = 1813 #Aden

	division = {
		id = { type = 12700 id = 1109 }
		name = "Aden Protectorate Levies"
		type = garrison
		model = 0
		strength = 20
	}
}

landunit = {
	id = { type = 12700 id = 1110 }
	name = "Gibraltar Command"
	location = 348 #Gibraltar

	division = {
		id = { type = 12700 id = 1111 }
		name = "Gibraltar Defence Force"
		type = garrison
		model = 0
		experience = 15

		extra = artillery
		brigade_model = 1
	}
}

landunit = {
	id = { type = 12700 id = 1112 }
	name = "Malta Command"
	location = 31 #Malta

	division = {
		id = { type = 12700 id = 1113 }
		name = "Malta Defence Force"
		type = garrison
		model = 0
		experience = 15

		extra = anti_air 
		brigade_model = 0
	}
}

landunit = {
	id = { type = 12700 id = 1114 }
	name = "Cyprus Command"
	location = 444 #Cyprus

	division = {
		id = { type = 12700 id = 1115 }
		name = "Cyprus Defence Force"
		type = garrison
		model = 0
		strength = 20

	}
}

landunit = {
	id = { type = 12700 id = 1116 }
	name = "Sudan Command"
	location = 1066 #Khartoum

	division = {
		id = { type = 12700 id = 1117 }
		name = "Sudan Defence Force"
		type = garrison
		model = 0
		strength = 20

		extra = police
		brigade_model = 0
	}
}

landunit = {
	id = { type = 12700 id = 1118 }
	name = "Palestine Command"
	location = 1797 # Jerusalem

	division = {
		id = { type = 12700 id = 1119 }
		name = "Jerusalem Defence Force"
		type = garrison
		model = 0
		strength = 30

	}
}

landunit = {
	id = { type = 12700 id = 1120 }
	name = "British Forces in Palestine"
	location = 1797 # Jerusalem

	division = {
		id = { type = 12700 id = 1121 }
		name = "8th Infantry Division"
		type = militia
		model = 0
		experience = 15
		extra = b_u9
		brigade_model = 3
	}
}

landunit = {
	id = { type = 12700 id = 1122 }
	name = "British Troops in Egypt"
	location = 901 #Port Said

	division = {
		id = { type = 12700 id = 1123 }
		name = "7th Infantry Division"
		type = militia
		model = 0
		experience = 15
		extra = b_u9
		brigade_model = 3
	}
}

landunit = {
	id = { type = 12700 id = 1124 }
	name = "Egypt Command"
	location = 901 #Port Said

	division = {
		id = { type = 12700 id = 1125 }
		name = "Canal Brigade"
		type = garrison
		model = 0
		experience = 15

	}
}

landunit = {
	id = { type = 12700 id = 1126 }
	name = "Gold Coast Command"
	location = 1002 # Accra

	division = {
		id = { type = 12700 id = 1127 }
		name = "4th Gold Coast Brigade"
		type = garrison
		model = 0
		strength = 50
		experience = 0

		extra = police
		brigade_model = 0
	}
}

landunit = {
	id = { type = 12700 id = 1128 }
	name = "Kenya Command"
	location = 1060 #Nairobi

	division = {
		id = { type = 12700 id = 1129 }
		name = "1st East African Brigade"
		type = militia
		model = 0
		strength = 30
		extra = police
		brigade_model = 0
	}
}

landunit = {
	id = { type = 12700 id = 1130 }
	name = "Tanganyika Command"
	location = 1140 # Dar es Salaam

	division = {
		id = { type = 12700 id = 1131 }
		name = "2nd East African Brigade"
		type = militia
		model = 0
		strength = 20
		extra = police
		brigade_model = 0
	}
}

landunit = {
	id = { type = 12700 id = 1132}
	name = "Rangoon Force"
	location = 1299 # Rangoon

	division = {
		id = { type = 12700 id = 1133 }
		name = "1st Burma Brigade"
		type = garrison
		model = 0
		experience = 0

		extra = artillery
		brigade_model = 1
	}
}

landunit = {
	id = { type = 12700 id = 1134}
	name = "Mandalay Force"
	location = 1296 # Mandalay

	division = {
		id = { type = 12700 id = 1135 }
		name = "2nd Burma Brigade"
		type = garrison
		model = 0
		experience = 0

		extra = police
		brigade_model = 0
	}
}

landunit = {
	id = { type = 12700 id = 1136 }
	name = "Nigeria Command"
	location = 1008 # Lagos

	division = {
		id = { type = 12700 id = 1137 }
		name = "1st West African Brigade"
		type = garrison
		model = 0
		strength = 50
		experience = 0

		extra = police
		brigade_model = 0
	}
}

landunit = {
	id = { type = 12700 id = 1138 }
	name = "South Atlantic Command"
	location = 988 # Freetown

	division = {
		id = { type = 12700 id = 1139 }
		name = "South Atlantic Command"
		type = garrison
		model = 0
		strength = 50
		experience = 0

	}
}

landunit = {
	id = { type = 12700 id = 1140 }
	name = "Mediteranean Fleet"
	location = 906 # Alexandria

	division = {
		id = { type = 12700 id = 1141 }
		name = "Mediteranean Fleet"
		type = garrison
		model = 0
		experience = 0

	}
}
	### UK Navy OOB ###
  navalunit =
  { name     = "Home Fleet"
    id       = { type = 12700 id = 84 }
    location = 5 # Scapa Flow
    base     = 5
    division =
    { id    = { type = 12700 id = 85 }
      name  = "HMS Nelson"
      type  = battleship
      model = 3
      extra1 = naval_sa_l
      extra2 = naval_fire_controll_l
      extra3 = naval_spotter_l
      extra4 = naval_anti_air_l
      extra5 = none
      brigade_model1 = 0
      brigade_model2 = 0
      brigade_model3 = 1
      brigade_model4 = 1
      brigade_model5 = 0
    }
    division =
    { id    = { type = 12700 id = 86 }
      name  = "HMS Rodney"
      type  = battleship
      model = 3
      extra1 = naval_sa_l
      extra2 = naval_fire_controll_l
      extra3 = naval_spotter_l
      extra4 = naval_anti_air_l
      extra5 = none
      brigade_model1 = 0
      brigade_model2 = 0
      brigade_model3 = 1
      brigade_model4 = 1
      brigade_model5 = 0
    }
    division =
    { id    = { type = 12700 id = 87 }
      name  = "HMS Royal Sovereign"
      type  = battleship
      model = 2
      extra1 = naval_sa_l
      extra2 = naval_fire_controll_l
      extra3 = naval_spotter_l
      extra4 = naval_anti_air_l
      extra5 = none
      brigade_model1 = 0
      brigade_model2 = 1
      brigade_model3 = 1
      brigade_model4 = 1
      brigade_model5 = 0
    }
    division =
    { id    = { type = 12700 id = 89 }
      name  = "HMS Resolution"
      type  = battleship
      model = 2
      extra1 = naval_sa_l
      extra2 = naval_fire_controll_l
      extra3 = naval_spotter_l
      extra4 = naval_anti_air_l
      extra5 = none
      brigade_model1 = 0
      brigade_model2 = 0
      brigade_model3 = 1
      brigade_model4 = 1
      brigade_model5 = 0
    }
    division =
    { id    = { type = 12700 id = 90 }
      name  = "HMS Ramillies"
      type  = battleship
      model = 2
      extra1 = naval_sa_l
      extra2 = naval_fire_controll_l
      extra3 = naval_spotter_l
      extra4 = naval_anti_air_l
      extra5 = none
      brigade_model1 = 0
      brigade_model2 = 0
      brigade_model3 = 0
      brigade_model4 = 0
      brigade_model5 = 0
    }
    division =
    { id    = { type = 12700 id = 149 }
      name  = "HMS Barham"
      type  = battleship
      model = 1
      extra1 = naval_sa_l
      extra2 = naval_fire_controll_l
      extra3 = naval_spotter_l
      extra4 = naval_anti_air_l
      extra5 = none
      brigade_model1 = 0
      brigade_model2 = 0
      brigade_model3 = 1
      brigade_model4 = 0
      brigade_model5 = 0
    }
    division =
    { id    = { type = 12700 id = 151 }
      name  = "HMS Malaya"
      type  = battleship
      model = 1
      extra1 = naval_sa_l
      extra2 = naval_fire_controll_l
      extra3 = naval_spotter_l
      extra4 = naval_anti_air_l
      extra5 = none
      brigade_model1 = 0
      brigade_model2 = 0
      brigade_model3 = 1
      brigade_model4 = 0
      brigade_model5 = 0
    }
    division =
    { id    = { type = 12700 id = 150 }
      name  = "HMS Valiant"
      type  = battleship
      model = 1
      extra1 = naval_sa_l
      extra2 = naval_fire_controll_l
      extra3 = naval_spotter_l
      extra4 = naval_anti_air_l
      extra5 = none
      brigade_model1 = 0
      brigade_model2 = 0
      brigade_model3 = 1
      brigade_model4 = 1
      brigade_model5 = 0
    }
    division =
    { id    = { type = 12700 id = 230 }
      name  = "HMS Erebus, HMS Terror & HMS Marshal Soult"
      type  = battleship
      model = 0
      extra1 = none
      extra2 = naval_fire_controll_l
      extra3 = naval_spotter_l
      extra4 = naval_anti_air_l
      extra5 = none
      brigade_model1 = 0
      brigade_model2 = 0
      brigade_model3 = 1
      brigade_model4 = 1
      brigade_model5 = 0
    }
    division =
    { id    = { type = 12700 id = 91 }
      name  = "HMS Hood"
      type  = battlecruiser
      model = 2
      extra1 = naval_sa_l
      extra2 = naval_fire_controll_l
      extra3 = none
      extra4 = naval_anti_air_l
      brigade_model1 = 0
      brigade_model2 = 1
      brigade_model3 = 0
      brigade_model4 = 0
    }
    division =
    { id    = { type = 12700 id = 92 }
      name  = "HMS Renown"
      type  = battlecruiser
      model = 1
      extra1 = naval_sa_l
      extra2 = naval_fire_controll_l
      extra3 = naval_spotter_l
      extra4 = naval_anti_air_l
      brigade_model1 = 0
      brigade_model2 = 0
      brigade_model3 = 1
      brigade_model4 = 1
    }
    division =
    { id    = { type = 12700 id = 94 }
      name  = "HMS Repulse"
      type  = battlecruiser
      model = 1
      extra1 = naval_sa_l
      extra2 = naval_fire_controll_l
      extra3 = naval_spotter_l
      extra4 = naval_anti_air_l
      brigade_model1 = 0
      brigade_model2 = 0
      brigade_model3 = 1
      brigade_model4 = 1
    }
    division =
    { id            = { type = 12700 id = 154 }
      name          = "HMS Courageous"
      type          = carrier
      model         = 1
      extra1        = cag
      brigade_model1= 2
    }
    division =
    { id            = { type = 12700 id = 93 }
      name          = "HMS Furious"
      type          = carrier
      model         = 1
      extra1        = cag
      brigade_model1= 2
    }
    division =
    { id            = { type = 12700 id = 155 }
      name          = "HMS Glorious"
      type          = carrier
      model         = 1
      extra1        = cag
      brigade_model1= 2
    }
    division =
    { id            = { type = 12700 id = 203 }
      name          = "HMS Hermes"
      type          = escort_carrier
      model 	    = 0
      extra1        = b_u1
      brigade_model1= 1
    }
    division =
    { id            = { type = 12700 id = 500 }
      name          = "HMS Pegasus"
      type          = escort_carrier
      model 	    = 0
      extra1        = b_u1
      brigade_model1= 0
    }
    division =
    { id    = { type = 12700 id = 96 }
      name  = "HMS Cairo"
      type  = light_cruiser
      model = 0
      extra1 = none
      extra2 = naval_fire_controll_s
      brigade_model1 = 0
      brigade_model2 = 0
    }
    division =
    { id    = { type = 12700 id = 183 }
      name  = "HMS Leander"
      type  = light_cruiser
      model = 2
      extra1 = naval_fire_controll_s
      extra2 = naval_spotter_s
      brigade_model1 = 1
      brigade_model2 = 1
    }
    division =
    { id    = { type = 12700 id = 99 }
      name  = "HMS Neptune"
      type  = light_cruiser
      model = 2
      extra1 = naval_fire_controll_s
      extra2 = naval_spotter_s
      brigade_model1 = 1
      brigade_model2 = 1
    }
    division =
    { id    = { type = 12700 id = 100 }
      name  = "HMS Orion"
      type  = light_cruiser
      model = 2
      extra1 = naval_fire_controll_s
      extra2 = naval_spotter_s
      brigade_model1 = 1
      brigade_model2 = 1
    }
    division =
    { id    = { type = 12700 id = 222 }
      name  = "HMS Dauntless"
      type  = light_cruiser
      model = 0
      extra1 = naval_spotter_s
      extra2 = naval_anti_air_s
      brigade_model1 = 1
      brigade_model2 = 1
    }
    division =
    { id    = { type = 12700 id = 101 }
      name  = "1st Destroyer Flotilla"
      type  = destroyer
      model = 1
      extra1 = naval_fire_controll_s
      brigade_model1 = 1
    }
    division =
    { id    = { type = 12700 id = 102 }
      name  = "2nd Destroyer Flotilla"
      type  = destroyer
      model = 1
      extra1 = naval_fire_controll_s
      brigade_model1 = 1
    }
    division =
    { id    = { type = 12700 id = 103 }
      name  = "3rd Destroyer Flotilla"
      type  = destroyer
      model = 1
      extra1 = naval_fire_controll_s
      brigade_model1 = 1
    }
    division =
    { id    = { type = 12700 id = 95 }
      name  = "4th Destroyer Flotilla"
      type  = destroyer
      model = 0
      extra1 = naval_fire_controll_s
      brigade_model1 = 1
    }
  }
  navalunit =
  { id       = { type = 12700 id = 104 }
    name     = "HMS Argus"
    location = 5 # Scapa Flow
    base     = 5
    division =
    { id            = { type = 12700 id = 105 }
      name          = "HMS Argus"
      type          = escort_carrier
      model         = 0
      extra1        = b_u1
      brigade_model1= 1
    }
  }
  # 2nd Submarine Squadron#
  navalunit =
  { name     = "2nd Submarine Squadron"
    id       = { type = 12700 id = 106 }
    location = 5 # Scapa Flow
    base     = 5
    division =
    { id    = { type = 12700 id = 107 }
      name  = "3rd Submarine Flotilla"
      type  = submarine
      model = 1
    }
    division =
    { id    = { type = 12700 id = 108 }
      name  = "4th Submarine Flotilla"
      type  = submarine
      model = 1
    }
    division =
    { id    = { type = 12700 id = 109 }
      name  = "5th Submarine Flotilla"
      type  = submarine
      model = 1
    }
    division =
    { id    = { type = 12700 id = 110 }
      name  = "6th Submarine Flotilla"
      type  = submarine
      model = 1
    }
    division =
    { id    = { type = 12700 id = 111 }
      name  = "7th Submarine Flotilla"
      type  = submarine
      model = 1
    }
  }
  # 1st Transport Squadron#
  navalunit =
  { name     = "1st Transport Squadron"
    id       = { type = 12700 id = 112 }
    location = 1505 # Hyderabad
    base     = 1505
    division =
    { id    = { type = 12700 id = 113 }
      name  = "Suffolk Flotilla"
      type  = transport
      model = 0
    }
    division =
    { id    = { type = 12700 id = 114 }
      name  = "Trojan Star Flotilla"
      type  = transport
      model = 0
    }
  }
  # 2nd Transport Squadron#
  navalunit =
  { name     = "2nd Transport Squadron"
    id       = { type = 12700 id = 115 }
    location = 21 # Southampton
    base     = 21
    division =
    { id    = { type = 12700 id = 116 }
      name  = "Empire Arquebus Flotilla"
      type  = transport
      model = 0
    }
    division =
    { id    = { type = 12700 id = 117 }
      name  = "Hororata Flotilla"
      type  = transport
      model = 0
    }
  }
  # 3rd Transport Squadron#
  navalunit =
  { name     = "3rd Transport Squadron"
    id       = { type = 12700 id = 118 }
    location = 21 # Southampton
    base     = 21
    division =
    { id    = { type = 12700 id = 119 }
      name  = "Clan Macauley Flotilla"
      type  = transport
      model = 0
    }
    division =
    { id    = { type = 12700 id = 120 }
      name  = "Empire Captain Flotilla"
      type  = transport
      model = 0
    }
    division =
    { id    = { type = 12700 id = 121 }
      name  = "Andes Flotilla"
      type  = transport
      model = 0
    }
    division =
    { id    = { type = 12700 id = 122 }
      name  = "Empire Charmain Flotilla"
      type  = transport
      model = 0
    }
  }
  # 4th Transport Squadron#
  navalunit =
  { name     = "4th Transport Squadron"
    id       = { type = 12700 id = 123 }
    location = 5 # Scapa Flow
    base     = 5
    division =
    { id    = { type = 12700 id = 124 }
      name  = "Essex Flotilla"
      type  = transport
      model = 0
    }
    division =
    { id    = { type = 12700 id = 125 }
      name  = "Maloja Flotilla"
      type  = transport
      model = 0
    }
  }
  # 5th Transport Squadron#
  navalunit =
  { name     = "5th Transport Squadron"
    id       = { type = 12700 id = 126 }
    location = 23 # Plymouth
    base     = 23
    division =
    { id    = { type = 12700 id = 127 }
      name  = "Empire Splendour Flotilla"
      type  = transport
      model = 0
    }
    division =
    { id    = { type = 12700 id = 128 }
      name  = "Sam Torch Flotilla"
      type  = transport
      model = 0
    }
    division =
    { id    = { type = 12700 id = 129 }
      name  = "Resolution Flotilla"
      type  = transport
      model = 0
    }
  }
  # Non-Associated Destroyers#
  navalunit =
  { name     = "1st Destroyer Squadron"
    id       = { type = 12700 id = 130 }
    location = 23 # Plymouth
    base     = 23
    division =
    { id    = { type = 12700 id = 131 }
      name  = "5th Destroyer Flotilla"
      type  = destroyer
      model = 0
      extra1 = naval_anti_air_s
      brigade_model1 = 1
    }
    division =
    { id    = { type = 12700 id = 132 }
      name  = "6th Destroyer Flotilla"
      type  = destroyer
      model = 1
      extra1 = naval_fire_controll_s
      brigade_model1 = 1
    }
    division =
    { id    = { type = 12700 id = 133 }
      name  = "7th Destroyer Flotilla"
      type  = destroyer
      model = 1
      extra1 = naval_fire_controll_s
      brigade_model1 = 1
    }
  }
  navalunit =
  { name     = "2nd Destroyer Squadron"
    id       = { type = 12700 id = 134 }
    location = 14
    base     = 14
    division =
    { id    = { type = 12700 id = 135 }
      name  = "8nd Destroyer Flotilla"
      type  = destroyer
      model = 0
      extra1 = naval_fire_controll_s
      brigade_model1 = 1
    }
    division =
    { id    = { type = 12700 id = 136 }
      name  = "9th Destroyer Flotilla"
      type  = destroyer
      model = 1
      extra1 = naval_fire_controll_s
      brigade_model1 = 1
    }
  }
  navalunit =
  { name     = "3rd Destroyer Squadron"
    id       = { type = 12700 id = 137 }
    location = 14 # Actually based at Milford Haven, but that is located in the same province as Cardiff.
    base     = 14
    division =
    { id    = { type = 12700 id = 138 }
      name  = "10th Destroyer Flotilla"
      type  = destroyer
      model = 0
      extra1 = naval_fire_controll_s
      brigade_model1 = 1
    }
    division =
    { id    = { type = 12700 id = 139 }
      name  = "11th Destroyer Flotilla"
      type  = destroyer
      model = 1
      extra1 = naval_fire_controll_s
      brigade_model1 = 1
    }
  }
  navalunit =
  { name     = "4th Destroyer Squadron"
    id       = { type = 12700 id = 140 }
    location = 21 # Southampton
    base     = 21
    division =
    { id    = { type = 12700 id = 141 }
      name  = "12th Destroyer Flotilla"
      type  = destroyer
      model = 0
      extra1 = naval_fire_controll_s
      brigade_model1 = 1
    }
    division =
    { id    = { type = 12700 id = 142 }
      name  = "13th Destroyer Flotilla"
      type  = destroyer
      model = 1
      extra1 = naval_anti_air_s
      brigade_model1 = 1
    }
  }
  navalunit =
  { name     = "5th Destroyer Squadron"
    id       = { type = 12700 id = 143 }
    location = 21 # Portsmouth
    base     = 21
    division =
    { id    = { type = 12700 id = 144 }
      name  = "14th Destroyer Flotilla"
      type  = destroyer
      model = 0
      extra1 = naval_fire_controll_s
      brigade_model1 = 1
    }
    division =
    { id    = { type = 12700 id = 145 }
      name  = "15th Destroyer Flotilla"
      type  = destroyer
      model = 1
      extra1 = naval_fire_controll_s
      brigade_model1 = 1
    }
    division =
    { id    = { type = 12700 id = 146 }
      name  = "16th Destroyer Flotilla"
      type  = destroyer
      model = 1
      extra1 = naval_fire_controll_s
      brigade_model1 = 1
    }
  }
  navalunit =
  { name     = "Mediterranean Fleet"
    id       = { type = 12700 id = 147 }
    location = 906 # Alexandria
    base     = 906
    division =
    { id    = { type = 12700 id = 148 }
      name  = "HMS Queen Elizabeth"
      type  = battleship
      model = 1
      extra1 = naval_sa_l
      extra2 = naval_fire_controll_l
      extra3 = none
      extra4 = naval_anti_air_l
      extra5 = none
      brigade_model1 = 0
      brigade_model2 = 1
      brigade_model3 = 0
      brigade_model4 = 1
      brigade_model5 = 0
    }
    division =
    { id    = { type = 12700 id = 153 }
      name  = "HMS Revenge"
      type  = battleship
      model = 2
      extra1 = naval_sa_l
      extra2 = naval_fire_controll_l
      extra3 = naval_spotter_l
      extra4 = naval_anti_air_l
      extra5 = none
      brigade_model1 = 0
      brigade_model2 = 0
      brigade_model3 = 1
      brigade_model4 = 1
      brigade_model5 = 0
    }
    division =
    { id    = { type = 12700 id = 156 }
      name  = "HMS Devonshire"
      type  = heavy_cruiser
      model = 1
      extra1 = naval_fire_controll_l
      extra2 = naval_spotter_l
      extra3 = naval_anti_air_l
      brigade_model1 = 1
      brigade_model2 = 1
      brigade_model3 = 0
    }
    division =
    { id    = { type = 12700 id = 157 }
      name  = "HMS London"
      type  = heavy_cruiser
      model = 1
      extra1 = naval_fire_controll_l
      extra2 = naval_spotter_l
      extra3 = naval_anti_air_l
      brigade_model1 = 0
      brigade_model2 = 1
      brigade_model3 = 1
    }
    division =
    { id    = { type = 12700 id = 158 }
      name  = "HMS Shropshire"
      type  = heavy_cruiser
      model = 1
      extra1 = naval_fire_controll_l
      extra2 = naval_spotter_l
      extra3 = naval_anti_air_l
      brigade_model1 = 0
      brigade_model2 = 1
      brigade_model3 = 1
    }
    division =
    { id    = { type = 12700 id = 159 }
      name  = "HMS Sussex"
      type  = heavy_cruiser
      model = 1
      extra1 = naval_fire_controll_l
      extra2 = naval_spotter_l
      extra3 = naval_anti_air_l
      brigade_model1 = 0
      brigade_model2 = 1
      brigade_model3 = 1
    }
    division =
    { id    = { type = 12700 id = 160 }
      name  = "HMS Exeter"
      type  = heavy_cruiser
      model = 1
      extra1 = naval_fire_controll_l
      extra2 = naval_spotter_l
      extra3 = naval_anti_air_l
      brigade_model1 = 1
      brigade_model2 = 1
      brigade_model3 = 0
    }
    division =
    { id    = { type = 12700 id = 161 }
      name  = "HMS York"
      type  = heavy_cruiser
      model = 1
      extra1 = naval_fire_controll_l
      extra2 = naval_spotter_l
      extra3 = naval_anti_air_l
      brigade_model1 = 1
      brigade_model2 = 1
      brigade_model3 = 0
    }
    division =
    { id    = { type = 12700 id = 97 }
      name  = "HMS Galatea"
      type  = light_cruiser
      model = 2
      extra1 = naval_spotter_s
      extra2 = naval_anti_air_s
      brigade_model1 = 1
      brigade_model2 = 0
    }
    division =
    { id    = { type = 12700 id = 167 }
      name  = "HMS Arethusa"
      type  = light_cruiser
      model = 2
      extra1 = naval_spotter_s
      extra2 = naval_anti_air_s
      brigade_model1 = 1
      brigade_model2 = 0
    }
    division =
    { id    = { type = 12700 id = 98 }
      name  = "HMS Dunedin"
      type  = light_cruiser
      model = 0
      extra1 = naval_fire_controll_s
      extra2 = naval_anti_air_s
      brigade_model1 = 0
      brigade_model2 = 1
    }
    division =
    { id    = { type = 12700 id = 163 }
      name  = "HMS Curlew"
      type  = light_cruiser
      model = 0
      extra1 = naval_fire_controll_s
      extra2 = none
      brigade_model1 = 0
      brigade_model2 = 0
    }
    division =
    { id    = { type = 12700 id = 164 }
      name  = "HMS Delhi"
      type  = light_cruiser
      model = 0
      extra1 = naval_fire_controll_s
      extra2 = naval_anti_air_s
      brigade_model1 = 0
      brigade_model2 = 1
    }
    division =
    { id    = { type = 12700 id = 165 }
      name  = "HMS Despatch"
      type  = light_cruiser
      model = 0
      extra1 = naval_fire_controll_s
      extra2 = naval_spotter_s
      brigade_model1 = 0
      brigade_model2 = 1
    }
    division =
    { id    = { type = 12700 id = 166 }
      name  = "HMS Durban"
      type  = light_cruiser
      model = 0
      extra1 = naval_fire_controll_s
      extra2 = naval_anti_air_s
      brigade_model1 = 0
      brigade_model2 = 1
    }
    division =
    { id    = { type = 12700 id = 168 }
      name  = "17th Destroyer Flotilla"
      type  = destroyer
      model = 1
      extra1 = naval_fire_controll_s
      brigade_model1 = 1
    }
    division =
    { id    = { type = 12700 id = 169 }
      name  = "18th Destroyer Flotilla"
      type  = destroyer
      model = 0
      extra1 = naval_fire_controll_s
      brigade_model1 = 1
    }
    division =
    { id    = { type = 12700 id = 170 }
      name  = "19th Destroyer Flotilla"
      type  = destroyer
      model = 0
      extra1 = naval_anti_air_s
      brigade_model1 = 1
    }
    division =
    { id    = { type = 12700 id = 171 }
      name  = "20th Destroyer Flotilla"
      type  = destroyer
      model = 0
      extra1 = naval_fire_controll_s
      brigade_model1 = 1
    }
    division =
    { id    = { type = 12700 id = 172 }
      name  = "21st Destroyer Flotilla"
      type  = destroyer
      model = 0
      extra1 = naval_fire_controll_s
      brigade_model1 = 0
    }
    division =
    { id    = { type = 12700 id = 173 }
      name  = "22nd Destroyer Flotilla"
      type  = destroyer
      model = 0
      extra1 = naval_anti_air_s
      brigade_model1 = 1
    }
  }
  # 1st Submarine Squadron#
  navalunit =
  { name     = "1st Submarine Squadron"
    id       = { type = 12700 id = 174 }
    location = 906 # Alexandria
    base     = 906
    division =
    { id    = { type = 12700 id = 175 }
      name  = "1st Submarine Flotilla"
      type  = submarine
      model = 2
    }
    division =
    { id    = { type = 12700 id = 176 }
      name  = "2nd Submarine Flotilla"
      type  = submarine
      model = 7
    }
  }
  # America & West Indies Station#
  navalunit =
  { name     = "America & West Indies Station"
    id       = { type = 12700 id = 177 }
    location = 538 # Bermuda
    base     = 538
    division =
    { id    = { type = 12700 id = 178 }
      name  = "HMS Dragon"
      type  = light_cruiser
      model = 0
      extra1 = naval_fire_controll_s
      extra2 = naval_anti_air_s
      brigade_model1 = 0
      brigade_model2 = 1
    }
    division =
    { id    = { type = 12700 id = 179 }
      name  = "HMS Ajax"
      type  = light_cruiser
      model = 2
      extra1 = naval_fire_controll_s
      extra2 = naval_spotter_s
      brigade_model1 = 1
      brigade_model2 = 1
    }
    division =
    { id    = { type = 12700 id = 180 }
      name  = "23rd Destroyer Flotilla"
      type  = destroyer
      model = 0
      extra1 = naval_fire_controll_s
      brigade_model1 = 1
    }
    division =
    { id    = { type = 12700 id = 181 }
      name  = "24th Destroyer Flotilla"
      type  = destroyer
      model = 0
      extra1 = naval_fire_controll_s
      brigade_model1 = 1
    }
  }
  # Africa Station#
  navalunit =
  { name     = "Africa Station"
    id       = { type = 12700 id = 182 }
    location = 988 # Freetown
    base     = 988
    division =
    { id    = { type = 12700 id = 206 }
      name  = "HMS Dorsetshire"
      type  = heavy_cruiser
      model = 1
      extra1 = naval_fire_controll_l
      extra2 = naval_spotter_l
      extra3 = naval_anti_air_l
      brigade_model1 = 1
      brigade_model2 = 1
      brigade_model3 = 0
    }
    division =
    { id    = { type = 12700 id = 184 }
      name  = "HMS Carlisle"
      type  = light_cruiser
      model = 0
      extra1 = naval_fire_controll_s
      extra2 = none
      brigade_model1 = 1
      brigade_model2 = 0
    }
    division =
    { id    = { type = 12700 id = 185 }
      name  = "25th Destroyer Flotilla"
      type  = destroyer
      model = 0
      extra1 = naval_anti_air_s
      brigade_model1 = 1
    }
    division =
    { id    = { type = 12700 id = 186 }
      name  = "26th Destroyer Flotilla"
      type  = destroyer
      model = 0
      extra1 = naval_fire_controll_s
      brigade_model1 = 1
    }
  }
  # East Indies Station#
  navalunit =
  { name     = "East Indies Station"
    id       = { type = 12700 id = 187 }
    location = 1517
    base     = 1517
    division =
    { id    = { type = 12700 id = 188 }
      name  = "HMS Norfolk"
      type  = heavy_cruiser
      model = 1
      extra1 = naval_fire_controll_l
      extra2 = naval_spotter_l
      extra3 = naval_anti_air_l
      brigade_model1 = 0
      brigade_model2 = 2
      brigade_model3 = 1
    }
    division =
    { id    = { type = 12700 id = 189 }
      name  = "HMS Diomede"
      type  = light_cruiser
      model = 0
      extra1 = naval_fire_controll_s
      extra2 = naval_anti_air_s
      brigade_model1 = 0
      brigade_model2 = 1
    }
    division =
    { id    = { type = 12700 id = 190 }
      name  = "HMS Emerald"
      type  = light_cruiser
      model = 1
      extra1 = naval_fire_controll_s
      extra2 = naval_spotter_s
      brigade_model1 = 0
      brigade_model2 = 1
    }
    division =
    { id    = { type = 12700 id = 191 }
      name  = "HMS Enterprise"
      type  = light_cruiser
      model = 1
      extra1 = naval_fire_controll_s
      extra2 = naval_spotter_s
      brigade_model1 = 0
      brigade_model2 = 1
    }
    division =
    { id    = { type = 12700 id = 192 }
      name  = "27th Destroyer Flotilla"
      type  = destroyer
      model = 0
      extra1 = naval_fire_controll_s
      brigade_model1 = 1
    }
    division =
    { id    = { type = 12700 id = 193 }
      name  = "28th Destroyer Flotilla"
      type  = destroyer
      model = 0
      extra1 = naval_fire_controll_s
      brigade_model1 = 0
    }
  }
  # China Station#
  navalunit =
  { name     = "China Station"
    id       = { type = 12700 id = 194 }
    location = 1315 # Hong Kong
    base     = 1315
    division =
    { id            = { type = 12700 id = 195 }
      name          = "HMS Eagle"
      type          = escort_carrier
      model         = 1
      extra1        = b_u1
      brigade_model1= 1
    }
    division =
    { id    = { type = 12700 id = 208 }
      name  = "HMS Berwick"
      type  = heavy_cruiser
      model = 1
      extra1 = naval_fire_controll_l
      extra2 = naval_spotter_l
      extra3 = naval_anti_air_l
      brigade_model1 = 1
      brigade_model2 = 1
      brigade_model3 = 0
    }
    division =
    { id    = { type = 12700 id = 209 }
      name  = "HMS Cornwall"
      type  = heavy_cruiser
      model = 1
      extra1 = naval_fire_controll_l
      extra2 = naval_spotter_l
      extra3 = naval_anti_air_l
      brigade_model1 = 1
      brigade_model2 = 1
      brigade_model3 = 0
    }
    division =
    { id    = { type = 12700 id = 211 }
      name  = "HMS Suffolk"
      type  = heavy_cruiser
      model = 1
      extra1 = naval_fire_controll_l
      extra2 = naval_spotter_l
      extra3 = naval_anti_air_l
      brigade_model1 = 0
      brigade_model2 = 1
      brigade_model3 = 1
    }
    division =
    { id    = { type = 12700 id = 212 }
      name  = "HMS Kent"
      type  = heavy_cruiser
      model = 1
      extra1 = naval_fire_controll_l
      extra2 = naval_spotter_l
      extra3 = naval_anti_air_l
      brigade_model1 = 1
      brigade_model2 = 1
      brigade_model3 = 1
    }
    division =
    { id    = { type = 12700 id = 196 }
      name  = "HMS Capetown"
      type  = light_cruiser
      model = 0
      extra1 = naval_fire_controll_s
      extra2 = none
      brigade_model1 = 1
      brigade_model2 = 0
    }
    division =
    { id    = { type = 12700 id = 221 }
      name  = "HMS Danae"
      type  = light_cruiser
      model = 0
      extra1 = naval_fire_controll_s
      extra2 = naval_anti_air_s
      brigade_model1 = 1
      brigade_model2 = 1
    }
    division =
    { id    = { type = 12700 id = 197 }
      name  = "29th Destroyer Flotilla"
      type  = destroyer
      model = 0
      extra1 = naval_fire_controll_s
      brigade_model1 = 0
    }
    division =
    { id    = { type = 12700 id = 198 }
      name  = "30th Destroyer Flotilla"
      type  = destroyer
      model = 0
      extra1 = naval_fire_controll_s
      brigade_model1 = 1
    }
  }
  # 3rd Submarine Squadron#
  navalunit =
  { name     = "3rd Submarine Squadron"
    id       = { type = 12700 id = 199 }
    location = 1315 # Hong Kong
    base     = 1315
    division =
    { id    = { type = 12700 id = 200 }
      name  = "8th Submarine Flotilla"
      type  = submarine
      model = 2
    }
    division =
    { id    = { type = 12700 id = 201 }
      name  = "9th Submarine Flotilla"
      type  = submarine
      model = 2
    }
  }
  # Reserve Fleet#
  navalunit =
  { name     = "Reserve Fleet"
    id       = { type = 12700 id = 202 }
    location = 21 # Southampton
    base     = 21
    division =
    { id    = { type = 12700 id = 204 }
      name  = "HMS Effingham"
      type  = heavy_cruiser
      model = 0
      extra1 = naval_sa_l
      extra2 = naval_fire_controll_l
      extra3 = naval_anti_air_l
      brigade_model1 = 0
      brigade_model2 = 0
      brigade_model3 = 0
    }
    division =
    { id    = { type = 12700 id = 205 }
      name  = "HMS Frobisher"
      type  = heavy_cruiser
      model = 0
      extra1 = none
      extra2 = none
      extra3 = none
      brigade_model1 = 0
      brigade_model2 = 0
      brigade_model3 = 0
    }
    division =
    { id    = { type = 12700 id = 207 }
      name  = "HMS Hawkins"
      type  = heavy_cruiser
      model = 0
      extra1 = naval_sa_l
      extra2 = naval_fire_controll_l
      extra3 = naval_anti_air_l
      brigade_model1 = 0
      brigade_model2 = 0
      brigade_model3 = 0
    }
    division =
    { id    = { type = 12700 id = 213 }
      name  = "HMS Caledon"
      type  = light_cruiser
      model = 0
      extra1 = naval_fire_controll_s
      extra2 = none
      brigade_model1 = 0
      brigade_model2 = 0
    }
    division =
    { id    = { type = 12700 id = 214 }
      name  = "HMS Calypso"
      type  = light_cruiser
      model = 0
      extra1 = naval_fire_controll_s
      extra2 = none
      brigade_model1 = 0
      brigade_model2 = 0
    }
    division =
    { id    = { type = 12700 id = 215 }
      name  = "HMS Caradoc"
      type  = light_cruiser
      model = 0
      extra1 = naval_fire_controll_s
      extra2 = none
      brigade_model1 = 0
      brigade_model2 = 0
    }
    division =
    { id    = { type = 12700 id = 216 }
      name  = "HMS Calcutta"
      type  = light_cruiser
      model = 0
      extra1 = naval_fire_controll_s
      extra2 = none
      brigade_model1 = 0
      brigade_model2 = 0
    }
    division =
    { id    = { type = 12700 id = 217 }
      name  = "HMS Colombo"
      type  = light_cruiser
      model = 0
      extra1 = none
      extra2 = none
      brigade_model1 = 0
      brigade_model2 = 0
    }
    division =
    { id    = { type = 12700 id = 218 }
      name  = "HMS Cardiff"
      type  = light_cruiser
      model = 0
      extra1 = naval_fire_controll_s
      extra2 = none
      brigade_model1 = 0
      brigade_model2 = 0
    }
    division =
    { id    = { type = 12700 id = 219 }
      name  = "HMS Ceres"
      type  = light_cruiser
      model = 0
      extra1 = none
      extra2 = none
      brigade_model1 = 0
      brigade_model2 = 0
    }
    division =
    { id    = { type = 12700 id = 220 }
      name  = "HMS Curacoa"
      type  = light_cruiser
      model = 0
      extra1 = none
      extra2 = none
      brigade_model1 = 0
      brigade_model2 = 0
    }
    division =
    { id    = { type = 12700 id = 231 }
      name  = "HMS Castor"
      type  = light_cruiser
      model = 0
      extra1 = naval_fire_controll_s
      extra2 = naval_anti_air_s
      brigade_model1 = 0
      brigade_model2 = 0
    }
    division =
    { id    = { type = 12700 id = 232 }
      name  = "HMS Constance"
      type  = light_cruiser
      model = 0
      extra1 = naval_fire_controll_s
      extra2 = naval_anti_air_s
      brigade_model1 = 0
      brigade_model2 = 0
    }
    division =
    { id    = { type = 12700 id = 224 }
      name  = "31st Destroyer Flotilla"
      type  = destroyer
      model = 0
      extra1 = naval_fire_controll_s
      brigade_model1 = 0
    }
    division =
    { id    = { type = 12700 id = 225 }
      name  = "32nd Destroyer Flotilla"
      type  = destroyer
      model = 0
      extra1 = naval_fire_controll_s
      brigade_model1 = 0
    }
  }
  # Shipyards #
  navalunit =
  { name     = "Devonport Shipyard"
    id       = { type = 12700 id = 229 }
    location = 21 # Southampton
    base     = 21
    division =
    { id    = { type = 12700 id = 88 }
      name  = "HMS Royal Oak"
      type  = battleship
      model = 2
      extra1 = naval_sa_l
      extra2 = naval_fire_controll_l
      extra3 = naval_spotter_l
      extra4 = naval_anti_air_l
      extra5 = none
      brigade_model1 = 1
      brigade_model2 = 1
      brigade_model3 = 2
      brigade_model4 = 1
      brigade_model5 = 0
    }
    division =
    { id    = { type = 12700 id = 152 }
      name  = "HMS Warspite"
      type  = battleship
      model = 1
      extra1 = naval_sa_l
      extra2 = naval_fire_controll_l
      extra3 = naval_spotter_l
      extra4 = naval_anti_air_l
      extra5 = none
      brigade_model1 = 1
      brigade_model2 = 1
      brigade_model3 = 1
      brigade_model4 = 1
      brigade_model5 = 0
    }
    division =
    { id    = { type = 12700 id = 210 }
      name  = "HMS Cumberland"
      type  = heavy_cruiser
      model = 1
      extra1 = naval_fire_controll_l
      extra2 = naval_spotter_l
      extra3 = naval_anti_air_l
      brigade_model1 = 1
      brigade_model2 = 1
      brigade_model3 = 0
    }
    division =
    { id    = { type = 12700 id = 223 }
      name  = "HMS Achilles"
      type  = light_cruiser
      model = 2
      extra1 = naval_fire_controll_s
      extra2 = naval_spotter_s
      brigade_model1 = 1
      brigade_model2 = 2
    }
    division =
    { id    = { type = 12700 id = 162 }
      name  = "HMS Coventry"
      type  = light_cruiser
      model = 0
      extra1 = none
      extra2 = none
      brigade_model1 = 0
      brigade_model2 = 0
    }
  }
  # #################
  #  Royal Airforce #
  # #################

airunit = {
	id = { type = 12700 id = 516 }
	name = "Fighter Command"
	location = 19 # London
	base = 19

	division = {
		id = { type = 12700 id = 501 }
		name = "No.11 Group"
		type = interceptor
		model = 0
	}
}

airunit = {
	id = { type = 12700 id = 502 }
	name = "No.12 Group"
	location = 13 # Sheffield
	base = 13

	division = {
		id = { type = 12700 id = 503 }
		name = "No.12 Group"
		type = interceptor
		model = 0
		strength = 50
	}
}

airunit = {
	id = { type = 12700 id = 504 }
	name = "No.2 Group"
	location = 16 # Birmingham
	base = 16

	division = {
		id = { type = 12700 id = 505 }
		name = "No.2 Group"
		type = tactical_bomber
		model = 0
		strength = 50
	}
}

airunit = {
	id = { type = 12700 id = 506 }
	name = "No.3 Group"
	location = 22 # Bristol
	base = 22

	division = {
		id = { type = 12700 id = 507 }
		name = "No.3 Group"
		type = tactical_bomber
		model = 0
		strength = 50
	}
}

airunit = {
	id = { type = 12700 id = 508 }
	name = "No.4 Group"
	location = 17 # Norwich
	base = 17

	division = {
		id = { type = 12700 id = 509 }
		name = "No.4 Group"
		type = strategic_bomber
		model = 0
		strength = 50
	}
}

airunit = {
	id = { type = 12700 id = 510 }
	name = "No.1 Group"
	location = 16 # Birmingham
	base = 16

	division = {
		id = { type = 12700 id = 511 }
		name = "No.1 Group"
		type = cas
		model = 0
		strength = 50
	}
}

airunit = {
	id = { type = 12700 id = 512 }
	name = "No.15 Group"
	location = 23 # Plymouth
	base = 23

	division = {
		id = { type = 12700 id = 513 }
		name = "No.15 Group"
		type = naval_bomber
		model = 0
	}
}

airunit = {
	id = { type = 12700 id = 514 }
	name = "No.16 Group"
	location = 20 # Dover
	base = 20

	division = {
		id = { type = 12700 id = 515 }
		name = "No.16 Group"
		type = cas
		model = 0
		strength = 30
	}
}

airunit = {
	id = { type = 12700 id = 517 }
	name = "Middle East Command"
	location = 901 # Port Said
	base = 901

	division = {
		id = { type = 12700 id = 518 }
		name = "Middle East Command"
		type = tactical_bomber
		model = 0
		strength = 60
	}
	division = {
		id = { type = 12700 id = 519 }
		name = "Middle East Command"
		type = interceptor
		model = 0
		strength = 40
	}
}

airunit = {
	id = { type = 12700 id = 520 }
	name = "Iraq Command"
	location = 1860 # Kirkuk
	base = 1860

	division = {
		id = { type = 12700 id = 521 }
		name = "Iraq Command"
		type = tactical_bomber
		model = 0
		strength = 20
	}
}

airunit = {
	id = { type = 12700 id = 522 }
	name = "Aden Command"
	location = 1813 # Aden
	base = 1813

	division = {
		id = { type = 12700 id = 523 }
		name = "Aden Command"
		type = interceptor
		model = 0
		strength = 20
	}
}

airunit = {
	id = { type = 12700 id = 524 }
	name = "Mediterranean Command"
	location = 31 # Malta
	base = 31

	division = {
		id = { type = 12700 id = 525 }
		name = "Mediterranean Command"
		type = naval_bomber
		model = 0
		strength = 25
	}
}

airunit = {
	id = { type = 12700 id = 526 }
	name = "India Command"
	location = 1469 # Delhi
	base = 1469

	division = {
		id = { type = 12700 id = 527 }
		name = "India Command"
		type = cas
		model = 0
		strength = 60
	}
}

airunit = {
	id = { type = 12700 id = 528 }
	name = "Far East Command I"
	location = 1353 # Singapore
	base = 1353

	division = {
		id = { type = 12700 id = 529 }
		name = "Far East Command I"
		type = cas
		model = 0
		strength = 30
	}
}

airunit = {
	id = { type = 12700 id = 530 }
	name = "Far East Command II"
	location = 1353 # Singapore
	base = 1353

	division = {
		id = { type = 12700 id = 531 }
		name = "Far East Command II"
		type = naval_bomber
		model = 0
		strength = 50
	}
}

# CONSTRUCTIONS

	province_development = { 
		id = { type = 12700 id = 258 } 
		name = "" 
		progress = 0.0000 
		location = 16 
		cost = 2.0000 
		date = { 
			year = 1938 
			month = october 
			day = 9 
			hour = 0 
			} 
		manpower = 0.1000 
		close_when_finished = yes 
		waitingforclosure = no 
		total_progress = 0.0000 
		size = 20 
		done = 0 
		days = 1725 
		days_for_first = 106 
		gearing_bonus = 0.0000 
		speed_step = 2 
		type = infrastructure 
		} 
	province_development = { 
		id = { type = 12700 id = 257 } 
		name = "" 
		progress = 0.0000 
		location = 19 
		cost = 2.0000 
		date = { 
			year = 1939 
			month = may 
			day = 24 
			hour = 0 
			} 
		manpower = 0.1000 
		close_when_finished = yes 
		waitingforclosure = no 
		total_progress = 0.0000 
		size = 20 
		done = 0 
		days = 1725 
		days_for_first = 106 
		gearing_bonus = 0.0000 
		speed_step = 1 
		type = infrastructure 
		} 
	province_development = { 
		id = { type = 12700 id = 256 } 
		name = "" 
		progress = 0.0000 
		location = 14 
		cost = 2.0000 
		date = { 
			year = 1939 
			month = may 
			day = 24 
			hour = 0 
			} 
		manpower = 0.1000 
		close_when_finished = yes 
		waitingforclosure = no 
		total_progress = 0.0000 
		size = 20 
		done = 0 
		days = 1725 
		days_for_first = 106 
		gearing_bonus = 0.0000 
		speed_step = 1 
		type = infrastructure 
		} 
	province_development = { 
		id = { type = 12700 id = 259 } 
		name = "" 
		progress = 0.0000 
		location = 13 
		cost = 2.0000 
		date = { 
			year = 1939 
			month = may 
			day = 24 
			hour = 0 
			} 
		manpower = 0.1000 
		close_when_finished = yes 
		waitingforclosure = no 
		total_progress = 0.0000 
		size = 20 
		done = 0 
		days = 1725 
		days_for_first = 106 
		gearing_bonus = 0.0000 
		speed_step = 1 
		type = infrastructure 
		} 
	province_development = { 
		id = { type = 12700 id = 260 } 
		name = "" 
		progress = 0.0000 
		location = 11 
		cost = 2.0000 
		date = { 
			year = 1940 
			month = october 
			day = 21 
			hour = 0 
			} 
		manpower = 0.1000 
		close_when_finished = yes 
		waitingforclosure = no 
		total_progress = 0.0000 
		size = 20 
		done = 0 
		days = 1725 
		days_for_first = 106 
		gearing_bonus = 0.0000 
		type = infrastructure 
		} 
	province_development = { 
		id = { type = 12700 id = 261 } 
		name = "" 
		progress = 0.0000 
		location = 9 
		cost = 2.0000 
		date = { 
			year = 1940 
			month = october 
			day = 21 
			hour = 0 
			} 
		manpower = 0.1000 
		close_when_finished = yes 
		waitingforclosure = no 
		total_progress = 0.0000 
		size = 20 
		done = 0 
		days = 1725 
		days_for_first = 106 
		gearing_bonus = 0.0000 
		type = infrastructure 
		} 
	province_development = { 
		id = { type = 12700 id = 262 } 
		name = "" 
		progress = 0.0000 
		location = 15 
		cost = 2.0000 
		date = { 
			year = 1940 
			month = october 
			day = 21 
			hour = 0 
			} 
		manpower = 0.1000 
		close_when_finished = yes 
		waitingforclosure = no 
		total_progress = 0.0000 
		size = 20 
		done = 0 
		days = 1725 
		days_for_first = 106 
		gearing_bonus = 0.0000 
		type = infrastructure 
		} 
	province_development = { 
		id = { type = 12700 id = 4025 } 
		name = "" 
		progress = 0.0000 
		location = 17 
		cost = 2.0000 
		date = { 
			year = 1940 
			month = october 
			day = 21 
			hour = 0 
			} 
		manpower = 0.1000 
		close_when_finished = yes 
		waitingforclosure = no 
		total_progress = 0.0000 
		size = 20 
		done = 0 
		days = 1725 
		days_for_first = 106 
		gearing_bonus = 0.0000 
		type = infrastructure 
		} 
	province_development = { 
		id = { type = 12700 id = 4024 } 
		name = "" 
		progress = 0.0000 
		location = 20 
		cost = 2.0000 
		date = { 
			year = 1940 
			month = october 
			day = 21 
			hour = 0 
			} 
		manpower = 0.1000 
		close_when_finished = yes 
		waitingforclosure = no 
		total_progress = 0.0000 
		size = 20 
		done = 0 
		days = 1725 
		days_for_first = 106 
		gearing_bonus = 0.0000 
		type = infrastructure 
		} 
	province_development = { 
		id = { type = 12700 id = 4026 } 
		name = "" 
		progress = 0.0000 
		location = 12 
		cost = 2.0000 
		date = { 
			year = 1940 
			month = october 
			day = 21 
			hour = 0 
			} 
		manpower = 0.1000 
		close_when_finished = yes 
		waitingforclosure = no 
		total_progress = 0.0000 
		size = 20 
		done = 0 
		days = 1725 
		days_for_first = 106 
		gearing_bonus = 0.0000 
		type = infrastructure 
		} 
	province_development = { 
		id = { type = 12700 id = 274 } 
		name = "" 
		progress = 0.0000 
		location = 10 
		cost = 2.0000 
		date = { 
			year = 1940 
			month = october 
			day = 21 
			hour = 0 
			} 
		manpower = 0.1000 
		close_when_finished = yes 
		waitingforclosure = no 
		total_progress = 0.0000 
		size = 20 
		done = 0 
		days = 1725 
		days_for_first = 106 
		gearing_bonus = 0.0000 
		type = infrastructure 
		} 
	province_development = { 
		id = { type = 12700 id = 275 } 
		name = "" 
		progress = 0.0000 
		location = 22 
		cost = 2.0000 
		date = { 
			year = 1940 
			month = october 
			day = 21 
			hour = 0 
			} 
		manpower = 0.1000 
		close_when_finished = yes 
		waitingforclosure = no 
		total_progress = 0.0000 
		size = 20 
		done = 0 
		days = 1725 
		days_for_first = 106 
		gearing_bonus = 0.0000 
		type = infrastructure 
		} 
	province_development = { 
		id = { type = 12700 id = 276 } 
		name = "" 
		progress = 0.0000 
		location = 21 
		cost = 2.0000 
		date = { 
			year = 1940 
			month = october 
			day = 21 
			hour = 0 
			} 
		manpower = 0.1000 
		close_when_finished = yes 
		waitingforclosure = no 
		total_progress = 0.0000 
		size = 20 
		done = 0 
		days = 1725 
		days_for_first = 106 
		gearing_bonus = 0.0000 
		type = infrastructure 
		} 
	province_development = { 
		id = { type = 12700 id = 4114 } 
		name = "" 
		progress = 0.0000 
		location = 871 
		cost = 2.0000 
		date = { 
			year = 1952 
			month = september 
			day = 0 
			hour = 0 
			} 
		manpower = 0.1000 
		close_when_finished = yes 
		waitingforclosure = no 
		total_progress = 0.0000 
		size = 28 
		done = 0 
		days = 2391 
		days_for_first = 265 
		gearing_bonus = 0.0000 
		type = infrastructure 
		} 
	province_development = { 
		id = { type = 12700 id = 4113 } 
		name = "" 
		progress = 0.0000 
		location = 873 
		cost = 2.0000 
		date = { 
			year = 1946 
			month = january 
			day = 0 
			hour = 0 
			} 
		manpower = 0.1000 
		close_when_finished = yes 
		waitingforclosure = no 
		total_progress = 0.0000 
		size = 28 
		done = 0 
		days = 2391 
		days_for_first = 159 
		gearing_bonus = 0.0000 
		type = infrastructure 
		} 
	province_development = { 
		id = { type = 12700 id = 4112 } 
		name = "" 
		progress = 0.0000 
		location = 444 
		cost = 2.0000 
		date = { 
			year = 1946 
			month = january 
			day = 0 
			hour = 0 
			} 
		manpower = 0.1000 
		close_when_finished = yes 
		waitingforclosure = no 
		total_progress = 0.0000 
		size = 28 
		done = 0 
		days = 2391 
		days_for_first = 159 
		gearing_bonus = 0.0000 
		type = infrastructure 
		} 
	province_development = { 
		id = { type = 12700 id = 4100 } 
		name = "" 
		progress = 0.0000 
		location = 809 
		cost = 2.0000 
		date = { 
			year = 1942 
			month = september 
			day = 0 
			hour = 0 
			} 
		manpower = 0.1000 
		close_when_finished = yes 
		waitingforclosure = no 
		total_progress = 0.0000 
		size = 28 
		done = 0 
		days = 2391 
		days_for_first = 106 
		gearing_bonus = 0.0000 
		type = infrastructure 
		} 
	province_development = { 
		id = { type = 12700 id = 4027 } 
		name = "" 
		progress = 0.0000 
		location = 891 
		cost = 2.0000 
		date = { 
			year = 1955 
			month = august 
			day = 6 
			hour = 0 
			} 
		manpower = 0.1000 
		close_when_finished = yes 
		waitingforclosure = no 
		total_progress = 0.0000 
		size = 28 
		done = 0 
		days = 2328 
		days_for_first = 252 
		gearing_bonus = 0.0000 
		type = infrastructure 
		} 
	brigade_development = { 
		id = { type = 12700 id = 4015 } 
		name = "37' Capital Radar" 
		progress = 0.0000 
		location = 19 
		cost = 0.8800 
		date = { 
			year = 1937 
			month = august 
			day = 21 
			hour = 0 
			} 
		manpower = 0.1000 
		close_when_finished = yes 
		waitingforclosure = no 
		retooling_time = 32.0000 
		total_progress = 0.0000 
		size = 7 
		done = 0 
		days = 1072 
		days_for_first = 92 
		gearing_bonus = 0.0000 
		type = naval_radar_l 
		model = 0 
		} 
	brigade_development = { 
		id = { type = 12700 id = 4016 } 
		name = "36' Capital Fire Control" 
		progress = 0.0000 
		location = 19 
		cost = 1.3200 
		date = { 
			year = 1936 
			month = april 
			day = 4 
			hour = 0 
			} 
		manpower = 0.1000 
		close_when_finished = yes 
		waitingforclosure = no 
		retooling_time = 32.0000 
		total_progress = 0.0000 
		size = 1 
		done = 0 
		days = 62 
		days_for_first = 62 
		gearing_bonus = 0.0000 
		type = naval_fire_controll_l 
		model = 1 
		} 
	brigade_development = { 
		id = { type = 12700 id = 4017 } 
		name = "36' Secondary Armament" 
		progress = 0.0000 
		location = 19 
		cost = 0.4400 
		date = { 
			year = 1936 
			month = september 
			day = 6 
			hour = 0 
			} 
		manpower = 0.2000 
		close_when_finished = yes 
		waitingforclosure = no 
		retooling_time = 32.0000 
		total_progress = 0.0000 
		size = 2 
		done = 0 
		days = 214 
		days_for_first = 110 
		gearing_bonus = 0.0000 
		type = naval_sa_l 
		model = 1 
		} 
	brigade_development = { 
		id = { type = 12700 id = 4018 } 
		name = "36' Capital Spotter" 
		progress = 0.0000 
		location = 19 
		cost = 0.8800 
		date = { 
			year = 1936 
			month = may 
			day = 22 
			hour = 0 
			} 
		manpower = 0.1000 
		close_when_finished = yes 
		waitingforclosure = no 
		retooling_time = 32.0000 
		total_progress = 0.0000 
		size = 1 
		done = 0 
		days = 110 
		days_for_first = 110 
		gearing_bonus = 0.0000 
		type = naval_spotter_l 
		model = 2 
		} 
	brigade_development = { 
		id = { type = 12700 id = 4019 } 
		name = "36' Fire Control" 
		progress = 0.0000 
		location = 19 
		cost = 0.4400 
		date = { 
			year = 1936 
			month = september 
			day = 2 
			hour = 0 
			} 
		manpower = 0.1000 
		close_when_finished = yes 
		waitingforclosure = no 
		retooling_time = 32.0000 
		total_progress = 0.0000 
		size = 4 
		done = 0 
		days = 212 
		days_for_first = 57 
		gearing_bonus = 0.0000 
		type = naval_fire_controll_s 
		model = 1 
		} 
	brigade_development = { 
		id = { type = 12700 id = 4020 } 
		name = "36' AA" 
		progress = 0.0000 
		location = 19 
		cost = 0.7040 
		date = { 
			year = 1937 
			month = july 
			day = 2 
			hour = 0 
			} 
		manpower = 0.1000 
		close_when_finished = yes 
		waitingforclosure = no 
		retooling_time = 32.0000 
		total_progress = 0.0000 
		size = 7 
		done = 0 
		days = 904 
		days_for_first = 84 
		gearing_bonus = 0.0000 
		type = naval_anti_air_s 
		model = 1 
		} 
	brigade_development = { 
		id = { type = 12700 id = 4021 } 
		name = "36' Capital AA" 
		progress = 0.0000 
		location = 19 
		cost = 0.8800 
		date = { 
			year = 1936 
			month = april 
			day = 12 
			hour = 0 
			} 
		manpower = 0.1000 
		close_when_finished = yes 
		waitingforclosure = no 
		retooling_time = 32.0000 
		total_progress = 0.0000 
		size = 1 
		done = 0 
		days = 70 
		days_for_first = 70 
		gearing_bonus = 0.0000 
		type = naval_anti_air_l 
		model = 1 
		} 
	brigade_development = { 
		id = { type = 12700 id = 4022 } 
		name = "37' Capital Radar" 
		progress = 0.0000 
		location = 19 
		cost = 0.8800 
		date = { 
			year = 1937 
			month = august 
			day = 21 
			hour = 0 
			} 
		manpower = 0.1000 
		close_when_finished = yes 
		waitingforclosure = no 
		retooling_time = 32.0000 
		total_progress = 0.0000 
		size = 7 
		done = 0 
		days = 562 
		days_for_first = 92 
		gearing_bonus = 0.0000 
		type = naval_radar_l 
		model = 0 
		} 
	brigade_development = { 
		id = { type = 12700 id = 4023 } 
		name = "36' AA" 
		progress = 0.0000 
		location = 19 
		cost = 0.7040 
		date = { 
			year = 1937 
			month = april 
			day = 26 
			hour = 0 
			} 
		manpower = 0.1000 
		close_when_finished = yes 
		waitingforclosure = no 
		retooling_time = 32.0000 
		total_progress = 0.0000 
		size = 6 
		done = 0 
		days = 442 
		days_for_first = 84 
		gearing_bonus = 0.0000 
		type = naval_anti_air_s 
		model = 1 
		} 
	division_development = { 
		id = { type = 12700 id = 271 } 
		name = "HMS Southampton" 
		progress = 0.0000 
		location = 0 
		cost = 4.1383 
		date = { 
			year = 1936 
			month = october 
			day = 28 
			hour = 0 
			} 
		manpower = 1.4000 
		close_when_finished = yes 
		waitingforclosure = no 
		total_progress = 0.9743 # 0.4848
		size = 3 
		done = 0 
		days = 1 
		days_for_first = 159 
		gearing_bonus = 0.0000 
		type = light_cruiser 
		extra = none 
		extra1 = naval_fire_controll_s 
		extra2 = naval_spotter_s 
		extra3 = none 
		extra4 = none 
		model = 3 
		brigade_model = 0 
		brigade_model1 = 1 
		brigade_model2 = 2 
		brigade_model3 = 0 
		brigade_model4 = 0 
		} 
	division_development = { 
		id = { type = 12700 id = 270 } 
		name = "HMS Newcastle" 
		progress = 0.0000 
		location = 0 
		cost = 4.1383 
		date = { 
			year = 1936 
			month = june 
			day = 21 
			hour = 0 
			} 
		manpower = 1.4000 
		close_when_finished = yes 
		waitingforclosure = no 
		total_progress = 0.8703 # 0.5132
		size = 2 
		done = 0 
		days = 1 
		days_for_first = 159 
		gearing_bonus = 0.0000 
		type = light_cruiser 
		extra = none 
		extra1 = naval_fire_controll_s 
		extra2 = naval_spotter_s 
		extra3 = none 
		extra4 = none 
		model = 3 
		brigade_model = 0 
		brigade_model1 = 1 
		brigade_model2 = 2 
		brigade_model3 = 0 
		brigade_model4 = 0 
		} 
	division_development = { 
		id = { type = 12700 id = 269 } 
		name = "HMS Aurora" 
		progress = 0.0000 
		location = 0 
		cost = 3.4301 
		date = { 
			year = 1936 
			month = may 
			day = 7 
			hour = 0 
			} 
		manpower = 1.4000 
		close_when_finished = yes 
		waitingforclosure = no 
		total_progress = 0.1964 
		size = 1 
		done = 0 
		days = 1 
		days_for_first = 159 
		gearing_bonus = 0.0000 
		type = light_cruiser 
		extra = none 
		extra1 = naval_fire_controll_s 
		extra2 = naval_anti_air_s 
		extra3 = none 
		extra4 = none 
		model = 2 
		brigade_model = 0 
		brigade_model1 = 1 
		brigade_model2 = 1 
		brigade_model3 = 0 
		brigade_model4 = 0 
		} 
	division_development = { 
		id = { type = 12700 id = 268 } 
		name = "34th Destroyer Flotilla" 
		progress = 0.0000 
		location = 0 
		cost = 3.2304 
		date = { 
			year = 1936 
			month = march 
			day = 26 
			hour = 0 
			} 
		manpower = 0.7000 
		close_when_finished = yes 
		waitingforclosure = no 
		total_progress = 0.0808 
		size = 1 
		done = 0 
		days = 1 
		days_for_first = 94 
		gearing_bonus = 0.0000 
		type = destroyer 
		extra = none 
		extra1 = naval_fire_controll_s 
		extra2 = none 
		extra3 = none 
		extra4 = none 
		model = 1 
		brigade_model = 0 
		brigade_model1 = 1 
		brigade_model2 = 0 
		brigade_model3 = 0 
		brigade_model4 = 0 
		} 
	division_development = { 
		id = { type = 12700 id = 267 } 
		name = "33rd Destroyer Flotilla" 
		progress = 0.0000 
		location = 0 
		cost = 3.2304 
		date = { 
			year = 1936 
			month = february 
			day = 27 
			hour = 0 
			} 
		manpower = 0.7000 
		close_when_finished = yes 
		waitingforclosure = no 
		total_progress = 0.3838 
		size = 1 
		done = 0 
		days = 1 
		days_for_first = 94 
		gearing_bonus = 0.0000 
		type = destroyer 
		extra = none 
		extra1 = naval_fire_controll_s 
		extra2 = none 
		extra3 = none 
		extra4 = none 
		model = 1 
		brigade_model = 0 
		brigade_model1 = 1 
		brigade_model2 = 0 
		brigade_model3 = 0 
		brigade_model4 = 0 
		} 
	division_development = { 
		id = { type = 12700 id = 266 } 
		name = "10th Submarine Flotilla" 
		progress = 0.0000 
		location = 0 
		cost = 1.5120 
		date = { 
			year = 1936 
			month = february 
			day = 28 
			hour = 0 
			} 
		manpower = 0.4000 
		close_when_finished = yes 
		waitingforclosure = no 
		total_progress = 0.5197 
		size = 1 
		done = 0 
		days = 1 
		days_for_first = 121 
		gearing_bonus = 0.0000 
		type = submarine 
		extra = none 
		extra1 = none 
		extra2 = none 
		extra3 = none 
		extra4 = none 
		model = 2 
		brigade_model = 0 
		brigade_model1 = 0 
		brigade_model2 = 0 
		brigade_model3 = 0 
		brigade_model4 = 0 
		} 
	division_development = { 
		id = { type = 12700 id = 265 } 
		name = "HMS Penelope" 
		progress = 0.0000 
		location = 0 
		cost = 3.4478 
		date = { 
			year = 1936 
			month = february 
			day = 26 
			hour = 0 
			} 
		manpower = 1.4000 
		close_when_finished = yes 
		waitingforclosure = no 
		total_progress = 0.6467 
		size = 1 
		done = 0 
		days = 1 
		days_for_first = 159 
		gearing_bonus = 0.0000 
		type = light_cruiser 
		extra = none 
		extra1 = naval_spotter_s 
		extra2 = naval_anti_air_s 
		extra3 = none 
		extra4 = none 
		model = 2 
		brigade_model = 0 
		brigade_model1 = 1 
		brigade_model2 = 1 
		brigade_model3 = 0 
		brigade_model4 = 0 
		} 
	division_development = { 
		id = { type = 12700 id = 264 } 
		name = "HMS Amphion" # HMAS Perth since 1939
		progress = 0.0000 
		location = 0 
		cost = 3.3324 
		date = { 
			year = 1936 
			month = january 
			day = 24 
			hour = 0 
			} 
		manpower = 1.4000 
		close_when_finished = yes 
		waitingforclosure = no 
		total_progress = 0.8450 
		size = 1 
		done = 0 
		days = 1 
		days_for_first = 159 
		gearing_bonus = 0.0000 
		type = light_cruiser 
		extra = none 
		extra1 = naval_spotter_s 
		extra2 = naval_anti_air_s 
		extra3 = none 
		extra4 = none 
		model = 2 
		brigade_model = 0 
		brigade_model1 = 1 
		brigade_model2 = 0 
		brigade_model3 = 0 
		brigade_model4 = 0 
		} 
	division_development = { 
		id = { type = 12700 id = 263 } 
		name = "HMS Apollo" 
		progress = 0.0000 
		location = 0 
		cost = 3.3324 
		date = { 
			year = 1936 
			month = january 
			day = 2 
			hour = 0 
			} 
		manpower = 1.4000 
		close_when_finished = yes 
		waitingforclosure = no 
		total_progress = 0.9862 
		size = 1 
		done = 0 
		days = 1 
		days_for_first = 159 
		gearing_bonus = 0.0000 
		type = light_cruiser 
		extra = none 
		extra1 = naval_spotter_s 
		extra2 = naval_anti_air_s 
		extra3 = none 
		extra4 = none 
		model = 2 
		brigade_model = 0 
		brigade_model1 = 1 
		brigade_model2 = 0 
		brigade_model3 = 0 
		brigade_model4 = 0 
		} 
}
