#####################
# Country main data #
#####################

country =
{ tag                    = URU
  # Resource Reserves
  energy                 = 332
  metal                  = 154
  rare_materials         = 62
  oil                    = 12
  supplies               = 396
  money                  = 20
  consumer = 0.3612 
  supply = 0.0278 
  production = 0.6000 
  reinforcement = 0.0000 
  upgrading = 0.0000 
  capital                = 849
  manpower               = 1.9 # 7 - building queue
  transports             = 16
  policy =
  { date              = { year = 0 month = january day = 0 }
    democratic        = 5
    political_left    = 2
    freedom           = 5
    free_market       = 5
    professional_army = 2
    defense_lobby     = 4
    interventionism   = 1
  }
  nationalprovinces      = { 849 }
  ownedprovinces         = { 849 }
  controlledprovinces    = { 849 }
  # ROTW Minor Tech '36
  # Group D 1936 techs
  # ######################
  # GW fighter
  techapps               = {  2290 2300 2310 1010 1190 1110 2450 2460 2510 5010 5020 5080 5090 6010 }

	diplomacy = {
		relation = { tag = AFG value = 1 }
		relation = { tag = ALB value = 1 }
		relation = { tag = ARG value = 25 }
		relation = { tag = AST value = 1 }
		relation = { tag = AUS value = 1 }
		relation = { tag = BEL value = 1 }
		relation = { tag = BHU value = 1 }
		relation = { tag = BOL value = 20 }
		relation = { tag = BRA value = -15 }
		relation = { tag = BUL value = 1 }
		relation = { tag = CAN value = 10 }
		relation = { tag = CGX value = 1 }
		relation = { tag = CHC value = 1 }
		relation = { tag = CHI value = 1 }
		relation = { tag = CHL value = 20 }
		relation = { tag = COL value = 20 }
		relation = { tag = COS value = 10 }
		relation = { tag = CSX value = 1 }
		relation = { tag = CUB value = 10 }
		relation = { tag = CXB value = 1 }
		relation = { tag = CYN value = 1 }
		relation = { tag = CZE value = 1 }
		relation = { tag = DEN value = 1 }
		relation = { tag = DOM value = 10 }
		relation = { tag = ECU value = 20 }
		relation = { tag = EGY value = 1 }
		relation = { tag = ENG value = 40 }
		relation = { tag = EST value = 1 }
		relation = { tag = ETH value = 1 }
		relation = { tag = FIN value = 1 }
		relation = { tag = FRA value = 35 }
		relation = { tag = GER value = 35 }
		relation = { tag = GRE value = 1 }
		relation = { tag = GUA value = 10 }
		relation = { tag = HAI value = 10 }
		relation = { tag = HOL value = 1 }
		relation = { tag = HON value = 10 }
		relation = { tag = HUN value = 1 }
		relation = { tag = IND value = 1 }
		relation = { tag = IRE value = 1 }
		relation = { tag = IRQ value = 1 }
		relation = { tag = ITA value = 20 }
		relation = { tag = JAP value = 15 }
		relation = { tag = LAT value = 1 }
		relation = { tag = LIB value = 1 }
		relation = { tag = LIT value = 1 }
		relation = { tag = LUX value = 1 }
		relation = { tag = MAN value = 1 }
		relation = { tag = MEX value = 10 }
		relation = { tag = MLY value = 1 }
		relation = { tag = MON value = 1 }
		relation = { tag = NEP value = 1 }
		relation = { tag = NIC value = 10 }
		relation = { tag = NOR value = 1 }
		relation = { tag = NZL value = 1 }
		relation = { tag = OMN value = 1 }
		relation = { tag = PAN value = 10 }
		relation = { tag = PAR value = 20 }
		relation = { tag = PER value = 1 }
		relation = { tag = PHI value = 1 }
		relation = { tag = POL value = 1 }
		relation = { tag = POR value = 1 }
		relation = { tag = PRU value = 20 }
		relation = { tag = ROM value = 1 }
		relation = { tag = SAF value = 1 }
		relation = { tag = SAL value = 10 }
		relation = { tag = SAU value = 1 }
		relation = { tag = SIA value = 1 }
		relation = { tag = SIK value = 1 }
		relation = { tag = SOV value = 10 }
		relation = { tag = SPA value = 15 }
		relation = { tag = SPR value = 15 }
		relation = { tag = SWE value = 1 }
		relation = { tag = SCH value = 50 }
		relation = { tag = TAN value = 1 }
		relation = { tag = TIB value = 1 }
		relation = { tag = TUR value = 1 }
		relation = { tag = U27 value = 1 }
		relation = { tag = USA value = 35 }
		relation = { tag = VEN value = 20 }
		relation = { tag = YEM value = 1 }
		relation = { tag = YUG value = 1 }
	}

	SpyInfo = { country = "URU" NumberOfSpies = 2 }
	SpyInfo = { country = "ARG" NumberOfSpies = 4 }
	SpyInfo = { country = "BOL" NumberOfSpies = 1 }
	SpyInfo = { country = "BRA" NumberOfSpies = 4 }
	SpyInfo = { country = "CHL" NumberOfSpies = 1 }
	SpyInfo = { country = "ENG" NumberOfSpies = 1 }
	SpyInfo = { country = "GER" NumberOfSpies = 1 }
	SpyInfo = { country = "PAR" NumberOfSpies = 2 }
	SpyInfo = { country = "PRU" NumberOfSpies = 1 }

  headofstate            = { type = 9 id = 41001 }
  headofgovernment       = { type = 9 id = 41002 }
  foreignminister        = { type = 9 id = 41003 }
  armamentminister       = { type = 9 id = 41004 }
  ministerofsecurity     = { type = 9 id = 41005 }
  ministerofintelligence = { type = 9 id = 41006 }
  chiefofstaff           = { type = 9 id = 41007 }
  chiefofarmy            = { type = 9 id = 41008 }
  chiefofnavy            = { type = 9 id = 41009 }
  chiefofair             = { type = 9 id = 41010 }
  landunit =
  { id       = { type = 13700 id = 1 }
    name     = "Ejercito de Uruguay"
    location = 849
    division =
    { id       = { type = 13700 id = 2 }
      name     = "4a Brigada de Inf. 'Don Claudio'"
      strength = 100
      type     = infantry
      extra    = b_u9
    }
  } 

navalunit = {
	id = { type = 13700 id = 3 }
	name = "Marina de Uruguay"
	location = 849
	base = 849

	division = {
		id = { type = 13700 id = 4 }
		name = "Flotilla T1"
		type = destroyer
		strength = 100
		model = 0
		}
	}

	province_development = { 
		id = { type = 13700 id = 5 } 
		name = "" 
		progress = 0.0000 
		location = 849 
		cost = 2.0000 
		date = { 
			year = 1943 
			month = july 
			day = 3 
			hour = 0 
			} 
		manpower = 0.1000 
		close_when_finished = yes 
		waitingforclosure = no 
		total_progress = 0.0000 
		size = 28 
		done = 0 
		days = 2569 
		days_for_first = 120 
		gearing_bonus = 0.0000 
		type = infrastructure 
		} 
}
