##############################
# Country definition for USA #
##############################

province = { id = 663	oilpool = 25	supplypool = 100 } # Pearl Harbour
province = { id = 889	oilpool = 25	supplypool = 100 } # Colon (Panama Canal)
province = { id = 1737	oilpool = 25	supplypool = 100 } # Manila

province = { id = 662	oilpool = 5 	supplypool = 20  } # Midway
province = { id = 895	oilpool = 5 	supplypool = 20  } # Puerto Rico
province = { id = 1624	oilpool = 5 	supplypool = 20  } # Guam
province = { id = 1786	oilpool = 5 	supplypool = 20  } # Wake Island

province = { id = 1756	oilpool = 0 	supplypool = 10  } # Samoa
province = { id = 1765	oilpool = 0 	supplypool = 10  } # Phoenix Island
province = { id = 1765	oilpool = 0 	supplypool = 10  } # Palmyra
province = { id = 1766	oilpool = 0 	supplypool = 10  } # Johnson Island

#####################
# Country main data #
#####################

country =
{ tag                    = USA
  # Resource Reserves
  energy                 = 35370
  metal                  = 16578
  rare_materials         = 11366
  oil                    = 23175
  supplies               = 9328
  money                  = 1000
  consumer = 0.1650 
  supply = 0.0877 
  production = 0.7473 
  reinforcement = 0.0000 
  upgrading = 0.0000 
  manpower               = 56.9000    # 100 - building queue
  transports             = 2456
  escorts                = 34
  peacetime_ic_mod       = 0.25
  capital                = 606

diplomacy = {
		relation = { tag = AFG value = -15 }
		relation = { tag = ALB value = -15 }
		relation = { tag = ARG value = 40 guaranteed = { day = 30 month = december year = 1935 } }
		relation = { tag = AST value = 65 }
		relation = { tag = AUS value = 5 }
		relation = { tag = BEL value = 25 }
		relation = { tag = BHU value = 5 }
		relation = { tag = BOL value = 25 guaranteed = { day = 30 month = december year = 1935 } }
		relation = { tag = BRA value = 45 guaranteed = { day = 30 month = december year = 1935 } }
		relation = { tag = BUL value = -15 }
		relation = { tag = CAN value = 100 guaranteed = { day = 30 month = december year = 1935 } }
		relation = { tag = CGX value = 25 }
		relation = { tag = CHC value = -15 }
		relation = { tag = CHI value = 75 }
		relation = { tag = CHL value = 50 guaranteed = { day = 30 month = december year = 1935 } }
		relation = { tag = COL value = 50 guaranteed = { day = 30 month = december year = 1935 } }
		relation = { tag = COS value = 50 guaranteed = { day = 30 month = december year = 1935 } }
		relation = { tag = CSX value = 15 }
		relation = { tag = CUB value = 175 guaranteed = { day = 30 month = december year = 1935 } access = yes }
		relation = { tag = CXB value = 50 }
		relation = { tag = CYN value = 15 }
		relation = { tag = CZE value = 40 }
		relation = { tag = DEN value = 50 }
		relation = { tag = DOM value = 75 guaranteed = { day = 30 month = december year = 1935 } }
		relation = { tag = ECU value = 65 guaranteed = { day = 30 month = december year = 1935 } }
		relation = { tag = EGY value = 25 }
		relation = { tag = ENG value = 100 }
		relation = { tag = EST value = 15 }
		relation = { tag = ETH value = 30 }
		relation = { tag = FIN value = 35 }
		relation = { tag = FRA value = 50 }
		relation = { tag = GER value = 25 }
		relation = { tag = GRE value = 35 }
		relation = { tag = GUA value = 50 guaranteed = { day = 30 month = december year = 1935 } }
		relation = { tag = HAI value = 60 guaranteed = { day = 30 month = december year = 1935 } }
		relation = { tag = HOL value = 50 }
		relation = { tag = HON value = 50 guaranteed = { day = 30 month = december year = 1935 } }
		relation = { tag = HUN value = -5 }
		relation = { tag = IND value = -5 }
		relation = { tag = IRE value = 75 }
		relation = { tag = IRQ value = 25 }
		relation = { tag = ITA value = 35 }
		relation = { tag = JAP value = 25 }
		relation = { tag = LAT value = 15 }
		relation = { tag = LIB value = 175 }
		relation = { tag = LIT value = 15 }
		relation = { tag = LUX value = 35 }
		relation = { tag = MAN value = -15 }
		relation = { tag = MEX value = 75 guaranteed = { day = 30 month = december year = 1935 } }
		relation = { tag = MLY value = 15 }
		relation = { tag = MON value = -25 }
		relation = { tag = NEP value = 15 }
		relation = { tag = NIC value = 65 guaranteed = { day = 30 month = december year = 1935 } }
		relation = { tag = NOR value = 45 }
		relation = { tag = NZL value = 65 }
		relation = { tag = OMN value = 15 }
		relation = { tag = PAN value = 100 guaranteed = { day = 30 month = december year = 1935 } }
		relation = { tag = PAR value = 25 guaranteed = { day = 30 month = december year = 1935 } }
		relation = { tag = PER value = 40 }
		relation = { tag = PHI value = 175 guaranteed = { day = 30 month = december year = 1935 } access = yes }
		relation = { tag = POL value = 25 }
		relation = { tag = POR value = 35 }
		relation = { tag = PRU value = 50 guaranteed = { day = 30 month = december year = 1935 } }
		relation = { tag = ROM value = 25 }
		relation = { tag = SAF value = 45 }
		relation = { tag = SAL value = 50 guaranteed = { day = 30 month = december year = 1935 } }
		relation = { tag = SAU value = 35 }
		relation = { tag = SIA value = 15 }
		relation = { tag = SIK value = 30 }
		relation = { tag = SOV value = 20 }
		relation = { tag = SPA value = 45 }
		relation = { tag = SPR value = 45 }
		relation = { tag = SWE value = 45 }
		relation = { tag = SCH value = 65 }
		relation = { tag = TAN value = -25 }
		relation = { tag = TIB value = 5 }
		relation = { tag = TUR value = 30 }
		relation = { tag = U27 value = 75 }
		relation = { tag = URU value = 35 guaranteed = { day = 30 month = december year = 1935 } }
		relation = { tag = VEN value = 75 guaranteed = { day = 30 month = december year = 1935 } }
		relation = { tag = YEM value = 15 }
		relation = { tag = YUG value = 40 }
	}

	SpyInfo = { country = "USA" NumberOfSpies = 1 }
	SpyInfo = { country = "AFG" NumberOfSpies = 1 }
	SpyInfo = { country = "ARG" NumberOfSpies = 2 }
	SpyInfo = { country = "AST" NumberOfSpies = 1 }
	SpyInfo = { country = "BEL" NumberOfSpies = 1 }
	SpyInfo = { country = "BOL" NumberOfSpies = 1 }
	SpyInfo = { country = "BRA" NumberOfSpies = 3 }
	SpyInfo = { country = "CAN" NumberOfSpies = 4 }
	SpyInfo = { country = "CGX" NumberOfSpies = 2 }
	SpyInfo = { country = "CHC" NumberOfSpies = 1 }
	SpyInfo = { country = "CHI" NumberOfSpies = 6 }
	SpyInfo = { country = "CHL" NumberOfSpies = 3 }
	SpyInfo = { country = "COL" NumberOfSpies = 3 }
	SpyInfo = { country = "COS" NumberOfSpies = 2 }
	SpyInfo = { country = "CSX" NumberOfSpies = 2 }
	SpyInfo = { country = "CUB" NumberOfSpies = 7 }
	SpyInfo = { country = "CXB" NumberOfSpies = 1 }
	SpyInfo = { country = "CYN" NumberOfSpies = 1 }
	SpyInfo = { country = "DOM" NumberOfSpies = 3 }
	SpyInfo = { country = "ECU" NumberOfSpies = 2 }
	SpyInfo = { country = "EGY" NumberOfSpies = 1 }
	SpyInfo = { country = "ENG" NumberOfSpies = 4 }
	SpyInfo = { country = "ETH" NumberOfSpies = 1 }
	SpyInfo = { country = "FIN" NumberOfSpies = 1 }
	SpyInfo = { country = "FRA" NumberOfSpies = 4 }
	SpyInfo = { country = "GER" NumberOfSpies = 3 }
	SpyInfo = { country = "GRE" NumberOfSpies = 1 }
	SpyInfo = { country = "GUA" NumberOfSpies = 2 }
	SpyInfo = { country = "HAI" NumberOfSpies = 4 }
	SpyInfo = { country = "HOL" NumberOfSpies = 1 }
	SpyInfo = { country = "HON" NumberOfSpies = 2 }
	SpyInfo = { country = "IND" NumberOfSpies = 1 }
	SpyInfo = { country = "IRE" NumberOfSpies = 1 }
	SpyInfo = { country = "ITA" NumberOfSpies = 2 }
	SpyInfo = { country = "JAP" NumberOfSpies = 1 }
	SpyInfo = { country = "LIB" NumberOfSpies = 6 }
	SpyInfo = { country = "MAN" NumberOfSpies = 2 }
	SpyInfo = { country = "MEX" NumberOfSpies = 6 }
	SpyInfo = { country = "NIC" NumberOfSpies = 2 }
	SpyInfo = { country = "NZL" NumberOfSpies = 1 }
	SpyInfo = { country = "PAN" NumberOfSpies = 6 }
	SpyInfo = { country = "PAR" NumberOfSpies = 1 }
	SpyInfo = { country = "PER" NumberOfSpies = 1 }
	SpyInfo = { country = "PHI" NumberOfSpies = 6 }
	SpyInfo = { country = "POR" NumberOfSpies = 1 }
	SpyInfo = { country = "PRU" NumberOfSpies = 2 }
	SpyInfo = { country = "SAF" NumberOfSpies = 1 }
	SpyInfo = { country = "SAL" NumberOfSpies = 2 }
	SpyInfo = { country = "SAU" NumberOfSpies = 2 }
	SpyInfo = { country = "SIA" NumberOfSpies = 1 }
	SpyInfo = { country = "SOV" NumberOfSpies = 4 }
	SpyInfo = { country = "SPR" NumberOfSpies = 3 }
	SpyInfo = { country = "SCH" NumberOfSpies = 2 }
	SpyInfo = { country = "TIB" NumberOfSpies = 1 }
	SpyInfo = { country = "TUR" NumberOfSpies = 4 }
	SpyInfo = { country = "U27" NumberOfSpies = 2 }
	SpyInfo = { country = "URU" NumberOfSpies = 2 }
	SpyInfo = { country = "VEN" NumberOfSpies = 3 }
	SpyInfo = { country = "SPA" NumberOfSpies = 2 }

  nationalprovinces      = { 651  650  649  648  677  676  672  646  647  669  670  644  645  634  635  636  637  643  633  632  631  638  639  606 
                             607  605  604  603  612  602  598  593  592  608  609  610  611  594  597  595  596  582  583  599  600  601  613  614 
                             629  630  640  641  642  671  673  674  675  678  679  615  628  617  616  618  619  627  680  681  682  683  684  685 
                             686  687  688  689  626  625  620  621  624  623  622  690  691  692  693  694  695  696  697  698  699  787  788  789 
                             790  791  792  793  710  711  712  713  714  715  716  717  719  720  721  748  722  723  724  725  727  728  729  730 
                             731  732  733  706  707  708  709  705  704  703  702  701  700  775  774  770  771  772  773  776  777  779  780  781 
                             782  783  784  785  786  778  769  768  734  736  735  767  761  762  763  764  765  766  553  551  550  549  548  547 
                             546  545  544  543  542  718  726  746  1408 895  889 
                           }
  ownedprovinces         = { 651  650  649  648  677  676  672  646  647  669  670  644  645  634  635  636  637  643  633  632  631  638  639  606 
                             607  605  604  603  612  602  598  593  592  608  609  610  611  594  597  595  596  582  583  599  600  601  613  614 
                             629  630  640  641  642  671  673  674  675  678  679  615  628  617  616  618  619  627  680  681  682  683  684  685 
                             686  687  688  689  626  625  620  621  624  623  622  690  691  692  693  694  695  696  697  698  699  787  788  789 
                             790  791  792  793  710  711  712  713  714  715  716  717  719  720  721  748  722  723  724  725  727  728  729  730 
                             731  732  733  706  707  708  709  705  704  703  702  701  700  775  774  770  771  772  773  776  777  779  780  781 
                             782  783  784  785  786  778  769  768  734  736  735  767  761  762  763  764  765  766  553  551  550  549  548  547 
                             546  545  544  543  542  718  726  746  895  889  658  659  660  661  662  663  1756 1766 1762 1786 1624 1408 1764 1765
                           }
  controlledprovinces    = { 651  650  649  648  677  676  672  646  647  669  670  644  645  634  635  636  637  643  633  632  631  638  639  606 
                             607  605  604  603  612  602  598  593  592  608  609  610  611  594  597  595  596  582  583  599  600  601  613  614 
                             629  630  640  641  642  671  673  674  675  678  679  615  628  617  616  618  619  627  680  681  682  683  684  685 
                             686  687  688  689  626  625  620  621  624  623  622  690  691  692  693  694  695  696  697  698  699  787  788  789 
                             790  791  792  793  710  711  712  713  714  715  716  717  719  720  721  748  722  723  724  725  727  728  729  730 
                             731  732  733  706  707  708  709  705  704  703  702  701  700  775  774  770  771  772  773  776  777  779  780  781 
                             782  783  784  785  786  778  769  768  734  736  735  767  761  762  763  764  765  766  553  551  550  549  548  547 
                             546  545  544  543  542  718  726  746  895  889  658  659  660  661  662  663  1756 1766 1762 1786 1624 1408 1764 1765
                           }
  # early esc car
  # USA 1936 techs
  # ######################
  techapps               = { 2020 3030 2400 1210 12100 4010  4020  4120  4130  4250  4260  4190  4220     2010  2290  2300  2310  2450  2460  2510  1010  1190  1200 
                             1310  5010  5020  5050  5080  5090  5310  5320  5470  5480  9010  9020  9030  9140  6010  6020  8010  8020  8030 
                             8040  8050  8060  8100  8110  3010  3020  3070  3080  3130  3140  3150  3190  3200  3210  3220  3250  3260  3270  3280  3320 
                             3330  3340  3400  3410  3420  14000 3470  5290  3100  3160  3090  5190  1150 2150
                           }
  blueprints             = { 8310 8320 }
  policy =
  { date              = { year = 0 month = january day = 0 }
    democratic        = 10
    political_left    = 6
    freedom           = 10
    free_market       = 10
    professional_army = 1
    defense_lobby     = 1
    interventionism   = 1
  }
  headofstate            = { type = 9 id = 6001 }
  headofgovernment       = { type = 9 id = 6002 }
  foreignminister        = { type = 9 id = 6003 }
  armamentminister       = { type = 9 id = 6004 }
  ministerofsecurity     = { type = 9 id = 6005 }
  ministerofintelligence = { type = 9 id = 6006 }
  chiefofstaff           = { type = 9 id = 6007 }
  chiefofarmy            = { type = 9 id = 6008 }
  chiefofnavy            = { type = 9 id = 6158 }
  chiefofair             = { type = 9 id = 6010 }

  nationalidentity = "policy_identity_guardians" 
	socialpolicy = "policy_social_enterprise" 
	nationalculture = "policy_culture_enterprise"

#LAND OOB

landunit = { 
	id = { type = 14800 id = 1000 }
	name = "VI Corps"
	location = 602

	division = { 
		id = { type = 14800 id = 1001 }
		name = "1st Infantry Division"
		type = infantry
		model = 0
		strength = 50
		extra = b_u9
		brigade_model = 3
		}
	}

landunit = { 
	id = { type = 14800 id = 1002 }
	name = "VIII Corps"
	location = 717

	division = { 
		id = { type = 14800 id = 1003 }
		name = "2nd Infantry Division"
		type = infantry
		model = 0
		strength = 50
		}
	}

landunit = { 
	id = { type = 14800 id = 1004 }
	name = "IX Corps"
	location = 782

	division = { 
		id = { type = 14800 id = 1005 }
		name = "3d Infantry Division"
		type = infantry
		model = 0
		strength = 50
		extra = engineer
		brigade_model = 0
		}
	}

landunit = { 
	id = { type = 14800 id = 1006 }
	name = "Cavalry Corps"
	location = 718

	division = { 
		id = { type = 14800 id = 1007 }
		name = "1st Cavalry Division"
		type = cavalry
		model = 0
		strength = 50
		extra = light_armor_brigade
		brigade_model = 0
		}
	}

landunit = { 
	id = { type = 14800 id = 1008 }
	name = "First Army"
	location = 593

	division = { 
		id = { type = 14800 id = 1009 }
		name = "First Army"
		type = hq
		model = 0
		strength = 30
		}
	}

landunit = { 
	id = { type = 14800 id = 1010 }
	name = "Hawaiian Department"
	location = 663

	division = { 
		id = { type = 14800 id = 1011 }
		name = "Hawaiian Division"
		type = infantry
		model = 0
		extra = engineer
		brigade_model = 0
		}
	}

landunit = { 
	id = { type = 14800 id = 1012 }
	name = "Phillipine Department"
	location = 1737

	division = { 
		id = { type = 14800 id = 1013 }
		name = "Phillipine Division"
		type = militia
		model = 0
		strength = 30
		}
	}

landunit = { 
	id = { type = 14800 id = 1014 }
	name = "Panama Canal Department"
	location = 889

	division = { 
		id = { type = 14800 id = 1015 }
		name = "Panama Mobile Force"
		type = militia
		model = 0
		extra = engineer
		brigade_model = 0
		}
	}

################################ 
# Coastal Defence Garrisons: 
# Research by Micah Goodman
################################ 

landunit = {
	id = { type = 12706 id = 1016 }
	name = "Harbor Defenses Portland"
	location = 583

	division = {
		id = { type = 12706 id = 1017 }
		name = "Harbor Defenses Portland"
		type = garrison
		model = 0
		strength = 35
		locked = yes
		}
	}

landunit = {
	id = { type = 12706 id = 1018 }
	name = "Harbor Defenses Portsmouth"
	location = 596

	division = {
		id = { type = 12706 id = 1019 }
		name = "Harbor Defenses Portsmouth"
		type = garrison
		model = 0
		strength = 15
		locked = yes
		}
	}

landunit = {
	id = { type = 12706 id = 1020 }
	name = "Harbor Defenses Boston"
	location = 600

	division = {
		id = { type = 12706 id = 1021 }
		name = "Harbor Defenses Boston"
		type = garrison
		model = 0
		strength = 45
		locked = yes
		extra = artillery
		brigade_model = 0
		}
	}

landunit = {
	id = { type = 12706 id = 1022 }
	name = "Harbor Defenses Narragansett Bay"
	location = 601

	division = {
		id = { type = 12706 id = 1023 }
		name = "Harbor Defenses Narragansett Bay"
		type = garrison
		model = 0
		strength = 40
		locked = yes
		}
	}

landunit = {
	id = { type = 12706 id = 1024 }
	name = "Harbor Defenses Long Island Sound"
	location = 602

	division = {
		id = { type = 12706 id = 1025 }
		name = "Harbor Defenses Long Island Sound"
		type = garrison
		model = 0
		strength = 50
		locked = yes
		extra = artillery
		brigade_model = 0
		}
	}

landunit = {
	id = { type = 12706 id = 1026 }
	name = "Harbor Defenses Sandy Hook"
	location = 603

	division = {
		id = { type = 12706 id = 1027 }
		name = "Harbor Defenses Sandy Hook"
		type = garrison
		model = 0
		strength = 40
		locked = yes
		extra = artillery
		brigade_model = 0
		}
	}

landunit = {
	id = { type = 12706 id = 1028 }
	name = "Harbor Defenses Delaware River"
	location = 605

	division = {
		id = { type = 12706 id = 1029 }
		name = "Harbor Defenses Delaware River"
		type = garrison
		model = 0
		strength = 20
		locked = yes
		}
	}

landunit = {
	id = { type = 12706 id = 1030 }
	name = "Harbor Defenses Chesapeake Bay"
	location = 633

	division = {
		id = { type = 12706 id = 1031 }
		name = "Harbor Defenses Chesapeake Bay"
		type = garrison
		model = 0
		strength = 50
		locked = yes
		extra = artillery
		brigade_model = 0
		}
	}

landunit = {
	id = { type = 12706 id = 1032 }
	name = "Harbor Defenses Charleston"
	location = 644

	division = {
		id = { type = 12706 id = 1033 }
		name = "Harbor Defenses Charleston"
		type = garrison
		model = 0
		strength = 20
		locked = yes
		}
	}

landunit = {
	id = { type = 12706 id = 1034 }
	name = "Harbor Defenses Galveston"
	location = 716

	division = {
		id = { type = 12706 id = 1035 }
		name = "Harbor Defenses Galveston"
		type = garrison
		model = 0
		strength = 35
		locked = yes
		extra = artillery
		brigade_model = 0
		}
	}

landunit = {
	id = { type = 12706 id = 1036 }
	name = "Harbor Defenses San Diego"
	location = 761

	division = {
		id = { type = 12706 id = 1037 }
		name = "Harbor Defenses San Diego"
		type = garrison
		model = 0
		strength = 20
		locked = yes
		}
	}

landunit = {
	id = { type = 12706 id = 1038 }
	name = "Harbor Defenses Los Angeles"
	location = 762

	division = {
		id = { type = 12706 id = 1039 }
		name = "Harbor Defenses Los Angeles"
		type = garrison
		model = 0
		strength = 20
		locked = yes
		}
	}

landunit = {
	id = { type = 12706 id = 1040 }
	name = "Harbor Defenses San Fransisco"
	location = 765

	division = {
		id = { type = 12706 id = 1041 }
		name = "Harbor Defenses San Fransisco"
		type = garrison
		model = 0
		strength = 40
		locked = yes
		extra = artillery
		brigade_model = 0
		}
	}

landunit = {
	id = { type = 12706 id = 1042 }
	name = "Harbor Defenses Columbia River"
	location = 782

	division = {
		id = { type = 12706 id = 1043 }
		name = "Harbor Defenses Columbia River"
		type = garrison
		model = 0
		strength = 25
		locked = yes
		extra = artillery
		brigade_model = 0
		}
	}

landunit = {
	id = { type = 12706 id = 1044 }
	name = "Harbor Defenses Puget Sound"
	location = 780

	division = {
		id = { type = 12706 id = 1045 }
		name = "Harbor Defenses Puget Sound"
		type = garrison
		model = 0
		strength = 35
		locked = yes
		extra = artillery
		brigade_model = 0
		}
	}

landunit = {
	id = { type = 12706 id = 1046 }
	name = "Hawaiian Coast Artillery Command"
	location = 663

	division = {
		id = { type = 12706 id = 1047 }
		name = "Harbor Defenses Honolulu"
		type = garrison
		model = 0
		locked = yes
		extra = artillery
		brigade_model = 0
		}
	}

landunit = { 
	id = { type = 14800 id = 1048 }
	name = "Phillipine Coast Artillery Command"
	location = 1738

	division = {
		id = { type = 12706 id = 1049 }
		name = "Phillipine Coast Artillery Command"
		type = garrison
		model = 0
		locked = yes
		extra = artillery
		brigade_model = 0
		}
	}

landunit = { 
	id = { type = 14800 id = 1050 }
	name = "Panama Coast Artillery Command"
	location = 889

	division = { 
		id = { type = 14800 id = 1051 }
		name = "Panama Coast Artillery Command"
		type = garrison
		model = 0
		locked = yes
		extra = artillery
		brigade_model = 0
		}
	}

landunit = { 
	id = { type = 14800 id = 1052 }
	name = "Harbor Defenses Savannah"
	location = 646

	division = { 
		id = { type = 14800 id = 1053 }
		name = "Harbor Defenses Savannah"
		type = garrison
		model = 0
		strength = 15
		locked = yes
		}
	}

################################
# Naval Garrisons
################################

landunit = { 
	id = { type = 14800 id = 1054 }
	name = "5th Naval District"
	location = 633

	division = { 
		id = { type = 14800 id = 1055 }
		name = "5th Naval District"
		type = garrison
		model = 0
		locked = yes
		extra = artillery
		brigade_model = 0
		}
	}

landunit = { 
	id = { type = 14800 id = 1056 }
	name = "6th Naval District"
	location = 644

	division = { 
		id = { type = 14800 id = 1057 }
		name = "6th Naval District"
		type = garrison
		model = 0
		locked = yes
		extra = artillery
		brigade_model = 0
		}
	}

landunit = {
	id = { type = 12706 id = 1058 }
	name = "11th Naval District"
	location = 761

	division = {
		id = { type = 12706 id = 1059 }
		name = "11th Naval District"
		type = garrison
		model = 0
		locked = yes
		extra = artillery
		brigade_model = 0
		}
	}

 ########################################
	### USA Navy OOB ###
 ########################################
  # US PACIFIC FLEET-SAN DIEGO, CALIFORNIA
  # Battleship Division 1
  # Nevada, Arizona, Pennsylvania
  navalunit =
  { name     = "USN Battleship Fleet 1"
    id       = { type = 14800 id = 26 }
    location = 761
    base     = 761
    division =
    { id            = { type = 14800 id = 27 }
      name          = "USS Lexington"
      type          = carrier
      model         = 1
      extra         = cag
      brigade_model = 2
    }
    division =
    { id    = { type = 14800 id = 28 }
      name  = "USS Nevada"
      type  = battleship
      model = 2
	extra1 = naval_improved_hull_l
	extra2 = naval_sa_l
	extra3 = none
	extra4 = none
	brigade_model1 = 0
	brigade_model2 = 0
	brigade_model3 = 0
	brigade_model4 = 0
    }
division =     
{ id    = { type = 14800 id = 170 }
      name  = "USS Pennsylvania"
      type  = battleship
      model = 2
	extra1 = naval_improved_hull_l
	extra2 = naval_sa_l
	extra3 = none
	extra4 = none
	brigade_model1 = 0
	brigade_model2 = 0
	brigade_model3 = 0
	brigade_model4 = 0
    }
    division =
    { id    = { type = 14800 id = 29 }
      name  = "USS Arizona"
      type  = battleship
      model = 2
	extra1 = naval_improved_hull_l
	extra2 = naval_sa_l
	extra3 = none
	extra4 = none
	brigade_model1 = 0
	brigade_model2 = 0
	brigade_model3 = 0
	brigade_model4 = 0
    }
  }
  # Battleship Division 2
  # Oklahoma, Tennessee, California
  navalunit =
  { name     = "USN Battleship Fleet 2"
    id       = { type = 14800 id = 31 }
    location = 761
    base     = 761
    division =
    { id            = { type = 14800 id = 32 }
      name          = "USS Saratoga"
      type          = carrier
      model         = 1
      extra         = cag
      brigade_model = 2
    }
    division =
    { id    = { type = 14800 id = 33 }
      name  = "USS Oklahoma"
      type  = battleship
      model = 2
	extra1 = naval_improved_hull_l
	extra2 = naval_sa_l
	extra3 = none
	extra4 = none
	brigade_model1 = 0
	brigade_model2 = 0
	brigade_model3 = 0
	brigade_model4 = 0
    }
    division =
    { id    = { type = 14800 id = 34 }
      name  = "USS Tennessee"
      type  = battleship
      model = 2
	extra1 = naval_improved_hull_l
	extra2 = naval_sa_l
	extra3 = none
	extra4 = none
	brigade_model1 = 0
	brigade_model2 = 0
	brigade_model3 = 0
	brigade_model4 = 0
    }
    division =
    { id    = { type = 14800 id = 35 }
      name  = "USS California"
      type  = battleship
      model = 2
	extra1 = naval_improved_hull_l
	extra2 = naval_sa_l
	extra3 = none
	extra4 = none
	brigade_model1 = 0
	brigade_model2 = 0
	brigade_model3 = 0
	brigade_model4 = 0
    }
  }
  # Battleship Division 4
  # Colorado, West Virginia, Maryland
  navalunit =
  { name     = "USN Battleship Fleet 4"
    id       = { type = 14800 id = 36 }
    location = 761
    base     = 761
    division =
    { id    = { type = 14800 id = 37 }
      name  = "USS Colorado"
      type  = battleship
      model = 2
	extra1 = naval_improved_hull_l
	extra2 = naval_sa_l
	extra3 = naval_fire_controll_l
	extra4 = none
	brigade_model1 = 0
	brigade_model2 = 0
	brigade_model3 = 1
	brigade_model4 = 0
    }
    division =
    { id    = { type = 14800 id = 38 }
      name  = "USS West Virginia"
      type  = battleship
      model = 2
	extra1 = naval_improved_hull_l
	extra2 = naval_sa_l
	extra3 = naval_fire_controll_l
	extra4 = none
	brigade_model1 = 0
	brigade_model2 = 0
	brigade_model3 = 1
	brigade_model4 = 0
    }
    division =
    { id    = { type = 14800 id = 39 }
      name  = "USS Maryland"
      type  = battleship
      model = 2
	extra1 = naval_improved_hull_l
	extra2 = naval_sa_l
	extra3 = naval_fire_controll_l
	extra4 = none
	brigade_model1 = 0
	brigade_model2 = 0
	brigade_model3 = 1
	brigade_model4 = 0
    }
  }
  # Cruiser Division 3
  # Richmond, Trenton, Concord
  navalunit =
  { name     = "USN Cruiser Fleet 3"
    id       = { type = 14800 id = 40 }
    location = 761
    base     = 761
    division =
    { id    = { type = 14800 id = 41 }
      name  = "USS Richmond"
      type  = light_cruiser
      model = 1
	extra1 = naval_fire_controll_s
	extra2 = naval_spotter_s
	brigade_model1 = 1
	brigade_model2 = 2
    }
    division =
    { id    = { type = 14800 id = 43 }
      name  = "USS Concord"
      type  = light_cruiser
      model = 1
	extra1 = naval_fire_controll_s
	extra2 = naval_spotter_s
	brigade_model1 = 1
	brigade_model2 = 2
    }
    division =
    { id    = { type = 14800 id = 44 }
      name  = "USS Raleigh"
      type  = light_cruiser
      model = 1
	extra1 = naval_fire_controll_s
	extra2 = naval_spotter_s
	brigade_model1 = 0
	brigade_model2 = 1
    }
    division =
    { id    = { type = 14800 id = 45 }
      name  = "USS Detroit"
      type  = light_cruiser
      model = 1
	extra1 = naval_fire_controll_s
	extra2 = naval_spotter_s
	brigade_model1 = 1
	brigade_model2 = 2
    }
    division =
    { id    = { type = 14800 id = 108 }
      name  = "USS Milwaukee"
      type  = light_cruiser
      model = 1
	extra1 = naval_fire_controll_s
	extra2 = naval_spotter_s
	brigade_model1 = 1
	brigade_model2 = 2
    }
    division =
    { id    = { type = 14800 id = 109 }
      name  = "USS Cincinnati"
      type  = light_cruiser
      model = 1
	extra1 = naval_fire_controll_s
	extra2 = naval_spotter_s
	brigade_model1 = 1
	brigade_model2 = 2
    }
    division =
    { id    = { type = 14800 id = 110 }
      name  = "USS Memphis"
      type  = light_cruiser
      model = 1
	extra1 = naval_fire_controll_s
	extra2 = naval_spotter_s
	brigade_model1 = 1
	brigade_model2 = 2
    }
  }
  # USS Trenton
  navalunit = 
   { name = "USS Trenton"
	id = { type = 14800 id = 200 }
	location = 651
	base = 651
    division =
    { id    = { type = 14800 id = 42 }
      name  = "USS Trenton"
      type  = light_cruiser
      model = 1
	extra1 = naval_fire_controll_s
	extra2 = naval_spotter_s
	brigade_model1 = 0
	brigade_model2 = 1
    }
}
  # Cruiser Division 4
  # Pensacola, Salt Lake City, Chicago, Indianapolis
  navalunit =
  { name     = "USN Cruiser Fleet 4"
    id       = { type = 14800 id = 46 }
    location = 761
    base     = 761
    division =
    { id    = { type = 14800 id = 47 }
      name  = "USS Pensacola"
      type  = heavy_cruiser
      model = 1
    extra1 = naval_fire_controll_l
    extra2 = naval_spotter_l
    extra3 = naval_anti_air_l
    brigade_model1 = 1
    brigade_model2 = 2
    brigade_model3 = 1
    }
    division =
    { id    = { type = 14800 id = 48 }
      name  = "USS Salt Lake City"
      type  = heavy_cruiser
      model = 1
    extra1 = naval_fire_controll_l
    extra2 = naval_spotter_l
    extra3 = naval_anti_air_l
    brigade_model1 = 1
    brigade_model2 = 2
    brigade_model3 = 1
    }
    division =
    { id    = { type = 14800 id = 49 }
      name  = "USS Chicago"
      type  = heavy_cruiser
      model = 1
    extra1 = naval_fire_controll_l
    extra2 = naval_spotter_l
    extra3 = naval_anti_air_l
    brigade_model1 = 1
    brigade_model2 = 2
    brigade_model3 = 1
    }
    division =
    { id    = { type = 14800 id = 50 }
      name  = "USS Indianapolis"
      type  = heavy_cruiser
      model = 1
    extra1 = naval_sa_l
    extra2 = naval_spotter_l
    extra3 = naval_anti_air_l
    brigade_model1 = 0
    brigade_model2 = 2
    brigade_model3 = 1
    }
  }
  # Cruiser Division 5
  # Northampton, Chester, Louisville, Portland
  navalunit =
  { name     = "USN Cruiser Fleet 5"
    id       = { type = 14800 id = 51 }
    location = 761
    base     = 761
    division =
    { id    = { type = 14800 id = 52 }
      name  = "USS Northampton"
      type  = heavy_cruiser
      model = 1
    extra1 = naval_fire_controll_l
    extra2 = naval_spotter_l
    extra3 = naval_anti_air_l
    brigade_model1 = 1
    brigade_model2 = 2
    brigade_model3 = 1
    }
    division =
    { id    = { type = 14800 id = 53 }
      name  = "USS Chester"
      type  = heavy_cruiser
      model = 1
    extra1 = naval_fire_controll_l
    extra2 = naval_spotter_l
    extra3 = naval_anti_air_l
    brigade_model1 = 1
    brigade_model2 = 2
    brigade_model3 = 1
    }
    division =
    { id    = { type = 14800 id = 54 }
      name  = "USS Louisville"
      type  = heavy_cruiser
      model = 1
    extra1 = naval_fire_controll_l
    extra2 = naval_spotter_l
    extra3 = naval_anti_air_l
    brigade_model1 = 1
    brigade_model2 = 2
    brigade_model3 = 1
    }
    division =
    { id    = { type = 14800 id = 55 }
      name  = "USS Portland"
      type  = heavy_cruiser
      model = 1
    extra1 = naval_sa_l
    extra2 = naval_spotter_l
    extra3 = naval_anti_air_l
    brigade_model1 = 0
    brigade_model2 = 2
    brigade_model3 = 1
    }
  }
  # Cruiser Division 6
  # New Orleans, Astoria, Minneapolis, San Francisco
  navalunit =
  { name     = "USN Cruiser Fleet 6"
    id       = { type = 14800 id = 56 }
    location = 761
    base     = 761
    division =
    { id    = { type = 14800 id = 57 }
      name  = "USS New Orleans"
      type  = heavy_cruiser
      model = 2
    extra1 = naval_fire_controll_l
    extra2 = naval_spotter_l
    extra3 = naval_anti_air_l
    brigade_model1 = 1
    brigade_model2 = 2
    brigade_model3 = 1
    }
    division =
    { id    = { type = 14800 id = 58 }
      name  = "USS Astoria"
      type  = heavy_cruiser
      model = 2
    extra1 = naval_fire_controll_l
    extra2 = naval_spotter_l
    extra3 = naval_anti_air_l
    brigade_model1 = 1
    brigade_model2 = 2
    brigade_model3 = 1
    }
    division =
    { id    = { type = 14800 id = 59 }
      name  = "USS Minneapolis"
      type  = heavy_cruiser
      model = 2
    extra1 = naval_fire_controll_l
    extra2 = naval_spotter_l
    extra3 = naval_anti_air_l
    brigade_model1 = 1
    brigade_model2 = 2
    brigade_model3 = 1
    }
    division =
    { id    = { type = 14800 id = 60 }
      name  = "USS San Francisco"
      type  = heavy_cruiser
      model = 2
    extra1 = naval_fire_controll_l
    extra2 = naval_spotter_l
    extra3 = naval_anti_air_l
    brigade_model1 = 1
    brigade_model2 = 2
    brigade_model3 = 1
    }
  }
  navalunit =
  { name     = "Pacific Destroyer Fleet"
    id       = { type = 14800 id = 61 }
    location = 761
    base     = 761
    division =
    { id    = { type = 14800 id = 62 }
      name  = "1st Destroyer Division"
      type  = destroyer
      model = 1
    }
    division =
    { id    = { type = 14800 id = 63 }
      name  = "2nd Destroyer Division"
      type  = destroyer
      model = 1
    }
    division =
    { id    = { type = 14800 id = 64 }
      name  = "3rd Destroyer Division"
      type  = destroyer
      model = 1
    }
  }
  navalunit =
  { location = 633
    base     = 633
    id       = { type = 14800 id = 65 }
    name     = "USN Battleship Fleet 5"
    division =
    { id    = { type = 14800 id = 66 }
      name  = "USS Arkansas"
      type  = battleship
      model = 0
	extra1 = naval_spotter_l
	extra2 = naval_sa_l
	extra3 = none
	extra4 = none
	brigade_model1 = 2
	brigade_model2 = 0
	brigade_model3 = 0
	brigade_model4 = 0
    }
    division =
    { id    = { type = 14800 id = 67 }
      name  = "USS New York"
      type  = battleship
      model = 1
	extra1 = naval_spotter_l
	extra2 = naval_sa_l
	extra3 = none
	extra4 = none
	brigade_model1 = 2
	brigade_model2 = 0
	brigade_model3 = 0
	brigade_model4 = 0
    }
    division =
    { id    = { type = 14800 id = 68 }
      name  = "USS Texas"
      type  = battleship
      model = 1
	extra1 = naval_spotter_l
	extra2 = naval_sa_l
	extra3 = none
	extra4 = none
	brigade_model1 = 2
	brigade_model2 = 0
	brigade_model3 = 0
	brigade_model4 = 0
    }
  }
  navalunit =
  { name     = "Pacific Submarine Fleet"
    id       = { type = 14800 id = 74 }
    location = 761
    base     = 761
    division =
    { id    = { type = 14800 id = 75 }
      name  = "1st Submarine Division"
      type  = submarine
      model = 1
    }
    division =
    { id    = { type = 14800 id = 76 }
      name  = "2nd Submarine Division"
      type  = submarine
      model = 1
    }
    division =
    { id    = { type = 14800 id = 77 }
      name  = "3rd Submarine Division"
      type  = submarine
      model = 1
    }
    division =
    { id    = { type = 14800 id = 78 }
      name  = "4th Submarine Division"
      type  = submarine
      model = 1
    }
    division =
    { id    = { type = 14800 id = 79 }
      name  = "5th Submarine Division"
      type  = submarine
      model = 0
    }
    division =
    { id    = { type = 14800 id = 80 }
      name  = "6th Submarine Division"
      type  = submarine
      model = 0
    }
  }
  navalunit =
  { location = 1737
    base     = 1737
    id       = { type = 14800 id = 81 }
    name     = "Asiatic Fleet"
    division =
    { id    = { type = 14800 id = 82 }
      name  = "13th Destroyer Division"
      type  = destroyer
      model = 0
    }
    division =
    { id    = { type = 14800 id = 83 }
      name  = "14th Destroyer Division"
      type  = destroyer
      model = 0
    }
    division =
    { id    = { type = 14800 id = 84 }
      name  = "15th Destroyer Division"
      type  = destroyer
      model = 0
    }
    division =
    { id    = { type = 14800 id = 24 }
      name  = "31st Destroyer Division"
      type  = destroyer
      model = 0
    }
    division =
    { id    = { type = 14800 id = 25 }
      name  = "32nd Destroyer Division"
      type  = destroyer
      model = 0
    }
    division =
    { id    = { type = 14800 id = 85 }
      name  = "7th Submarine Division"
      type  = submarine
      model = 1
    }
    division =
    { id    = { type = 14800 id = 86 }
      name  = "8th Submarine Division"
      type  = submarine
      model = 1
    }
  }
  navalunit =
  { location = 1737
    base     = 1737
    id       = { type = 14800 id = 87 }
    name     = "2nd USN Submarine Fleet"
    division =
    { id    = { type = 14800 id = 88 }
      name  = "9th Submarine Division"
      type  = submarine
      model = 1
    }
  }
  navalunit =
  { location = 782
    base     = 782
    id       = { type = 14800 id = 89 }
    name     = "USN Seattle Fleet"
    division =
    { id       = { type = 14800 id = 90 }
      name     = "USS Marblehead"
      strength = 100
      type     = light_cruiser
      model    = 1
	extra1 = naval_fire_controll_s
	extra2 = naval_spotter_s
	brigade_model1 = 1
	brigade_model2 = 2
    }
    division =
    { id    = { type = 14800 id = 91 }
      name  = "16th Destroyer Division"
      type  = destroyer
      model = 0
    }
    division =
    { id    = { type = 14800 id = 69 }
      name  = "47th Destroyer Division"
      type  = destroyer
      model = 0
    }
  }
  navalunit =
  { location = 782
    base     = 782
    id       = { type = 14800 id = 92 }
    name     = "USN Columbia Fleet"
    division =
    { id       = { type = 14800 id = 93 }
      name     = "USS Houston"
      strength = 100
      type     = heavy_cruiser
      model    = 1
    extra1 = naval_fire_controll_l
    extra2 = naval_spotter_l
    extra3 = naval_anti_air_l
    brigade_model1 = 1
    brigade_model2 = 2
    brigade_model3 = 1
    }
    division =
    { id    = { type = 14800 id = 70 }
      name  = "43rd Destroyer Division"
      type  = destroyer
      model = 0
    }
    division =
    { id    = { type = 14800 id = 94 }
      name  = "10th Submarine Division"
      type  = submarine
      model = 1
    }
  }
  navalunit =
  { location = 889
    base     = 889
    id       = { type = 14800 id = 95 }
    name     = "USN Carribean Fleet"
    division =
    { id    = { type = 14800 id = 96 }
      name  = "17th Destroyer Division"
      type  = destroyer
      model = 0
    }
    division =
    { id    = { type = 14800 id = 97 }
      name  = "11th Submarine Division"
      type  = submarine
      model = 1
    }
    division =
    { id    = { type = 14800 id = 71 }
      name  = "41st Destroyer Division"
      type  = destroyer
      model = 0
    }
    division =
    { id    = { type = 14800 id = 72 }
      name  = "42nd Destroyer Division"
      type  = destroyer
      model = 0
    }
  }
  navalunit =
  { location = 761
    base     = 761
    id       = { type = 14800 id = 98 }
    name     = "USN Battleship Fleet 3"
    division =
    { id    = { type = 14800 id = 99 }
      name  = "USS New Mexico"
      type  = battleship
      model = 2
	extra1 = naval_improved_hull_l
	extra2 = naval_sa_l
	extra3 = none
	extra4 = none
	brigade_model1 = 0
	brigade_model2 = 0
	brigade_model3 = 0
	brigade_model4 = 0
    }
    division =
    { id    = { type = 14800 id = 100 }
      name  = "USS Mississippi"
      type  = battleship
      model = 2
	extra1 = naval_improved_hull_l
	extra2 = naval_sa_l
	extra3 = none
	extra4 = none
	brigade_model1 = 0
	brigade_model2 = 0
	brigade_model3 = 0
	brigade_model4 = 0
    }
    division =
    { id    = { type = 14800 id = 101 }
      name  = "USS Idaho"
      type  = battleship
      model = 2
	extra1 = naval_improved_hull_l
	extra2 = naval_sa_l
	extra3 = none
	extra4 = none
	brigade_model1 = 0
	brigade_model2 = 0
	brigade_model3 = 0
	brigade_model4 = 0
    }
    division =
    { id    = { type = 14800 id = 103 }
      name  = "44th Destroyer Division"
      type  = destroyer
      model = 0
    }
    division =
    { id    = { type = 14800 id = 104 }
      name  = "45th Destroyer Division"
      type  = destroyer
      model = 0
    }
    division =
    { id    = { type = 14800 id = 105 }
      name  = "46th Destroyer Division"
      type  = destroyer
      model = 0
    }
  }
  navalunit =
  { location = 633
    base     = 633
    id       = { type = 14800 id = 106 }
    name     = "USN Cruiser Fleet 2"
    division =
    { id    = { type = 14800 id = 107 }
      name  = "USS Omaha"
      type  = light_cruiser
      model = 1
	extra1 = naval_fire_controll_s
	extra2 = naval_spotter_s
	brigade_model1 = 1
	brigade_model2 = 2
    }
  }
  navalunit =
  { location = 633
    base     = 633
    id       = { type = 14800 id = 111 }
    name     = "USN Cruiser Fleet 7"
    division =
    { id    = { type = 14800 id = 112 }
      name  = "USS Augusta"
      type  = heavy_cruiser
      model = 1
    extra1 = naval_fire_controll_l
    extra2 = naval_spotter_l
    extra3 = naval_anti_air_l
    brigade_model1 = 1
    brigade_model2 = 2
    brigade_model3 = 1
    }
    division =
    { id    = { type = 14800 id = 113 }
      name  = "USS Tuscaloosa"
      type  = heavy_cruiser
      model = 2
    extra1 = naval_fire_controll_l
    extra2 = naval_spotter_l
    extra3 = naval_anti_air_l
    brigade_model1 = 1
    brigade_model2 = 2
    brigade_model3 = 1
    }
  }
  navalunit =
  { location = 761
    base     = 761
    id       = { type = 14800 id = 114 }
    name     = "USS Ranger Taskforce"
    division =
    { id            = { type = 14800 id = 115 }
      name          = "USS Ranger"
      type          = carrier
      model         = 2
      extra         = cag
      brigade_model = 2
    }
    division =
    { id    = { type = 14800 id = 500 }
      name  = "USS Langley"
      type  = escort_carrier
      model = 0
      extra1        = b_u1
      brigade_model1= 0
    }
    division =
    { id    = { type = 14800 id = 116 }
      name  = "18th Destroyer Division"
      type  = destroyer
      model = 0
    }
    division =
    { id    = { type = 14800 id = 117 }
      name  = "19th Destroyer Division"
      type  = destroyer
      model = 0
    }
    division =
    { id    = { type = 14800 id = 118 }
      name  = "20th Destroyer Division"
      type  = destroyer
      model = 0
    }
    division =
    { id    = { type = 14800 id = 119 }
      name  = "21st Destroyer Division"
      type  = destroyer
      model = 0
    }
    division =
    { id    = { type = 14800 id = 120 }
      name  = "22nd Destroyer Division"
      type  = destroyer
      model = 0
    }
    division =
    { id    = { type = 14800 id = 121 }
      name  = "23rd Destroyer Division"
      type  = destroyer
      model = 0
    }
    division =
    { id    = { type = 14800 id = 122 }
      name  = "24th Destroyer Division"
      type  = destroyer
      model = 0
    }
    division =
    { id    = { type = 14800 id = 123 }
      name  = "25th Destroyer Division"
      type  = destroyer
      model = 0
    }
    division =
    { id    = { type = 14800 id = 124 }
      name  = "26th Destroyer Division"
      type  = destroyer
      model = 0
    }
    division =
    { id    = { type = 14800 id = 125 }
      name  = "27th Destroyer Division"
      type  = destroyer
      model = 0
    }
    division =
    { id    = { type = 14800 id = 126 }
      name  = "28th Destroyer Division"
      type  = destroyer
      model = 0
    }
  }
  navalunit =
  { location = 633
    base     = 633
    id       = { type = 14800 id = 127 }
    name     = "Atlantic Submarine Fleet"
    division =
    { id    = { type = 14800 id = 128 }
      name  = "12th Submarine Division"
      type  = submarine
      model = 1
    }
    division =
    { id    = { type = 14800 id = 129 }
      name  = "13th Submarine Division"
      type  = submarine
      model = 1
    }
    division =
    { id    = { type = 14800 id = 130 }
      name  = "14th Submarine Division"
      type  = submarine
      model = 1
    }
    division =
    { id    = { type = 14800 id = 131 }
      name  = "15th Submarine Division"
      type  = submarine
      model = 1
    }
    division =
    { id    = { type = 14800 id = 132 }
      name  = "16th Submarine Division"
      type  = submarine
      model = 2
    }
    division =
    { id    = { type = 14800 id = 133 }
      name  = "17th Submarine Division"
      type  = submarine
      model = 7
    }
  }
  navalunit =
  { location = 633
    base     = 633
    id       = { type = 14800 id = 160 }
    name     = "Atlantic Transport Fleet"
    division =
    { id   = { type = 14800 id = 134 }
      name = "Abner Doubleday Flotilla"
      type = transport
    }
    division =
    { id   = { type = 14800 id = 135 }
      name = "Brigham Young Flotilla"
      type = transport
    }
    division =
    { id   = { type = 14800 id = 136 }
      name = "William B. Travis Flotilla"
      type = transport
    }
    division =
    { id   = { type = 14800 id = 137 }
      name = "Peter Stuyvesant Flotilla"
      type = transport
    }
    division =
    { id   = { type = 14800 id = 138 }
      name = "Henry L. Benning Flotilla"
      type = transport
    }
    division =
    { id   = { type = 14800 id = 139 }
      name = "Casimir Pulaski Flotilla"
      type = transport
    }
    division =
    { id   = { type = 14800 id = 140 }
      name = "Sam Houston Flotilla"
      type = transport
    }
    division =
    { id   = { type = 14800 id = 141 }
      name = "Francis Scott Key Flotilla"
      type = transport
    }
    division =
    { id   = { type = 14800 id = 142 }
      name = "Walter Reed Flotilla"
      type = transport
    }
    division =
    { id   = { type = 14800 id = 143 }
      name = "Dolly Madison Flotilla"
      type = transport
    }
    division =
    { id   = { type = 14800 id = 144 }
      name = "Frederick Douglass Flotilla"
      type = transport
    }
    division =
    { id   = { type = 14800 id = 145 }
      name = "Clara Barton Flotilla"
      type = transport
    }
  }
  navalunit =
  { location = 761
    base     = 761
    id       = { type = 14800 id = 146 }
    name     = "Pacific Transport Fleet"
    division =
    { id   = { type = 14800 id = 147 }
      name = "Charles Goodyear Flotilla"
      type = transport
    }
    division =
    { id   = { type = 14800 id = 148 }
      name = "Anthony Wayne Flotilla"
      type = transport
    }
    division =
    { id   = { type = 14800 id = 149 }
      name = "John Hancock Flotilla"
      type = transport
    }
    division =
    { id   = { type = 14800 id = 150 }
      name = "Samuel Dexter Flotilla"
      type = transport
    }
    division =
    { id   = { type = 14800 id = 151 }
      name = "Stephen C. Crane Flotilla"
      type = transport
    }
    division =
    { id   = { type = 14800 id = 152 }
      name = "William McKinley Flotilla"
      type = transport
    }
    division =
    { id   = { type = 14800 id = 153 }
      name = "George A. Custer Flotilla"
      type = transport
    }
    division =
    { id   = { type = 14800 id = 154 }
      name = "August Belmont Flotilla"
      type = transport
    }
    division =
    { id   = { type = 14800 id = 156 }
      name = "Emily Dickinson Flotilla"
      type = transport
    }
    division =
    { id   = { type = 14800 id = 157 }
      name = "Molly Pitcher Flotilla"
      type = transport
    }
    division =
    { id   = { type = 14800 id = 158 }
      name = "Antonin Dvorak Flotilla"
      type = transport
    }
    division =
    { id   = { type = 14800 id = 159 }
      name = "J. E. B. Stuart Flotilla"
      type = transport
    }
  }
 #####################################
	### USA Air OOB ###
 #####################################

airunit = {
	id = { type = 14800 id = 522 }
	name = "1st Wing"
	location = 762 # Los Angeles
	base = 762

	division = {
		id = { type = 14800 id = 501 }
		name = "7th Bombardment Group"
		type = strategic_bomber
		model = 0
		strength = 20
		}
	division = {
		id = { type = 14800 id = 502 }
		name = "19th Bombardment Group"
		type = strategic_bomber
		model = 0
		strength = 20
		}
	division = {
		id = { type = 14800 id = 503 }
		name = "17th Attack Group"
		type = tactical_bomber
		model = 0
		strength = 30
		}
	}

airunit = {
	id = { type = 14800 id = 504 }
	name = "2nd Wing"
	location = 633 # Norfolk
	base = 633

	division = {
		id = { type = 14800 id = 505 }
		name = "2nd Bombardment Group"
		type = strategic_bomber
		model = 0
		strength = 20
		}
	division = {
		id = { type = 14800 id = 506 }
		name = "8th Pursuit Group"
		type = interceptor
		model = 0
		strength = 30
		}
	}

airunit = {
	id = { type = 14800 id = 507 }
	name = "3rd Wing"
	location = 681 # Alexandria, LA
	base = 681

	division = {
		id = { type = 14800 id = 508 }
		name = "3rd Attack Group"
		type = cas
		model = 0
		strength = 30
		}
	division = {
		id = { type = 14800 id = 509 }
		name = "20th Pursuit Group"
		type = interceptor
		model = 0
		strength = 30
		}
	}

airunit = {
	id = { type = 14800 id = 510 }
	name = "18th Composite Wing"
	location = 663 # Pearl Harbor
	base = 663

	division = {
		id = { type = 14800 id = 511 }
		name = "5th Composite Group"
		type = tactical_bomber
		model = 0
		strength = 20
		}
	division = {
		id = { type = 14800 id = 512 }
		name = "18th Pursuit Group"
		type = interceptor
		model = 0
		strength = 20
		}
	}

airunit = {
	id = { type = 14800 id = 513 }
	name = "19th Composite Wing"
	location = 889 # Canal Zone
	base = 889

	division = {
		id = { type = 14800 id = 514 }
		name = "6th Composite Group" # Albrook
		type = tactical_bomber 
		model = 0
		strength = 10
		}
	division = {
		id = { type = 14800 id = 515 }
		name = "16th Pursuit Group" # Albrook
		type = interceptor
		model = 0
		strength = 20
		}
	}

airunit = {
	id = { type = 14800 id = 516 }
	name = "1st Pursuit Group"
	location = 616 # Detroit
	base = 616

	division = {
		id = { type = 14800 id = 517 }
		name = "1st Pursuit Group"
		type = interceptor
		model = 0
		strength = 30
		}
	}

airunit = {
	id = { type = 14800 id = 518 }
	name = "4th Composite Group"
	location = 1737 # Manila
	base = 1737
	

	division = {
		id = { type = 14800 id = 519 }
		name = "4th Composite Group"
		type = cas
		model = 0
		strength = 20
		}
	}

airunit = {
	id = { type = 14800 id = 520 }
	name = "9th Bombardment Group"
	location = 602 # New York
	base = 602

	division = {
		id = { type = 14800 id = 521 }
		name = "9th Bombardment Group"
		type = strategic_bomber
		model = 0
		strength = 20
		}
	}

 ######################################
	### Development ###
 ###################################### 
	division_development = { 
		id = { type = 14800 id = 295 } 
		name = "USS Enterprise" 
		progress = 0.0000 
		location = 606 
		cost = 5.8959 
		date = { 
			year = 1940 
			month = november 
			day = 4 
			hour = 0 
			} 
		manpower = 2.3000 
		close_when_finished = yes 
		waitingforclosure = no 
		retooling_time = 80.0000 
		total_progress = 0.0000 
		size = 3 
		done = 0 
		days = 1664 
		days_for_first = 584 
		gearing_bonus = 0.0000 
		type = carrier 
		extra = cag 
		extra1 = naval_anti_air_l 
		extra2 = none 
		extra3 = none 
		extra4 = none 
		model = 2 
		brigade_model = 2 
		brigade_model1 = 1 
		brigade_model2 = 0 
		brigade_model3 = 0 
		brigade_model4 = 0 
		} 
	division_development = { 
		id = { type = 14800 id = 161 } 
		name = "USS Yorktown" 
		progress = 0.0000 
		location = 0 
		cost = 5.8959 
		date = { 
			year = 1939 
			month = july 
			day = 16 
			hour = 0 
			} 
		manpower = 2.3000 
		close_when_finished = yes 
		waitingforclosure = no 
		total_progress = 0.8612 # 0.4797
		size = 3 
		done = 0 
		days = 1 
		days_for_first = 642 
		gearing_bonus = 0.0000 
		type = carrier 
		extra = cag 
		extra1 = naval_anti_air_l 
		extra2 = none 
		extra3 = none 
		extra4 = none 
		model = 2 
		brigade_model = 2 
		brigade_model1 = 1 
		brigade_model2 = 0 
		brigade_model3 = 0 
		brigade_model4 = 0 
		} 
	brigade_development = { 
		id = { type = 14800 id = 268 } 
		name = "36' AA" 
		progress = 0.0000 
		location = 606 
		cost = 0.6400 
		date = { 
			year = 1940 
			month = december 
			day = 15 
			hour = 0 
			} 
		manpower = 0.1000 
		close_when_finished = yes 
		waitingforclosure = no 
		retooling_time = 44.0000 
		total_progress = 0.0000 
		size = 30 
		done = 0 
		days = 1741 
		days_for_first = 76 
		gearing_bonus = 0.0000 
		type = naval_anti_air_s 
		model = 1 
		} 
	brigade_development = { 
		id = { type = 14800 id = 274 } 
		name = "36' Spotter" 
		progress = 0.0000 
		location = 606 
		cost = 0.6000 
		date = { 
			year = 1938 
			month = august 
			day = 21 
			hour = 0 
			} 
		manpower = 0.1000 
		close_when_finished = yes 
		waitingforclosure = no 
		retooling_time = 44.0000 
		total_progress = 0.0000 
		size = 17 
		done = 0 
		days = 908 
		days_for_first = 68 
		gearing_bonus = 0.0000 
		type = naval_spotter_s 
		model = 2 
		} 
	brigade_development = { 
		id = { type = 14800 id = 279 } 
		name = "36' Capital AA" 
		progress = 0.0000 
		location = 606 
		cost = 0.8000 
		date = { 
			year = 1936 
			month = october 
			day = 10 
			hour = 0 
			} 
		manpower = 0.1000 
		close_when_finished = yes 
		waitingforclosure = no 
		retooling_time = 44.0000 
		total_progress = 0.0000 
		size = 4 
		done = 0 
		days = 237 
		days_for_first = 64 
		gearing_bonus = 0.0000 
		type = naval_anti_air_l 
		model = 1 
		} 
	division_development = { 
		id = { type = 14800 id = 280 } 
		name = "1st 'Big Red One' Division" 
		progress = 0.0000 
		location = 606 
		cost = 7.9886 
		date = { 
			year = 1940 
			month = june 
			day = 15 
			hour = 0 
			} 
		manpower = 15.0000 
		close_when_finished = yes 
		waitingforclosure = no 
		retooling_time = 88.0000 
		total_progress = 0.0000 
		size = 26 
		done = 0 
		days = 1300 
		days_for_first = 76 
		gearing_bonus = 0.0000 
		type = infantry 
		extra = anti_tank 
		extra1 = none 
		extra2 = none 
		extra3 = none 
		extra4 = none 
		model = 0 
		brigade_model = 0 
		brigade_model1 = 0 
		brigade_model2 = 0 
		brigade_model3 = 0 
		brigade_model4 = 0 
		} 
	division_development = { 
		id = { type = 14800 id = 277 } 
		name = "1st Armored 'Old Ironsides' Div." 
		progress = 0.0000 
		location = 606 
		cost = 14.2029 
		date = { 
			year = 1939 
			month = december 
			day = 2 
			hour = 0 
			} 
		manpower = 13.0000 
		close_when_finished = yes 
		waitingforclosure = no 
		retooling_time = 88.0000 
		total_progress = 0.0000 
		size = 12 
		done = 0 
		days = 1461 
		days_for_first = 137 
		gearing_bonus = 0.0000 
		type = armor 
		extra = engineer 
		extra1 = none 
		extra2 = none 
		extra3 = none 
		extra4 = none 
		model = 0 
		brigade_model = 0 
		brigade_model1 = 0 
		brigade_model2 = 0 
		brigade_model3 = 0 
		brigade_model4 = 0 
		} 
	province_development = { 
		id = { type = 14800 id = 184 } 
		name = "" 
		progress = 0.0000 
		location = 602 
		cost = 2.0000 
		date = { 
			year = 1939 
			month = september 
			day = 17 
			hour = 0 
			} 
		manpower = 0.1000 
		close_when_finished = yes 
		waitingforclosure = no 
		total_progress = 0.0000 
		size = 20 
		done = 0 
		days = 1344 
		days_for_first = 86 
		gearing_bonus = 0.0000 
		type = infrastructure 
		} 
	province_development = { 
		id = { type = 14800 id = 187 } 
		name = "" 
		progress = 0.0000 
		location = 620 
		cost = 2.0000 
		date = { 
			year = 1940 
			month = june 
			day = 0 
			hour = 0 
			} 
		manpower = 0.1000 
		close_when_finished = yes 
		waitingforclosure = no 
		total_progress = 0.0000 
		size = 24 
		done = 0 
		days = 1598 
		days_for_first = 86 
		gearing_bonus = 0.0000 
		type = infrastructure 
		} 
	province_development = { 
		id = { type = 14800 id = 192 } 
		name = "" 
		progress = 0.0000 
		location = 606 
		cost = 2.0000 
		date = { 
			year = 1939 
			month = september 
			day = 17 
			hour = 0 
			} 
		manpower = 0.1000 
		close_when_finished = yes 
		waitingforclosure = no 
		total_progress = 0.0000 
		size = 20 
		done = 0 
		days = 1344 
		days_for_first = 86 
		gearing_bonus = 0.0000 
		type = infrastructure 
		} 
	province_development = { 
		id = { type = 14800 id = 238 } 
		name = "" 
		progress = 0.0000 
		location = 613 
		cost = 2.0000 
		date = { 
			year = 1939 
			month = september 
			day = 17 
			hour = 0 
			} 
		manpower = 0.1000 
		close_when_finished = yes 
		waitingforclosure = no 
		total_progress = 0.0000 
		size = 20 
		done = 0 
		days = 1344 
		days_for_first = 86 
		gearing_bonus = 0.0000 
		type = infrastructure 
		} 
	province_development = { 
		id = { type = 14800 id = 288 } 
		name = "" 
		progress = 0.0000 
		location = 694 
		cost = 2.0000 
		date = { 
			year = 1940 
			month = june 
			day = 0 
			hour = 0 
			} 
		manpower = 0.1000 
		close_when_finished = yes 
		waitingforclosure = no 
		total_progress = 0.0000 
		size = 24 
		done = 0 
		days = 1598 
		days_for_first = 86 
		gearing_bonus = 0.0000 
		type = infrastructure 
		} 
	province_development = { 
		id = { type = 14800 id = 287 } 
		name = "" 
		progress = 0.0000 
		location = 727 
		cost = 2.0000 
		date = { 
			year = 1941 
			month = february 
			day = 14 
			hour = 0 
			} 
		manpower = 0.1000 
		close_when_finished = yes 
		waitingforclosure = no 
		total_progress = 0.0000 
		size = 28 
		done = 0 
		days = 1853 
		days_for_first = 86 
		gearing_bonus = 0.0000 
		type = infrastructure 
		} 
	province_development = { 
		id = { type = 14800 id = 290 } 
		name = "" 
		progress = 0.0000 
		location = 622 
		cost = 2.0000 
		date = { 
			year = 1940 
			month = june 
			day = 0 
			hour = 0 
			} 
		manpower = 0.1000 
		close_when_finished = yes 
		waitingforclosure = no 
		total_progress = 0.0000 
		size = 24 
		done = 0 
		days = 1598 
		days_for_first = 86 
		gearing_bonus = 0.0000 
		type = infrastructure 
		} 
	province_development = { 
		id = { type = 14800 id = 289 } 
		name = "" 
		progress = 0.0000 
		location = 684 
		cost = 2.0000 
		date = { 
			year = 1940 
			month = june 
			day = 0 
			hour = 0 
			} 
		manpower = 0.1000 
		close_when_finished = yes 
		waitingforclosure = no 
		total_progress = 0.0000 
		size = 24 
		done = 0 
		days = 1598 
		days_for_first = 86 
		gearing_bonus = 0.0000 
		type = infrastructure 
		} 
	province_development = { 
		id = { type = 14800 id = 190 } 
		name = "" 
		progress = 0.0000 
		location = 615 
		cost = 2.0000 
		date = { 
			year = 1940 
			month = june 
			day = 0 
			hour = 0 
			} 
		manpower = 0.1000 
		close_when_finished = yes 
		waitingforclosure = no 
		total_progress = 0.0000 
		size = 24 
		done = 0 
		days = 1598 
		days_for_first = 86 
		gearing_bonus = 0.0000 
		type = infrastructure 
		} 
	province_development = { 
		id = { type = 14800 id = 291 } 
		name = "" 
		progress = 0.0000 
		location = 790 
		cost = 2.0000 
		date = { 
			year = 1940 
			month = june 
			day = 0 
			hour = 0 
			} 
		manpower = 0.1000 
		close_when_finished = yes 
		waitingforclosure = no 
		total_progress = 0.0000 
		size = 24 
		done = 0 
		days = 1598 
		days_for_first = 86 
		gearing_bonus = 0.0000 
		type = infrastructure 
		} 
	province_development = { 
		id = { type = 14800 id = 263 } 
		name = "" 
		progress = 0.0000 
		location = 642 
		cost = 2.0000 
		date = { 
			year = 1940 
			month = june 
			day = 0 
			hour = 0 
			} 
		manpower = 0.1000 
		close_when_finished = yes 
		waitingforclosure = no 
		total_progress = 0.0000 
		size = 24 
		done = 0 
		days = 1598 
		days_for_first = 86 
		gearing_bonus = 0.0000 
		type = infrastructure 
		} 
	province_development = { 
		id = { type = 14800 id = 264 } 
		name = "" 
		progress = 0.0000 
		location = 625 
		cost = 2.0000 
		date = { 
			year = 1940 
			month = june 
			day = 0 
			hour = 0 
			} 
		manpower = 0.1000 
		close_when_finished = yes 
		waitingforclosure = no 
		total_progress = 0.0000 
		size = 24 
		done = 0 
		days = 1598 
		days_for_first = 86 
		gearing_bonus = 0.0000 
		type = infrastructure 
		} 
	province_development = { 
		id = { type = 14800 id = 267 } 
		name = "" 
		progress = 0.0000 
		location = 629 
		cost = 2.0000 
		date = { 
			year = 1941 
			month = february 
			day = 14 
			hour = 0 
			} 
		manpower = 0.1000 
		close_when_finished = yes 
		waitingforclosure = no 
		total_progress = 0.0000 
		size = 28 
		done = 0 
		days = 1853 
		days_for_first = 86 
		gearing_bonus = 0.0000 
		type = infrastructure 
		} 
	province_development = { 
		id = { type = 14800 id = 186 } 
		name = "" 
		progress = 0.0000 
		location = 608 
		cost = 2.0000 
		date = { 
			year = 1939 
			month = september 
			day = 17 
			hour = 0 
			} 
		manpower = 0.1000 
		close_when_finished = yes 
		waitingforclosure = no 
		total_progress = 0.0000 
		size = 20 
		done = 0 
		days = 1344 
		days_for_first = 86 
		gearing_bonus = 0.0000 
		type = infrastructure 
		} 
	province_development = { 
		id = { type = 14800 id = 185 } 
		name = "" 
		progress = 0.0000 
		location = 603 
		cost = 2.0000 
		date = { 
			year = 1939 
			month = september 
			day = 17 
			hour = 0 
			} 
		manpower = 0.1000 
		close_when_finished = yes 
		waitingforclosure = no 
		total_progress = 0.0000 
		size = 20 
		done = 0 
		days = 1344 
		days_for_first = 86 
		gearing_bonus = 0.0000 
		type = infrastructure 
		} 
	province_development = { 
		id = { type = 14800 id = 189 } 
		name = "" 
		progress = 0.0000 
		location = 616 
		cost = 2.0000 
		date = { 
			year = 1940 
			month = june 
			day = 0 
			hour = 0 
			} 
		manpower = 0.1000 
		close_when_finished = yes 
		waitingforclosure = no 
		total_progress = 0.0000 
		size = 24 
		done = 0 
		days = 1598 
		days_for_first = 86 
		gearing_bonus = 0.0000 
		type = infrastructure 
		} 
	province_development = { 
		id = { type = 14800 id = 191 } 
		name = "" 
		progress = 0.0000 
		location = 628 
		cost = 2.0000 
		date = { 
			year = 1940 
			month = june 
			day = 0 
			hour = 0 
			} 
		manpower = 0.1000 
		close_when_finished = yes 
		waitingforclosure = no 
		total_progress = 0.0000 
		size = 24 
		done = 0 
		days = 1598 
		days_for_first = 86 
		gearing_bonus = 0.0000 
		type = infrastructure 
		} 
	province_development = { 
		id = { type = 14800 id = 202 } 
		name = "" 
		progress = 0.0000 
		location = 716 
		cost = 2.0000 
		date = { 
			year = 1940 
			month = june 
			day = 0 
			hour = 0 
			} 
		manpower = 0.1000 
		close_when_finished = yes 
		waitingforclosure = no 
		total_progress = 0.0000 
		size = 24 
		done = 0 
		days = 1598 
		days_for_first = 86 
		gearing_bonus = 0.0000 
		type = infrastructure 
		} 
	province_development = { 
		id = { type = 14800 id = 205 } 
		name = "" 
		progress = 0.0000 
		location = 609 
		cost = 2.0000 
		date = { 
			year = 1940 
			month = june 
			day = 0 
			hour = 0 
			} 
		manpower = 0.1000 
		close_when_finished = yes 
		waitingforclosure = no 
		total_progress = 0.0000 
		size = 24 
		done = 0 
		days = 1598 
		days_for_first = 86 
		gearing_bonus = 0.0000 
		type = infrastructure 
		} 
	province_development = { 
		id = { type = 14800 id = 214 } 
		name = "" 
		progress = 0.0000 
		location = 672 
		cost = 2.0000 
		date = { 
			year = 1940 
			month = june 
			day = 0 
			hour = 0 
			} 
		manpower = 0.1000 
		close_when_finished = yes 
		waitingforclosure = no 
		total_progress = 0.0000 
		size = 24 
		done = 0 
		days = 1598 
		days_for_first = 86 
		gearing_bonus = 0.0000 
		type = infrastructure 
		} 
	province_development = { 
		id = { type = 14800 id = 234 } 
		name = "" 
		progress = 0.0000 
		location = 649 
		cost = 2.0000 
		date = { 
			year = 1940 
			month = june 
			day = 0 
			hour = 0 
			} 
		manpower = 0.1000 
		close_when_finished = yes 
		waitingforclosure = no 
		total_progress = 0.0000 
		size = 24 
		done = 0 
		days = 1598 
		days_for_first = 86 
		gearing_bonus = 0.0000 
		type = infrastructure 
		} 
	province_development = { 
		id = { type = 14800 id = 235 } 
		name = "" 
		progress = 0.0000 
		location = 677 
		cost = 2.0000 
		date = { 
			year = 1940 
			month = june 
			day = 0 
			hour = 0 
			} 
		manpower = 0.1000 
		close_when_finished = yes 
		waitingforclosure = no 
		total_progress = 0.0000 
		size = 24 
		done = 0 
		days = 1598 
		days_for_first = 86 
		gearing_bonus = 0.0000 
		type = infrastructure 
		} 
	province_development = { 
		id = { type = 14800 id = 246 } 
		name = "" 
		progress = 0.0000 
		location = 721 
		cost = 2.0000 
		date = { 
			year = 1940 
			month = june 
			day = 0 
			hour = 0 
			} 
		manpower = 0.1000 
		close_when_finished = yes 
		waitingforclosure = no 
		total_progress = 0.0000 
		size = 24 
		done = 0 
		days = 1598 
		days_for_first = 86 
		gearing_bonus = 0.0000 
		type = infrastructure 
		} 
	province_development = { 
		id = { type = 14800 id = 247 } 
		name = "" 
		progress = 0.0000 
		location = 722 
		cost = 2.0000 
		date = { 
			year = 1941 
			month = february 
			day = 14 
			hour = 0 
			} 
		manpower = 0.1000 
		close_when_finished = yes 
		waitingforclosure = no 
		total_progress = 0.0000 
		size = 28 
		done = 0 
		days = 1853 
		days_for_first = 86 
		gearing_bonus = 0.0000 
		type = infrastructure 
		} 
	province_development = { 
		id = { type = 14800 id = 270 } 
		name = "" 
		progress = 0.0000 
		location = 600 
		cost = 2.0000 
		date = { 
			year = 1939 
			month = september 
			day = 17 
			hour = 0 
			} 
		manpower = 0.1000 
		close_when_finished = yes 
		waitingforclosure = no 
		total_progress = 0.0000 
		size = 20 
		done = 0 
		days = 1344 
		days_for_first = 86 
		gearing_bonus = 0.0000 
		type = infrastructure 
		} 
	province_development = { 
		id = { type = 14800 id = 275 } 
		name = "" 
		progress = 0.0000 
		location = 621 
		cost = 2.0000 
		date = { 
			year = 1940 
			month = june 
			day = 0 
			hour = 0 
			} 
		manpower = 0.1000 
		close_when_finished = yes 
		waitingforclosure = no 
		total_progress = 0.0000 
		size = 24 
		done = 0 
		days = 1598 
		days_for_first = 86 
		gearing_bonus = 0.0000 
		type = infrastructure 
		} 
	province_development = { 
		id = { type = 14800 id = 276 } 
		name = "" 
		progress = 0.0000 
		location = 693 
		cost = 2.0000 
		date = { 
			year = 1940 
			month = june 
			day = 0 
			hour = 0 
			} 
		manpower = 0.1000 
		close_when_finished = yes 
		waitingforclosure = no 
		total_progress = 0.0000 
		size = 24 
		done = 0 
		days = 1598 
		days_for_first = 86 
		gearing_bonus = 0.0000 
		type = infrastructure 
		} 
	province_development = { 
		id = { type = 14800 id = 278 } 
		name = "" 
		progress = 0.0000 
		location = 762 
		cost = 2.0000 
		date = { 
			year = 1940 
			month = june 
			day = 0 
			hour = 0 
			} 
		manpower = 0.1000 
		close_when_finished = yes 
		waitingforclosure = no 
		total_progress = 0.0000 
		size = 24 
		done = 0 
		days = 1598 
		days_for_first = 86 
		gearing_bonus = 0.0000 
		type = infrastructure 
		} 
	province_development = { 
		id = { type = 14800 id = 283 } 
		name = "" 
		progress = 0.0000 
		location = 601 
		cost = 2.0000 
		date = { 
			year = 1940 
			month = june 
			day = 0 
			hour = 0 
			} 
		manpower = 0.1000 
		close_when_finished = yes 
		waitingforclosure = no 
		total_progress = 0.0000 
		size = 24 
		done = 0 
		days = 1598 
		days_for_first = 86 
		gearing_bonus = 0.0000 
		type = infrastructure 
		} 
	province_development = { 
		id = { type = 14800 id = 285 } 
		name = "" 
		progress = 0.0000 
		location = 715 
		cost = 2.0000 
		date = { 
			year = 1940 
			month = june 
			day = 0 
			hour = 0 
			} 
		manpower = 0.1000 
		close_when_finished = yes 
		waitingforclosure = no 
		total_progress = 0.0000 
		size = 24 
		done = 0 
		days = 1598 
		days_for_first = 86 
		gearing_bonus = 0.0000 
		type = infrastructure 
		} 
	province_development = { 
		id = { type = 14800 id = 292 } 
		name = "" 
		progress = 0.0000 
		location = 746 
		cost = 2.0000 
		date = { 
			year = 1940 
			month = june 
			day = 0 
			hour = 0 
			} 
		manpower = 0.1000 
		close_when_finished = yes 
		waitingforclosure = no 
		total_progress = 0.0000 
		size = 24 
		done = 0 
		days = 1598 
		days_for_first = 86 
		gearing_bonus = 0.0000 
		type = infrastructure 
		} 
	province_development = { 
		id = { type = 14800 id = 293 } 
		name = "" 
		progress = 0.0000 
		location = 719 
		cost = 2.0000 
		date = { 
			year = 1940 
			month = june 
			day = 0 
			hour = 0 
			} 
		manpower = 0.1000 
		close_when_finished = yes 
		waitingforclosure = no 
		total_progress = 0.0000 
		size = 24 
		done = 0 
		days = 1598 
		days_for_first = 86 
		gearing_bonus = 0.0000 
		type = infrastructure 
		} 
	province_development = { 
		id = { type = 14800 id = 258 } 
		name = "" 
		progress = 0.0000 
		location = 614 
		cost = 2.0000 
		date = { 
			year = 1939 
			month = september 
			day = 17 
			hour = 0 
			} 
		manpower = 0.1000 
		close_when_finished = yes 
		waitingforclosure = no 
		total_progress = 0.0000 
		size = 20 
		done = 0 
		days = 1344 
		days_for_first = 86 
		gearing_bonus = 0.0000 
		type = infrastructure 
		} 
	province_development = { 
		id = { type = 14800 id = 259 } 
		name = "" 
		progress = 0.0000 
		location = 689 
		cost = 2.0000 
		date = { 
			year = 1940 
			month = june 
			day = 0 
			hour = 0 
			} 
		manpower = 0.1000 
		close_when_finished = yes 
		waitingforclosure = no 
		total_progress = 0.0000 
		size = 24 
		done = 0 
		days = 1598 
		days_for_first = 86 
		gearing_bonus = 0.0000 
		type = infrastructure 
		} 
	province_development = { 
		id = { type = 14800 id = 260 } 
		name = "" 
		progress = 0.0000 
		location = 607 
		cost = 2.0000 
		date = { 
			year = 1939 
			month = september 
			day = 17 
			hour = 0 
			} 
		manpower = 0.1000 
		close_when_finished = yes 
		waitingforclosure = no 
		total_progress = 0.0000 
		size = 20 
		done = 0 
		days = 1344 
		days_for_first = 86 
		gearing_bonus = 0.0000 
		type = infrastructure 
		} 
	province_development = { 
		id = { type = 14800 id = 261 } 
		name = "" 
		progress = 0.0000 
		location = 690 
		cost = 2.0000 
		date = { 
			year = 1940 
			month = june 
			day = 0 
			hour = 0 
			} 
		manpower = 0.1000 
		close_when_finished = yes 
		waitingforclosure = no 
		total_progress = 0.0000 
		size = 24 
		done = 0 
		days = 1598 
		days_for_first = 86 
		gearing_bonus = 0.0000 
		type = infrastructure 
		} 
	province_development = { 
		id = { type = 14800 id = 262 } 
		name = "" 
		progress = 0.0000 
		location = 619 
		cost = 2.0000 
		date = { 
			year = 1940 
			month = june 
			day = 0 
			hour = 0 
			} 
		manpower = 0.1000 
		close_when_finished = yes 
		waitingforclosure = no 
		total_progress = 0.0000 
		size = 24 
		done = 0 
		days = 1598 
		days_for_first = 86 
		gearing_bonus = 0.0000 
		type = infrastructure 
		} 
	province_development = { 
		id = { type = 14800 id = 265 } 
		name = "" 
		progress = 0.0000 
		location = 641 
		cost = 2.0000 
		date = { 
			year = 1940 
			month = june 
			day = 0 
			hour = 0 
			} 
		manpower = 0.1000 
		close_when_finished = yes 
		waitingforclosure = no 
		total_progress = 0.0000 
		size = 24 
		done = 0 
		days = 1535 
		days_for_first = 86 
		gearing_bonus = 0.0000 
		type = infrastructure 
		} 
	province_development = { 
		id = { type = 14800 id = 266 } 
		name = "" 
		progress = 0.0000 
		location = 640 
		cost = 2.0000 
		date = { 
			year = 1940 
			month = june 
			day = 0 
			hour = 0 
			} 
		manpower = 0.1000 
		close_when_finished = yes 
		waitingforclosure = no 
		total_progress = 0.0000 
		size = 24 
		done = 0 
		days = 1535 
		days_for_first = 86 
		gearing_bonus = 0.0000 
		type = infrastructure 
		} 
	province_development = { 
		id = { type = 14800 id = 273 } 
		name = "" 
		progress = 0.0000 
		location = 630 
		cost = 2.0000 
		date = { 
			year = 1941 
			month = february 
			day = 14 
			hour = 0 
			} 
		manpower = 0.1000 
		close_when_finished = yes 
		waitingforclosure = no 
		total_progress = 0.0000 
		size = 28 
		done = 0 
		days = 1853 
		days_for_first = 86 
		gearing_bonus = 0.0000 
		type = infrastructure 
		} 
	province_development = { 
		id = { type = 14800 id = 272 } 
		name = "" 
		progress = 0.0000 
		location = 639 
		cost = 2.0000 
		date = { 
			year = 1941 
			month = february 
			day = 14 
			hour = 0 
			} 
		manpower = 0.1000 
		close_when_finished = yes 
		waitingforclosure = no 
		total_progress = 0.0000 
		size = 28 
		done = 0 
		days = 1853 
		days_for_first = 86 
		gearing_bonus = 0.0000 
		type = infrastructure 
		} 
	province_development = { 
		id = { type = 14800 id = 271 } 
		name = "" 
		progress = 0.0000 
		location = 763 
		cost = 2.0000 
		date = { 
			year = 1940 
			month = june 
			day = 0 
			hour = 0 
			} 
		manpower = 0.1000 
		close_when_finished = yes 
		waitingforclosure = no 
		total_progress = 0.0000 
		size = 24 
		done = 0 
		days = 1535 
		days_for_first = 86 
		gearing_bonus = 0.0000 
		type = infrastructure 
		} 
	province_development = { 
		id = { type = 14800 id = 15271 } 
		name = "" 
		progress = 0.0000 
		location = 626 
		cost = 2.0000 
		date = { 
			year = 1940 
			month = june 
			day = 0 
			hour = 0 
			} 
		manpower = 0.1000 
		close_when_finished = yes 
		waitingforclosure = no 
		total_progress = 0.0000 
		size = 24 
		done = 0 
		days = 1535 
		days_for_first = 86 
		gearing_bonus = 0.0000 
		type = infrastructure 
		} 
	province_development = { 
		id = { type = 14800 id = 15272 } 
		name = "" 
		progress = 0.0000 
		location = 793 
		cost = 2.0000 
		date = { 
			year = 1940 
			month = june 
			day = 0 
			hour = 0 
			} 
		manpower = 0.1000 
		close_when_finished = yes 
		waitingforclosure = no 
		total_progress = 0.0000 
		size = 24 
		done = 0 
		days = 1535 
		days_for_first = 86 
		gearing_bonus = 0.0000 
		type = infrastructure 
		} 
	province_development = { 
		id = { type = 14800 id = 15273 } 
		name = "" 
		progress = 0.0000 
		location = 627 
		cost = 2.0000 
		date = { 
			year = 1940 
			month = june 
			day = 0 
			hour = 0 
			} 
		manpower = 0.1000 
		close_when_finished = yes 
		waitingforclosure = no 
		total_progress = 0.0000 
		size = 24 
		done = 0 
		days = 1535 
		days_for_first = 86 
		gearing_bonus = 0.0000 
		type = infrastructure 
		} 
	province_development = { 
		id = { type = 14800 id = 15274 } 
		name = "" 
		progress = 0.0000 
		location = 612 
		cost = 2.0000 
		date = { 
			year = 1939 
			month = september 
			day = 17 
			hour = 0 
			} 
		manpower = 0.1000 
		close_when_finished = yes 
		waitingforclosure = no 
		total_progress = 0.0000 
		size = 20 
		done = 0 
		days = 1535 
		days_for_first = 86 
		gearing_bonus = 0.0000 
		type = infrastructure 
		} 
	province_development = { 
		id = { type = 14800 id = 15275 } 
		name = "" 
		progress = 0.0000 
		location = 792 
		cost = 2.0000 
		date = { 
			year = 1940 
			month = june 
			day = 0 
			hour = 0 
			} 
		manpower = 0.1000 
		close_when_finished = yes 
		waitingforclosure = no 
		total_progress = 0.0000 
		size = 24 
		done = 0 
		days = 1535 
		days_for_first = 86 
		gearing_bonus = 0.0000 
		type = infrastructure 
		} 
	province_development = { 
		id = { type = 14800 id = 15276 } 
		name = "" 
		progress = 0.0000 
		location = 720 
		cost = 2.0000 
		date = { 
			year = 1940 
			month = june 
			day = 0 
			hour = 0 
			} 
		manpower = 0.1000 
		close_when_finished = yes 
		waitingforclosure = no 
		total_progress = 0.0000 
		size = 24 
		done = 0 
		days = 1535 
		days_for_first = 86 
		gearing_bonus = 0.0000 
		type = infrastructure 
		} 
	province_development = { 
		id = { type = 14800 id = 15277 } 
		name = "" 
		progress = 0.0000 
		location = 604 
		cost = 2.0000 
		date = { 
			year = 1939 
			month = september 
			day = 17 
			hour = 0 
			} 
		manpower = 0.1000 
		close_when_finished = yes 
		waitingforclosure = no 
		total_progress = 0.0000 
		size = 20 
		done = 0 
		days = 1535 
		days_for_first = 86 
		gearing_bonus = 0.0000 
		type = infrastructure 
		} 
	province_development = { 
		id = { type = 14800 id = 15278 } 
		name = "" 
		progress = 0.0000 
		location = 611 
		cost = 2.0000 
		date = { 
			year = 1941 
			month = february 
			day = 14 
			hour = 0 
			} 
		manpower = 0.1000 
		close_when_finished = yes 
		waitingforclosure = no 
		total_progress = 0.0000 
		size = 28 
		done = 0 
		days = 1535 
		days_for_first = 86 
		gearing_bonus = 0.0000 
		type = infrastructure 
		} 
	province_development = { 
		id = { type = 14800 id = 15279 } 
		name = "" 
		progress = 0.0000 
		location = 671 
		cost = 2.0000 
		date = { 
			year = 1941 
			month = february 
			day = 14 
			hour = 0 
			} 
		manpower = 0.1000 
		close_when_finished = yes 
		waitingforclosure = no 
		total_progress = 0.0000 
		size = 28 
		done = 0 
		days = 1535 
		days_for_first = 86 
		gearing_bonus = 0.0000 
		type = infrastructure 
		} 
	province_development = { 
		id = { type = 14800 id = 15280 } 
		name = "" 
		progress = 0.0000 
		location = 610 
		cost = 2.0000 
		date = { 
			year = 1940 
			month = june 
			day = 0 
			hour = 0 
			} 
		manpower = 0.1000 
		close_when_finished = yes 
		waitingforclosure = no 
		total_progress = 0.0000 
		size = 24 
		done = 0 
		days = 1535 
		days_for_first = 86 
		gearing_bonus = 0.0000 
		type = infrastructure 
		} 
	province_development = { 
		id = { type = 14800 id = 269 } 
		name = "" 
		progress = 0.0000 
		location = 732 
		cost = 2.0000 
		date = { 
			year = 1941 
			month = february 
			day = 14 
			hour = 0 
			} 
		manpower = 0.1000 
		close_when_finished = yes 
		waitingforclosure = no 
		total_progress = 0.0000 
		size = 28 
		done = 0 
		days = 1853 
		days_for_first = 86 
		gearing_bonus = 0.0000 
		type = infrastructure 
		} 
	division_development = { 
		id = { type = 14800 id = 176 } 
		name = "USS Brooklyn" 
		progress = 0.0000 
		location = 0 
		cost = 4.9707 
		date = { 
			year = 1937 
			month = july 
			day = 22 
			hour = 0 
			} 
		manpower = 1.4000 
		close_when_finished = yes 
		waitingforclosure = no 
		total_progress = 0.7848 # 0.2420
		size = 4 
		done = 0 
		days = 1 
		days_for_first = 193 
		gearing_bonus = 0.0000 
		type = light_cruiser 
		extra = none 
		extra1 = naval_spotter_s 
		extra2 = naval_anti_air_s 
		extra3 = none 
		extra4 = none 
		model = 3 
		brigade_model = 0 
		brigade_model1 = 2 
		brigade_model2 = 1 
		brigade_model3 = 0 
		brigade_model4 = 0 
		} 
	division_development = { 
		id = { type = 14800 id = 181 } 
		name = "USS Savannah" 
		progress = 0.0000 
		location = 0 
		cost = 4.9707 
		date = { 
			year = 1937 
			month = february 
			day = 17 
			hour = 0 
			} 
		manpower = 1.4000 
		close_when_finished = yes 
		waitingforclosure = no 
		total_progress = 0.7409 # 0.3728
		size = 3 
		done = 0 
		days = 1 
		days_for_first = 193 
		gearing_bonus = 0.0000 
		type = light_cruiser 
		extra = none 
		extra1 = naval_spotter_s 
		extra2 = naval_anti_air_s 
		extra3 = none 
		extra4 = none 
		model = 3 
		brigade_model = 0 
		brigade_model1 = 2 
		brigade_model2 = 1 
		brigade_model3 = 0 
		brigade_model4 = 0 
		} 
	division_development = { 
		id = { type = 14800 id = 163 } 
		name = "USS Quincy" 
		progress = 0.0000 
		location = 0 
		cost = 3.7599 
		date = { 
			year = 1936 
			month = november 
			day = 29 
			hour = 0 
			} 
		manpower = 1.3000 
		close_when_finished = yes 
		waitingforclosure = no 
		total_progress = 0.8290 
		size = 2 
		done = 0 
		days = 1 
		days_for_first = 294 
		gearing_bonus = 0.0000 
		type = heavy_cruiser 
		extra = none 
		extra1 = naval_fire_controll_l 
		extra2 = naval_spotter_l 
		extra3 = naval_anti_air_l 
		extra4 = none 
		model = 2 
		brigade_model = 0 
		brigade_model1 = 1 
		brigade_model2 = 2 
		brigade_model3 = 1 
		brigade_model4 = 0 
		} 
	division_development = { 
		id = { type = 14800 id = 172 } 
		name = "USS Vincennes" 
		progress = 0.0000 
		location = 0 
		cost = 3.7599 
		date = { 
			year = 1936 
			month = april 
			day = 17 
			hour = 0 
			} 
		manpower = 1.3000 
		close_when_finished = yes 
		waitingforclosure = no 
		total_progress = 0.6352 
		size = 1 
		done = 0 
		days = 1 
		days_for_first = 294 
		gearing_bonus = 0.0000 
		type = heavy_cruiser 
		extra = none 
		extra1 = naval_fire_controll_l 
		extra2 = naval_spotter_l 
		extra3 = naval_anti_air_l 
		extra4 = none 
		model = 2 
		brigade_model = 0 
		brigade_model1 = 1 
		brigade_model2 = 2 
		brigade_model3 = 1 
		brigade_model4 = 0 
		} 
	division_development = { 
		id = { type = 14800 id = 166 } 
		name = "18th Submarine Division" 
		progress = 0.0000 
		location = 0 
		cost = 1.7600 
		date = { 
			year = 1936 
			month = may 
			day = 1 
			hour = 0 
			} 
		manpower = 0.4000 
		close_when_finished = yes 
		waitingforclosure = no 
		total_progress = 0.1418 
		size = 1 
		done = 0 
		days = 1 
		days_for_first = 141 
		gearing_bonus = 0.0000 
		type = submarine 
		extra = none 
		extra1 = none 
		extra2 = none 
		extra3 = none 
		extra4 = none 
		model = 2 
		brigade_model = 0 
		brigade_model1 = 0 
		brigade_model2 = 0 
		brigade_model3 = 0 
		brigade_model4 = 0 
		} 
	division_development = { 
		id = { type = 14800 id = 165 } 
		name = "29th Destroyer Division" 
		progress = 0.0000 
		location = 0 
		cost = 3.3600 
		date = { 
			year = 1936 
			month = march 
			day = 1 
			hour = 0 
			} 
		manpower = 0.6000 
		close_when_finished = yes 
		waitingforclosure = no 
		total_progress = 0.4190 
		size = 1 
		done = 0 
		days = 1 
		days_for_first = 105 
		gearing_bonus = 0.0000 
		type = destroyer 
		extra = none 
		extra1 = none 
		extra2 = none 
		extra3 = none 
		extra4 = none 
		model = 1 
		brigade_model = 0 
		brigade_model1 = 0 
		brigade_model2 = 0 
		brigade_model3 = 0 
		brigade_model4 = 0 
		} 
	division_development = { 
		id = { type = 14800 id = 164 } 
		name = "4th Destroyer Division" 
		progress = 0.0000 
		location = 0 
		cost = 3.3600 
		date = { 
			year = 1936 
			month = february 
			day = 0 
			hour = 0 
			} 
		manpower = 0.6000 
		close_when_finished = yes 
		waitingforclosure = no 
		total_progress = 0.7048 
		size = 1 
		done = 0 
		days = 1 
		days_for_first = 105 
		gearing_bonus = 0.0000 
		type = destroyer 
		extra = none 
		extra1 = none 
		extra2 = none 
		extra3 = none 
		extra4 = none 
		model = 1 
		brigade_model = 0 
		brigade_model1 = 0 
		brigade_model2 = 0 
		brigade_model3 = 0 
		brigade_model4 = 0 
		}
}