  
###############################
# Victory points distribution #
###############################
## for copying ## province = { id = points = } #  added
province = { id = 1 points = 1 } # Reykjavik added
province = { id = 5 points = 1 } # Scapa Flow added
province = { id = 9 points = 2 } # Glasgow was 5
province = { id = 10 points = 3 } # Edinburgh was 5
province = { id = 12 points = 2 } # Blackpool added
province = { id = 11 points = 8 } # Sunderland was 10
province = { id = 13 points = 4 } # Sheffield added
province = { id = 14 points = 7 } # Liverpool added
province = { id = 15 points = 3 } # Cardiff added
province = { id = 16 points = 5 } # Birmingham
province = { id = 17 points = 1 } # Norwich added
province = { id = 19 points = 16 } # London was 30
province = { id = 20 points = 1 } # Dover added
province = { id = 21 points = 1 } # Portsmouth added
province = { id = 22 points = 1 } # Bristol added
province = { id = 23 points = 1 } # Plymouth added
province = { id = 28 points = 1 } # Belfast was 5
province = { id = 30 points = 3 } # Dublin was 2
province = { id = 31 points = 1 } # Malta was 3
province = { id = 32 points = 2 } # Brest added
province = { id = 33 points = 1 } # Rennes added
province = { id = 35 points = 1 } # Nantes added
province = { id = 36 points = 1 } # Angers added
province = { id = 38 points = 1 } # Cherbourg added
province = { id = 43 points = 1 } # Dunkerque was 2
province = { id = 44 points = 3 } # Lille was 2
province = { id = 45 points = 2 } # Ghent added
province = { id = 46 points = 1 } # Rotterdam added
province = { id = 47 points = 7 } # Amsterdam was 5
province = { id = 49 points = 2 } # Eindhoven added
province = { id = 50 points = 2 } # Antwerp
province = { id = 51 points = 5 } # Brussels was 3
province = { id = 52 points = 1 } # Mons added
province = { id = 56 points = 17 } # Paris was 25
province = { id = 57 points = 1 } # Orleans added
province = { id = 59 points = 1 } # Cholet added
province = { id = 62 points = 1 } # Auxerre added
province = { id = 65 points = 1 } # Namur added
province = { id = 66 points = 1 } # Aachen added 
province = { id = 67 points = 5 } # Essen was 25
province = { id = 68 points = 2 } # Liege added
province = { id = 71 points = 3 } # Luxembourg was 2
province = { id = 72 points = 5 } # Metz added
province = { id = 73 points = 3 } # Strasbourg
province = { id = 74 points = 3 } # Saarbrucken added
province = { id = 75 points = 9 } # Cologne was 10
province = { id = 76 points = 6 } # Dortmund added
province = { id = 77 points = 1 } # Arnhem added
province = { id = 80 points = 1 } # Wilhelmshaven added
province = { id = 81 points = 1 } # Munster added
province = { id = 83 points = 1 } # Schweinfurt added
province = { id = 86 points = 3 } # Hannover was 5
province = { id = 88 points = 1 } # Hamburg was 5
province = { id = 90 points = 2 } # Kiel was 5
province = { id = 93 points = 1 } # Malmö
province = { id = 98 points = 1 } # Göteborg was 2
province = { id = 101 points = 5 } # Stockholm was 4
province = { id = 110 points = 1 } # Bergen added
province = { id = 107 points = 3 } # Oslo was 5
province = { id = 113 points = 1 } # Falun
province = { id = 118 points = 1 } # Trondheim
province = { id = 125 points = 1 } # Narvik was 5
province = { id = 126 points = 5 } # Kiruna added
province = { id = 132 points = 1 } # Petsano added
province = { id = 133 points = 2 } # Murmansk was 5
province = { id = 137 points = 1 } # Oulu added
province = { id = 141 points = 1 } # Turku
province = { id = 142 points = 5 } # Helsinki was 3
province = { id = 154 points = 1 } # Archangelsk was 5
province = { id = 163 points = 1 } # Stalingrad was 30
province = { id = 168 points = 1 } # Gorkij added
province = { id = 175 points = 15 } # Moscow was 50
province = { id = 187 points = 3 } # Leningrad was 30
province = { id = 194 points = 2 } # Tallinn was 2
province = { id = 197 points = 2 } # Riga was 2
province = { id = 200 points = 1 } # Pskov added
province = { id = 207 points = 2 } # Kaunas was 2
province = { id = 212 points = 1 } # Minsk added
province = { id = 217 points = 1 } # Vitebsk was 2
province = { id = 220 points = 1 } # Mogilev added
province = { id = 228 points = 1 } # Vinnitsa added
province = { id = 233 points = 1 } # Odessa was 2
province = { id = 235 points = 1 } # Dnepropetovsk added
province = { id = 236 points = 4 } # Krivoy Rog added
province = { id = 238 points = 2 } # Kiev was 5
province = { id = 243 points = 1 } # Kursk added
province = { id = 246 points = 2 } # Zaporozhye added
province = { id = 247 points = 1 } # Belgorod added
province = { id = 248 points = 1 } # Kharkov
province = { id = 249 points = 3 } # Stalino added
province = { id = 253 points = 2 } # Sevastopol
province = { id = 256 points = 1 } # Krasnodar
province = { id = 258 points = 1 } # Rostov was 2
province = { id = 278 points = 1 } # Tula
province = { id = 292 points = 1 } # Aalborg added
province = { id = 294 points = 6 } # Copenhagen was 1
province = { id = 296 points = 1 } # Rostock added
province = { id = 298 points = 1 } # Magdeburg added
province = { id = 300 points = 18 } # Berlin was 30
province = { id = 302 points = 1 } # Stettin added
province = { id = 303 points = 1 } # Danzig was 2
province = { id = 310 points = 4 } # Leipzig was 5
province = { id = 311 points = 4 } # Dresden was 5
province = { id = 312 points = 2 } # Nuremberg was 5
province = { id = 313 points = 2 } # Frankfurt added
province = { id = 314 points = 5 } # Stuttgart
province = { id = 316 points = 1 } # Mulhouse was 7
province = { id = 318 points = 1 } # Dijon added
province = { id = 319 points = 1 } # Chalon-sur-Chaone
province = { id = 323 points = 1 } # La Rochelle added
province = { id = 325 points = 2 } # Bordeaux was 7
province = { id = 332 points = 1 } # Oviedo
province = { id = 334 points = 1 } # La Coruña
province = { id = 335 points = 1 } # Oporto
province = { id = 336 points = 3 } # Lissabon
province = { id = 339 points = 1 } # Valladolid
province = { id = 341 points = 4 } # Madrid was 3
province = { id = 345 points = 1 } # Faro
province = { id = 346 points = 1 } # Huelva
province = { id = 347 points = 2 } # Seville
province = { id = 348 points = 6 } # Gibraltar was 7
province = { id = 351 points = 1 } # Jaen added
province = { id = 354 points = 1 } # València
province = { id = 356 points = 1 } # Tarragona
province = { id = 357 points = 1 } # Barcelona
province = { id = 358 points = 1 } # Perpignan
province = { id = 359 points = 1 } # Toulouse was 7
province = { id = 363 points = 1 } # Nimes
province = { id = 364 points = 3 } # Marseille was 7
province = { id = 365 points = 1 } # Toulon added
province = { id = 368 points = 2 } # Genoa was 7
province = { id = 369 points = 1 } # La Spezia added
province = { id = 370 points = 6 } # Milan was 7
province = { id = 376 points = 1 } # Munich was 10
province = { id = 377 points = 1 } # Innsbruck was 2
province = { id = 378 points = 6 } # Venice was 7
province = { id = 380 points = 1 } # Ljubljana
province = { id = 382 points = 1 } # Zagreb
province = { id = 384 points = 1 } # Split
province = { id = 386 points = 1 } # Sarajevo
province = { id = 389 points = 1 } # Podogrica added
province = { id = 390 points = 1 } # Tirana
province = { id = 401 points = 5 } # Athens was 1
province = { id = 403 points = 1 } # Larisa
province = { id = 409 points = 4 } # Istanbul
province = { id = 411 points = 1 } # Salonika
province = { id = 415 points = 1 } # Pristina added
province = { id = 417 points = 6 } # Sofia was 1
province = { id = 420 points = 1 } # Pleven added
province = { id = 421 points = 1 } # Plovdiv
province = { id = 422 points = 2 } # Varna was 1 
province = { id = 423 points = 1 } # Constanta added
province = { id = 424 points = 5 } # Bucharest was 2
province = { id = 428 points = 1 } # Cluj-Napoca
province = { id = 431 points = 3 } # Ploesti was 5
province = { id = 433 points = 1 } # Iasi added
province = { id = 439 points = 1 } # Izmit
province = { id = 444 points = 1 } # Cyprus
province = { id = 446 points = 1 } # Kayseri
province = { id = 448 points = 3 } # Ankara was 2
province = { id = 453 points = 6 } # Belgrade was 2
province = { id = 456 points = 1 } # Pecs was 2
province = { id = 457 points = 7 } # Budapest was 2
province = { id = 458 points = 2 } # Gyor added
province = { id = 460 points = 1 } # Graz was 2
province = { id = 463 points = 6 } # Vienna
province = { id = 469 points = 3 } # Prague was 6
province = { id = 470 points = 2 } # Pilsen was 1
province = { id = 471 points = 1 } # Usti added
province = { id = 473 points = 4 } # Breslau added
province = { id = 474 points = 2 } # Ostrava added
province = { id = 475 points = 1 } # Brno added
province = { id = 476 points = 5 } # Bratislava was 4
province = { id = 479 points = 3 } # Cracow was 2
province = { id = 480 points = 1 } # Kielce added
province = { id = 481 points = 1 } # Czestochowa added
province = { id = 482 points = 4 } # Oppeln added
province = { id = 483 points = 1 } # Lodz was 2
province = { id = 485 points = 5 } # Warsaw was 4
province = { id = 487 points = 1 } # Lublin added
province = { id = 488 points = 1 } # Zamosc added
province = { id = 490 points = 1 } # Kosice was 2
province = { id = 497 points = 1 } # Debrecen
province = { id = 501 points = 1 } # Lvov was 2
province = { id = 510 points = 2 } # Konigsberg added
province = { id = 512 points = 2 } # Bologna was 5
province = { id = 513 points = 1 } # Florence added
province = { id = 515 points = 9 } # Rome was 15
province = { id = 520 points = 1 } # Foggia added
province = { id = 521 points = 1 } # Naples was 6
province = { id = 523 points = 2 } # Taranto was 5
province = { id = 525 points = 2 } # Palermo was 5
province = { id = 528 points = 2 } # Lyon
province = { id = 530 points = 1 } # Geneva added
province = { id = 531 points = 2 } # Turin added
province = { id = 532 points = 2 } # Bern
province = { id = 533 points = 1 } # Zürich
province = { id = 534 points = 1 } # Sardinia added
province = { id = 719 points = 1 } # Abilene added
province = { id = 539 points = 1 } # Managua was 1
province = { id = 540 points = 1 } # San José was 1
province = { id = 541 points = 2 } # Vancouver was 1
province = { id = 549 points = 1 } # Anchorage
province = { id = 555 points = 1 } # Kamloops added
province = { id = 556 points = 1 } # Vancouver Island added
province = { id = 500 points = 1 } # Stryj added
province = { id = 572 points = 1 } # Sault Ste Marie
province = { id = 576 points = 1 } # Newfoundland added
province = { id = 579 points = 1 } # Halifax added
province = { id = 584 points = 1 } # Sherbrook added
province = { id = 586 points = 1 } # Quecbec City added
province = { id = 588 points = 3 } # Ottawa was 1
province = { id = 589 points = 1 } # Toronto
province = { id = 599 points = 1 } # Worchester added
province = { id = 600 points = 2 } # Boston
province = { id = 601 points = 1 } # Hartford added
province = { id = 602 points = 6 } # New York was 1
province = { id = 603 points = 5 } #  Newark added
province = { id = 604 points = 4 } #  Atlantic City added
province = { id = 606 points = 10 } # Washington D.C. was 1
province = { id = 607 points = 1 } # Baltimore added
province = { id = 608 points = 5 } # Philadelphia was 1
province = { id = 609 points = 4 } # Harrisburg added
province = { id = 612 points = 2 } # Syracuse added
province = { id = 613 points = 2 } # Buffalo
province = { id = 614 points = 3 } # Pittsburgh was 2
province = { id = 615 points = 3 } # Cleveland was 1
province = { id = 616 points = 3 } # Detroit was 1
province = { id = 618 points = 1 } # Great Rapids added
province = { id = 619 points = 1 } # Indianapolis
province = { id = 620 points = 4 } # Chicago was 1
province = { id = 621 points = 1 } # Milwaukee
province = { id = 626 points = 1 } # Decatur added
province = { id = 622 points = 1 } # Marquette added
province = { id = 627 points = 2 } # Evansville added
province = { id = 628 points = 3 } # Cincinatti added
province = { id = 629 points = 3 } # Charleston, WV added
province = { id = 630 points = 2 } # Clarksburg added
province = { id = 633 points = 1 } # Norfolk
province = { id = 639 points = 2 } # Marion added
province = { id = 640 points = 4 } # Louisville was 1
province = { id = 641 points = 3 } # Owensboro added
province = { id = 642 points = 1 } # Nashville
province = { id = 651 points = 1 } # Miami
province = { id = 654 points = 1 } # Havana
province = { id = 657 points = 1 } # Guantanamo
province = { id = 663 points = 1 } # Pearl Harbour was 1
province = { id = 667 points = 4 } # Buenos Aires
province = { id = 669 points = 1 } # Augusta added
province = { id = 670 points = 1 } # Atlanta
province = { id = 672 points = 3 } # Birmingham, AL added
province = { id = 682 points = 2 } # Monroe added
province = { id = 684 points = 1 } # Little Rock
province = { id = 689 points = 1 } # St. Louis
province = { id = 690 points = 1 } # Kansas City
province = { id = 691 points = 1 } # Cedar Rapids added
province = { id = 692 points = 1 } # Des Moines
province = { id = 693 points = 1 } # Minneapolis
province = { id = 694 points = 1 } # Duluth added
province = { id = 698 points = 1 } # Bismarck
province = { id = 707 points = 1 } # Denver
province = { id = 713 points = 2 } # Oklahoma city added
province = { id = 715 points = 3 } # Dallas was 1
province = { id = 716 points = 9 } # Houston was 3
province = { id = 721 points = 4 } # Lubbock added
province = { id = 722 points = 2 } # Rosswell added
province = { id = 726 points = 1 } # Los Alamos added
province = { id = 727 points = 2 } # Silver City added
province = { id = 733 points = 1 } # Salt Lake City
province = { id = 742 points = 1 } # Chihuahua added
province = { id = 749 points = 1 } # Tampico added
province = { id = 748 points = 1 } # Corpus Cristi added
province = { id = 750 points = 1 } # Leon added
province = { id = 752 points = 2 } # Mexico City
province = { id = 753 points = 1 } # Puebla
province = { id = 754 points = 1 } # Acapulco
province = { id = 755 points = 1 } # Villahermosa
province = { id = 757 points = 1 } # Guatemala was 1
province = { id = 759 points = 1 } # San Salvador was 1
province = { id = 760 points = 1 } # Tegucigalpa was 1
province = { id = 761 points = 3 } # San Diego was 1
province = { id = 762 points = 4 } # Los Angeles was 1
province = { id = 763 points = 1 } # Fresno added
province = { id = 765 points = 3 } # San Francisco was 1
province = { id = 780 points = 2 } # Seattle was 1
province = { id = 783 points = 1 } # Portland
province = { id = 789 points = 1 } # Omaha
province = { id = 790 points = 1 } # Scottsbluff added
province = { id = 793 points = 1 } # Tulsa
province = { id = 796 points = 1 } # Edmonton
province = { id = 797 points = 1 } # Calgary added
province = { id = 802 points = 1 } # Barquisimeto
province = { id = 803 points = 1 } # Barranquilla was 2
province = { id = 804 points = 3 } # Maracaibo was 2
province = { id = 809 points = 1 } # Trinidad added
province = { id = 811 points = 1 } # Caracas
province = { id = 813 points = 2 } # Bogotá
province = { id = 815 points = 1 } # Quito
province = { id = 830 points = 3 } # Lima was 2
province = { id = 832 points = 2 } # La Paz
province = { id = 838 points = 1 } # Sucre added
province = { id = 839 points = 3 } # Antofagasta was 2
province = { id = 840 points = 4 } # Santiago was 2
province = { id = 843 points = 1 } # San Miguel de Tucuman
province = { id = 848 points = 1 } # Porto Alegre added
province = { id = 849 points = 3 } # Montevideo was 1
province = { id = 851 points = 1 } # Rosario added
province = { id = 852 points = 1 } # Mar del Plata
province = { id = 853 points = 1 } # Bahia Blanca added
province = { id = 871 points = 1 } # Cuyuni added
province = { id = 873 points = 1 } # Georgetown added
province = { id = 874 points = 1 } # Paramaribo added
province = { id = 880 points = 1 } # Fortaleza added
province = { id = 881 points = 1 } # Recife
province = { id = 882 points = 1 } # Salvador was 2
province = { id = 884 points = 1 } # Vitória
province = { id = 885 points = 4 } # Rio de Janeiro was 2
province = { id = 886 points = 1 } # São Paulo
province = { id = 888 points = 1 } # Panamá
province = { id = 889 points = 5 } # Colon
province = { id = 891 points = 1 } # Jamaica
province = { id = 892 points = 1 } # Port-au-Prince was 1
province = { id = 894 points = 1 } # Santo Domingo was 1
province = { id = 900 points = 6 } # Suez
province = { id = 901 points = 1 } # Port Said was 3
province = { id = 903 points = 1 } # Cairo was 2
province = { id = 906 points = 2 } # Alexandria was 5
province = { id = 919 points = 1 } # Tobruk was 3
province = { id = 924 points = 1 } # Bengazi
province = { id = 932 points = 1 } # Tripoli
province = { id = 939 points = 1 } # Tunis was 5
province = { id = 949 points = 1 } # Algiers was 5
province = { id = 953 points = 1 } # Oran added
province = { id = 958 points = 1 } # Casablanca was 2
province = { id = 981 points = 1 } # Dakar was 5
province = { id = 988 points = 1 } # Freetown added
province = { id = 992 points = 1 } # Monrovia
province = { id = 993 points = 1 } # Abidjan added
province = { id = 1002 points = 1 } # Accra added
province = { id = 1008 points = 1 } # Lagos added
province = { id = 1033 points = 1 } # Massaua added
province = { id = 1046 points = 1 } # Addis Ababa
province = { id = 1056 points = 1 } # Mogadishu added
province = { id = 1064 points = 1 } # Entebbe added
province = { id = 1066 points = 1 } # Khartoum added
province = { id = 1095 points = 1 } # Banana
province = { id = 1101 points = 1 } # Benguella added
province = { id = 1124 points = 1} # Bulawayo added
province = { id = 1116 points = 1 } # Cape Town was 3
province = { id = 1119 points = 1 } # Durban was 2
province = { id = 1120 points = 1 } # Johannesburg
province = { id = 1121 points = 3 } # Pretoria added
province = { id = 1125 points = 1 } # Harare added
province = { id = 1126 points = 1 } # Lusaka added
province = { id = 1127 points = 1 } # Élisabethville was 1
province = { id = 1129 points = 1 } # Ndola added
province = { id = 1133 points = 1 } # Quelimane added
province = { id = 746 points = 1 } # Midland
province = { id = 1151 points = 5 } # Molotov added
province = { id = 1179 points = 3 } # Sapporo was 2
province = { id = 1181 points = 1 } # Akita was 5
province = { id = 1180 points = 1 } # Sendai
province = { id = 1182 points = 2 } # Fukushima was 5
province = { id = 1183 points = 1 } # Niigata was 5
province = { id = 1184 points = 24 } # Tokyo was 10
province = { id = 1185 points = 4 } # Nagoya was 10
province = { id = 1186 points = 2 } # Kanazawa was 5
province = { id = 1187 points = 5 } # Osaka was 10
province = { id = 1188 points = 3 } # Hiroshima added
province = { id = 1189 points = 3 } # Shikoku was 5
province = { id = 1190 points = 5 } # Fukuoka
province = { id = 1193 points = 1 } # Okinawa
province = { id = 1196 points = 2 } # Busan was 1
province = { id = 1199 points = 1 } # Seoul
province = { id = 1201 points = 1 } # Pyongyang
province = { id = 1202 points = 1 } # Dalian added
province = { id = 1205 points = 1 } # Beiping was 5
province = { id = 1209 points = 1 } # Datong
province = { id = 1226 points = 1 } # Changzhi was 0
province = { id = 1253 points = 2 } # Wuchang
province = { id = 1232 points = 1 } # Hankou
province = { id = 1225 points = 1 } # Taiyuan
province = { id = 1260 points = 1 } # Changde
province = { id = 1228 points = 1 } # Zhengzhou added
province = { id = 1235 points = 2 } # Nanjing was 3
province = { id = 1237 points = 3 } # Shanghai
province = { id = 1238 points = 1 } # Hangzhou
province = { id = 1251 points = 1 } # Nancheng added
province = { id = 1255 points = 1 } # Changsha added
province = { id = 1319 points = 1 } # Nanning
province = { id = 1271 points = 1 } # Yan'an
province = { id = 1270 points = 1 } # Xianyang
province = { id = 1276 points = 1 } # Lanzhou added
province = { id = 1285 points = 1 } # Dhaka added
province = { id = 1296 points = 1 } # Mandalay
province = { id = 1299 points = 1 } # Rangoon was 2
province = { id = 1307 points = 1 } # Kunming was 3
province = { id = 1313 points = 2 } # Guangzhou
province = { id = 1315 points = 2 } # Hong Kong
province = { id = 1236 points = 1 } # Suzhou
province = { id = 1322 points = 1 } # Kaohsiung
province = { id = 1323 points = 1 } # Taipei
province = { id = 1328 points = 1 } # Hanoi was 5
province = { id = 1337 points = 1 } # Saigon was 10
province = { id = 1340 points = 1 } # Phnom Penh added
province = { id = 1343 points = 3 } # Bangkok
province = { id = 1345 points = 2 } # Thom Buri was 1
province = { id = 1347 points = 1 } # Kra added
province = { id = 1348 points = 1 } # Singora
province = { id = 1349 points = 3 } # Alor Star added
province = { id = 1350 points = 1 } # Kota Bahru was 2
province = { id = 1351 points = 1 } # Kuantan added
province = { id = 1352 points = 3 } # Kuala Lumpur was 1
province = { id = 1353 points = 3 } # Singapore
province = { id = 1354 points = 1 } # Bangka Island
province = { id = 1356 points = 1 } # Dumai added
province = { id = 1358 points = 1 } # Palembang was 2
province = { id = 1359 points = 1 } # Oosthaven was 2
province = { id = 1360 points = 1 } # Chengdu
province = { id = 1364 points = 1 } # Guiyang
province = { id = 1372 points = 2 } # Vladivostok was 10
province = { id = 1379 points = 1 } # Harbin was 4
province = { id = 1389 points = 4 } # Mukden was 2
province = { id = 1390 points = 4 } # Xinjing added
province = { id = 1394 points = 1 } # Andong
province = { id = 1395 points = 1 } # Yingkou added
province = { id = 1208 points = 1 } # Hohhot
province = { id = 1404 points = 1 } # Ulan Bator was 1
province = { id = 1416 points = 1 } # Irkutsk
province = { id = 1418 points = 1 } # Kyzl added was 1
province = { id = 1422 points = 1 } # Alma-Ata
province = { id = 1424 points = 2 } # Zhambyl added
province = { id = 1427 points = 2 } # Tashkent
province = { id = 1429 points = 1 } # Frunze added
province = { id = 1433 points = 1 } # Urumqi
province = { id = 1453 points = 1 } # Lhasa was 2
province = { id = 1455 points = 1 } # Punakha
province = { id = 1457 points = 1 } # Calcutta was 5
province = { id = 1459 points = 1 } # Ranci added
province = { id = 1460 points = 1 } # Jabalpur added
province = { id = 1461 points = 1 } # Vishakhapatnam added
province = { id = 1469 points = 1 } # Delhi was 5
province = { id = 1471 points = 1 } # Lucknow added
province = { id = 1473 points = 1 } # Kathmandu was 1
province = { id = 1477 points = 1 } # Meerut added
province = { id = 1479 points = 1 } # Jodhpur added
province = { id = 1485 points = 1 } # Stalinabad added
province = { id = 1486 points = 1 } # Kabul was 1
province = { id = 1494 points = 1 } # Karachi added
province = { id = 1497 points = 1 } # Bandar Abbas
province = { id = 1502 points = 1 } # Teheran was 2
province = { id = 1505 points = 2 } # Bombay was 5
province = { id = 1507 points = 1 } # Hyderabad, IND added
province = { id = 1511 points = 1 } # Bangalore added
province = { id = 1516 points = 1 } # Trincomalee added
province = { id = 1517 points = 1 } # Columbo added
province = { id = 1546 points = 1 } # Kemerovo added
province = { id = 1548 points = 2 } # Novosibirsk was 1
province = { id = 1552 points = 1 } # Omsk
province = { id = 1554 points = 1 } # Karaganda added
province = { id = 1560 points = 1 } # Krasnoyarsk added
province = { id = 1561 points = 1 } # Achinsk added
province = { id = 1566 points = 1 } # Berezniki added
province = { id = 1567 points = 2 } # Ufa added
province = { id = 1572 points = 3 } # Sverdlovsk added
province = { id = 1574 points = 1 } # Chelyabinsk added
province = { id = 1577 points = 1 } # Orsk added
province = { id = 1578 points = 2 } # Aktyubinsk added
province = { id = 1191 points = 1 } # Kagoshima
province = { id = 1178 points = 1 } # Asahikawa
province = { id = 1642 points = 1 } # Pontianak
province = { id = 1355 points = 1 } # Medan
province = { id = 1624 points = 1 } # Guam was 2
province = { id = 1628 points = 1 } # Batavia was 3
province = { id = 1630 points = 1 } #  Semarang added
province = { id = 1632 points = 1 } # Soerabeya added
province = { id = 1644 points = 1 } # Kuching added
province = { id = 1648 points = 1 } # Tarakan added
province = { id = 1649 points = 1 } # Samarinda added
province = { id = 1692 points = 1 } # Noumea
province = { id = 1698 points = 1 } # Rockhampton
province = { id = 1703 points = 1 } # Darwin
province = { id = 1712 points = 1 } # Perth
province = { id = 1718 points = 1 } # Port Augusta
province = { id = 1722 points = 1 } # Brisbane
province = { id = 1724 points = 1 } # Newcastle
province = { id = 1727 points = 3 } # Sydney
province = { id = 1728 points = 1 } # Canberra
province = { id = 1729 points = 1 } # Tasmania added
province = { id = 1730 points = 1 } # Melbourne
province = { id = 1733 points = 1 } # Adelaide
province = { id = 1734 points = 1 } # Broken Hill added
province = { id = 1737 points = 1 } # Manila was 3
province = { id = 1740 points = 1 } # Lingay Gulf
province = { id = 1748 points = 1 } # Zamboanga
province = { id = 438 points = 1 } # Antalya
province = { id = 1792 points = 1 } # Damascus added
province = { id = 1794 points = 1 } # Beirut added
province = { id = 1797 points = 1 } # Jerusalem
province = { id = 1812 points = 1 } # Sanaa added
province = { id = 1819 points = 1 } # Mascate
province = { id = 1820 points = 1 } # Doha
province = { id = 1821 points = 1 } # Damman added
province = { id = 1823 points = 1 } # Basrah
province = { id = 1825 points = 2 } # Abadan was 1
province = { id = 1828 points = 1 } # Kuybyshev added
province = { id = 1832 points = 1 } # Saratov added
province = { id = 1838 points = 1 } # Astrakhan added
province = { id = 1844 points = 1 } # Maikop was 2
province = { id = 1847 points = 2 } # Grozny added
province = { id = 1848 points = 1 } # Batum added
province = { id = 1850 points = 2 } # Tblisi added
province = { id = 1856 points = 1 } # Yerevan added
province = { id = 1860 points = 1 } # Kirkuk added
province = { id = 1866 points = 1 } # Baghdad
province = { id = 1867 points = 1 } # The Azores
province = { id = 1868 points = 1 } # Auckland
province = { id = 1871 points = 1 } # Wellington
province = { id = 1872 points = 1 } # Christchurch
province = { id = 1907 points = 5 } # Baku added