##############################
# Country definition for CXB #
##############################

country =
{ tag                    = CXB
  regular_id             = CHI
  intrinsic_gov_type     = paternal_autocrat
  puppet                 = CHI
  # Resource Reserves
  energy                 = 200
  metal                  = 200
  rare_materials         = 100
  oil                    = 100
  supplies               = 100
  money                  = 50
  consumer = 0.0000 
  supply = 0.0000 
  production = 1.0000 
  reinforcement = 0.0000 
  upgrading = 0.0000 
  capital                = 1443 # Xining
  manpower               = 200 # 200 - building queue
  dissent                = 15

	diplomacy = {
		relation = { tag = AFG value = 1 }
		relation = { tag = ALB value = 1 }
		relation = { tag = ARG value = 1 }
		relation = { tag = AST value = 1 }
		relation = { tag = AUS value = 1 }
		relation = { tag = BEL value = 1 }
		relation = { tag = BHU value = 1 }
		relation = { tag = BOL value = 1 }
		relation = { tag = BRA value = 1 }
		relation = { tag = BUL value = 1 }
		relation = { tag = CAN value = 1 }
		relation = { tag = CGX value = -5 }
		relation = { tag = CHC value = -40 }
		relation = { tag = CHI value = 175 access = yes }
		relation = { tag = CHL value = 1 }
		relation = { tag = COL value = 1 }
		relation = { tag = COS value = 1 }
		relation = { tag = CSX value = 30 access = yes }
		relation = { tag = CUB value = 1 }
		relation = { tag = CYN value = -15 }
		relation = { tag = CZE value = 1 }
		relation = { tag = DEN value = 1 }
		relation = { tag = DOM value = 1 }
		relation = { tag = ECU value = 1 }
		relation = { tag = EGY value = 1 }
		relation = { tag = ENG value = 25 }
		relation = { tag = EST value = 1 }
		relation = { tag = ETH value = 1 }
		relation = { tag = FIN value = 1 }
		relation = { tag = FRA value = 30 }
		relation = { tag = GER value = 40 }
		relation = { tag = GRE value = 1 }
		relation = { tag = GUA value = 1 }
		relation = { tag = HAI value = 1 }
		relation = { tag = HOL value = 1 }
		relation = { tag = HON value = 1 }
		relation = { tag = HUN value = 1 }
		relation = { tag = IND value = 1 }
		relation = { tag = IRE value = 1 }
		relation = { tag = IRQ value = 1 }
		relation = { tag = ITA value = 30 }
		relation = { tag = JAP value = -35 }
		relation = { tag = LAT value = 1 }
		relation = { tag = LIB value = 1 }
		relation = { tag = LIT value = 1 }
		relation = { tag = LUX value = 1 }
		relation = { tag = MAN value = -75 }
		relation = { tag = MEX value = 1 }
		relation = { tag = MLY value = 1 }
		relation = { tag = MON value = -30 }
		relation = { tag = NEP value = 1 }
		relation = { tag = NIC value = 1 }
		relation = { tag = NOR value = 1 }
		relation = { tag = NZL value = 1 }
		relation = { tag = OMN value = 1 }
		relation = { tag = PAN value = 1 }
		relation = { tag = PAR value = 1 }
		relation = { tag = PER value = 1 }
		relation = { tag = PHI value = 1 }
		relation = { tag = POL value = 1 }
		relation = { tag = POR value = 1 }
		relation = { tag = PRU value = 1 }
		relation = { tag = ROM value = 1 }
		relation = { tag = SAF value = 1 }
		relation = { tag = SAL value = 1 }
		relation = { tag = SAU value = 1 }
		relation = { tag = SIA value = 1 }
		relation = { tag = SIK value = -50 }
		relation = { tag = SOV value = 35 }
		relation = { tag = SPA value = 1 }
		relation = { tag = SPR value = 1 }
		relation = { tag = SWE value = 1 }
		relation = { tag = SCH value = 1 }
		relation = { tag = TAN value = -20 }
		relation = { tag = TIB value = 1 }
		relation = { tag = TUR value = 1 }
		relation = { tag = U27 value = 1 }
		relation = { tag = URU value = 1 }
		relation = { tag = USA value = 50 }
		relation = { tag = VEN value = 1 }
		relation = { tag = YEM value = 1 }
		relation = { tag = YUG value = 1 }
	}

	SpyInfo = { country = "CXB" NumberOfSpies = 3 }
	SpyInfo = { country = "CGX" NumberOfSpies = 2 }
	SpyInfo = { country = "CHC" NumberOfSpies = 2 }
	SpyInfo = { country = "CHI" NumberOfSpies = 4 }
	SpyInfo = { country = "CSX" NumberOfSpies = 2 }
	SpyInfo = { country = "CYN" NumberOfSpies = 1 }
	SpyInfo = { country = "IND" NumberOfSpies = 1 }
	SpyInfo = { country = "JAP" NumberOfSpies = 1 }
	SpyInfo = { country = "MAN" NumberOfSpies = 2 }
	SpyInfo = { country = "MON" NumberOfSpies = 4 }
	SpyInfo = { country = "SIK" NumberOfSpies = 4 }
	SpyInfo = { country = "SOV" NumberOfSpies = 1 }
	SpyInfo = { country = "TAN" NumberOfSpies = 4 }
	SpyInfo = { country = "TIB" NumberOfSpies = 1 }

  policy =
  { date              = { year = 0 month = january day = 0 }
    democratic        = 3
    political_left    = 4
    freedom           = 3
    free_market       = 3
    professional_army = 1
    defense_lobby     = 10
    interventionism   = 3
  }
  nationalprovinces      = { 1442 1441 1273 1440 1443 1276 1275 1274 1444 1439 }
  ownedprovinces         = { 1442 1441 1273 1440 1443 1274 1444 1439 }
  controlledprovinces    = { 1442 1441 1273 1440 1443 1274 1444 1439 }
  # ROTW Minor Tech '36
  # Group E 1936 techs
  # ######################
  # GW fighter
  techapps               = { 1010 1190 5080 6210 1200 }
  blueprints             = { }

  headofstate            = { type = 9 id = 504001 }
  headofgovernment       = { type = 9 id = 504002 }
  foreignminister        = { type = 9 id = 504003 }
  armamentminister       = { type = 9 id = 504004 }
  ministerofsecurity     = { type = 9 id = 504005 }
  ministerofintelligence = { type = 9 id = 504006 }
  chiefofstaff           = { type = 9 id = 504007 }
  chiefofarmy            = { type = 9 id = 504008 }
  chiefofnavy            = { type = 9 id = 504009 }
  chiefofair             = { type = 9 id = 504010 }
  # ######
  # XIBEI SAN MA OOB
  # ######
  landunit =
  { location = 1273 # Yinchuan
    name     = "15. Lujun"
    # ## leader = 504004 # Ma Hongkui
    id       = { type = 22200 id = 1 }
    division =
    { experience = 40
      id         = { type = 22200 id = 2 }
      name       = "35. Bubing Shi"
      type       = infantry
      strength   = 100
      model      = 0
    }
  }
  landunit =
  { location = 1273 # Yinchuan
    name     = "11. Jun"
    # ## leader = 504005 # Ma Hongbin
    id       = { type = 22200 id = 3 }
    division =
    { experience = 40
      id         = { type = 22200 id = 4 }
      name       = "Xin 7. Bubing Shi"
      type       = militia
      strength   = 100
      model      = 0
    }
    division =
    { experience   = 40
      id           = { type = 22200 id = 5 }
      name         = "Xin 7. Qibing Shi"
      type         = cavalry
      #max_strength = 100
      strength     = 100
      model        = 0
    }
    division =
    { experience = 40
      id         = { type = 22200 id = 6 }
      name       = "10. Duli Lü"
      type       = infantry
      strength   = 50
      model      = 0
    }
  }
  landunit =
  { location = 1443 # Xining
    name     = "Xin 2. Jun"
    # ## leader = 504006 # Ma Hongbin
    id       = { type = 22200 id = 7 }
    division =
    { experience = 40
      id         = { type = 22200 id = 8 }
      name       = "Qibing Di'1 Shi"
      type       = cavalry
      strength   = 100
      model      = 0
    }
    division =
    { experience = 40
      id         = { type = 22200 id = 9 }
      name       = "1. Qibing Lü"
      type       = cavalry
      strength   = 100
      model      = 0
    }
  }
  landunit =
  { location = 1443 # Xotan
    name     = "Tunganistan Jun"
    # ## leader = # Ma Hushan
    id       = { type = 22200 id = 10 }
    division =
    { experience = 40
      id         = { type = 22200 id = 11 }
      name       = "Tungan Shi"
      type       = militia
      strength   = 50
      model      = 0
    }
  }
  landunit =
  { location = 1443 # Xining
    name     = "3. Jun"
    # ## leader = # Zeng Wanzhong
    id       = { type = 22200 id = 12 }
    division =
    { experience = 40
      id         = { type = 22200 id = 13 }
      name       = "3. Jun"
      type       = infantry
      model      = 0
    }
  }
  landunit =
  { location = 1440 # Jinchang
    name     = "10. Jun"
    # ## leader = 50112 # Xu Yuanquan
    id       = { type = 22200 id = 14 }
    division =
    { experience = 40
      id         = { type = 22200 id = 15 }
      name       = "10. Jun"
      type       = infantry
      model      = 0
    }
  }
  landunit =
  { location = 1273 # Yinchuan
    name     = "15. Jun"
    # ## leader = 50214 # Liu Mao'en
    id       = { type = 22200 id = 16 }
    division =
    { id    = { type = 22200 id = 17 }
      name  = "15. Jun"
      type  = infantry
      model = 0
    }
  }
  landunit =
  { location = 1274 # Guyuan
    name     = "25. Jun"
    # ## leader = 50307 # Wan Yaohuang
    id       = { type = 22200 id = 18 }
    division =
    { experience = 40
      id         = { type = 22200 id = 19 }
      name       = "25. Jun"
      type       = infantry
      model      = 0
    }
    dig_in   = 20.000
  }
  landunit =
  { location = 1276 # Lanzhou
    name     = "31. Jun"
    # ## leader = # Liang Guanying
    id       = { type = 22200 id = 20 }
    division =
    { experience = 40
      id         = { type = 22200 id = 21 }
      name       = "31. Jun"
      type       = infantry
      model      = 0
    }
    dig_in   = 20.000
  }
  landunit =
  { location = 1277 # Tianshui
    name     = "41. Jun"
    # ## leader = 50263 # Sun Zhen
    id       = { type = 22200 id = 22 }
    division =
    { experience = 40
      id         = { type = 22200 id = 23 }
      name       = "41. Jun"
      type       = infantry
      model      = 0
    }
    dig_in   = 20.000
  }
  landunit =
  { location = 1277 # Tianshui
    name     = "25. Bubing Shi"
    # ## leader = 50154 # Guan Linzheng
    id       = { type = 22200 id = 24 }
    division =
    { experience   = 40
      id           = { type = 22200 id = 25 }
      name         = "25. Bubing Shi"
      type         = infantry
      #max_strength = 50
      strength     = 50
      model        = 0
    }
    dig_in   = 20.000
  } 
}
