#####################
# Country main data #
#####################

country =
{ tag                    = YUG
  # Resource Reserves
  energy                 = 1349
  metal                  = 1014
  rare_materials         = 276
  oil                    = 132
  supplies               = 933
  money                  = 40
  consumer = 0.1896 
  supply = 0.0862 
  production = 0.7242 
  reinforcement = 0.0000 
  upgrading = 0.0000 
  capital                = 453
  manpower               = 149.7000  # 155 - building queue -5 for HQ
  transports             = 76
  escorts                = 6
	diplomacy = {
		relation = { tag = AFG value = 1 }
		relation = { tag = ALB value = -20 }
		relation = { tag = ARG value = 1 }
		relation = { tag = AST value = 10 }
		relation = { tag = AUS value = -20 }
		relation = { tag = BEL value = 25 }
		relation = { tag = BHU value = 1 }
		relation = { tag = BOL value = 1 }
		relation = { tag = BRA value = 1 }
		relation = { tag = BUL value = 20 }
		relation = { tag = CAN value = 20 }
		relation = { tag = CGX value = 1 }
		relation = { tag = CHC value = 1 }
		relation = { tag = CHI value = 10 }
		relation = { tag = CHL value = 1 }
		relation = { tag = COL value = 1 }
		relation = { tag = COS value = 1 }
		relation = { tag = CSX value = 1 }
		relation = { tag = CUB value = 1 }
		relation = { tag = CXB value = 1 }
		relation = { tag = CYN value = 1 }
		relation = { tag = CZE value = 40 guaranteed = { day = 30 month = december year = 1935 } }
		relation = { tag = DEN value = 20 }
		relation = { tag = DOM value = 1 }
		relation = { tag = ECU value = 1 }
		relation = { tag = EGY value = 1 }
		relation = { tag = ENG value = 40 }
		relation = { tag = EST value = 20 }
		relation = { tag = ETH value = 1 }
		relation = { tag = FIN value = 20 }
		relation = { tag = FRA value = 40 }
		relation = { tag = GER value = 40 }
		relation = { tag = GRE value = -10 guaranteed = { day = 30 month = august year = 1934 } }
		relation = { tag = GUA value = 1 }
		relation = { tag = HAI value = 1 }
		relation = { tag = HOL value = 20 }
		relation = { tag = HON value = 1 }
		relation = { tag = HUN value = -10 }
		relation = { tag = IND value = 1 }
		relation = { tag = IRE value = 20 }
		relation = { tag = IRQ value = 1 }
		relation = { tag = ITA value = 40 }
		relation = { tag = JAP value = 20 }
		relation = { tag = LAT value = 20 }
		relation = { tag = LIB value = 1 }
		relation = { tag = LIT value = 20 }
		relation = { tag = LUX value = 20 }
		relation = { tag = MAN value = 1 }
		relation = { tag = MEX value = 1 }
		relation = { tag = MLY value = 1 }
		relation = { tag = MON value = 1 }
		relation = { tag = NEP value = 1 }
		relation = { tag = NIC value = 1 }
		relation = { tag = NOR value = 1 }
		relation = { tag = NZL value = 10 }
		relation = { tag = OMN value = 1 }
		relation = { tag = PAN value = 1 }
		relation = { tag = PAR value = 1 }
		relation = { tag = PER value = 1 }
		relation = { tag = PHI value = 1 }
		relation = { tag = POL value = 30 }
		relation = { tag = POR value = 20 }
		relation = { tag = PRU value = 1 }
		relation = { tag = ROM value = -10 guaranteed = { day = 30 month = december year = 1935 } }
		relation = { tag = SAF value = 10 }
		relation = { tag = SAL value = 1 }
		relation = { tag = SAU value = 10 }
		relation = { tag = SIA value = 1 }
		relation = { tag = SIK value = 1 }
		relation = { tag = SOV value = 40 }
		relation = { tag = SPA value = 20 }
		relation = { tag = SPR value = 20 }
		relation = { tag = SWE value = 20 }
		relation = { tag = SCH value = 50 }
		relation = { tag = TAN value = 1 }
		relation = { tag = TIB value = 1 }
		relation = { tag = TUR value = -20 guaranteed = { day = 30 month = august year = 1934 } }
		relation = { tag = U27 value = 1 }
		relation = { tag = URU value = 1 }
		relation = { tag = USA value = 40 }
		relation = { tag = VEN value = 1 }
		relation = { tag = YEM value = 1 }
	}

	SpyInfo = { country = "YUG" NumberOfSpies = 6 }
	SpyInfo = { country = "ALB" NumberOfSpies = 4 }
	SpyInfo = { country = "AUS" NumberOfSpies = 4 }
	SpyInfo = { country = "ENG" NumberOfSpies = 1 }
	SpyInfo = { country = "FRA" NumberOfSpies = 2 }
	SpyInfo = { country = "GER" NumberOfSpies = 3 }
	SpyInfo = { country = "GRE" NumberOfSpies = 4 }
	SpyInfo = { country = "HUN" NumberOfSpies = 4 }
	SpyInfo = { country = "ITA" NumberOfSpies = 4 }
	SpyInfo = { country = "POL" NumberOfSpies = 1 }
	SpyInfo = { country = "ROM" NumberOfSpies = 4 }
	SpyInfo = { country = "SOV" NumberOfSpies = 2 }
	SpyInfo = { country = "SCH" NumberOfSpies = 1 }
	SpyInfo = { country = "TUR" NumberOfSpies = 2 }

  nationalprovinces      = { 380 459 455 454 453 382 381 383 384 385 386 387 388 389 451 452 418 415 493 494 413 414 }
  ownedprovinces         = { 380 459 455 454 453 382 381 383 384 385 386 387 388 389 451 452 418 415 493 494 413 414 }
  controlledprovinces    = { 380 459 455 454 453 382 381 383 384 385 386 387 388 389 451 452 418 415 493 494 413 414 }
  # Eastern Minor Tech '36
  # Group D 1936 techs
  # ######################
  # GW fighter
  techapps               = { 4010  2290 2300 2310 1010 1190 1110 2450 2460 2510 5010 5080 5090 4120 9010 6210 6300 3010 3020 3030 3400 8040
                             8050
                           }
  policy =
  { date              = { year = 0 month = january day = 0 }
    democratic        = 4
    political_left    = 3
    freedom           = 5
    free_market       = 5
    professional_army = 3
    defense_lobby     = 7
    interventionism   = 6
  }
  headofstate            = { type = 9 id = 20001 }
  headofgovernment       = { type = 9 id = 20002 }
  foreignminister        = { type = 9 id = 20003 }
  armamentminister       = { type = 9 id = 20004 }
  ministerofsecurity     = { type = 9 id = 20005 }
  ministerofintelligence = { type = 9 id = 20006 }
  chiefofstaff           = { type = 9 id = 20007 }
  chiefofarmy            = { type = 9 id = 20008 }
  chiefofnavy            = { type = 9 id = 20009 }
  chiefofair             = { type = 9 id = 20010 }
  landunit =
  { id       = { type = 19800 id = 1 }
    location = 453
    name     = "IV. Kraljevska Jugoslavenska Armija"
    division =
    { id       = { type = 19800 id = 2 }
      name     = "27. Savska Pesadijska Divizija"
      strength = 70
      type     = infantry
      extra    = artillery
    }
  }
  landunit =
  { id       = { type = 19800 id = 3 }
    location = 453
    name     = "VII. Kraljevska Jugoslavenska Armija"
    division =
    { id       = { type = 19800 id = 4 }
      name     = "32. Triglavska Pesadijska Divizija"
      strength = 70
      type     = infantry
      extra    = artillery
    }
    division =
    { id       = { type = 19800 id = 5 }
      name     = "Triglavski Odred"
      strength = 70
      type     = bergsjaeger
    }
    division =
    { id       = { type = 19800 id = 6 }
      name     = "1. Konjicka Divizija"
      strength = 70
      type     = cavalry
    }
  }
  landunit =
  { id       = { type = 19800 id = 7 }
    name     = "I. Kraljevska Jugoslavenska Armija"
    location = 453
    division =
    { id       = { type = 19800 id = 200 }
      name     = "1. armija"
      strength = 100
      type     = hq
      extra    = anti_air
    }
    division =
    { id       = { type = 19800 id = 8 }
      name     = "7. Potiska Pesadijska Divizija"
      strength = 70
      type     = infantry
      extra    = artillery
    }
    division =
    { id       = { type = 19800 id = 9 }
      name     = "3. Konjicka Divizija"
      strength = 70
      type     = cavalry
    }
  }
  landunit =
  { id       = { type = 19800 id = 10 }
    location = 386
    name     = "II. Kraljevska Jugoslavenska Armija"
    division =
    { id       = { type = 19800 id = 11 }
      name     = "10. Bosanska Pesadijska Divizija"
      strength = 70
      type     = infantry
    }
    division =
    { id       = { type = 19800 id = 12 }
      name     = "17. Vrbaska Pesadijska Divizija"
      strength = 70
      type     = infantry
    }
  }
  landunit =
  { id       = { type = 19800 id = 13 }
    location = 415
    name     = "III. Kraljevska Jugoslavenska Armija"
    division =
    { id       = { type = 19800 id = 14 }
      name     = "13. Hercegovacka Pesadijska Divizija"
      strength = 70
      type     = infantry
    }
    division =
    { id       = { type = 19800 id = 15 }
      name     = "15. Zetska Pesadijska Divizija"
      strength = 70
      type     = infantry
    }
  }
  landunit =
  { id       = { type = 19800 id = 16 }
    location = 384
    name     = "III. Kraljevska Teritorijalna Armija"
    division =
    { id       = { type = 19800 id = 17 }
      name     = "5. Sumadijska Pesadijska Divizija"
      strength = 70
      type     = infantry
      extra    = anti_air
    }
    division =
    { id       = { type = 19800 id = 18 }
      name     = "20. Bregalnicka Pesadijska Divizija"
      strength = 70
      type     = infantry
    }
    division =
    { id       = { type = 19800 id = 19 }
      name     = "22. Ibarska Pesadijska Divizija"
      strength = 70
      type     = infantry
    }
  }
  landunit =
  { id       = { type = 19800 id = 20 }
    location = 380
    name     = "V. Nezavisna Armija"
    division =
    { id       = { type = 19800 id = 21 }
      name     = "8. Krajinska Pesadijska Divizija"
      strength = 70
      type     = infantry
      extra    = artillery
    }
    division =
    { id       = { type = 19800 id = 22 }
      name     = "9. Timocka Pesadijska Divizija"
      strength = 70
      type     = infantry
    }
    division =
    { id       = { type = 19800 id = 23 }
      name     = "2. Konjicka Divizija"
      strength = 70
      type     = cavalry
    }
  }
  landunit =
  { id       = { type = 19800 id = 24 }
    location = 453
    name     = "VI. Nezavisna Armija"
    division =
    { id       = { type = 19800 id = 25 }
      name     = "3. Dunavska Pesadijska Divizija"
      strength = 70
      type     = infantry
    }
    division =
    { id       = { type = 19800 id = 26 }
      name     = "4. Konjicka Divizija"
      strength = 70
      type     = cavalry
    }
  }
  # ##########################
  # ##########################
  navalunit =
  { id       = { type = 19800 id = 30 }
    name     = "Kraljevska Jugoslavenska Ratna Mornarica"
    location = 384
    base     = 384
    division =
    { id       = { type = 19800 id = 100 }
      name     = "Dalmacija"
      type     = light_cruiser
      model    = 0
      strength = 100
      extra1 = none
      extra2 = none
      brigade_model1 = 0
      brigade_model2 = 0
    }
    division =
    { id       = { type = 19800 id = 101 }
      name     = "Zmaj"
      type     = light_cruiser
      model    = 0
      strength = 100
      extra1 = naval_spotter_s
      extra2 = none
      brigade_model1 = 0
      brigade_model2 = 0
    }
    division =
    { id       = { type = 19800 id = 102 }
      name     = "1. Razaracka Flotila"
      type     = destroyer
      model    = 1
      strength = 100
      extra1 = naval_mines
      brigade_model1 = 0
    }
    division =
    { id       = { type = 19800 id = 103 }
      name     = "2. Razaracka Flotila"
      type     = destroyer
      model    = 0
      strength = 100
    }
    division =
    { id       = { type = 19800 id = 31 }
      name     = "3. Razaracka Flotila"
      type     = destroyer
      model    = 0
      strength = 100
    }
    division =
    { id    = { type = 19800 id = 32 }
      name  = "1. Podmornicka Flotila"
      type  = submarine
      model = 0
    }
  }
  # #########################
  # #########################
  airunit =
  { location = 453
    base     = 453
    id       = { type = 19800 id = 27 }
    name     = "Operativno Zrakoplovstvo"
    division =
    { id       = { type = 19800 id = 28 }
      name     = "2. Vazduhoplovni Lovacki Puk"
      strength = 30
      type     = interceptor
      model    = 0
    }
    division =
    { id       = { type = 19800 id = 29 }
      name     = "26. Takticki Bombarderski Puk"
      strength = 30
      type     = tactical_bomber
      model    = 0
    }
  } 
	province_development = { 
		id = { type = 19800 id = 33 } 
		name = "" 
		progress = 0.0000 
		location = 453 
		cost = 2.0000 
		date = { 
			year = 1941 
			month = december 
			day = 11 
			hour = 0 
			} 
		manpower = 0.1000 
		close_when_finished = yes 
		waitingforclosure = no 
		total_progress = 0.0000 
		size = 24 
		done = 0 
		days = 2042 
		days_for_first = 110 
		gearing_bonus = 0.0000 
		type = infrastructure 
		} 
	province_development = { 
		id = { type = 19800 id = 39 } 
		name = "" 
		progress = 0.0000 
		location = 415 
		cost = 2.0000 
		date = { 
			year = 1940 
			month = july 
			day = 17 
			hour = 0 
			} 
		manpower = 0.1000 
		close_when_finished = yes 
		waitingforclosure = no 
		total_progress = 0.0000 
		size = 26 
		done = 0 
		days = 2125 
		days_for_first = 110 
		gearing_bonus = 0.0000 
		speed_step = 1 
		type = infrastructure 
		} 
	brigade_development = { 
		id = { type = 19800 id = 42 } 
		name = "36' AA" 
		progress = 0.0000 
		location = 453 
		cost = 0.7360 
		date = { 
			year = 1936 
			month = december 
			day = 27 
			hour = 0 
			} 
		manpower = 0.1000 
		close_when_finished = yes 
		waitingforclosure = no 
		retooling_time = 36.0000 
		total_progress = 0.0000 
		size = 4 
		done = 0 
		days = 87 
		days_for_first = 87 
		gearing_bonus = 0.0000 
		type = naval_anti_air_s 
		model = 1 
		} 
}
